//
// Copyright (C) 2006-2011 Christoph Sommer <christoph.sommer@uibk.ac.at>
//
// Documentation for these modules is at http://veins.car2x.org/
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//

#ifndef epidemic_rsu_H
#define epidemic_rsu_H

#include <queue>
#include <unordered_map>
#include "veins/modules/application/ieee80211p/BaseWaveApplLayer.h"
#include "veins/modules/world/annotations/AnnotationManager.h"

using Veins::AnnotationManager;
using namespace std;

class epidemic_rsu : public BaseWaveApplLayer {
    public:
        virtual void initialize(int stage);
    protected:
        AnnotationManager* annotations;
        BaseMobility* mobi;
        bool sentMessage;
        //Hash table to represent the node buffer. It stores messages generated by itself as well messages carried on behalf of other nodes
        typedef unordered_map<string, WaveShortMessage> MyMapEpidemicMessageBuffer;
        typedef pair<string, WaveShortMessage> MyPairEpidemicMessageBuffer;
        //Creating a unordered_map to represent the local epidemic messages buffer
        MyMapEpidemicMessageBuffer epidemicLocalMessageBuffer;
        //Bit Vector to represent a summary vector that indicates which entries in their local hash table are set.
        unordered_map<string, bool> epidemicLocalSummaryVector;
        //Bit Vector to represent a summary vector that indicates which entries in remote hash table are set.
        unordered_map<string, bool> epidemicRemoteSummaryVector;
        //Bit Vector to represent a result summary vector that will be used to make a request of messages.
        unordered_map<string, bool> epidemicRequestMessageVector;
        //bitset<BROADCAST> epidemicSummaryVector;
        //Cache with nodes that I recently met
        unordered_map<unsigned int, simtime_t> nodesRecentlyFoundList;
        //Cache with nodes that I recently sent the summary vector
        unordered_map<unsigned int, simtime_t> nodesIRecentlySentSummaryVector;
        //implementation of FIFO in order to maintain the limited length of the buffer activated
        queue<string> queueFIFO;
        double maiortempo = 0;

        struct messages {
            unsigned short int copyMessage;
            string hops;
            unsigned short int minHop;
            unsigned short int maxHop;
            unsigned short int sumHops;
            unsigned short int countT;
            unsigned short int countP;
            string wsmData;
            simtime_t sumTimeRecived;
            string times;
        };
        map<string, struct messages> messagesReceived;
        unordered_map<string, WaveShortMessage> MessageBuffer;

    protected:
        virtual void onBeacon(WaveShortMessage* wsm);
        virtual void onData(WaveShortMessage* wsm);
        void sendLocalSummaryVector(unsigned int newRecipientAddress);
        void sendEpidemicRequestMessageVector(unsigned int newRecipientAddress);
        void sendMessagesRequested(string s, unsigned int recipientAddress);
        void sendBeacon();
        void sendBeacon(unsigned int target);
        virtual void sendWSM(WaveShortMessage* wsm);
        //Return a string with the whole summaryvector
        string getLocalSummaryVectorData();
        string getEpidemicRequestMessageVectorData();
        WaveShortMessage getEpidemicLocalMessageBuffer(string s);
        void printNodesIRecentlySentSummaryVector();
        void printEpidemicLocalMessageBuffer();
        void printEpidemicRequestMessageVector();
        void printWaveShortMessage(WaveShortMessage wsm);
        void printWaveShortMessage(WaveShortMessage* wsm);
        void printEpidemicLocalSummaryVectorData();
        void printEpidemicRemoteSummaryVectorData();
        void createEpidemicRequestMessageVector();
        void printQueueFIFO(queue<string> qFIFO);
        void createEpidemicRemoteSummaryVector(string s);
        virtual void finish();

        void epidemic_InitializeVariables();
        void messagesReceivedMeasuring(WaveShortMessage* wsm);
        void printCountMessagesReceived();
};

#endif
