Veins Framework: Consts80211p.h File Reference
Consts80211p.h File Reference
Namespaces
Channels
Channels as reserved by the FCC.
Enumerations
enum Channels::ChannelNumber {
Channels::CRIT_SOL = 172, Channels::SCH1 = 174, Channels::SCH2 = 176, Channels::CCH = 178,
Channels::SCH3 = 180, Channels::SCH4 = 182, Channels::HPPS = 184
}
enum t_channel { type_CCH =0, type_SCH }
Variables
const double NUM_BITRATES_80211P = 8
Bit rates for 802.11p.
const double BITRATES_80211P []
const double N_DBPS_80211P []
Number of Data Bits Per Symbol (N_NBPS) corresponding to bitrates in BITRATES_80211P.
const double T_SYM_80211P = 8e-6
Symbol interval.
const int PHY_HDR_TOTAL_LENGTH = 46
Length of PHY HEADER.
const double PHY_HDR_PREAMBLE_DURATION = 32e-6
Duration of the PLCP Preamble.
const double PHY_HDR_PLCPSIGNAL_DURATION = 8e-6
Duration of the PLCP Signal.
const int PHY_HDR_PLCPSIGNAL_LENGTH = 24
Length of the PLCP Signal.
const int PHY_HDR_PSDU_HEADER_LENGTH = PHY_HDR_TOTAL_LENGTH - PHY_HDR_PLCPSIGNAL_LENGTH
Lenght of the PhyHeader sent with normal bitrate.
const double PHY_HDR_BANDWIDTH = 3000000
Bitrate of the PLCP Signal.
const SimTime SLOTLENGTH_11P = SimTime().setRaw(13000000UL)
Slot Time for 10 MHz channel spacing.
const SimTime SIFS_11P = SimTime().setRaw(32000000UL)
Short interframe space.
const SimTime RADIODELAY_11P = SimTime().setRaw(1000000UL)
Time it takes to switch from Rx to Tx Mode.
const unsigned CWMIN_11P = 15
Contention Window minimal size.
const unsigned CWMAX_11P = 1023
Contention Window maximal size.
const SimTime SWITCHING_INTERVAL_11P = SimTime().setRaw(50000000000UL)
1609.4 slot length
const SimTime GUARD_INTERVAL_11P = SimTime().setRaw(4000000000UL)
1609.4 slot length
Enumeration Type Documentation
enum t_channel
Enumerator
type_CCH
type_SCH
Definition at line 157 of file Consts80211p.h.
                {
         type_CCH=0,
         type_SCH,
 };
Variable Documentation
const double BITRATES_80211P[]
Initial value:
= {
        3000000,
        4500000,
        6000000,
        9000000,
        12000000,
        18000000,
        24000000,
        27000000
}
Definition at line 29 of file Consts80211p.h.
Referenced by Mac1609_4::setParametersForBitrate().
const unsigned CWMAX_11P = 1023
Contention Window maximal size.
as defined in Table 17-15 OFDM PHY characteristics in the IEEE 802.11-2007 standard
Definition at line 126 of file Consts80211p.h.
Referenced by Mac1609_4::initialize().
const unsigned CWMIN_11P = 15
Contention Window minimal size.
as defined in Table 17-15 OFDM PHY characteristics in the IEEE 802.11-2007 standard
Definition at line 120 of file Consts80211p.h.
Referenced by Mac1609_4::initialize().
const SimTime GUARD_INTERVAL_11P = SimTime().setRaw(4000000000UL)
1609.4 slot length
as defined in Table H.1 in the IEEE 1609.4-2010 standard It is the sum of SyncTolerance and MaxChSwitchTime as defined in 6.2.5 in the IEEE 1609.4-2010 Standard
Definition at line 139 of file Consts80211p.h.
Referenced by Mac1609_4::guardActive(), and Mac1609_4::timeLeftTillGuardOver().
const double N_DBPS_80211P[]
Initial value:
= {
        24,
        36,
        48,
        72,
        96,
        144,
        192,
        216
}
Number of Data Bits Per Symbol (N_NBPS) corresponding to bitrates in BITRATES_80211P.
as defined in Table 17-3 in the IEEE 802.11-2007 standard
Definition at line 44 of file Consts80211p.h.
Referenced by Mac1609_4::setParametersForBitrate().
const double NUM_BITRATES_80211P = 8
Bit rates for 802.11p.
as defined in Table 17-14 MIB attribute default values/ranges in the IEEE 802.11-2007 standard
Definition at line 28 of file Consts80211p.h.
Referenced by Mac1609_4::setParametersForBitrate().
const double PHY_HDR_BANDWIDTH = 3000000
Bitrate of the PLCP Signal.
as defined in Table 17.4 Timing-related parameters in the IEEE 802.11-2007 standard 24 bits in 8e-6 seconds
Definition at line 96 of file Consts80211p.h.
Referenced by Decider80211p::packetOk().
const double PHY_HDR_PLCPSIGNAL_DURATION = 8e-6
Duration of the PLCP Signal.
as defined in Table 17.4 Timing-related parameters in the IEEE 802.11-2007 standard
Definition at line 78 of file Consts80211p.h.
Referenced by Mac1609_4::getFrameDuration().
const int PHY_HDR_PLCPSIGNAL_LENGTH = 24
Length of the PLCP Signal.
as defined in Figure 17.1 PPDU frame format in the IEEE 802.11-2007 standard
Definition at line 84 of file Consts80211p.h.
Referenced by Decider80211p::packetOk().
const double PHY_HDR_PREAMBLE_DURATION = 32e-6
Duration of the PLCP Preamble.
as defined in Table 17.4 Timing-related parameters in the IEEE 802.11-2007 standard
Definition at line 72 of file Consts80211p.h.
Referenced by Decider80211p::checkIfSignalOk(), and Mac1609_4::getFrameDuration().
const int PHY_HDR_PSDU_HEADER_LENGTH = PHY_HDR_TOTAL_LENGTH - PHY_HDR_PLCPSIGNAL_LENGTH
Lenght of the PhyHeader sent with normal bitrate.
Definition at line 89 of file Consts80211p.h.
const int PHY_HDR_TOTAL_LENGTH = 46
Length of PHY HEADER.
as defined in 17.3.2 PLCP frame format in the IEEE 802.11-2007 standard 40bit header + 6 bit tail
Definition at line 66 of file Consts80211p.h.
Referenced by PhyLayer80211p::initialize().
const SimTime RADIODELAY_11P = SimTime().setRaw(1000000UL)
Time it takes to switch from Rx to Tx Mode.
as defined in Table 17-15 OFDM PHY characteristics in the IEEE 802.11-2007 standard
Definition at line 114 of file Consts80211p.h.
Referenced by Mac1609_4::handleSelfMsg().
const SimTime SIFS_11P = SimTime().setRaw(32000000UL)
Short interframe space.
as defined in Table 17-15 OFDM PHY characteristics in the IEEE 802.11-2007 standard
Definition at line 108 of file Consts80211p.h.
Referenced by Mac1609_4::EDCA::initiateTransmit(), Mac1609_4::EDCA::startContent(), and Mac1609_4::EDCA::stopContent().
const SimTime SLOTLENGTH_11P = SimTime().setRaw(13000000UL)
Slot Time for 10 MHz channel spacing.
as defined in Table 17-15 OFDM PHY characteristics in the IEEE 802.11-2007 standard
Definition at line 102 of file Consts80211p.h.
Referenced by Mac1609_4::EDCA::initiateTransmit(), Mac1609_4::EDCA::startContent(), and Mac1609_4::EDCA::stopContent().
const SimTime SWITCHING_INTERVAL_11P = SimTime().setRaw(50000000000UL)
1609.4 slot length
as defined in Table H.1 in the IEEE 1609.4-2010 standard
Definition at line 132 of file Consts80211p.h.
Referenced by Mac1609_4::handleSelfMsg(), and Mac1609_4::initialize().
const double T_SYM_80211P = 8e-6
Symbol interval.
as defined in Table 17-4 in the IEEE 802.11-2007 standard
Definition at line 59 of file Consts80211p.h.
Referenced by Mac1609_4::getFrameDuration().