Veins Framework: asserts.cc File Reference
asserts.cc File Reference
#include "asserts.h"
Functions
void fail (std::string msg)
Prints a fail message with the passed text.
void pass (std::string msg, bool hidePassed)
Prints a pass message with the passed text.
void assertTrue (std::string msg, bool value, bool hidePassed)
Asserts that the passed boolean value is true.
void assertFalse (std::string msg, bool value)
Asserts that the passed boolean value is false.
Variables
bool haltOnFails = false
bool displayPassed = true
Function Documentation
void assertFalse (std::string msg, bool value)
Asserts that the passed boolean value is false.
Definition at line 25 of file asserts.cc.
 { assertTrue(msg, !value); }
void assertTrue (std::string msg, bool value, bool hidePassed)
Asserts that the passed boolean value is true.
Definition at line 17 of file asserts.cc.
Referenced by assertFalse(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), Veins::mfcv_epidemic_app::handlePositionUpdate(), Veins::epidemic_app::handlePositionUpdate(), and Veins::default_veins_TraCI_TestApp::handlePositionUpdate().
{
         if (!value) {
                 fail(msg);
         } else {
                 pass(msg, hidePassed);
         }
 }
void fail (std::string msg)
Prints a fail message with the passed text.
Definition at line 6 of file asserts.cc.
Referenced by assertClose(), assertEqual(), assertEqualSilent(), assertNotEqual(), and assertTrue().
{
         std::cout << "FAILED: " << msg << std::endl;
         if(haltOnFails)
                 exit(1);
 }
void pass (std::string msg, bool hidePassed)
Prints a pass message with the passed text.
Definition at line 12 of file asserts.cc.
Referenced by assertClose(), assertEqual(), assertEqualSilent(), assertNotEqual(), and assertTrue().
{
         if(!hidePassed && displayPassed)
                 std::cout << "Passed: " << msg << std::endl;
 }
Variable Documentation
bool displayPassed = true
Definition at line 4 of file asserts.cc.
Referenced by pass().
bool haltOnFails = false
Definition at line 3 of file asserts.cc.
Referenced by fail().