Veins Framework: asserts.h File Reference
asserts.h File Reference
#include <iostream>
#include <string>
#include <sstream>
#include <stdlib.h>
#include <math.h>
Functions
template<class T , class T2 >
void fail (std::string msg, T expected, T2 actual)
Prints a expect-fail message with the passed text, the passed expected value and the passed actual value.
void fail (std::string msg)
Prints a fail message with the passed text.
void pass (std::string msg, bool hidePassed=false)
Prints a pass message with the passed text.
void assertTrue (std::string msg, bool value, bool hidePassed=false)
Asserts that the passed boolean value is true.
void assertFalse (std::string msg, bool value)
Asserts that the passed boolean value is false.
template<class T >
void assertClose (std::string msg, T target, T actual)
Asserts that the passed value is close to the passed expected value.
template<class T , class T2 >
void assertEqual (std::string msg, T target, T2 actual)
Asserts that the passed value is equal to the passed expected value.
template<class T , class T2 >
void assertEqualSilent (std::string msg, T target, T2 actual)
Asserts that the passed value is equal to the passed expected value.
template<class T , class T2 >
void assertNotEqual (std::string msg, T target, T2 actual)
Asserts that the passed value is not equal to the passed expected value.
template<class T >
std::string toString (const T &v)
Converts the passed value to a string.
Variables
bool haltOnFails
bool displayPassed
Function Documentation
template<class T > void assertClose (std::string msg, T target, T actual)
Asserts that the passed value is close to the passed expected value.
THis is used for floating point variables.
Definition at line 46 of file asserts.h.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), Veins::mfcv_epidemic_app::handlePositionUpdate(), and Veins::epidemic_app::handlePositionUpdate().
{
     if (fabs(target - actual) > 0.0000001) {
         fail(msg, target, actual);
         } else {
                 pass(msg);
         }
 }
template<class T , class T2 > void assertEqual (std::string msg, T target, T2 actual)
Asserts that the passed value is equal to the passed expected value.
Definition at line 58 of file asserts.h.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), Veins::mfcv_epidemic_app::handlePositionUpdate(), and Veins::epidemic_app::handlePositionUpdate().
{
     if (target == actual) {
         pass(msg);
         } else {
                 fail(msg, target, actual);
         }
 }
template<class T , class T2 > void assertEqualSilent (std::string msg, T target, T2 actual)
Asserts that the passed value is equal to the passed expected value.
Definition at line 70 of file asserts.h.
{
     if (target == actual) {
         pass(msg);
         } else {
                 fail(msg);
         }
 }
void assertFalse (std::string msg, bool value)
Asserts that the passed boolean value is false.
Definition at line 25 of file asserts.cc.
 { assertTrue(msg, !value); }
template<class T , class T2 > void assertNotEqual (std::string msg, T target, T2 actual)
Asserts that the passed value is not equal to the passed expected value.
Definition at line 82 of file asserts.h.
{
     if (target != actual) {
         pass(msg);
         } else {
                 fail(msg, target, actual);
         }
 }
void assertTrue (std::string msg, bool value, bool hidePassed = false)
Asserts that the passed boolean value is true.
Definition at line 17 of file asserts.cc.
Referenced by assertFalse(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), Veins::mfcv_epidemic_app::handlePositionUpdate(), Veins::epidemic_app::handlePositionUpdate(), and Veins::default_veins_TraCI_TestApp::handlePositionUpdate().
{
         if (!value) {
                 fail(msg);
         } else {
                 pass(msg, hidePassed);
         }
 }
template<class T , class T2 > void fail (std::string msg, T expected, T2 actual)
Prints a expect-fail message with the passed text, the passed expected value and the passed actual value.
Definition at line 17 of file asserts.h.
{
         std::cout << "FAILED: " << msg << ": value was '" << actual
                 << "' instead of '" << expected << "'" << std::endl;
 }
void fail (std::string msg)
Prints a fail message with the passed text.
Definition at line 6 of file asserts.cc.
Referenced by assertClose(), assertEqual(), assertEqualSilent(), assertNotEqual(), and assertTrue().
{
         std::cout << "FAILED: " << msg << std::endl;
         if(haltOnFails)
                 exit(1);
 }
void pass (std::string msg, bool hidePassed = false)
Prints a pass message with the passed text.
Definition at line 12 of file asserts.cc.
Referenced by assertClose(), assertEqual(), assertEqualSilent(), assertNotEqual(), and assertTrue().
{
         if(!hidePassed && displayPassed)
                 std::cout << "Passed: " << msg << std::endl;
 }
template<class T > std::string toString (const T & v)
Converts the passed value to a string.
There has to be an implementation of the << operator for the type of the variable and std::ostream:
std::ostream& operator<<(std::ostream& o, const T& v)
Definition at line 97 of file asserts.h.
Referenced by ConstMapping::toString().
{
         std::ostringstream o;
         o << v;
         return o.str();
 };
Variable Documentation
bool displayPassed
Definition at line 4 of file asserts.cc.
Referenced by pass().
bool haltOnFails
Definition at line 3 of file asserts.cc.
Referenced by fail().