Veins Framework: vehDist_rsu Class Reference
vehDist_rsu Class Reference
#include <vehDist_rsu.h>
Classes
struct messages
Public Member Functions
virtual void initialize (int stage)
Initialization of the module and some variables.
Public Member Functions inherited from BaseWaveApplLayer
~BaseWaveApplLayer ()
virtual void initialize_default_veins_TraCI (int stage)
virtual void initialize_minicurso_UFPI_TraCI (int stage)
virtual void initialize_epidemic (int stage)
virtual void initialize_mfcv_epidemic (int stage)
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed.
void saveMessagesOnFile (WaveShortMessage *wsm, string fileName)
void printHeaderfileExecution ()
void openFileAndClose (string fileName, bool append)
Public Member Functions inherited from BaseApplLayer
BaseApplLayer ()
BaseApplLayer (unsigned stacksize)
Public Member Functions inherited from BaseLayer
BaseLayer ()
BaseLayer (unsigned stacksize)
virtual ~BaseLayer ()
virtual void handleMessage (cMessage *)
Called every time a message arrives.
Public Member Functions inherited from Veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from BaseModule
BaseModule ()
Function to get the logging name of id.
BaseModule (unsigned stacksize)
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
Protected Member Functions
virtual void onBeacon (WaveShortMessage *wsm)
virtual void onData (WaveShortMessage *wsm)
virtual void sendWSM (WaveShortMessage *wsm)
void sendMessage (std::string blockedRoadId)
WaveShortMessage * prepareBeaconStatusWSM (std::string name, int lengthBits, t_channel channel, int priority, unsigned int rcvId, int serial)
void handleSelfMsg (cMessage *msg)
handle self messages
void restartFilesResult ()
virtual void finish ()
Called when the simulation has finished.
void printCountMessagesReceived ()
void messagesReceivedMeasuring (WaveShortMessage *wsm)
void handleLowerMsg (cMessage *msg)
handle messages from below
void onBeaconStatus (WaveShortMessage *wsm)
void onBeaconMessage (WaveShortMessage *wsm)
Protected Member Functions inherited from BaseWaveApplLayer
virtual WaveShortMessage * prepareWSM (std::string name, int dataLengthBits, t_channel channel, int priority, unsigned int rcvId, int serial=0)
virtual WaveShortMessage * prepareWSM_epidemic (string name, int dataLengthBits, t_channel channel, int priority, unsigned int rcvId, int serial=0)
virtual unsigned int MACToInteger ()
virtual void handlePositionUpdate (cObject *obj)
Protected Member Functions inherited from BaseApplLayer
void sendDelayedDown (cMessage *, simtime_t_cref)
Sends a message delayed to the lower layer.
virtual const LAddress::L3Type myApplAddr () const
Return my application layer address.
virtual void handleLowerControl (cMessage *msg)
Handle control messages from lower layer.
virtual void handleUpperMsg (cMessage *msg)
Handle messages from upper layer.
virtual void handleUpperControl (cMessage *msg)
Handle control messages from upper layer.
Protected Member Functions inherited from BaseLayer
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from Veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
Protected Attributes
AnnotationManager * annotations
BaseMobility * mobi
bool sentMessage
map< string, struct messages > messagesReceived
Protected Attributes inherited from BaseWaveApplLayer
std::ofstream myfile
int beaconLengthBits
int beaconPriority
bool sendData
bool sendBeacons
simtime_t individualOffset
int dataLengthBits
bool dataOnSch
int dataPriority
Coord curPosition
int mySCH
int myId
cMessage * sendBeaconEvt
WaveAppToMac1609_4Interface * myMac
int sendSummaryVectorInterval
unsigned int maximumEpidemicBufferSize
unsigned int hopCount
unsigned int maximumMfcvEpidemicBufferSize
string source
string target
int target_x
int target_y
string fileMessagesNameUnicast
string fileMessagesNameBroadcast
string fileMessagesCount
string fileMessagesDrop
string fileMessagesGenerated
int repeatNumber
unsigned int beaconMessageHopLimit
int numVehicles
int countGenerateBeaconMessage
double ttlBeaconMessage
double timeLimitGenerateBeaconMessage
string stringTmp
double doubleTmp
Protected Attributes inherited from BaseApplLayer
int headerLength
Length of the ApplPkt header.
Protected Attributes inherited from BaseLayer
PassedMessage * passedMsg
The last message passed through this layer.
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
Protected Attributes inherited from Veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from BaseModule
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Public Types inherited from BaseWaveApplLayer
enum WaveApplMessageKinds {
SERVICE_PROVIDER = LAST_BASE_APPL_MESSAGE_KIND, SEND_BEACON_EVT, SEND_BEACON_EVT_minicurso, SERVICE_EXPIRED_EVT,
SERVICE_QUERY_EVT, SERVICE_EVT, MOBILITY_EVT, SEND_BEACON_EVT_epidemic,
SEND_BEACON_EVT_mfcv_epidemic
}
Public Types inherited from BaseApplLayer
enum BaseApplMessageKinds { LAST_BASE_APPL_MESSAGE_KIND = 25000 }
The message kinds this layer uses.
enum BaseApplControlKinds { LAST_BASE_APPL_CONTROL_KIND = 25500 }
The control message kinds this layer uses.
Static Public Attributes inherited from BaseLayer
static const simsignalwrap_t catPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_PACKET_NAME)
SignalID for packets.
static const simsignalwrap_t catPassedMsgSignal = simsignalwrap_t(MIXIM_SIGNAL_PASSEDMSG_NAME)
Signal for passed messages.
static const simsignalwrap_t catDroppedPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_DROPPEDPACKET_NAME)
Signal for dropped packets.
Static Protected Attributes inherited from BaseWaveApplLayer
static const simsignalwrap_t mobilityStateChangedSignal = simsignalwrap_t(MIXIM_SIGNAL_MOBILITY_CHANGE_NAME)
static unsigned short int vehCount = 0
static unsigned short int rsuCount = 0
Static Protected Attributes inherited from BaseModule
static const simsignalwrap_t catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME)
Stores the category of the HostState.
Detailed Description
Definition at line 28 of file vehDist_rsu.h.
Member Function Documentation
void vehDist_rsu::finish () protected virtual
Called when the simulation has finished.
Reimplemented from BaseWaveApplLayer.
Definition at line 228 of file vehDist_rsu.cc.
{
     printCountMessagesReceived();
 }
void vehDist_rsu::handleLowerMsg (cMessage * msg) protected virtual
handle messages from below
Reimplemented from BaseWaveApplLayer.
Definition at line 50 of file vehDist_rsu.cc.
{
     WaveShortMessage* wsm = dynamic_cast<WaveShortMessage*>(msg);
     ASSERT(wsm);
     if (std::string(wsm->getName()) == "beacon") {
         onBeacon(wsm);
     }
     else if (std::string(wsm->getName()) == "data") {
         onData(wsm);
     }
 //
     else if (std::string(wsm->getName()) == "data2veh") {
         cout << "data2veh now" << endl;
     }
     else if (std::string(wsm->getName()) == "data2rsu") {
         cout << "data2rsu now" << endl;
     }
     else if (std::string(wsm->getName()) == "beaconStatus") {
         onBeaconStatus(wsm);
     }
     else if (std::string(wsm->getName()) == "beaconMessage") {
         onBeaconMessage(wsm);
     }
 //
     else {
         DBG << "unknown message (" << wsm->getName() << ")  received\n";
     }
     delete(msg);
 }
void vehDist_rsu::handleSelfMsg (cMessage * msg) protected virtual
handle self messages
Reimplemented from BaseWaveApplLayer.
Definition at line 181 of file vehDist_rsu.cc.
{
     switch (msg->getKind()) {
         case SEND_BEACON_EVT: {
             //sendWSM(prepareWSM("beacon", beaconLengthBits, type_CCH, beaconPriority, 0, -1));
             sendWSM(prepareBeaconStatusWSM("beaconStatus", beaconLengthBits, type_CCH, beaconPriority, 0, -1));
             scheduleAt(simTime() + par("beaconInterval").doubleValue(), sendBeaconEvt);
             break;
         }
         default: {
             if (msg)
                 DBG << "APP: Error: Got Self Message of unknown kind! Name: " << msg->getName() << endl;
             break;
         }
     }
 }
void vehDist_rsu::initialize (int stage) virtual
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseLayer.
Then we have to intialize the gates and - if necessary - some own variables.
Reimplemented from BaseApplLayer.
Definition at line 25 of file vehDist_rsu.cc.
{
     BaseWaveApplLayer::initialize_default_veins_TraCI(stage);
     if (stage == 0) {
         mobi = dynamic_cast<BaseMobility*> (getParentModule()->getSubmodule("mobility"));
         ASSERT(mobi);
         annotations = AnnotationManagerAccess().getIfExists();
         ASSERT(annotations);
         beaconMessageHopLimit = par("beaconMessageHopLimit").doubleValue();
         stringTmp = ev.getConfig()->getConfigValue("seed-set");
         repeatNumber = atoi(stringTmp.c_str()); // number of execution (${repetition})
         restartFilesResult();
         //cout << " " << findHost()->getFullName() << " entered in the scenario" << endl;
     }
 }
void vehDist_rsu::messagesReceivedMeasuring (WaveShortMessage * wsm) protected
Definition at line 121 of file vehDist_rsu.cc.
Referenced by onBeaconMessage().
{
     map<string, struct messages>::iterator it = messagesReceived.find(wsm->getGlobalMessageIdentificaton());
     if (it != messagesReceived.end()){
         it->second.hops += ", ";
         it->second.hops += to_string(beaconMessageHopLimit - wsm->getHopCount());
         it->second.HopsCount = it->second.HopsCount + 1;
         it->second.averageHops += (beaconMessageHopLimit - wsm->getHopCount());
         if ((beaconMessageHopLimit - wsm->getHopCount()) > it->second. maxHop){
             it->second.maxHop = (beaconMessageHopLimit - wsm->getHopCount());
         }
         if ((beaconMessageHopLimit - wsm->getHopCount()) < it->second. minHop){
              it->second.minHop = (beaconMessageHopLimit - wsm->getHopCount());
          }
         it->second.timeAverage += (simTime() - wsm->getTimestamp());
         it->second.times += ", ";
         simtime_t tmpTime = (simTime() - wsm->getTimestamp());
         it->second.times += tmpTime.str();
     } else {
         struct messages m;
         m.HopsCount = 1;
         m.wsmData = wsm->getWsmData();
         m.hops = to_string(beaconMessageHopLimit - wsm->getHopCount());
         m.maxHop = m.minHop = m.averageHops = beaconMessageHopLimit - wsm->getHopCount();
         m.averageHops = (beaconMessageHopLimit - wsm->getHopCount());
         m.timeAverage = (simTime() - wsm->getTimestamp());
         simtime_t tmpTime = (simTime() - wsm->getTimestamp());
         m.times = tmpTime.str();
         messagesReceived.insert(make_pair(wsm->getGlobalMessageIdentificaton(), m));
     }
 }
void vehDist_rsu::onBeacon (WaveShortMessage * wsm) protected virtual
Implements BaseWaveApplLayer.
Definition at line 43 of file vehDist_rsu.cc.
Referenced by handleLowerMsg().
{
 }
void vehDist_rsu::onBeaconMessage (WaveShortMessage * wsm) protected
Definition at line 109 of file vehDist_rsu.cc.
Referenced by handleLowerMsg().
{
     if (strcmp(wsm->getRecipientAddressTemporary(), findHost()->getFullName()) == 0){
         findHost()->bubble("Received Message");
         saveMessagesOnFile(wsm, fileMessagesNameUnicast);
         messagesReceivedMeasuring(wsm);
     }
     else{
         saveMessagesOnFile(wsm, fileMessagesNameBroadcast);
     }
 }
void vehDist_rsu::onBeaconStatus (WaveShortMessage * wsm) protected
Definition at line 46 of file vehDist_rsu.cc.
Referenced by handleLowerMsg().
{
     // to do?
 }
void vehDist_rsu::onData (WaveShortMessage * wsm) protected virtual
Implements BaseWaveApplLayer.
Definition at line 106 of file vehDist_rsu.cc.
Referenced by handleLowerMsg().
{
 }
WaveShortMessage * vehDist_rsu::prepareBeaconStatusWSM (std::string name, int lengthBits, t_channel channel, int priority, unsigned int rcvId, int serial) protected
Definition at line 155 of file vehDist_rsu.cc.
Referenced by handleSelfMsg().
{
     WaveShortMessage* wsm = new WaveShortMessage(name.c_str());
     wsm->addBitLength(headerLength);
     wsm->addBitLength(lengthBits);
     switch (channel) {
         case type_SCH: wsm->setChannelNumber(Channels::SCH1); break; //will be rewritten at Mac1609_4 to actual Service Channel. This is just so no controlInfo is needed
         case type_CCH: wsm->setChannelNumber(Channels::CCH); break;
     }
     wsm->setPsid(0);
     wsm->setPriority(priority);
     wsm->setWsmVersion(1);
     wsm->setSerial(serial);
     wsm->setTimestamp(simTime());
     wsm->setSenderPos(curPosition);
     wsm->setSenderAddressTemporary(findHost()->getFullName());
     //beacon don't need
     //wsm->setRecipientAddressString(); => "BROADCAST"
     //wsm->setSource(source);
     //wsm->setTarget(target);
     DBG << "Creating BeaconStatus with Priority " << priority << " at Applayer at " << wsm->getTimestamp() << std::endl;
     return wsm;
 }
void vehDist_rsu::printCountMessagesReceived () protected
Definition at line 196 of file vehDist_rsu.cc.
Referenced by finish().
{
     myfile.open (fileMessagesCount, std::ios_base::app);
     if (messagesReceived.empty()) {
         myfile << "messagesReceived from " << findHost()->getFullName() << " is empty now" << endl;
     } else {
         myfile << "messagesReceived from " << findHost()->getFullName() << endl;
         map<string, struct messages>::iterator it;
         for (it = messagesReceived.begin(); it != messagesReceived.end(); it++) {
             myfile << endl;
             myfile << "Message Id: " << it->first << endl;
             myfile << "Count received: " << it->second.HopsCount << endl;
             myfile << it->second.wsmData << endl;
             myfile << "Hops: " << it->second.hops << endl;
             myfile << "Sum hops: " << it->second.averageHops << endl;
             it->second.averageHops = (it->second.averageHops/it->second.HopsCount);
             myfile << "Average Hops: " << it->second.averageHops << endl;
             myfile << "Max Hop: " << it->second.maxHop << endl;
             myfile << "Min Hop: " << it->second.minHop << endl;
             myfile << "Times: " << it->second.times << endl;
             myfile << "Sum times: " << it->second.timeAverage << endl;
             myfile << "Avegare time to received: " << (it->second.timeAverage/it->second.HopsCount) << endl;
         }
         myfile << endl << "### Count Messages Received: " << messagesReceived.size() << " ###" << endl << endl;
         // ver: 34 geradas, mas s 2* entregues
         myfile << endl;
     }
     myfile.close();
 }
void vehDist_rsu::restartFilesResult () protected
Definition at line 80 of file vehDist_rsu.cc.
Referenced by initialize().
{
     fileMessagesNameBroadcast = "results/rsuBroadcastMessages.txt";
     fileMessagesNameUnicast = "results/";
     fileMessagesNameUnicast += findHost()->getFullName();
     fileMessagesNameUnicast += "MessagesReceived.txt";
     fileMessagesCount = "results/";
     fileMessagesCount += findHost()->getFullName();
     fileMessagesCount += "CountMessagesReceived.txt";
      //fileMessagesDrop = ...
     if ((strcmp(findHost()->getFullName(), "rsu[0]") == 0) && (repeatNumber == 0)) { //Open a new file (blank)
         system("mkdir results 2> /dev/null"); //create a folder results
         openFileAndClose(fileMessagesNameBroadcast, false);
         openFileAndClose(fileMessagesNameUnicast, false);
         openFileAndClose(fileMessagesCount, false);
     }else if ((strcmp(findHost()->getFullName(), "rsu[0]") == 0) && (repeatNumber != 0)) { // for just append
         openFileAndClose(fileMessagesNameBroadcast, true);
         openFileAndClose(fileMessagesNameUnicast, true);
         openFileAndClose(fileMessagesCount, true);
     }
 }
void vehDist_rsu::sendMessage (std::string blockedRoadId) protected
Definition at line 236 of file vehDist_rsu.cc.
{
     sentMessage = true;
     t_channel channel = dataOnSch ? type_SCH : type_CCH;
     WaveShortMessage* wsm = prepareWSM("data2rsu", dataLengthBits, channel, dataPriority, -1,2);
     wsm->setWsmData(blockedRoadId.c_str());
     sendWSM(wsm);
 }
void vehDist_rsu::sendWSM (WaveShortMessage * wsm) protected virtual
Reimplemented from BaseWaveApplLayer.
Definition at line 232 of file vehDist_rsu.cc.
Referenced by handleSelfMsg(), and sendMessage().
{
     sendDelayedDown(wsm,individualOffset);
 }
Member Data Documentation
AnnotationManager* vehDist_rsu::annotations protected
Definition at line 32 of file vehDist_rsu.h.
Referenced by initialize().
map<string, struct messages> vehDist_rsu::messagesReceived protected
Definition at line 47 of file vehDist_rsu.h.
Referenced by messagesReceivedMeasuring(), and printCountMessagesReceived().
BaseMobility* vehDist_rsu::mobi protected
Definition at line 33 of file vehDist_rsu.h.
Referenced by initialize().
bool vehDist_rsu::sentMessage protected
Definition at line 34 of file vehDist_rsu.h.
Referenced by sendMessage().
The documentation for this class was generated from the following files:
vehDist_rsu.h
vehDist_rsu.cc