Veins Framework: BaseApplLayer Class Reference
BaseApplLayer Class Reference
Base class for the application layer.
#include <BaseApplLayer.h>
Public Types
enum BaseApplMessageKinds { LAST_BASE_APPL_MESSAGE_KIND = 25000 }
The message kinds this layer uses.
enum BaseApplControlKinds { LAST_BASE_APPL_CONTROL_KIND = 25500 }
The control message kinds this layer uses.
Public Member Functions
BaseApplLayer ()
BaseApplLayer (unsigned stacksize)
virtual void initialize (int)
Initialization of the module and some variables.
Public Member Functions inherited from BaseLayer
BaseLayer ()
BaseLayer (unsigned stacksize)
virtual ~BaseLayer ()
virtual void handleMessage (cMessage *)
Called every time a message arrives.
virtual void finish ()
Called when the simulation has finished.
Public Member Functions inherited from Veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from BaseModule
BaseModule ()
Function to get the logging name of id.
BaseModule (unsigned stacksize)
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed.
Protected Member Functions
void sendDelayedDown (cMessage *, simtime_t_cref)
Sends a message delayed to the lower layer.
virtual const LAddress::L3Type myApplAddr () const
Return my application layer address.
Handle Messages
Functions to redefine by the programmer
These are the functions provided to add own functionality to your modules. These functions are called whenever a self message or a data message from the upper or lower layer arrives respectively.
virtual void handleSelfMsg (cMessage *msg)
Handle self messages such as timer...
virtual void handleLowerMsg (cMessage *msg)
Handle messages from lower layer.
virtual void handleLowerControl (cMessage *msg)
Handle control messages from lower layer.
virtual void handleUpperMsg (cMessage *msg)
Handle messages from upper layer.
virtual void handleUpperControl (cMessage *msg)
Handle control messages from upper layer.
Protected Member Functions inherited from BaseLayer
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from Veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
Protected Attributes
int headerLength
Length of the ApplPkt header.
Protected Attributes inherited from BaseLayer
PassedMessage * passedMsg
The last message passed through this layer.
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
Protected Attributes inherited from Veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from BaseModule
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Static Public Attributes inherited from BaseLayer
static const simsignalwrap_t catPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_PACKET_NAME)
SignalID for packets.
static const simsignalwrap_t catPassedMsgSignal = simsignalwrap_t(MIXIM_SIGNAL_PASSEDMSG_NAME)
Signal for passed messages.
static const simsignalwrap_t catDroppedPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_DROPPEDPACKET_NAME)
Signal for dropped packets.
Static Protected Attributes inherited from BaseModule
static const simsignalwrap_t catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME)
Stores the category of the HostState.
Detailed Description
Base class for the application layer.
This is the generic class for all application layer modules. If you want to implement your own application layer you have to subclass your module from this class.
Author
Daniel Willkomm
Definition at line 44 of file BaseApplLayer.h.
Member Enumeration Documentation
enum BaseApplLayer::BaseApplControlKinds
The control message kinds this layer uses.
Enumerator
LAST_BASE_APPL_CONTROL_KIND
Stores the id on which classes extending BaseAppl should continue their own control kinds.
Definition at line 54 of file BaseApplLayer.h.
{
                 LAST_BASE_APPL_CONTROL_KIND = 25500,
         };
enum BaseApplLayer::BaseApplMessageKinds
The message kinds this layer uses.
Enumerator
LAST_BASE_APPL_MESSAGE_KIND
Stores the id on which classes extending BaseAppl should continue their own message kinds.
Definition at line 48 of file BaseApplLayer.h.
{
                 LAST_BASE_APPL_MESSAGE_KIND = 25000,
         };
Constructor & Destructor Documentation
BaseApplLayer::BaseApplLayer () inline
Definition at line 67 of file BaseApplLayer.h.
                         : BaseLayer()
         {}
BaseApplLayer::BaseApplLayer (unsigned stacksize) inline
Definition at line 69 of file BaseApplLayer.h.
                                           : BaseLayer(stacksize)
         {}
Member Function Documentation
virtual void BaseApplLayer::handleLowerControl (cMessage * msg) inline protected virtual
Handle control messages from lower layer.
The basic application layer just silently deletes all messages it receives.
Implements BaseLayer.
Definition at line 118 of file BaseApplLayer.h.
{
                 EV << "BaseApplLayer: handleLowerControl not redefined; delete msg\n";
                 delete msg;
         };
virtual void BaseApplLayer::handleLowerMsg (cMessage * msg) inline protected virtual
Handle messages from lower layer.
Redefine this function if you want to process messages from lower layers.
The basic application layer just silently deletes all messages it receives.
Implements BaseLayer.
Reimplemented in BaseWaveApplLayer, vehDist, mfcv, vehDist_rsu, Veins::default_veins_TraCI_TestApp, Veins::epidemic_app, Veins::mfcv_epidemic_app, Veins::minicurso_UFPI_TraCI_TestApp, mfcv_rsu, AdvancedFlooding, and Flooding.
Definition at line 107 of file BaseApplLayer.h.
{
                 EV << "BaseApplLayer: handleLowerMsg not redefined; delete msg\n";
                 delete msg;
         };
virtual void BaseApplLayer::handleSelfMsg (cMessage * msg) inline protected virtual
Handle self messages such as timer...
Define this function if you want to process timer or other kinds of self messages
Implements BaseLayer.
Reimplemented in mfcv_epidemic, BaseWaveApplLayer, mfcv_epidemic_rsu, vehDist, minicurso_UFPI_TraCI, mfcv, Veins::default_veins_TraCI_TestApp, Veins::epidemic_app, Veins::mfcv_epidemic_app, Veins::minicurso_UFPI_TraCI_TestApp, vehDist_rsu, service_discovery, test1, AdvancedFlooding, mfcv_rsu, minicurso_UFPI_TraCI_RSU, osdp, Flooding, service_discovery_RSU, test1_rsu, and osdp_RSU.
Definition at line 93 of file BaseApplLayer.h.
{
                 EV << "BaseApplLayer: handleSelfMsg not redefined; delete msg\n";
                 delete msg;
         };
virtual void BaseApplLayer::handleUpperControl (cMessage * msg) inline protected virtual
Handle control messages from upper layer.
Implements BaseLayer.
Definition at line 135 of file BaseApplLayer.h.
{
                 assert(false);
                 opp_error("Application has no upper layers!");
                 delete msg;
         }
virtual void BaseApplLayer::handleUpperMsg (cMessage * msg) inline protected virtual
Handle messages from upper layer.
This function is pure virtual here, because there is no reasonable guess what to do with it by default.
Implements BaseLayer.
Definition at line 128 of file BaseApplLayer.h.
{
                 assert(false);
                 opp_error("Application has no upper layers!");
                 delete msg;
         }
void BaseApplLayer::initialize (int stage) virtual
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseLayer.
Then we have to intialize the gates and - if necessary - some own variables.
Reimplemented from BaseLayer.
Reimplemented in Veins::default_veins_TraCI_TestApp, Veins::epidemic_app, Veins::mfcv_epidemic_app, Veins::minicurso_UFPI_TraCI_TestApp, epidemic, mfcv_epidemic, mfcv, minicurso_UFPI_TraCI, epidemic_rsu, mfcv_epidemic_rsu, default_veins_TraCI, default_veins_TraCI_RSU, mfcv_rsu, minicurso_UFPI_TraCI_RSU, vehDist, vehDist_rsu, AdvancedFlooding, service_discovery, test1, Flooding, osdp, osdp_RSU, service_discovery_RSU, and test1_rsu.
Definition at line 33 of file BaseApplLayer.cc.
Referenced by Flooding::initialize(), AdvancedFlooding::initialize(), Veins::mfcv_epidemic_app::initialize(), Veins::minicurso_UFPI_TraCI_TestApp::initialize(), Veins::epidemic_app::initialize(), Veins::default_veins_TraCI_TestApp::initialize(), BaseWaveApplLayer::initialize_default_veins_TraCI(), BaseWaveApplLayer::initialize_epidemic(), BaseWaveApplLayer::initialize_mfcv_epidemic(), and BaseWaveApplLayer::initialize_minicurso_UFPI_TraCI().
 {
     BaseLayer::initialize(stage);
     if(stage==0){
         headerLength= par("headerLength");
     }
 }
virtual const LAddress::L3Type BaseApplLayer::myApplAddr () const inline protected virtual
Return my application layer address.
We use the node module index as application address
Definition at line 151 of file BaseApplLayer.h.
{
                 return LAddress::L3Type( getParentModule()->getIndex() );
         };
void BaseApplLayer::sendDelayedDown (cMessage * msg, simtime_t_cref delay) protected
Sends a message delayed to the lower layer.
Send message down to lower layer.
Definition at line 44 of file BaseApplLayer.cc.
Referenced by osdp_RSU::sendWSM(), service_discovery_RSU::sendWSM(), test1_rsu::sendWSM(), Flooding::sendWSM(), mfcv_rsu::sendWSM(), minicurso_UFPI_TraCI_RSU::sendWSM(), default_veins_TraCI_RSU::sendWSM(), AdvancedFlooding::sendWSM(), default_veins_TraCI::sendWSM(), vehDist_rsu::sendWSM(), mfcv::sendWSM(), vehDist::sendWSM(), mfcv_epidemic_rsu::sendWSM(), epidemic_rsu::sendWSM(), minicurso_UFPI_TraCI::sendWSM(), and BaseWaveApplLayer::sendWSM().
{
     recordPacket(PassedMessage::OUTGOING, PassedMessage::LOWER_DATA, msg);
     sendDelayed(msg, delay, lowerLayerOut);
 }
Member Data Documentation
int BaseApplLayer::headerLength protected
Length of the ApplPkt header.
Definition at line 63 of file BaseApplLayer.h.
Referenced by vehDist::generateBeaconMessage(), Flooding::initialize(), AdvancedFlooding::initialize(), initialize(), BaseWaveApplLayer::initialize_default_veins_TraCI(), BaseWaveApplLayer::initialize_epidemic(), BaseWaveApplLayer::initialize_mfcv_epidemic(), BaseWaveApplLayer::initialize_minicurso_UFPI_TraCI(), vehDist_rsu::prepareBeaconStatusWSM(), vehDist::prepareBeaconStatusWSM(), Flooding::prepareWSM(), AdvancedFlooding::prepareWSM(), BaseWaveApplLayer::prepareWSM(), BaseWaveApplLayer::prepareWSM_epidemic(), mfcv_epidemic_rsu::prepareWSM_mfcv_epidemic(), mfcv::prepareWSM_node(), and mfcv_rsu::prepareWSM_rsu().
The documentation for this class was generated from the following files:
BaseApplLayer.h
BaseApplLayer.cc