Veins Framework: SimpleConstMapping Class Reference
SimpleConstMapping Class Reference abstract
Abstract subclass of ConstMapping which can be used as base for any ConstMapping implementation with read access of constant complexity.
#include <MappingBase.h>
Public Member Functions
virtual ConstMappingIterator * createConstIterator () const
Returns a pointer of a new Iterator which is able to iterate over the Mapping.
virtual ConstMappingIterator * createConstIterator (const Argument &pos) const
Returns a pointer of a new Iterator which is able to iterate over the Mapping.
SimpleConstMapping (const DimensionSet &dims)
Initializes a not yet iterateable SimpleConstmapping with the passed DimensionSet as domain.
SimpleConstMapping (const DimensionSet &dims, const Argument &key)
Fully initializes this mapping with the passed position as key entry.
SimpleConstMapping (const DimensionSet &dims, const Argument &key1, const Argument &key2)
Fully initializes this mapping with the passed two positions as key entries.
SimpleConstMapping (const DimensionSet &dims, const Argument &min, const Argument &max, const Argument &interval)
Fully initializes this mapping with the key entries defined by the passed min, max and interval values.
void initializeArguments (const Argument &key)
Initializes the key entry set with the passed position as entry.
void initializeArguments (const Argument &key1, const Argument &key2)
Initializes the key entry set with the passed two positions as entries.
void initializeArguments (const Argument &min, const Argument &max, const Argument &interval)
Initializes the key entry set with the passed min, max and interval-Arguments.
virtual argument_value_t getValue (const Argument &pos) const =0
Returns the value of the mapping at the passed position.
ConstMapping * constClone () const =0
creates a clone of this mapping.
Public Member Functions inherited from ConstMapping
ConstMapping ()
Initializes the ConstMapping with a the time dimension as domain.
ConstMapping (const DimensionSet &dimSet)
Initializes the ConstMapping with the passed DimensionSet as Domain.
virtual ~ConstMapping ()
argument_value_t operator[] (const Argument &pos) const
Returns the value of this Mapping at the position specified by the passed Argument.
const DimensionSet & getDimensionSet () const
Returns this Mappings domain as DimensionSet.
template<class stream >
stream & print (stream &out, argument_value_cref_t lTimeScale=argument_value_t(1000), argument_value_cref_t lLeftColScale=Argument::MappedOne, const std::string &sTableHead=std::string("o\\ms"), const Dimension *const pOnlyDim=NULL) const
Prints the Mapping to an output stream.
Protected Types
typedef std::set< Argument > KeyEntrySet
Type for a set of Arguments defining key entries.
Protected Member Functions
void createKeyEntries (const Argument &from, const Argument &to, const Argument &step, Argument &pos)
Utility method to fill add range of key entries in the time dimension to the key entry set.
void createKeyEntries (const Argument &from, const Argument &to, const Argument &step, DimensionSet::const_iterator curDim, Argument &pos)
Utility method to fill add range of key entries in the passed dimension (and recursively its sub dimensions) to the key entry set.
Protected Attributes
KeyEntrySet keyEntries
A set of Arguments defining the "points of interest" an iterator should iterate over.
Protected Attributes inherited from ConstMapping
DimensionSet dimensions
The dimensions of this mappings domain.
Additional Inherited Members
Public Types inherited from ConstMapping
typedef Argument::mapped_type argument_value_t
typedef Argument::mapped_type_cref argument_value_cref_t
Detailed Description
Abstract subclass of ConstMapping which can be used as base for any ConstMapping implementation with read access of constant complexity.
Any subclass only has to implement the "getValue()" and the "clone()"-method.
The subclass has to define the "points of interest" an iterator should iterate over. This should be done either at construction time or later by calling the "initializeArguments()"-method.
The SimpleConstMapping class provides Iterator creation by using the SimpleConstMappingIterator which assumes that the underlying ConstMappings getValue()-method is fast enough to be called on every iteration step (which means constant complexity).
Author
Karl Wessel
Definition at line 1324 of file MappingBase.h.
Member Typedef Documentation
typedef std::set<Argument> SimpleConstMapping::KeyEntrySet protected
Type for a set of Arguments defining key entries.
Definition at line 1327 of file MappingBase.h.
Constructor & Destructor Documentation
SimpleConstMapping::SimpleConstMapping (const DimensionSet & dims) inline
Initializes a not yet iterateable SimpleConstmapping with the passed DimensionSet as domain.
Definition at line 1374 of file MappingBase.h.
                                                     :
                 ConstMapping(dims) {}
SimpleConstMapping::SimpleConstMapping (const DimensionSet & dims, const Argument & key) inline
Fully initializes this mapping with the passed position as key entry.
A SimpleConstMapping initialized by this constructor is able to return a valid ConstIterator.
Definition at line 1384 of file MappingBase.h.
                                                                :
                 ConstMapping(dims){
                 initializeArguments(key);
         }
SimpleConstMapping::SimpleConstMapping (const DimensionSet & dims, const Argument & key1, const Argument & key2) inline
Fully initializes this mapping with the passed two positions as key entries.
A SimpleConstMapping initialized by this constructor is able to return a valid ConstIterator.
Definition at line 1398 of file MappingBase.h.
                                                                                       :
                 ConstMapping(dims){
                 initializeArguments(key1, key2);
         }
SimpleConstMapping::SimpleConstMapping (const DimensionSet & dims, const Argument & min, const Argument & max, const Argument & interval) inline
Fully initializes this mapping with the key entries defined by the passed min, max and interval values.
A SimpleConstMapping initialized by this constructor is able to return a valid ConstIterator.
Definition at line 1412 of file MappingBase.h.
                                                                                                               :
                 ConstMapping(dims){
                 initializeArguments(min, max, interval);
         }
Member Function Documentation
ConstMapping* SimpleConstMapping::constClone () const pure virtual
creates a clone of this mapping.
This method has to be implemented by every subclass.
Implements ConstMapping.
Implemented in ConstantSimpleConstMapping, TwoRayInterferenceModel::Mapping, JakesFadingMapping, and SimplePathlossConstMapping.
virtual ConstMappingIterator* SimpleConstMapping::createConstIterator () const inline virtual
Returns a pointer of a new Iterator which is able to iterate over the Mapping.
This method asserts that the mapping had been fully initialized.
Implements ConstMapping.
Definition at line 1355 of file MappingBase.h.
{
                 return new SimpleConstMappingIterator(this, &keyEntries);
         }
virtual ConstMappingIterator* SimpleConstMapping::createConstIterator (const Argument & pos) const inline virtual
Returns a pointer of a new Iterator which is able to iterate over the Mapping.
The iterator starts at the passed position.
This method asserts that the mapping had been fully initialized.
Implements ConstMapping.
Definition at line 1365 of file MappingBase.h.
{
                 return new SimpleConstMappingIterator(this, &keyEntries, pos);
         }
void SimpleConstMapping::createKeyEntries (const Argument & from, const Argument & to, const Argument & step, Argument & pos) protected
Utility method to fill add range of key entries in the time dimension to the key entry set.
Definition at line 343 of file MappingBase.cc.
Referenced by createKeyEntries(), and initializeArguments().
 {
         //get iteration borders and steps
         simtime_t_cref fromT = from.getTime();
         simtime_t_cref toT   = to.getTime();
         simtime_t_cref stepT = step.getTime();
         //iterate over interval without the end of the interval
         for(simtime_t t = fromT; t < toT; t += stepT){
                 //create key entry at current position
                 pos.setTime(t);
                 keyEntries.insert(pos);
         }
         //makes sure that the end of the interval becomes it own key entry
         pos.setTime(toT);
         keyEntries.insert(pos);
 }
void SimpleConstMapping::createKeyEntries (const Argument & from, const Argument & to, const Argument & step, DimensionSet::const_iterator curDim, Argument & pos) protected
Utility method to fill add range of key entries in the passed dimension (and recursively its sub dimensions) to the key entry set.
Definition at line 362 of file MappingBase.cc.
 {
         //get the dimension to iterate over
         DimensionSet::const_reference d = *curDim;
         //increase iterator to next dimension (means curDim now stores the next dimension)
         --curDim;
         bool nextIsTime = (*curDim == Dimension::time);
         //get our iteration borders and steps
         argument_value_cref_t fromD = from.getArgValue(d);
         argument_value_cref_t toD   = to.getArgValue(d);
         argument_value_cref_t stepD = step.getArgValue(d);
         //iterate over interval without the last entry
         for(argument_value_t i = fromD; i < toD; i += stepD){
                 pos.setArgValue(d, i); //update position
                 //call iteration over sub dimension
                 if(nextIsTime){
                         createKeyEntries(from, to, step, pos);
                 } else {
                         createKeyEntries(from, to, step, curDim, pos);
                 }
         }
         //makes sure that the end of the interval has its own key entry
         pos.setArgValue(d, toD);
         if(nextIsTime){
                 createKeyEntries(from, to, step, pos);
         } else {
                 createKeyEntries(from, to, step, curDim, pos);
         }
 }
virtual argument_value_t SimpleConstMapping::getValue (const Argument & pos) const pure virtual
Returns the value of the mapping at the passed position.
This method has to be implemented by every subclass and should only have constant complexity.
Implements ConstMapping.
Implemented in ConstantSimpleConstMapping, TwoRayInterferenceModel::Mapping, JakesFadingMapping, and SimplePathlossConstMapping.
void SimpleConstMapping::initializeArguments (const Argument & key) inline
Initializes the key entry set with the passed position as entry.
Convenience method for simple mappings.
Definition at line 1425 of file MappingBase.h.
Referenced by BasePhyLayer::getThermalNoise().
{
                 keyEntries.clear();
                 keyEntries.insert(key);
         }
void SimpleConstMapping::initializeArguments (const Argument & key1, const Argument & key2) inline
Initializes the key entry set with the passed two positions as entries.
Convenience method for simple mappings.
Definition at line 1436 of file MappingBase.h.
{
                 keyEntries.clear();
                 keyEntries.insert(key1);
                 keyEntries.insert(key2);
         }
void SimpleConstMapping::initializeArguments (const Argument & min, const Argument & max, const Argument & interval)
Initializes the key entry set with the passed min, max and interval-Arguments.
After a call to this method this SimpleConstMapping is able to return a valid ConstIterator.
Definition at line 398 of file MappingBase.cc.
{
         keyEntries.clear();
         DimensionSet::const_iterator dimIt = --(dimensions.end());
         Argument                     pos   = min;
         if(*dimIt == Dimension::time)
                 createKeyEntries(min, max, interval, pos);
         else
                 createKeyEntries(min, max, interval, dimIt, pos);
 }
Member Data Documentation
KeyEntrySet SimpleConstMapping::keyEntries protected
A set of Arguments defining the "points of interest" an iterator should iterate over.
Definition at line 1331 of file MappingBase.h.
Referenced by createKeyEntries(), and initializeArguments().
The documentation for this class was generated from the following files:
MappingBase.h
MappingBase.cc