Veins Framework: mfcv_epidemic_rsu Class Reference
mfcv_epidemic_rsu Class Reference
Small RSU Demo using 11p.
#include <mfcv_epidemic_rsu.h>
Public Member Functions
virtual void initialize (int stage)
Initialization of the module and some variables.
Public Member Functions inherited from BaseWaveApplLayer
~BaseWaveApplLayer ()
virtual void initialize_default_veins_TraCI (int stage)
virtual void initialize_minicurso_UFPI_TraCI (int stage)
virtual void initialize_epidemic (int stage)
virtual void initialize_mfcv_epidemic (int stage)
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed.
void saveMessagesOnFile (WaveShortMessage *wsm, string fileName)
void printHeaderfileExecution ()
void openFileAndClose (string fileName, bool append)
Public Member Functions inherited from BaseApplLayer
BaseApplLayer ()
BaseApplLayer (unsigned stacksize)
Public Member Functions inherited from BaseLayer
BaseLayer ()
BaseLayer (unsigned stacksize)
virtual ~BaseLayer ()
virtual void handleMessage (cMessage *)
Called every time a message arrives.
Public Member Functions inherited from Veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from BaseModule
BaseModule ()
Function to get the logging name of id.
BaseModule (unsigned stacksize)
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
Protected Types
typedef unordered_map< string,
WaveShortMessage > MyMapMfcv_EpidemicMessageBuffer
typedef pair< string,
WaveShortMessage > MyPairMfcv_EpidemicMessageBuffer
Protected Member Functions
virtual void onBeacon (WaveShortMessage *wsm)
virtual void onData (WaveShortMessage *wsm)
void sendLocalSummaryVector (unsigned int newRecipientAddress)
void sendMfcv_EpidemicRequestMessageVector (unsigned int newRecipientAddress)
void sendMessagesRequested (string s, unsigned int recipientAddress)
void sendBeacon ()
void sendBeacon (unsigned int target)
virtual void sendWSM (WaveShortMessage *wsm)
string getLocalSummaryVectorData ()
string getMfcv_EpidemicRequestMessageVectorData ()
WaveShortMessage getMfcv_EpidemicLocalMessageBuffer (string s)
void printNodesIRecentlySentSummaryVector ()
void printMfcv_EpidemicLocalMessageBuffer ()
void printMfcv_EpidemicRequestMessageVector ()
void printWaveShortMessage (WaveShortMessage wsm)
void printWaveShortMessage (WaveShortMessage *wsm)
void printMfcv_EpidemicLocalSummaryVectorData ()
void printMfcv_EpidemicRemoteSummaryVectorData ()
void createMfcv_EpidemicRequestMessageVector ()
void printQueueFIFO (queue< string > qFIFO)
void createMfcv_EpidemicRemoteSummaryVector (string s)
virtual void finish ()
Called when the simulation has finished.
unsigned int getAngleDegrees ()
void handleSelfMsg (cMessage *msg)
handle self messages
WaveShortMessage * prepareWSM_mfcv_epidemic (std::string name, int lengthBits, t_channel channel, int priority, unsigned int rcvId, int serial)
Protected Member Functions inherited from BaseWaveApplLayer
virtual void handleLowerMsg (cMessage *msg)
handle messages from below
virtual WaveShortMessage * prepareWSM (std::string name, int dataLengthBits, t_channel channel, int priority, unsigned int rcvId, int serial=0)
virtual WaveShortMessage * prepareWSM_epidemic (string name, int dataLengthBits, t_channel channel, int priority, unsigned int rcvId, int serial=0)
virtual unsigned int MACToInteger ()
virtual void handlePositionUpdate (cObject *obj)
Protected Member Functions inherited from BaseApplLayer
void sendDelayedDown (cMessage *, simtime_t_cref)
Sends a message delayed to the lower layer.
virtual const LAddress::L3Type myApplAddr () const
Return my application layer address.
virtual void handleLowerControl (cMessage *msg)
Handle control messages from lower layer.
virtual void handleUpperMsg (cMessage *msg)
Handle messages from upper layer.
virtual void handleUpperControl (cMessage *msg)
Handle control messages from upper layer.
Protected Member Functions inherited from BaseLayer
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from Veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
Protected Attributes
AnnotationManager * annotations
BaseMobility * mobi
bool sentMessage
MyMapMfcv_EpidemicMessageBuffer mfcv_epidemicLocalMessageBuffer
unordered_map< string, bool > mfcv_epidemicLocalSummaryVector
unordered_map< string, bool > mfcv_epidemicRemoteSummaryVector
unordered_map< string, bool > mfcv_epidemicRequestMessageVector
unordered_map< unsigned int,
simtime_t > nodesRecentlyFoundList
unordered_map< unsigned int,
simtime_t > nodesIRecentlySentSummaryVector
queue< string > queueFIFO
double maiortempo = 0
Protected Attributes inherited from BaseWaveApplLayer
std::ofstream myfile
int beaconLengthBits
int beaconPriority
bool sendData
bool sendBeacons
simtime_t individualOffset
int dataLengthBits
bool dataOnSch
int dataPriority
Coord curPosition
int mySCH
int myId
cMessage * sendBeaconEvt
WaveAppToMac1609_4Interface * myMac
int sendSummaryVectorInterval
unsigned int maximumEpidemicBufferSize
unsigned int hopCount
unsigned int maximumMfcvEpidemicBufferSize
string source
string target
int target_x
int target_y
string fileMessagesNameUnicast
string fileMessagesNameBroadcast
string fileMessagesCount
string fileMessagesDrop
string fileMessagesGenerated
int repeatNumber
unsigned int beaconMessageHopLimit
int numVehicles
int countGenerateBeaconMessage
double ttlBeaconMessage
double timeLimitGenerateBeaconMessage
string stringTmp
double doubleTmp
Protected Attributes inherited from BaseApplLayer
int headerLength
Length of the ApplPkt header.
Protected Attributes inherited from BaseLayer
PassedMessage * passedMsg
The last message passed through this layer.
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
Protected Attributes inherited from Veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from BaseModule
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Public Types inherited from BaseWaveApplLayer
enum WaveApplMessageKinds {
SERVICE_PROVIDER = LAST_BASE_APPL_MESSAGE_KIND, SEND_BEACON_EVT, SEND_BEACON_EVT_minicurso, SERVICE_EXPIRED_EVT,
SERVICE_QUERY_EVT, SERVICE_EVT, MOBILITY_EVT, SEND_BEACON_EVT_epidemic,
SEND_BEACON_EVT_mfcv_epidemic
}
Public Types inherited from BaseApplLayer
enum BaseApplMessageKinds { LAST_BASE_APPL_MESSAGE_KIND = 25000 }
The message kinds this layer uses.
enum BaseApplControlKinds { LAST_BASE_APPL_CONTROL_KIND = 25500 }
The control message kinds this layer uses.
Static Public Attributes inherited from BaseLayer
static const simsignalwrap_t catPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_PACKET_NAME)
SignalID for packets.
static const simsignalwrap_t catPassedMsgSignal = simsignalwrap_t(MIXIM_SIGNAL_PASSEDMSG_NAME)
Signal for passed messages.
static const simsignalwrap_t catDroppedPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_DROPPEDPACKET_NAME)
Signal for dropped packets.
Static Protected Attributes inherited from BaseWaveApplLayer
static const simsignalwrap_t mobilityStateChangedSignal = simsignalwrap_t(MIXIM_SIGNAL_MOBILITY_CHANGE_NAME)
static unsigned short int vehCount = 0
static unsigned short int rsuCount = 0
Static Protected Attributes inherited from BaseModule
static const simsignalwrap_t catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME)
Stores the category of the HostState.
Detailed Description
Small RSU Demo using 11p.
Definition at line 35 of file mfcv_epidemic_rsu.h.
Member Typedef Documentation
typedef unordered_map<string, WaveShortMessage> mfcv_epidemic_rsu::MyMapMfcv_EpidemicMessageBuffer protected
Definition at line 43 of file mfcv_epidemic_rsu.h.
typedef pair<string, WaveShortMessage> mfcv_epidemic_rsu::MyPairMfcv_EpidemicMessageBuffer protected
Definition at line 44 of file mfcv_epidemic_rsu.h.
Member Function Documentation
void mfcv_epidemic_rsu::createMfcv_EpidemicRemoteSummaryVector (string s) protected
Definition at line 430 of file mfcv_epidemic_rsu.cc.
Referenced by onData().
{
     //cout << "Creating the mfcv_epidemicRemoteSummaryVector in " << findHost()->getFullName() << endl;
     string delimiter = "|";
     size_t pos = 0;
     string token;
     unsigned i = 0;
     mfcv_epidemicRemoteSummaryVector.clear();
     while ((pos = s.find(delimiter)) != std::string::npos) {
       //token = s.substr(0, pos);
       //std::cout << token << std::endl;
       //Catch jus the key of the local summary vector
       if(i%2 == 0)
         mfcv_epidemicRemoteSummaryVector.insert(make_pair<string, bool>(s.substr(0, pos),true));
       s.erase(0, pos + delimiter.length());
       i++;
     }
     //std::cout << s << std::endl;
 }
void mfcv_epidemic_rsu::createMfcv_EpidemicRequestMessageVector () protected
Definition at line 449 of file mfcv_epidemic_rsu.cc.
Referenced by onData().
{
     mfcv_epidemicRequestMessageVector.clear();
     for(auto& x: mfcv_epidemicRemoteSummaryVector){
         unordered_map<string,bool>::const_iterator got = mfcv_epidemicLocalSummaryVector.find(x.first);
         //cout << "I'm in createMfcv_EpidemicRequestMessageVector().  x.first: " << x.first << " x.second: " << x.second << endl;
         if(got == mfcv_epidemicLocalSummaryVector.end()){ //true value means that there is no entry in the mfcv_epidemicLocalSummaryVector for a mfcv_epidemicRemoteSummaryVector key
             //Putting the message in the Mfcv_EpidemicRequestMessageVector
             string s = x.first;
             mfcv_epidemicRequestMessageVector.insert(make_pair<string, bool>(s.c_str(),true));
         }
         //An entry in the unordered_map was found
         else{
             //cout << "I'm in createMfcv_EpidemicRequestMessageVector().  got->first: " << got->first << " got->second: " << got->second << endl;
             //cout << "The message " << got->first << " in the mfcv_epidemicRemoteSummaryVector was found in my mfcv_epidemicLocalSummaryVector." << endl;
         }
     }
 }
void mfcv_epidemic_rsu::finish () protected virtual
Called when the simulation has finished.
Reimplemented from BaseWaveApplLayer.
Definition at line 612 of file mfcv_epidemic_rsu.cc.
{
 //    // This function is called by OMNeT++ at the end of the simulation.
 //    cout << "Number of Messages Received: " << numMessageReceived << endl;
 //    cout << "Hop count, min:    " << hopCountStats.getMin() << endl;
 //    cout << "Hop count, max:    " << hopCountStats.getMax() << endl;
 //    cout << "Hop count, mean:   " << hopCountStats.getMean() << endl;
 //    cout << "Hop count, stddev: " << hopCountStats.getStddev() << endl;
 //
 //    // This function is called by OMNeT++ at the end of the simulation.
 //    cout << "Maior Delay: " << maiortempo << endl;
 //    cout << "messageArrivalTimeStats, min:    " << messageArrivalTimeStats.getMin() << endl;
 //    cout << "messageArrivalTimeStats, max:    " << messageArrivalTimeStats.getMax() << endl;
 //    cout << "messageArrivalTimeStats, mean:   " << messageArrivalTimeStats.getMean() << endl;
 //    cout << "messageArrivalTimeStats, stddev: " << messageArrivalTimeStats.getStddev() << endl;
 //
 //
 //    // This function is called by OMNeT++ at the end of the simulation.
 //    EV << "Number of Messages Received: " << numMessageReceived << endl;
 //    EV << "Hop count, min:    " << hopCountStats.getMin() << endl;
 //    EV << "Hop count, max:    " << hopCountStats.getMax() << endl;
 //    EV << "Hop count, mean:   " << hopCountStats.getMean() << endl;
 //    EV << "Hop count, stddev: " << hopCountStats.getStddev() << endl;
 //
 //    // This function is called by OMNeT++ at the end of the simulation.
 //    EV << "Maior Delay: " << maiortempo << endl;
 //    EV << "messageArrivalTimeStats, min:    " << messageArrivalTimeStats.getMin() << endl;
 //    EV << "messageArrivalTimeStats, max:    " << messageArrivalTimeStats.getMax() << endl;
 //    EV << "messageArrivalTimeStats, mean:   " << messageArrivalTimeStats.getMean() << endl;
 //    EV << "messageArrivalTimeStats, stddev: " << messageArrivalTimeStats.getStddev() << endl;
 //
 //    recordScalar("#numMessageReceived", numMessageReceived);
 //
 //    hopCountStats.recordAs("hop CCount");
 //    messageArrivalTimeStats.recordAs("Latency to Delivery Message");
 }
unsigned int mfcv_epidemic_rsu::getAngleDegrees () protected
Definition at line 683 of file mfcv_epidemic_rsu.cc.
Referenced by prepareWSM_mfcv_epidemic().
{
    // RSU return angle 0
    return 0;
 }
string mfcv_epidemic_rsu::getLocalSummaryVectorData () protected
Definition at line 487 of file mfcv_epidemic_rsu.cc.
Referenced by sendLocalSummaryVector().
{
     ostringstream ss;
     for(auto& x: mfcv_epidemicLocalSummaryVector)
         ss << x.first << "|" << x.second << "|";
     string s = ss.str();
     s = s.substr(0, s.length() - 1);
     //cout << "Mfcv_EpidemicLocalSummaryVector from " << findHost()->getFullName() << "(" << MACToInteger() << "): " <<  s  << endl;
     return s.c_str();
 }
WaveShortMessage mfcv_epidemic_rsu::getMfcv_EpidemicLocalMessageBuffer (string s) protected
string mfcv_epidemic_rsu::getMfcv_EpidemicRequestMessageVectorData () protected
Definition at line 467 of file mfcv_epidemic_rsu.cc.
Referenced by sendMfcv_EpidemicRequestMessageVector().
{
     ostringstream ss;
     //adding the requester name in order to identify if the requester is also the target of the messages with hopcount == 1.
     //In this case, hopcount == 1, the messages can be sent to the target. Otherwise, the message will not be spread
     ss << findHost()->getFullName() << "|";
     for(auto& x: mfcv_epidemicRequestMessageVector)
         ss << x.first << "|" << x.second << "|";
     string s = ss.str();
     s = s.substr(0, s.length() - 1);
     cout << "String format of Mfcv_EpidemicRequestMessageVector from " << findHost()->getFullName() << ": " <<  s  << endl;
     return s.c_str();
 }
void mfcv_epidemic_rsu::handleSelfMsg (cMessage * msg) protected virtual
handle self messages
Reimplemented from BaseWaveApplLayer.
Definition at line 688 of file mfcv_epidemic_rsu.cc.
{
     switch (msg->getKind()) {
 //        case SEND_BEACON_EVT: {
 //            sendWSM(prepareWSM("beacon", beaconLengthBits, type_CCH, beaconPriority, 0, -1));
 //            scheduleAt(simTime() + par("beaconInterval").doubleValue(), sendBeaconEvt);
 //            break;
 //        }
 //        case SEND_BEACON_EVT_minicurso: {
 //            sendWSM(prepareWSM("beacon_minicurso", beaconLengthBits, type_CCH, beaconPriority, 0, -1));
 //            scheduleAt(simTime() + par("beaconInterval").doubleValue(), sendBeaconEvt);
 //            break;
 //        }
 //        case SEND_BEACON_EVT_epidemic: {
 //            //prepareWSM(std::string name, int lengthBits, t_channel channel, int priority, int rcvId, int serial)
 //            //I our implementation, if rcvId = BROADCAST then we are broadcasting beacons. Otherwise, this parameter must be instantiated with the receiver address
 //            sendWSM(prepareWSM_epidemic("beacon", beaconLengthBits, type_CCH, beaconPriority, BROADCAST, -1));
 //            scheduleAt(simTime() + par("beaconInterval").doubleValue(), sendBeaconEvt);
 //            break;
 //        }
         case SEND_BEACON_EVT_mfcv_epidemic: {
             //prepareWSM(std::string name, int lengthBits, t_channel channel, int priority, int rcvId, int serial)
             //I our implementation, if rcvId = BROADCAST then we are broadcasting beacons. Otherwise, this parameter must be instantiated with the receiver address
             sendWSM(prepareWSM_mfcv_epidemic("beacon", beaconLengthBits, type_CCH, beaconPriority, BROADCAST, -1));
             scheduleAt(simTime() + par("beaconInterval").doubleValue(), sendBeaconEvt);
             break;
         }
         default: {
             if (msg)
                 DBG << "APP: Error: Got Self Message of unknown kind! Name: " << msg->getName() << endl;
             break;
         }
     }
 }
void mfcv_epidemic_rsu::initialize (int stage) virtual
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseLayer.
Then we have to intialize the gates and - if necessary - some own variables.
Reimplemented from BaseApplLayer.
Definition at line 27 of file mfcv_epidemic_rsu.cc.
{
     BaseWaveApplLayer::initialize_mfcv_epidemic(stage);
     if (stage == 0) {
         //test Jonh
         BaseWaveApplLayer::rsuCount++;
         mobi = dynamic_cast<BaseMobility*> (getParentModule()->getSubmodule("mobility"));
         ASSERT(mobi);
         annotations = AnnotationManagerAccess().getIfExists();
         ASSERT(annotations);
         //To record some statistics about the simulation
         //hopCountStats.setName("hopCountStats"); //Histogram
         //hopCountStats.setRangeAutoUpper(0, 10, 1.5); //Histogram
         //hopCountVector.setName("HopCount");
         //messageArrivalTimeStats.setName("messageArrivalStats"); //Histogram
         //messageArrivalTimeStats.setRangeAutoUpper(0, 10, 1.5); //Histogram
         //messageArrivalTimeVector.setName("messageArrivalVector");
         //numMessageReceived = 0;
         std::cout << "I'm " << findHost()->getFullName() <<  " myMac: " << myMac << " MACToInteger: " << MACToInteger() << endl;
         // test Jonh
         cout << "rsu ID: " << findHost()->getId() << endl;
         cout << "simTime(): " << SimTime() << endl;
         cout << "rsu Position: " << mobi->getCurrentPosition();
         cout << "rsu fullName " << findHost()->getFullName() << endl;
         cout << "rsu BaseWaveApplLayer::vehCount: " << BaseWaveApplLayer::vehCount << endl;
         cout << "rsu BaseWaveApplLayer::rsuCount: " << BaseWaveApplLayer::rsuCount << endl;
         cout << endl;
     }
     if(stage != 0) {
        cout << "outside if rsu Position: " << mobi->getCurrentPosition() << " stage: "<< stage<< endl;
     }
 }
void mfcv_epidemic_rsu::onBeacon (WaveShortMessage * wsm) protected virtual
Implements BaseWaveApplLayer.
Definition at line 66 of file mfcv_epidemic_rsu.cc.
{
     //cout << "I'm " << findHost()->getFullName() << "(" << MACToInteger() << ") and I received a Beacon from " << wsm->getSenderAddress() << " with destination " << wsm->getRecipientAddress() << endl;
     //Verifying if I have the smaller address in order to start the anti-entropy session sending out my summary vector
     if(wsm->getSenderAddress() > MACToInteger()){ //true means that I have the smaller address
         //cout << "I'm " << findHost()->getFullName() << " and my ID is smaller than the Beacon sender." << endl;
         //Verifying if (current contact simutime - last contact simutime) is bigger than previous slide window defined
         //A new summary vector needs to be re-sent to the same contact node only "sendSummaryVectorInterval" seconds after the last one
         unordered_map<unsigned int,simtime_t>::const_iterator got = nodesIRecentlySentSummaryVector.find(wsm->getSenderAddress());
         if(got == nodesIRecentlySentSummaryVector.end()){ //true value means that there is no entry in the nodesIRecentlySentSummaryVector for the current contact node
             //cout << "I'm " << findHost()->getFullName() << ". Contact not found in nodesIRecentlySentSummaryVector. Sending my summary vector to " << wsm->getSenderAddress() << endl;
             //Sending my summary vector to another mobile node
             sendLocalSummaryVector(wsm->getSenderAddress());
             nodesIRecentlySentSummaryVector.insert(make_pair<unsigned int, simtime_t>(wsm->getSenderAddress(),simTime()));
             printNodesIRecentlySentSummaryVector();
         }
         //An entry in the unordered_map was found
         else{
            //cout << "I'm " << findHost()->getFullName() << ". Contact found in nodesIRecentlySentSummaryVector. Node: " << got->first << " added at " << (simTime() - got->second) << " seconds ago." << endl;
            if((simTime() - got->second) > sendSummaryVectorInterval){ //checking if I should update the nodesIRecentlySentSummaryVector entry
                //cout << "I'm " << findHost()->getFullName() << " and I'm updating the entry in the nodesIRecentlySentSummaryVector." << endl;
                sendLocalSummaryVector(wsm->getSenderAddress());
                nodesIRecentlySentSummaryVector.erase(wsm->getSenderAddress());
                nodesIRecentlySentSummaryVector.insert(make_pair<unsigned int, simtime_t>(wsm->getSenderAddress(),simTime()));
                printNodesIRecentlySentSummaryVector();
            }
         }
     }
     //My address is bigger than the Beacon sender
     else{
         //do nothing
         //std::cout << "My ID is bigger than the Beacon sender." << std::endl;
     }
 }
void mfcv_epidemic_rsu::onData (WaveShortMessage * wsm) protected virtual
Implements BaseWaveApplLayer.
Definition at line 102 of file mfcv_epidemic_rsu.cc.
{
     //Verifying the kind of a received message: if a summary vector (true) or a mfcv_epidemic buffer data message (false).
     if(wsm->getSummaryVector()){
        //checking if the summary vector was sent to me
        if(wsm->getRecipientAddress() == MACToInteger()){
           cout << "I'm " << findHost()->getFullName() << "(" << MACToInteger() << ") and I just recieved the summary vector |> " << wsm->getWsmData() << " <| from " << wsm->getSenderAddress() << endl;
           //Creating the remote summary vector with the data received in wsm->message field
           createMfcv_EpidemicRemoteSummaryVector(wsm->getWsmData());
           printMfcv_EpidemicRemoteSummaryVectorData();
           printMfcv_EpidemicLocalSummaryVectorData();
           //Creating a key vector in order to request messages that I still do not have in my buffer
           createMfcv_EpidemicRequestMessageVector();
           printMfcv_EpidemicRequestMessageVector();
           //Verifying if this is the end of second round of the anti-entropy session when the Mfcv_EpidemicRemoteSummaryVector and Mfcv_EpidemicLocalSummaryVector are equals
           if((mfcv_epidemicRequestMessageVector.empty() ||(strcmp(wsm->getWsmData(),"") == 0)) && (wsm->getSenderAddress() > MACToInteger())){
              //cout << "Mfcv_EpidemicRequestMessageVector from " << findHost()->getFullName() << " is empty now " << endl;
              //cout << "Or strcmp(wsm->getWsmData(),\"\") == 0) " << endl;
              //cout << "And  wsm->getSenderAddress() > MACToInteger() " << endl;
           }else if(mfcv_epidemicRequestMessageVector.empty()){
               //cout << "Mfcv_EpidemicRequestMessageVector from " << findHost()->getFullName() << " is empty now " << endl;
               //changing the turn of the anti-entropy session. In this case, I have not found any differences between Mfcv_EpidemicRemoteSummaryVector and Mfcv_EpidemicLocalSummaryVector but I need to change the round of anti-entropy session
               sendLocalSummaryVector(wsm->getSenderAddress());
           }else{
               //Sending a request vector in order to get messages that I don't have
               sendMfcv_EpidemicRequestMessageVector(wsm->getSenderAddress());
           }
        }
     }
     //is a data message requisition or a data message content
     else{
         //cout << "I'm " << findHost()->getFullName() << ". This is not a summary vector" << endl;
         //Verifying if this is a request message
         if(wsm->getRequestMessages()){
             //checking if the request vector was sent to me
             if(wsm->getRecipientAddress() == MACToInteger()){
                 //Searching for elements in the mfcv_epidemicLocalMessageBuffer and sending them to requester
                 cout << "I'm " << findHost()->getFullName() << ". I received the mfcv_epidemicRequestMessageVector |> " << wsm->getWsmData() << " <| from " << wsm->getSenderAddress() << endl;
                 sendMessagesRequested(wsm->getWsmData(), wsm->getSenderAddress());
             }
         }
         //is data content
         else{
              if(wsm->getRecipientAddress() == MACToInteger()){
                  //WSMData generated by car[3]|car[3]|rsu[0]|1.2
                  cout << "I'm " << findHost()->getFullName() << "(" << MACToInteger() << "). I received all the message requested |> " << wsm->getWsmData() << " <| from " << wsm->getSenderAddress() << endl;
                  cout << "Before message processing " << endl;
                  printMfcv_EpidemicLocalMessageBuffer();
                  cout << "Before message processing " << endl;
                  printMfcv_EpidemicLocalSummaryVectorData();
                  cout << "Before message processing " << endl;
                  printQueueFIFO(queueFIFO);
                  string delimiter = "|";
                  size_t pos = 0;
                  string tokenkey, tokenData, tokenSource, tokenTarget, tokenTimestamp, tokenhopcount;
                  string messageReceived = wsm->getWsmData();
                  simtime_t st;
                  //cout << "pos = messageReceived.find(delimiter): " << messageReceived.find(delimiter) << endl;
                  //cout << "std::string::npos: " << std::string::npos << endl;
                  while((pos = messageReceived.find(delimiter)) != std::string::npos) {
                         tokenkey = messageReceived.substr(0, pos);
                         messageReceived.erase(0, pos + delimiter.length());
                         pos = messageReceived.find(delimiter);
                         tokenData = messageReceived.substr(0, pos);
                         messageReceived.erase(0, pos + delimiter.length());
                         pos = messageReceived.find(delimiter);
                         tokenSource = messageReceived.substr(0, pos);
                         messageReceived.erase(0, pos + delimiter.length());
                         pos = messageReceived.find(delimiter);
                         tokenTarget = messageReceived.substr(0, pos);
                         messageReceived.erase(0, pos + delimiter.length());
                         pos = messageReceived.find(delimiter);
                         tokenTimestamp = messageReceived.substr(0, pos);
                         messageReceived.erase(0, pos + delimiter.length());
                         pos = messageReceived.find(delimiter);
                         tokenhopcount = messageReceived.substr(0, pos);
                         messageReceived.erase(0, pos + delimiter.length());
                         //cout << "I'm " << findHost()->getFullName() << " and the message received is tokenData: " << tokenData << "tokenSource: " << tokenSource << "tokenTarget: " << tokenTarget << "tokenTimestamp: " << tokenTimestamp << endl;
                         WaveShortMessage w = *wsm;
                         w.setWsmData(tokenData.c_str());
                         w.setSource(tokenSource.c_str());
                         w.setTarget(tokenTarget.c_str());
                         w.setTimestamp(st.parse(tokenTimestamp.c_str()));
                         w.setHopCount(stoi(tokenhopcount));
                         //checking if the maximum buffer size was reached
                         if(queueFIFO.size() < maximumMfcvEpidemicBufferSize){
                             //Verifying if there is no entry for current message received in my mfcv_epidemicLocalMessageBuffer
                             unordered_map<string,WaveShortMessage>::const_iterator got = mfcv_epidemicLocalMessageBuffer.find(tokenkey);
                             if(got == mfcv_epidemicLocalMessageBuffer.end()){ //true value means that there is no entry in the mfcv_epidemicLocalMessageBuffer for the current message identification
                                 //Putting the message in the mfcv_epidemicLocalMessageBuffer
                                 mfcv_epidemicLocalMessageBuffer.insert(MyPairMfcv_EpidemicMessageBuffer(tokenkey,w));
                                 //Putting the message in the Mfcv_EpidemicLocalSummaryVector
                                 mfcv_epidemicLocalSummaryVector.insert(make_pair<string, bool>(tokenkey.c_str(),true));
                                 //FIFO strategy to set the maximum size that a node is willing to allocate mfcv_epidemic messages in its buffer
                                 queueFIFO.push(tokenkey.c_str());
                                 //printQueueFIFO(queueFIFO);
                                 bubble("message added in my buffer"); //making animation message more informative
                                 //recording some statistics
 //                                cout << "findHost()->getFullName() == w.getTarget(): " << " findHost()->getFullName(): " << findHost()->getFullName() << " w.getTarget():" << w.getTarget() << endl;
                                 if(strcmp(findHost()->getFullName(), w.getTarget()) == 0){
                                     //hopCountVector.record(hopCount - w.getHopCount());
                                     //hopCountStats.collect(hopCount - w.getHopCount());
                                     //messageArrivalTimeVector.record((simTime() - w.getTimestamp()));
                                     //messageArrivalTimeStats.collect((simTime() - w.getTimestamp()));
                                     //numMessageReceived++;
                                    // emit(delayToDeliverSignal, (simTime() - w.getTimestamp()));
                                    // emit(hopsToDeliverSignal, (hopCount - w.getHopCount()));
                                    // emit(messageArrivalSignal, 1);
                                     if(maiortempo < (simTime() - w.getTimestamp()).dbl())
                                         maiortempo = (simTime() - w.getTimestamp()).dbl();
 //                                    cout << "numMessageReceived: " << numMessageReceived << endl;
                                 }
                             }
                             //An entry in the unordered_map was found
                             else{
                                 //do nothing because the message is already in my mfcv_epidemicLocalBuffer
                             }
                         }
                         //The maximum buffer size was reached, so I have to remove the first item from the queueFIFO
                         else{
                             //Verifying if there is no entry for current message received in my mfcv_epidemicLocalMessageBuffer
                             unordered_map<string,WaveShortMessage>::const_iterator got = mfcv_epidemicLocalMessageBuffer.find(tokenkey.c_str());
                             if(got == mfcv_epidemicLocalMessageBuffer.end()){ //true value means that there is no entry in the mfcv_epidemicLocalMessageBuffer for the current message identification
                                 mfcv_epidemicLocalMessageBuffer.erase(queueFIFO.front());
                                 mfcv_epidemicLocalSummaryVector.erase(queueFIFO.front());
                                 queueFIFO.pop();
                                 //Putting the message in the mfcv_epidemicLocalMessageBuffer
                                 mfcv_epidemicLocalMessageBuffer.insert(MyPairMfcv_EpidemicMessageBuffer(tokenkey,w));
                                 //Putting the message in the Mfcv_EpidemicLocalSummaryVector
                                 mfcv_epidemicLocalSummaryVector.insert(make_pair<string, bool>(tokenkey.c_str(),true));
                                 //FIFO strategy to set the maximum size that a node is willing to allocate mfcv_epidemic messages in its buffer
                                 queueFIFO.push(tokenkey.c_str());
                                 //printQueueFIFO(queueFIFO);
                                 //recording some statistics
 //                                cout << "findHost()->getFullName() == w.getTarget(): " << " findHost()->getFullName(): " << findHost()->getFullName() << " w.getTarget():" << w.getTarget() << endl;
                                 if(strcmp(findHost()->getFullName(), w.getTarget()) == 0){
                                     //hopCountVector.record(hopCount - w.getHopCount());
                                     //hopCountStats.collect(hopCount - w.getHopCount());
                                     //messageArrivalTimeVector.record((simTime() - w.getTimestamp()));
                                     //messageArrivalTimeStats.collect((simTime() - w.getTimestamp()));
                                     cout << "Removing an item in my buffer because the size of it was reached" << endl;
                                     //cout << "numMessageReceived++: " << numMessageReceived++ << endl;
                                     //numMessageReceived++;
                                     //emit(arrivalSignal, (hopCount - w.getHopCount()));
                                     //emit(arrivalSignal, (simTime() - w.getTimestamp()));
                                     if(maiortempo < (simTime() - w.getTimestamp()).dbl())
                                         maiortempo = (simTime() - w.getTimestamp()).dbl();
 //                                    cout << "numMessageReceived: " << numMessageReceived << endl;
                                 }
                             }
                             //An entry in the unordered_map was found
                             else{
                                 //do nothing because the message is already in my mfcv_epidemicLocalBuffer
                             }
                         }
                  } // end of while
                  cout << "After message processing " << endl;
                  printMfcv_EpidemicLocalMessageBuffer();
                  cout << "After message processing " << endl;
                  printMfcv_EpidemicLocalSummaryVectorData();
                  cout << "After message processing " << endl;
                  printQueueFIFO(queueFIFO);
                  //changing the turn of the anti-entropy session. If this is the first round, call sendLocalSummaryVector(wsm->getSenderAddress())
                  if(wsm->getSenderAddress() < MACToInteger())
                    sendLocalSummaryVector(wsm->getSenderAddress());
              } //end of if
         }// end of else
         //Verifying if I'm the target of a message
         if(strcmp(wsm->getTarget(),findHost()->getFullName()) == 0){
           std::cout << "I'm " << findHost()->getFullName() << ", the recipient of the message." << " at " << simTime() << std::endl;
           //sendWSM(prepareWSM_mfcv_epidemic("beacon", beaconLengthBits, type_CCH, beaconPriority, wsm->getSenderAddress(), -1));
         }
         //this node is a relaying node because it is not the target of the message
         else{
              //std::cout << findHost()->getFullName() << " will cache the message for forwarding it later." << " at " << simTime() << std::endl;
         }
     }
 }
WaveShortMessage * mfcv_epidemic_rsu::prepareWSM_mfcv_epidemic (std::string name, int lengthBits, t_channel channel, int priority, unsigned int rcvId, int serial) protected
Definition at line 651 of file mfcv_epidemic_rsu.cc.
Referenced by handleSelfMsg(), sendBeacon(), sendLocalSummaryVector(), sendMessagesRequested(), and sendMfcv_EpidemicRequestMessageVector().
{
     cout << "In prepareWSM_mfcv_epidemic" << endl;
     WaveShortMessage* wsm = new WaveShortMessage(name.c_str());
     wsm->addBitLength(headerLength);
     wsm->addBitLength(lengthBits);
     switch (channel) {
         case type_SCH: wsm->setChannelNumber(Channels::SCH1); break; //will be rewritten at Mac1609_4 to actual Service Channel. This is just so no controlInfo is needed
         case type_CCH: wsm->setChannelNumber(Channels::CCH); break;
     }
     wsm->setPsid(0);
     wsm->setPriority(priority);
     wsm->setWsmVersion(1);
     wsm->setTimestamp(simTime());
     wsm->setSenderAddress(MACToInteger());
     wsm->setRecipientAddress(rcvId);
     //wsm->setSource(source);
     //wsm->setTarget(target);
     wsm->setSenderPos(curPosition);
     wsm->setSerial(serial);
     cout << "In prepareWSM_mfcv_epidemic2" << endl;
     // test Jonh
     wsm->setHeading(getAngleDegrees());
     if (name == "beacon") {
         DBG << "Creating Beacon with Priority " << priority << " at Applayer at " << wsm->getTimestamp() << std::endl;
     }else if (name == "data") {
         DBG << "Creating Data with Priority " << priority << " at Applayer at " << wsm->getTimestamp() << std::endl;
     }
     return wsm;
 }
void mfcv_epidemic_rsu::printMfcv_EpidemicLocalMessageBuffer () protected
Definition at line 505 of file mfcv_epidemic_rsu.cc.
Referenced by onData(), and sendMessagesRequested().
{
     if(mfcv_epidemicLocalMessageBuffer.empty()){
            cout << "Mfcv_EpidemicLocalMessageBuffer from " << findHost()->getFullName() << " is empty now " << endl;
     }else{
         int i = 0;
         cout << "Printing the mfcv_epidemicLocalMessageBuffer from " << findHost()->getFullName() << "(" << MACToInteger() <<"):" << endl;
         for(auto& x: mfcv_epidemicLocalMessageBuffer){
             WaveShortMessage wsmBuffered = x.second;
             cout << " Key " << ++i << ": " << x.first << " - Message Content: " << wsmBuffered.getWsmData() << " source: " << wsmBuffered.getSource() << " target: " << wsmBuffered.getTarget() << " Timestamp: " << wsmBuffered.getTimestamp() << " HopCount: " << wsmBuffered.getHopCount() << endl;
         }
     }
 }
void mfcv_epidemic_rsu::printMfcv_EpidemicLocalSummaryVectorData () protected
Definition at line 518 of file mfcv_epidemic_rsu.cc.
Referenced by onData().
{
     if(mfcv_epidemicLocalSummaryVector.empty()){
            cout << "Mfcv_EpidemicLocalSummaryVector from " << findHost()->getFullName() << " is empty now " << endl;
     }else{
         ostringstream ss;
         for(auto& x: mfcv_epidemicLocalSummaryVector)
            ss << x.first << "|" << x.second << "|";
         string s = ss.str();
         s = s.substr(0, s.length() - 1);
         cout << "Mfcv_EpidemicLocalSummaryVector from " << findHost()->getFullName() << "(" << MACToInteger() << "): " <<  s  << endl;
     }
 }
void mfcv_epidemic_rsu::printMfcv_EpidemicRemoteSummaryVectorData () protected
Definition at line 531 of file mfcv_epidemic_rsu.cc.
Referenced by onData().
{
     if(mfcv_epidemicRemoteSummaryVector.empty()){
            cout << "Mfcv_EpidemicRemoteSummaryVector from " << findHost()->getFullName() << " is empty now " << endl;
     }else{
         ostringstream ss;
         for(auto& x: mfcv_epidemicRemoteSummaryVector)
             ss << x.first << "|" << x.second << "|";
         string s = ss.str();
         s = s.substr(0, s.length() - 1);
         cout << "Mfcv_EpidemicRemoteSummaryVector from " << findHost()->getFullName() << ": " <<  s  << endl;
     }
 }
void mfcv_epidemic_rsu::printMfcv_EpidemicRequestMessageVector () protected
Definition at line 544 of file mfcv_epidemic_rsu.cc.
Referenced by onData().
{
     if(mfcv_epidemicRequestMessageVector.empty()){
         cout << "Mfcv_EpidemicRequestMessageVector from " << findHost()->getFullName() << " is empty now " << endl;
     }
     else{
         ostringstream ss;
         for(auto& x: mfcv_epidemicRequestMessageVector)
             ss << x.first << "|" << x.second << "|";
         string s = ss.str();
         s = s.substr(0, s.length() - 1);
         cout << "Mfcv_EpidemicRequestMessageVector from " << findHost()->getFullName() << ": " <<  s  << endl;
     }
 }
void mfcv_epidemic_rsu::printNodesIRecentlySentSummaryVector () protected
Definition at line 559 of file mfcv_epidemic_rsu.cc.
Referenced by onBeacon().
{
     if(nodesIRecentlySentSummaryVector.empty()){
            cout << "NodesIRecentlySentSummaryVector from " << findHost()->getFullName() << " is empty now " << endl;
     }
     else{
         int i = 0;
         cout << "NodesIRecentlySentSummaryVector from " << findHost()->getFullName() << " (" << MACToInteger() << "):" << endl;
         for(auto& x: nodesIRecentlySentSummaryVector)
             cout << ++i << " Node: " << x.first << " added at " << x.second << endl;
     }
 }
void mfcv_epidemic_rsu::printQueueFIFO (queue< string > qFIFO) protected
Definition at line 497 of file mfcv_epidemic_rsu.cc.
Referenced by onData().
{
     int i = 0;
     while(!qFIFO.empty()){
         cout << "I'm " << findHost()->getFullName() << " - queueFIFO Element " << ++i << ": " << qFIFO.front() << endl;
         qFIFO.pop();
     }
 }
void mfcv_epidemic_rsu::printWaveShortMessage (WaveShortMessage wsm) protected
Definition at line 571 of file mfcv_epidemic_rsu.cc.
{
     cout << "wsm.getName():" << wsm.getName() << endl;
     cout << "wsm.getBitLength():" << wsm.getBitLength() << endl;
     cout << "wsm.getChannelNumber():" << wsm.getChannelNumber() << endl;
     cout << "wsm.getPsid():" << wsm.getPsid() << endl;
     cout << "wsm.getPriority():" << wsm.getPriority() << endl;
     cout << "wsm.getWsmVersion():" << wsm.getWsmVersion() << endl;
     cout << "wsm.getTimestamp():" << wsm.getTimestamp() << endl;
     cout << "wsm.getSenderAddress():" << wsm.getSenderAddress() << endl;
     cout << "wsm.getRecipientAddress():" << wsm.getRecipientAddress() << endl;
     cout << "wsm.getSource():" << wsm.getSource() << endl;
     cout << "wsm.getTarget():" << wsm.getTarget() << endl;
     cout << "wsm.getSenderPos():" << wsm.getSenderPos() << endl;
     cout << "wsm.getSerial():" << wsm.getSerial() << endl;
     cout << "wsm.getSummaryVector():" << wsm.getSummaryVector() << endl;
     cout << "wsm.getRequestMessages():" << wsm.getRequestMessages() << endl;
     cout << "wsm.getWsmData():" << wsm.getWsmData() << endl;
     cout << "wsm.getLocalMessageIdentificaton(): " << wsm.getLocalMessageIdentificaton() << endl;
     cout << "wsm.getGlobalMessageIdentificaton(): " << wsm.getGlobalMessageIdentificaton() << endl;
     cout << "wsm.getHopCount(): " << wsm.getHopCount() << endl;
 }
void mfcv_epidemic_rsu::printWaveShortMessage (WaveShortMessage * wsm) protected
Definition at line 593 of file mfcv_epidemic_rsu.cc.
{
     cout << "wsm->getName()" << wsm->getName() << endl;
     cout << "wsm->getBitLength()" << wsm->getBitLength() << endl;
     cout << "wsm->getChannelNumber()" << wsm->getChannelNumber() << endl;
     cout << "wsm->getPsid()" << wsm->getPsid() << endl;
     cout << "wsm->getPriority()" << wsm->getPriority() << endl;
     cout << "wsm->getWsmVersion()" << wsm->getWsmVersion() << endl;
     cout << "wsm->getTimestamp()" << wsm->getTimestamp() << endl;
     cout << "wsm->getSenderAddress()" << wsm->getSenderAddress() << endl;
     cout << "wsm->getRecipientAddress()" << wsm->getRecipientAddress() << endl;
     cout << "wsm->getSource()" << wsm->getSource() << endl;
     cout << "wsm->getTarget()" << wsm->getTarget() << endl;
     cout << "wsm->getSenderPos()" << wsm->getSenderPos() << endl;
     cout << "wsm->getSerial()" << wsm->getSerial() << endl;
     cout << "wsm->getSummaryVector()" << wsm->getSummaryVector() << endl;
     cout << "wsm->getRequestMessages()" << wsm->getRequestMessages() << endl;
     cout << "wsm->getWsmData()" << wsm->getWsmData() << endl;
 }
void mfcv_epidemic_rsu::sendBeacon () protected
Definition at line 283 of file mfcv_epidemic_rsu.cc.
{
     t_channel channel = dataOnSch ? type_SCH : type_CCH;
     std::cout << "Channel: " << channel << std::endl;
     WaveShortMessage* wsm = prepareWSM_mfcv_epidemic("beacon", dataLengthBits, channel, dataPriority, BROADCAST,2);
     sendWSM(wsm);
 }
void mfcv_epidemic_rsu::sendBeacon (unsigned int target) protected
void mfcv_epidemic_rsu::sendLocalSummaryVector (unsigned int newRecipientAddress) protected
Definition at line 295 of file mfcv_epidemic_rsu.cc.
Referenced by onBeacon(), and onData().
{
     t_channel channel = dataOnSch ? type_SCH : type_CCH;
     WaveShortMessage* wsm = prepareWSM_mfcv_epidemic("data", dataLengthBits, channel, dataPriority, newRecipientAddress,2);
     wsm->setSummaryVector(true);
     wsm->setRequestMessages(false);
     //Put the summary vector here, on data wsm field
     wsm->setWsmData(getLocalSummaryVectorData().c_str());
     //Sending the summary vector
     sendWSM(wsm);
 }
void mfcv_epidemic_rsu::sendMessagesRequested (string s, unsigned int recipientAddress) protected
Definition at line 306 of file mfcv_epidemic_rsu.cc.
Referenced by onData().
{
     cout << "I'm " << findHost()->getFullName() << "(" << MACToInteger() << "). Sending the following messages resquested: " << s << " to " << recipientAddress << endl;
     t_channel channel = dataOnSch ? type_SCH : type_CCH;
     WaveShortMessage* wsm = prepareWSM_mfcv_epidemic("data", dataLengthBits, channel, dataPriority, recipientAddress,2);
     string delimiter = "|";
     size_t pos = 0;
     string token;
     unsigned i = 0;
     string message="";
     printMfcv_EpidemicLocalMessageBuffer();
     //Extracting who request message
     pos = s.find(delimiter);
     string tokenRequester = s.substr(0, pos);
     s.erase(0, pos + delimiter.length());
     while ((pos = s.find(delimiter)) != std::string::npos) {
       //Catch jus the key of the local summary vector
       if(i%2 == 0){
           ostringstream ss;
           //cout << "i = " << i << " - looking for the message key(s.substr(0, pos)): " << s.substr(0, pos) << endl;
           WaveShortMessage w;
           unordered_map<string,WaveShortMessage>::const_iterator got = mfcv_epidemicLocalMessageBuffer.find(s.substr(0, pos));
           if(got == mfcv_epidemicLocalMessageBuffer.end()){ //true value means that there is no entry in the mfcv_epidemicLocalSummaryVector for a mfcv_epidemicRemoteSummaryVector key
           }else{
                w = got->second;
                //WaveShortMessage w = getMfcv_EpidemicLocalMessageBuffer(s.substr(0, pos));
                //Verifying if I'm still able to spread the message or not. If w.getHopCount == 1 I'm able to send the message only to its target
                if(w.getHopCount() > 1){
                  ss << s.substr(0, pos) << "|" << w.getWsmData() << "|" << w.getSource() << "|" << w.getTarget() << "|" << w.getTimestamp() << "|" << w.getHopCount() - 1 << "|";
                }else if(w.getHopCount() == 1){
                  if((strcmp(tokenRequester.c_str(),w.getTarget()) == 0)){
                    ss << s.substr(0, pos) << "|" << w.getWsmData() << "|" << w.getSource() << "|" << w.getTarget() << "|" << w.getTimestamp() << "|" << w.getHopCount() - 1 << "|";
                  }
                }
                //cout << "ss.str() inside the sendMessageRequested method: " << ss.str() << endl;
                message += ss.str();
                //cout << "message inside the sendMessageRequested method. message += ss.str(): " << message << endl;
           }
       }
       //cout << "i = " << i << " - s inside the sendMessageRequested method: " << s << endl;
       s.erase(0, pos + delimiter.length());
       //cout << "i = " << i << " - s inside the sendMessageRequested method, after s.erase(0, pos + delimiter.length()): " << s << endl;
       i++;
     }
     message = message.substr(0, message.length() - 1);
     cout << "Message that is sending as a result of a requisition vector request. wsm->setWsmData: " <<  message << endl;
     wsm->setWsmData(message.c_str());
     wsm->setSummaryVector(false);
     wsm->setRequestMessages(false);
     sendWSM(wsm);
 }
void mfcv_epidemic_rsu::sendMfcv_EpidemicRequestMessageVector (unsigned int newRecipientAddress) protected
Definition at line 417 of file mfcv_epidemic_rsu.cc.
Referenced by onData().
{
     t_channel channel = dataOnSch ? type_SCH : type_CCH;
     WaveShortMessage* wsm = prepareWSM_mfcv_epidemic("data", dataLengthBits, channel, dataPriority, newRecipientAddress,2);
     wsm->setSummaryVector(false);
     wsm->setRequestMessages(true);
     //Put the summary vector here
     wsm->setWsmData(getMfcv_EpidemicRequestMessageVectorData().c_str());
     //Sending the summary vector
     sendWSM(wsm);
     //cout << "Sending a vector of request messages from " << findHost()->getFullName() <<"(" << MACToInteger() << ") to " << newRecipientAddress << endl;
     //mfcv_epidemicRequestMessageVector.clear();
 }
void mfcv_epidemic_rsu::sendWSM (WaveShortMessage * wsm) protected virtual
Reimplemented from BaseWaveApplLayer.
Definition at line 290 of file mfcv_epidemic_rsu.cc.
Referenced by handleSelfMsg(), sendBeacon(), sendLocalSummaryVector(), sendMessagesRequested(), and sendMfcv_EpidemicRequestMessageVector().
{
     sendDelayedDown(wsm,individualOffset);
 }
Member Data Documentation
AnnotationManager* mfcv_epidemic_rsu::annotations protected
Definition at line 39 of file mfcv_epidemic_rsu.h.
Referenced by initialize().
double mfcv_epidemic_rsu::maiortempo = 0 protected
Definition at line 60 of file mfcv_epidemic_rsu.h.
Referenced by onData().
MyMapMfcv_EpidemicMessageBuffer mfcv_epidemic_rsu::mfcv_epidemicLocalMessageBuffer protected
Definition at line 46 of file mfcv_epidemic_rsu.h.
Referenced by onData(), printMfcv_EpidemicLocalMessageBuffer(), and sendMessagesRequested().
unordered_map<string, bool> mfcv_epidemic_rsu::mfcv_epidemicLocalSummaryVector protected
Definition at line 48 of file mfcv_epidemic_rsu.h.
Referenced by createMfcv_EpidemicRequestMessageVector(), getLocalSummaryVectorData(), onData(), and printMfcv_EpidemicLocalSummaryVectorData().
unordered_map<string, bool> mfcv_epidemic_rsu::mfcv_epidemicRemoteSummaryVector protected
Definition at line 50 of file mfcv_epidemic_rsu.h.
Referenced by createMfcv_EpidemicRemoteSummaryVector(), createMfcv_EpidemicRequestMessageVector(), and printMfcv_EpidemicRemoteSummaryVectorData().
unordered_map<string, bool> mfcv_epidemic_rsu::mfcv_epidemicRequestMessageVector protected
Definition at line 52 of file mfcv_epidemic_rsu.h.
Referenced by createMfcv_EpidemicRequestMessageVector(), getMfcv_EpidemicRequestMessageVectorData(), onData(), and printMfcv_EpidemicRequestMessageVector().
BaseMobility* mfcv_epidemic_rsu::mobi protected
Definition at line 40 of file mfcv_epidemic_rsu.h.
Referenced by initialize().
unordered_map<unsigned int, simtime_t> mfcv_epidemic_rsu::nodesIRecentlySentSummaryVector protected
Definition at line 57 of file mfcv_epidemic_rsu.h.
Referenced by onBeacon(), and printNodesIRecentlySentSummaryVector().
unordered_map<unsigned int, simtime_t> mfcv_epidemic_rsu::nodesRecentlyFoundList protected
Definition at line 55 of file mfcv_epidemic_rsu.h.
queue<string> mfcv_epidemic_rsu::queueFIFO protected
Definition at line 59 of file mfcv_epidemic_rsu.h.
Referenced by onData().
bool mfcv_epidemic_rsu::sentMessage protected
Definition at line 41 of file mfcv_epidemic_rsu.h.
The documentation for this class was generated from the following files:
mfcv_epidemic_rsu.h
mfcv_epidemic_rsu.cc