Veins Framework: WaveShortMessage Class Reference
WaveShortMessage Class Reference
Class generated from modules/messages/WaveShortMessage.msg:27 by nedtool.
#include <WaveShortMessage_m.h>
Public Member Functions
WaveShortMessage (const char *name=NULL, int kind=0)
WaveShortMessage (const WaveShortMessage &other)
virtual ~WaveShortMessage ()
WaveShortMessage & operator= (const WaveShortMessage &other)
virtual WaveShortMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getWsmVersion () const
virtual void setWsmVersion (int wsmVersion)
virtual int getSecurityType () const
virtual void setSecurityType (int securityType)
virtual int getChannelNumber () const
virtual void setChannelNumber (int channelNumber)
virtual int getDataRate () const
virtual void setDataRate (int dataRate)
virtual int getPriority () const
virtual void setPriority (int priority)
virtual int getPsid () const
virtual void setPsid (int psid)
virtual const char * getPsc () const
virtual void setPsc (const char *psc)
virtual int getWsmLength () const
virtual void setWsmLength (int wsmLength)
virtual const char * getWsmData () const
virtual void setWsmData (const char *wsmData)
virtual int getSerial () const
virtual void setSerial (int serial)
virtual Coord & getSenderPos ()
virtual const Coord & getSenderPos () const
virtual void setSenderPos (const Coord &senderPos)
virtual simtime_t getTimestamp () const
virtual void setTimestamp (simtime_t timestamp)
virtual unsigned int getSenderAddress () const
virtual void setSenderAddress (unsigned int senderAddress)
virtual unsigned int getRecipientAddress () const
virtual void setRecipientAddress (unsigned int recipientAddress)
virtual const char * getSource () const
virtual void setSource (const char *source)
virtual const char * getTarget () const
virtual void setTarget (const char *target)
virtual bool getSummaryVector () const
virtual void setSummaryVector (bool summaryVector)
virtual bool getRequestMessages () const
virtual void setRequestMessages (bool requestMessages)
virtual const char * getGlobalMessageIdentificaton () const
virtual void setGlobalMessageIdentificaton (const char *globalMessageIdentificaton)
virtual const char * getLocalMessageIdentificaton () const
virtual void setLocalMessageIdentificaton (const char *localMessageIdentificaton)
virtual unsigned int getHopCount () const
virtual void setHopCount (unsigned int hopCount)
virtual bool getAckRequest () const
virtual void setAckRequest (bool ackRequest)
virtual const char * getRoadId () const
virtual void setRoadId (const char *roadId)
virtual double getSenderSpeed () const
virtual void setSenderSpeed (double senderSpeed)
virtual unsigned short getCategory () const
virtual void setCategory (unsigned short category)
virtual int getVehicleId () const
virtual void setVehicleId (int vehicleId)
virtual unsigned short getHeading () const
virtual void setHeading (unsigned short heading)
virtual Coord & getTargetPos ()
virtual const Coord & getTargetPos () const
virtual void setTargetPos (const Coord &TargetPos)
virtual Coord & getSenderPosBack ()
virtual const Coord & getSenderPosBack () const
virtual void setSenderPosBack (const Coord &senderPosBack)
virtual simtime_t getMessageTimestampGenerate () const
virtual void setMessageTimestampGenerate (simtime_t messageTimestampGenerate)
Protected Member Functions
bool operator== (const WaveShortMessage &)
Protected Attributes
int wsmVersion_var
int securityType_var
int channelNumber_var
int dataRate_var
int priority_var
int psid_var
opp_string psc_var
int wsmLength_var
opp_string wsmData_var
int serial_var
Coord senderPos_var
simtime_t timestamp_var
unsigned int senderAddress_var
unsigned int recipientAddress_var
opp_string source_var
opp_string target_var
bool summaryVector_var
bool requestMessages_var
opp_string globalMessageIdentificaton_var
opp_string localMessageIdentificaton_var
unsigned int hopCount_var
bool ackRequest_var
opp_string roadId_var
double senderSpeed_var
unsigned short category_var
int vehicleId_var
unsigned short heading_var
Coord TargetPos_var
Coord senderPosBack_var
simtime_t messageTimestampGenerate_var
Private Member Functions
void copy (const WaveShortMessage &other)
Detailed Description
Class generated from modules/messages/WaveShortMessage.msg:27 by nedtool.
packet WaveShortMessage
{
    // Version of the Wave Short Message
    int wsmVersion = 0;
    // Determine which security mechanism was used
    int securityType = 0;
    // Channel Number on which this packet was sent
    int channelNumber;
    // Data rate with which this packet was sent
    int dataRate = 1;
    // Power Level with which this packet was sent
    int priority = 3;
    // Unique number to identify the service
    int psid = 0;
    // Provider Service Context
    string psc = "Service with some Data";
    // Length of Wave Short Message
    int wsmLength;
    // Data of Wave Short Message
    string wsmData = "Some Data";
    // not sure, but I think is like a port number or identification of an application
    int serial = 0;
    Coord senderPos;
    simtime_t timestamp = 0;
    // int senderAddress = 0;
    // int recipientAddress = -1;
    // Epidemic changes
    // Set the Address of the sender;
    unsigned int senderAddress = 0;
    // Set the Address of the recipient. 268435455 means broadcast, the conversion of OxFFFFFFF to int;
    unsigned int recipientAddress = 268435455;
    // Add for Epidemic
    // Set the source which generate the message, e.g., car[0], car[1] etc.
    string source;
    // Set the target which the message will be delivered, e.g., rsu[0], rsu[1] etc.
    string target;
    // Set if this is a summary vector or not. true value means summaryvector
    bool summaryVector = false;
    // Set if this is a request vector or not. true value means requestvector
    bool requestMessages = false;
    // Unique global message identification
    string globalMessageIdentificaton;
    // Unique local message identification
    string localMessageIdentificaton;
    // Hop Count works like TTL in the IP packets. -1 means that this variable has not being used
    unsigned int hopCount = 0;
    // Determine if a message has been successfully received or not. False is default value assigned to it
    bool ackRequest = false;
    //Add Minicurso_UFPI - Send ID da pista e velocidade
    //Current ID of the road, e. g., 1ato2b
    string roadId = "";
    // Speed of vehicle in the moment which send a message WSM, wsm->setSenderSpeed(traci->getSpeed());
    double senderSpeed = 0.0;
    // MFCV
    // Category of vehicle (1 to 10): 1 is bus, 2 is cab, ... need to complete
    unsigned short category = 0;
    // vehicle ID (wsm->setVehicleId(traci->getId());)
    int vehicleId;
    // Path history of the vehicle, calculated from time to time
    //string pathHistory;
    // Radius of Gyration of the vehicle, calculated from time to time.
    // The vehicle send yours Radius of Gyration to another vehicles
    //double radius_of_Gyration;
    // test Jonh
    unsigned short heading;
    // targetPost
    Coord TargetPos;
    Coord senderPosBack;
    simtime_t messageTimestampGenerate = 0;
}
Definition at line 105 of file WaveShortMessage_m.h.
Constructor & Destructor Documentation
WaveShortMessage::WaveShortMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
WaveShortMessage::WaveShortMessage (const WaveShortMessage & other)
virtual WaveShortMessage::~WaveShortMessage () virtual
Member Function Documentation
void WaveShortMessage::copy (const WaveShortMessage & other) private
virtual WaveShortMessage* WaveShortMessage::dup () const inline virtual
Reimplemented in FloodingMessage.
Definition at line 151 of file WaveShortMessage_m.h.
Referenced by Mac1609_4::handleSelfMsg(), and vehDist::onData().
 {return new WaveShortMessage(*this);}
virtual bool WaveShortMessage::getAckRequest () const virtual
virtual unsigned short WaveShortMessage::getCategory () const virtual
virtual int WaveShortMessage::getChannelNumber () const virtual
Referenced by Mac1609_4::handleUpperMsg(), epidemic_rsu::printWaveShortMessage(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic::recordOnFile(), vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), and vehDist::recordOnFileMessagesBroadcast().
virtual int WaveShortMessage::getDataRate () const virtual
virtual const char* WaveShortMessage::getGlobalMessageIdentificaton () const virtual
Referenced by vehDist::generateMessage(), epidemic::generateMessage(), mfcv_epidemic::generateMessage(), vehDist::onData(), epidemic_rsu::printWaveShortMessage(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), and mfcv_epidemic::printWaveShortMessage().
virtual unsigned short WaveShortMessage::getHeading () const virtual
Referenced by mfcv_epidemic::onBeacon(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic::recordOnFile(), vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), and vehDist::recordOnFileMessagesBroadcast().
virtual unsigned int WaveShortMessage::getHopCount () const virtual
Referenced by vehDist::onData(), epidemic_rsu::printEpidemicLocalMessageBuffer(), epidemic::printEpidemicLocalMessageBuffer(), mfcv_epidemic_rsu::printMfcv_EpidemicLocalMessageBuffer(), mfcv_epidemic::printMfcv_EpidemicLocalMessageBuffer(), mfcv_epidemic::printMfcv_EpidemicLocalMessageBufferOnFile(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic_rsu::sendMessagesRequested(), epidemic_rsu::sendMessagesRequested(), epidemic::sendMessagesRequested(), mfcv_epidemic::sendMessagesRequested(), and vehDist::updateMessageWSM().
virtual const char* WaveShortMessage::getLocalMessageIdentificaton () const virtual
Referenced by epidemic_rsu::printWaveShortMessage(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), and mfcv_epidemic::printWaveShortMessage().
virtual simtime_t WaveShortMessage::getMessageTimestampGenerate () const virtual
Referenced by vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), and vehDist::recordOnFileMessagesBroadcast().
virtual int WaveShortMessage::getPriority () const virtual
Referenced by Mac1609_4::handleSelfMsg(), Mac1609_4::handleUpperMsg(), epidemic_rsu::printWaveShortMessage(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic::recordOnFile(), vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), vehDist::recordOnFileMessagesBroadcast(), and vehDist::updateMessageWSM().
virtual const char* WaveShortMessage::getPsc () const virtual
virtual int WaveShortMessage::getPsid () const virtual
Referenced by epidemic_rsu::printWaveShortMessage(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic::recordOnFile(), vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), and vehDist::recordOnFileMessagesBroadcast().
virtual unsigned int WaveShortMessage::getRecipientAddress () const virtual
Referenced by vehDist_rsu::onData(), test1::onData(), service_discovery::onData(), epidemic_rsu::onData(), mfcv_epidemic_rsu::onData(), vehDist::onData(), epidemic::onData(), mfcv_epidemic::onData(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic::recordOnFile(), vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), and vehDist::recordOnFileMessagesBroadcast().
virtual bool WaveShortMessage::getRequestMessages () const virtual
Referenced by epidemic_rsu::onData(), mfcv_epidemic_rsu::onData(), epidemic::onData(), mfcv_epidemic::onData(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic::recordOnFile(), vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), and vehDist::recordOnFileMessagesBroadcast().
virtual const char* WaveShortMessage::getRoadId () const virtual
Referenced by mfcv_rsu::onBeacon(), and minicurso_UFPI_TraCI::onBeacon().
virtual int WaveShortMessage::getSecurityType () const virtual
virtual unsigned int WaveShortMessage::getSenderAddress () const virtual
Referenced by epidemic_rsu::onBeacon(), mfcv_epidemic_rsu::onBeacon(), vehDist::onBeacon(), epidemic::onBeacon(), mfcv_epidemic::onBeacon(), service_discovery::onData(), test1::onData(), epidemic_rsu::onData(), mfcv_epidemic_rsu::onData(), vehDist::onData(), epidemic::onData(), mfcv_epidemic::onData(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic::recordOnFile(), vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), and vehDist::recordOnFileMessagesBroadcast().
virtual Coord& WaveShortMessage::getSenderPos () virtual
Referenced by mfcv_epidemic::onBeacon(), default_veins_TraCI_RSU::onData(), mfcv_rsu::onData(), minicurso_UFPI_TraCI_RSU::onData(), default_veins_TraCI::onData(), mfcv::onData(), epidemic::onData(), minicurso_UFPI_TraCI::onData(), mfcv_epidemic::onData(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic::recordOnFile(), vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), and vehDist::recordOnFileMessagesBroadcast().
virtual const Coord& WaveShortMessage::getSenderPos () const inline virtual
Definition at line 177 of file WaveShortMessage_m.h.
Referenced by getSenderPos().
 {return const_cast<WaveShortMessage*>(this)->getSenderPos();}
virtual Coord& WaveShortMessage::getSenderPosBack () virtual
Referenced by mfcv_epidemic::onBeacon().
virtual const Coord& WaveShortMessage::getSenderPosBack () const inline virtual
Definition at line 215 of file WaveShortMessage_m.h.
Referenced by getSenderPosBack().
 {return const_cast<WaveShortMessage*>(this)->getSenderPosBack();}
virtual double WaveShortMessage::getSenderSpeed () const virtual
Referenced by minicurso_UFPI_TraCI::onBeacon().
virtual int WaveShortMessage::getSerial () const virtual
Referenced by epidemic_rsu::printWaveShortMessage(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic::recordOnFile(), vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), and vehDist::recordOnFileMessagesBroadcast().
virtual const char* WaveShortMessage::getSource () const virtual
Referenced by vehDist::onData(), epidemic_rsu::printEpidemicLocalMessageBuffer(), epidemic::printEpidemicLocalMessageBuffer(), mfcv_epidemic_rsu::printMfcv_EpidemicLocalMessageBuffer(), mfcv_epidemic::printMfcv_EpidemicLocalMessageBuffer(), mfcv_epidemic::printMfcv_EpidemicLocalMessageBufferOnFile(), epidemic_rsu::printWaveShortMessage(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic::recordOnFile(), vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), vehDist::recordOnFileMessagesBroadcast(), epidemic_rsu::sendMessagesRequested(), mfcv_epidemic_rsu::sendMessagesRequested(), epidemic::sendMessagesRequested(), and mfcv_epidemic::sendMessagesRequested().
virtual bool WaveShortMessage::getSummaryVector () const virtual
Referenced by epidemic_rsu::onData(), mfcv_epidemic_rsu::onData(), epidemic::onData(), mfcv_epidemic::onData(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic::recordOnFile(), vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), and vehDist::recordOnFileMessagesBroadcast().
virtual const char* WaveShortMessage::getTarget () const virtual
Referenced by vehDist_rsu::onData(), epidemic_rsu::onData(), mfcv_epidemic_rsu::onData(), epidemic::onData(), mfcv_epidemic::onData(), epidemic_rsu::printEpidemicLocalMessageBuffer(), epidemic::printEpidemicLocalMessageBuffer(), mfcv_epidemic_rsu::printMfcv_EpidemicLocalMessageBuffer(), mfcv_epidemic::printMfcv_EpidemicLocalMessageBuffer(), mfcv_epidemic::printMfcv_EpidemicLocalMessageBufferOnFile(), epidemic_rsu::printWaveShortMessage(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic::recordOnFile(), vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), vehDist::recordOnFileMessagesBroadcast(), epidemic_rsu::sendMessagesRequested(), mfcv_epidemic_rsu::sendMessagesRequested(), epidemic::sendMessagesRequested(), and mfcv_epidemic::sendMessagesRequested().
virtual Coord& WaveShortMessage::getTargetPos () virtual
Referenced by mfcv_epidemic::onBeacon().
virtual const Coord& WaveShortMessage::getTargetPos () const inline virtual
Definition at line 212 of file WaveShortMessage_m.h.
Referenced by getTargetPos().
 {return const_cast<WaveShortMessage*>(this)->getTargetPos();}
virtual simtime_t WaveShortMessage::getTimestamp () const virtual
Referenced by epidemic_rsu::onData(), mfcv_epidemic_rsu::onData(), vehDist::prepareBeaconWSM(), Flooding::prepareWSM(), AdvancedFlooding::prepareWSM(), BaseWaveApplLayer::prepareWSM(), BaseWaveApplLayer::prepareWSM_epidemic(), mfcv_epidemic_rsu::prepareWSM_mfcv_epidemic(), mfcv_epidemic::prepareWSM_mfcv_epidemic(), mfcv::prepareWSM_node(), mfcv_rsu::prepareWSM_rsu(), epidemic_rsu::printEpidemicLocalMessageBuffer(), epidemic::printEpidemicLocalMessageBuffer(), mfcv_epidemic_rsu::printMfcv_EpidemicLocalMessageBuffer(), mfcv_epidemic::printMfcv_EpidemicLocalMessageBuffer(), mfcv_epidemic::printMfcv_EpidemicLocalMessageBufferOnFile(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic::recordOnFile(), vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), vehDist::recordOnFileMessagesBroadcast(), mfcv_epidemic_rsu::sendMessagesRequested(), epidemic_rsu::sendMessagesRequested(), epidemic::sendMessagesRequested(), mfcv_epidemic::sendMessagesRequested(), and vehDist::updateMessageWSM().
virtual int WaveShortMessage::getVehicleId () const virtual
virtual const char* WaveShortMessage::getWsmData () const virtual
Referenced by osdp::onData(), mfcv_rsu::onData(), default_veins_TraCI_RSU::onData(), minicurso_UFPI_TraCI_RSU::onData(), service_discovery::onData(), test1::onData(), default_veins_TraCI::onData(), mfcv::onData(), mfcv_epidemic_rsu::onData(), epidemic_rsu::onData(), epidemic::onData(), minicurso_UFPI_TraCI::onData(), mfcv_epidemic::onData(), epidemic_rsu::printEpidemicLocalMessageBuffer(), epidemic::printEpidemicLocalMessageBuffer(), mfcv_epidemic_rsu::printMfcv_EpidemicLocalMessageBuffer(), mfcv_epidemic::printMfcv_EpidemicLocalMessageBuffer(), mfcv_epidemic::printMfcv_EpidemicLocalMessageBufferOnFile(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic::recordOnFile(), vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), vehDist::recordOnFileMessagesBroadcast(), epidemic_rsu::sendMessagesRequested(), mfcv_epidemic_rsu::sendMessagesRequested(), epidemic::sendMessagesRequested(), and mfcv_epidemic::sendMessagesRequested().
virtual int WaveShortMessage::getWsmLength () const virtual
virtual int WaveShortMessage::getWsmVersion () const virtual
Referenced by epidemic_rsu::printWaveShortMessage(), mfcv_epidemic_rsu::printWaveShortMessage(), epidemic::printWaveShortMessage(), mfcv_epidemic::printWaveShortMessage(), mfcv_epidemic::recordOnFile(), vehDist_rsu::recordOnFileMessages(), vehDist::recordOnFileMessages(), vehDist_rsu::recordOnFileMessagesBroadcast(), and vehDist::recordOnFileMessagesBroadcast().
WaveShortMessage& WaveShortMessage::operator= (const WaveShortMessage & other)
bool WaveShortMessage::operator== (const WaveShortMessage &) protected
virtual void WaveShortMessage::parsimPack (cCommBuffer * b) virtual
Reimplemented in FloodingMessage.
Referenced by doPacking().
virtual void WaveShortMessage::parsimUnpack (cCommBuffer * b) virtual
Reimplemented in FloodingMessage.
Referenced by doUnpacking().
virtual void WaveShortMessage::setAckRequest (bool ackRequest) virtual
virtual void WaveShortMessage::setCategory (unsigned short category) virtual
Referenced by vehDist::prepareBeaconWSM(), mfcv_epidemic::prepareWSM_mfcv_epidemic(), and mfcv::prepareWSM_node().
virtual void WaveShortMessage::setChannelNumber (int channelNumber) virtual
Referenced by vehDist::generateMessage(), epidemic::generateMessage(), mfcv_epidemic::generateMessage(), Mac1609_4::handleUpperMsg(), vehDist::prepareBeaconWSM(), Flooding::prepareWSM(), AdvancedFlooding::prepareWSM(), BaseWaveApplLayer::prepareWSM(), BaseWaveApplLayer::prepareWSM_epidemic(), mfcv_epidemic_rsu::prepareWSM_mfcv_epidemic(), mfcv_epidemic::prepareWSM_mfcv_epidemic(), mfcv::prepareWSM_node(), and mfcv_rsu::prepareWSM_rsu().
virtual void WaveShortMessage::setDataRate (int dataRate) virtual
virtual void WaveShortMessage::setGlobalMessageIdentificaton (const char * globalMessageIdentificaton) virtual
Referenced by vehDist::generateMessage(), epidemic::generateMessage(), and mfcv_epidemic::generateMessage().
virtual void WaveShortMessage::setHeading (unsigned short heading) virtual
Referenced by vehDist::prepareBeaconWSM(), mfcv_epidemic_rsu::prepareWSM_mfcv_epidemic(), and mfcv_epidemic::prepareWSM_mfcv_epidemic().
virtual void WaveShortMessage::setHopCount (unsigned int hopCount) virtual
Referenced by vehDist::generateMessage(), epidemic::generateMessage(), mfcv_epidemic::generateMessage(), epidemic_rsu::onData(), mfcv_epidemic_rsu::onData(), epidemic::onData(), mfcv_epidemic::onData(), and vehDist::updateMessageWSM().
virtual void WaveShortMessage::setLocalMessageIdentificaton (const char * localMessageIdentificaton) virtual
Referenced by epidemic::generateMessage(), and mfcv_epidemic::generateMessage().
virtual void WaveShortMessage::setMessageTimestampGenerate (simtime_t messageTimestampGenerate) virtual
Referenced by vehDist::generateMessage().
virtual void WaveShortMessage::setPriority (int priority) virtual
Referenced by vehDist::generateMessage(), epidemic::generateMessage(), mfcv_epidemic::generateMessage(), vehDist::prepareBeaconWSM(), Flooding::prepareWSM(), AdvancedFlooding::prepareWSM(), BaseWaveApplLayer::prepareWSM(), BaseWaveApplLayer::prepareWSM_epidemic(), mfcv_epidemic_rsu::prepareWSM_mfcv_epidemic(), mfcv_epidemic::prepareWSM_mfcv_epidemic(), mfcv::prepareWSM_node(), and mfcv_rsu::prepareWSM_rsu().
virtual void WaveShortMessage::setPsc (const char * psc) virtual
virtual void WaveShortMessage::setPsid (int psid) virtual
Referenced by vehDist::generateMessage(), epidemic::generateMessage(), mfcv_epidemic::generateMessage(), vehDist::prepareBeaconWSM(), Flooding::prepareWSM(), AdvancedFlooding::prepareWSM(), BaseWaveApplLayer::prepareWSM(), BaseWaveApplLayer::prepareWSM_epidemic(), mfcv_epidemic_rsu::prepareWSM_mfcv_epidemic(), mfcv_epidemic::prepareWSM_mfcv_epidemic(), mfcv::prepareWSM_node(), and mfcv_rsu::prepareWSM_rsu().
virtual void WaveShortMessage::setRecipientAddress (unsigned int recipientAddress) virtual
Referenced by vehDist::generateMessage(), epidemic::generateMessage(), mfcv_epidemic::generateMessage(), vehDist::prepareBeaconWSM(), Flooding::prepareWSM(), AdvancedFlooding::prepareWSM(), BaseWaveApplLayer::prepareWSM(), BaseWaveApplLayer::prepareWSM_epidemic(), mfcv_epidemic_rsu::prepareWSM_mfcv_epidemic(), mfcv_epidemic::prepareWSM_mfcv_epidemic(), mfcv::prepareWSM_node(), mfcv_rsu::prepareWSM_rsu(), and vehDist::updateMessageWSM().
virtual void WaveShortMessage::setRequestMessages (bool requestMessages) virtual
Referenced by epidemic_rsu::sendEpidemicRequestMessageVector(), epidemic::sendEpidemicRequestMessageVector(), epidemic_rsu::sendLocalSummaryVector(), mfcv_epidemic_rsu::sendLocalSummaryVector(), epidemic::sendLocalSummaryVector(), mfcv_epidemic::sendLocalSummaryVector(), epidemic_rsu::sendMessagesRequested(), mfcv_epidemic_rsu::sendMessagesRequested(), epidemic::sendMessagesRequested(), mfcv_epidemic::sendMessagesRequested(), mfcv_epidemic_rsu::sendMfcv_EpidemicRequestMessageVector(), and mfcv_epidemic::sendMfcv_EpidemicRequestMessageVector().
virtual void WaveShortMessage::setRoadId (const char * roadId) virtual
Referenced by vehDist::prepareBeaconWSM(), BaseWaveApplLayer::prepareWSM(), mfcv_epidemic::prepareWSM_mfcv_epidemic(), mfcv::prepareWSM_node(), and vehDist::updateMessageWSM().
virtual void WaveShortMessage::setSecurityType (int securityType) virtual
virtual void WaveShortMessage::setSenderAddress (unsigned int senderAddress) virtual
Referenced by vehDist::generateMessage(), epidemic::generateMessage(), mfcv_epidemic::generateMessage(), vehDist::prepareBeaconWSM(), Flooding::prepareWSM(), AdvancedFlooding::prepareWSM(), BaseWaveApplLayer::prepareWSM(), BaseWaveApplLayer::prepareWSM_epidemic(), mfcv_epidemic_rsu::prepareWSM_mfcv_epidemic(), mfcv_epidemic::prepareWSM_mfcv_epidemic(), mfcv::prepareWSM_node(), mfcv_rsu::prepareWSM_rsu(), and vehDist::updateMessageWSM().
virtual void WaveShortMessage::setSenderPos (const Coord & senderPos) virtual
Referenced by vehDist::generateMessage(), epidemic::generateMessage(), mfcv_epidemic::generateMessage(), vehDist::prepareBeaconWSM(), Flooding::prepareWSM(), AdvancedFlooding::prepareWSM(), BaseWaveApplLayer::prepareWSM(), BaseWaveApplLayer::prepareWSM_epidemic(), mfcv_epidemic_rsu::prepareWSM_mfcv_epidemic(), mfcv_epidemic::prepareWSM_mfcv_epidemic(), mfcv::prepareWSM_node(), mfcv_rsu::prepareWSM_rsu(), and vehDist::updateMessageWSM().
virtual void WaveShortMessage::setSenderPosBack (const Coord & senderPosBack) virtual
Referenced by mfcv_epidemic::generateMessage(), vehDist::prepareBeaconWSM(), mfcv_epidemic::prepareWSM_mfcv_epidemic(), and vehDist::updateMessageWSM().
virtual void WaveShortMessage::setSenderSpeed (double senderSpeed) virtual
Referenced by vehDist::prepareBeaconWSM(), BaseWaveApplLayer::prepareWSM(), mfcv_epidemic::prepareWSM_mfcv_epidemic(), mfcv::prepareWSM_node(), and vehDist::updateMessageWSM().
virtual void WaveShortMessage::setSerial (int serial) virtual
Referenced by vehDist::generateMessage(), epidemic::generateMessage(), mfcv_epidemic::generateMessage(), vehDist::prepareBeaconWSM(), Flooding::prepareWSM(), AdvancedFlooding::prepareWSM(), BaseWaveApplLayer::prepareWSM(), BaseWaveApplLayer::prepareWSM_epidemic(), mfcv_epidemic_rsu::prepareWSM_mfcv_epidemic(), mfcv_epidemic::prepareWSM_mfcv_epidemic(), mfcv::prepareWSM_node(), and mfcv_rsu::prepareWSM_rsu().
virtual void WaveShortMessage::setSource (const char * source) virtual
Referenced by vehDist::generateMessage(), epidemic::generateMessage(), mfcv_epidemic::generateMessage(), mfcv_epidemic_rsu::onData(), epidemic_rsu::onData(), epidemic::onData(), and mfcv_epidemic::onData().
virtual void WaveShortMessage::setSummaryVector (bool summaryVector) virtual
Referenced by epidemic::generateMessage(), mfcv_epidemic::generateMessage(), epidemic_rsu::sendEpidemicRequestMessageVector(), epidemic::sendEpidemicRequestMessageVector(), epidemic_rsu::sendLocalSummaryVector(), mfcv_epidemic_rsu::sendLocalSummaryVector(), epidemic::sendLocalSummaryVector(), mfcv_epidemic::sendLocalSummaryVector(), epidemic_rsu::sendMessagesRequested(), mfcv_epidemic_rsu::sendMessagesRequested(), epidemic::sendMessagesRequested(), mfcv_epidemic::sendMessagesRequested(), mfcv_epidemic_rsu::sendMfcv_EpidemicRequestMessageVector(), and mfcv_epidemic::sendMfcv_EpidemicRequestMessageVector().
virtual void WaveShortMessage::setTarget (const char * target) virtual
Referenced by vehDist::generateMessage(), epidemic::generateMessage(), mfcv_epidemic::generateMessage(), mfcv_epidemic_rsu::onData(), epidemic_rsu::onData(), epidemic::onData(), and mfcv_epidemic::onData().
virtual void WaveShortMessage::setTargetPos (const Coord & TargetPos) virtual
Referenced by vehDist::generateMessage(), mfcv_epidemic::generateMessage(), and mfcv_epidemic::prepareWSM_mfcv_epidemic().
virtual void WaveShortMessage::setTimestamp (simtime_t timestamp) virtual
Referenced by vehDist::generateMessage(), epidemic::generateMessage(), mfcv_epidemic::generateMessage(), vehDist_rsu::onData(), mfcv_epidemic_rsu::onData(), epidemic_rsu::onData(), vehDist::onData(), epidemic::onData(), mfcv_epidemic::onData(), vehDist::prepareBeaconWSM(), Flooding::prepareWSM(), AdvancedFlooding::prepareWSM(), BaseWaveApplLayer::prepareWSM(), BaseWaveApplLayer::prepareWSM_epidemic(), mfcv_epidemic_rsu::prepareWSM_mfcv_epidemic(), mfcv_epidemic::prepareWSM_mfcv_epidemic(), mfcv::prepareWSM_node(), mfcv_rsu::prepareWSM_rsu(), and vehDist::updateMessageWSM().
virtual void WaveShortMessage::setVehicleId (int vehicleId) virtual
Referenced by vehDist::prepareBeaconWSM(), mfcv_epidemic::prepareWSM_mfcv_epidemic(), mfcv::prepareWSM_node(), and vehDist::updateMessageWSM().
virtual void WaveShortMessage::setWsmData (const char * wsmData) virtual
Referenced by vehDist::generateMessage(), epidemic::generateMessage(), mfcv_epidemic::generateMessage(), epidemic_rsu::onData(), mfcv_epidemic_rsu::onData(), epidemic::onData(), mfcv_epidemic::onData(), epidemic_rsu::sendEpidemicRequestMessageVector(), epidemic::sendEpidemicRequestMessageVector(), epidemic_rsu::sendLocalSummaryVector(), mfcv_epidemic_rsu::sendLocalSummaryVector(), epidemic::sendLocalSummaryVector(), mfcv_epidemic::sendLocalSummaryVector(), osdp_RSU::sendMessage(), service_discovery_RSU::sendMessage(), test1_rsu::sendMessage(), vehDist_rsu::sendMessage(), osdp::sendMessage(), minicurso_UFPI_TraCI_RSU::sendMessage(), mfcv_rsu::sendMessage(), default_veins_TraCI_RSU::sendMessage(), service_discovery::sendMessage(), test1::sendMessage(), default_veins_TraCI::sendMessage(), mfcv::sendMessage(), vehDist::sendMessage(), minicurso_UFPI_TraCI::sendMessage(), mfcv_epidemic_rsu::sendMessagesRequested(), epidemic_rsu::sendMessagesRequested(), epidemic::sendMessagesRequested(), mfcv_epidemic::sendMessagesRequested(), mfcv_epidemic_rsu::sendMfcv_EpidemicRequestMessageVector(), and mfcv_epidemic::sendMfcv_EpidemicRequestMessageVector().
virtual void WaveShortMessage::setWsmLength (int wsmLength) virtual
virtual void WaveShortMessage::setWsmVersion (int wsmVersion) virtual
Referenced by vehDist::generateMessage(), epidemic::generateMessage(), mfcv_epidemic::generateMessage(), vehDist::prepareBeaconWSM(), Flooding::prepareWSM(), AdvancedFlooding::prepareWSM(), BaseWaveApplLayer::prepareWSM(), BaseWaveApplLayer::prepareWSM_epidemic(), mfcv_epidemic_rsu::prepareWSM_mfcv_epidemic(), mfcv_epidemic::prepareWSM_mfcv_epidemic(), mfcv::prepareWSM_node(), and mfcv_rsu::prepareWSM_rsu().
Member Data Documentation
bool WaveShortMessage::ackRequest_var protected
Definition at line 129 of file WaveShortMessage_m.h.
unsigned short WaveShortMessage::category_var protected
Definition at line 132 of file WaveShortMessage_m.h.
int WaveShortMessage::channelNumber_var protected
Definition at line 110 of file WaveShortMessage_m.h.
int WaveShortMessage::dataRate_var protected
Definition at line 111 of file WaveShortMessage_m.h.
opp_string WaveShortMessage::globalMessageIdentificaton_var protected
Definition at line 126 of file WaveShortMessage_m.h.
unsigned short WaveShortMessage::heading_var protected
Definition at line 134 of file WaveShortMessage_m.h.
unsigned int WaveShortMessage::hopCount_var protected
Definition at line 128 of file WaveShortMessage_m.h.
opp_string WaveShortMessage::localMessageIdentificaton_var protected
Definition at line 127 of file WaveShortMessage_m.h.
simtime_t WaveShortMessage::messageTimestampGenerate_var protected
Definition at line 137 of file WaveShortMessage_m.h.
int WaveShortMessage::priority_var protected
Definition at line 112 of file WaveShortMessage_m.h.
opp_string WaveShortMessage::psc_var protected
Definition at line 114 of file WaveShortMessage_m.h.
int WaveShortMessage::psid_var protected
Definition at line 113 of file WaveShortMessage_m.h.
unsigned int WaveShortMessage::recipientAddress_var protected
Definition at line 121 of file WaveShortMessage_m.h.
bool WaveShortMessage::requestMessages_var protected
Definition at line 125 of file WaveShortMessage_m.h.
opp_string WaveShortMessage::roadId_var protected
Definition at line 130 of file WaveShortMessage_m.h.
int WaveShortMessage::securityType_var protected
Definition at line 109 of file WaveShortMessage_m.h.
unsigned int WaveShortMessage::senderAddress_var protected
Definition at line 120 of file WaveShortMessage_m.h.
Coord WaveShortMessage::senderPos_var protected
Definition at line 118 of file WaveShortMessage_m.h.
Coord WaveShortMessage::senderPosBack_var protected
Definition at line 136 of file WaveShortMessage_m.h.
double WaveShortMessage::senderSpeed_var protected
Definition at line 131 of file WaveShortMessage_m.h.
int WaveShortMessage::serial_var protected
Definition at line 117 of file WaveShortMessage_m.h.
opp_string WaveShortMessage::source_var protected
Definition at line 122 of file WaveShortMessage_m.h.
bool WaveShortMessage::summaryVector_var protected
Definition at line 124 of file WaveShortMessage_m.h.
opp_string WaveShortMessage::target_var protected
Definition at line 123 of file WaveShortMessage_m.h.
Coord WaveShortMessage::TargetPos_var protected
Definition at line 135 of file WaveShortMessage_m.h.
simtime_t WaveShortMessage::timestamp_var protected
Definition at line 119 of file WaveShortMessage_m.h.
int WaveShortMessage::vehicleId_var protected
Definition at line 133 of file WaveShortMessage_m.h.
opp_string WaveShortMessage::wsmData_var protected
Definition at line 116 of file WaveShortMessage_m.h.
int WaveShortMessage::wsmLength_var protected
Definition at line 115 of file WaveShortMessage_m.h.
int WaveShortMessage::wsmVersion_var protected
Definition at line 108 of file WaveShortMessage_m.h.
The documentation for this class was generated from the following file:
WaveShortMessage_m.h