Veins Framework: ConcatConstMapping< Operator > Class Template Reference
ConcatConstMapping< Operator > Class Template Reference
Defines it values by concatenating one or more Mappings to a reference Mapping.
#include <MappingUtils.h>
Public Member Functions
template<class Iterator >
ConcatConstMapping (ConstMapping *refMapping, Iterator first, Iterator last, bool continueOutOfRange=true, Argument::mapped_type_cref oorValue=Argument::mapped_type(0), Operator op=Operator())
Initializes with the passed reference Mapping, the operator and the Mappings defined by the passed iterator.
ConcatConstMapping (ConstMapping *refMapping, ConstMapping *other, bool continueOutOfRange=true, Argument::mapped_type_cref oorValue=Argument::mapped_type(0), Operator op=Operator())
Initializes with the passed reference Mapping, the operator and another Mapping to concatenate.
void addMapping (ConstMapping *m)
Adds another Mapping to the list of Mappings to concatenate.
virtual Argument::mapped_type getValue (const Argument &pos) const
Returns the value of this Mapping at the position specified by the passed Argument.
Mapping * createConcatenatedMapping () const
Returns the concatenated Mapping.
virtual ConstMappingIterator * createConstIterator () const
Returns a pointer of a new Iterator which is able to iterate over this Mapping.
virtual ConstMappingIterator * createConstIterator (const Argument &pos) const
Returns a pointer of a new Iterator which is able to iterate over the function.
virtual ConstMapping * constClone () const
returns a deep copy of this mapping instance.
ConstMapping * getRefMapping ()
Returns the pointer to the reference mapping.
Public Member Functions inherited from ConstMapping
ConstMapping ()
Initializes the ConstMapping with a the time dimension as domain.
ConstMapping (const DimensionSet &dimSet)
Initializes the ConstMapping with the passed DimensionSet as Domain.
virtual ~ConstMapping ()
argument_value_t operator[] (const Argument &pos) const
Returns the value of this Mapping at the position specified by the passed Argument.
const DimensionSet & getDimensionSet () const
Returns this Mappings domain as DimensionSet.
template<class stream >
stream & print (stream &out, argument_value_cref_t lTimeScale=argument_value_t(1000), argument_value_cref_t lLeftColScale=Argument::MappedOne, const std::string &sTableHead=std::string("o\\ms"), const Dimension *const pOnlyDim=NULL) const
Prints the Mapping to an output stream.
Protected Types
typedef std::pair< Dimension,
Argument::const_iterator > DimIteratorPair
typedef std::list< ConstMapping * > MappingSet
Protected Attributes
MappingSet mappings
ConstMapping * refMapping
bool continueOutOfRange
Argument::mapped_type oorValue
Operator op
Protected Attributes inherited from ConstMapping
DimensionSet dimensions
The dimensions of this mappings domain.
Additional Inherited Members
Public Types inherited from ConstMapping
typedef Argument::mapped_type argument_value_t
typedef Argument::mapped_type_cref argument_value_cref_t
Detailed Description
template<class Operator>
class ConcatConstMapping< Operator >
Defines it values by concatenating one or more Mappings to a reference Mapping.
Author
Karl Wessel
Definition at line 1944 of file MappingUtils.h.
Member Typedef Documentation
template<class Operator > typedef std::pair<Dimension, Argument::const_iterator> ConcatConstMapping< Operator >::DimIteratorPair protected
Definition at line 1946 of file MappingUtils.h.
template<class Operator > typedef std::list<ConstMapping*> ConcatConstMapping< Operator >::MappingSet protected
Definition at line 1947 of file MappingUtils.h.
Constructor & Destructor Documentation
template<class Operator > template<class Iterator > ConcatConstMapping< Operator >::ConcatConstMapping (ConstMapping * refMapping, Iterator first, Iterator last, bool continueOutOfRange = true, Argument::mapped_type_cref oorValue = Argument::mapped_type(0), Operator op = Operator()) inline
Initializes with the passed reference Mapping, the operator and the Mappings defined by the passed iterator.
Definition at line 1961 of file MappingUtils.h.
Referenced by ConcatConstMapping< Operator >::constClone().
                                                     :
                 ConstMapping(refMapping->getDimensionSet()),
                 refMapping(refMapping),
                 continueOutOfRange(continueOutOfRange),
                 oorValue(oorValue),
                 op(op)
         {
                 while(first != last) {
                         mappings.push_back(*first);
                         ++first;
                 }
         }
template<class Operator > ConcatConstMapping< Operator >::ConcatConstMapping (ConstMapping * refMapping, ConstMapping * other, bool continueOutOfRange = true, Argument::mapped_type_cref oorValue = Argument::mapped_type(0), Operator op = Operator()) inline
Initializes with the passed reference Mapping, the operator and another Mapping to concatenate.
Definition at line 1982 of file MappingUtils.h.
                                                     :
                 ConstMapping(refMapping->getDimensionSet()),
                 refMapping(refMapping),
                 continueOutOfRange(continueOutOfRange),
                 oorValue(oorValue),
                 op(op)
         {
                 mappings.push_back(other);
         }
Member Function Documentation
template<class Operator > void ConcatConstMapping< Operator >::addMapping (ConstMapping * m) inline
Adds another Mapping to the list of Mappings to concatenate.
Definition at line 1999 of file MappingUtils.h.
{
                 mappings.push_back(m);
         }
template<class Operator > virtual ConstMapping* ConcatConstMapping< Operator >::constClone () const inline virtual
returns a deep copy of this mapping instance.
Implements ConstMapping.
Definition at line 2050 of file MappingUtils.h.
{
                 return new ConcatConstMapping(*this);
         }
template<class Operator > Mapping* ConcatConstMapping< Operator >::createConcatenatedMapping () const inline
Returns the concatenated Mapping.
Definition at line 2017 of file MappingUtils.h.
Referenced by ConcatConstMapping< Operator >::createConstIterator().
{
                 assert(!mappings.empty());
                 MappingSet::const_iterator       it    = mappings.begin();
                 const MappingSet::const_iterator itEnd = mappings.end();
                 Mapping* result = MappingUtils::applyElementWiseOperator(*refMapping, **it, op,
                                                                                                                                  oorValue, continueOutOfRange);
                 while(++it != itEnd) {
                         Mapping* buf = result;
                         result = MappingUtils::applyElementWiseOperator(*buf, **it, op,
                                                                                                                         oorValue, continueOutOfRange);
                         delete buf;
                 }
                 return result;
         }
template<class Operator > virtual ConstMappingIterator* ConcatConstMapping< Operator >::createConstIterator () const inline virtual
Returns a pointer of a new Iterator which is able to iterate over this Mapping.
See class ConstIterator for details.
Implements ConstMapping.
Definition at line 2036 of file MappingUtils.h.
{
                 if(mappings.empty()) {
                         return refMapping->createConstIterator();
                 }
                 return new ConcatConstMappingIterator(createConcatenatedMapping());
         }
template<class Operator > virtual ConstMappingIterator* ConcatConstMapping< Operator >::createConstIterator (const Argument & pos) const inline virtual
Returns a pointer of a new Iterator which is able to iterate over the function.
The iterator starts at the passed position.
See class ConstIterator for details.
Implements ConstMapping.
Definition at line 2043 of file MappingUtils.h.
{
                 if(mappings.empty()) {
                         return refMapping->createConstIterator(pos);
                 }
                 return new ConcatConstMappingIterator(createConcatenatedMapping(), pos);
         }
template<class Operator > ConstMapping* ConcatConstMapping< Operator >::getRefMapping () inline
Returns the pointer to the reference mapping.
Definition at line 2057 of file MappingUtils.h.
Referenced by Signal::~Signal().
{
                 return refMapping;
         }
template<class Operator > virtual Argument::mapped_type ConcatConstMapping< Operator >::getValue (const Argument & pos) const inline virtual
Returns the value of this Mapping at the position specified by the passed Argument.
The complexity of this method depends on the actual implementation.
Implements ConstMapping.
Definition at line 2003 of file MappingUtils.h.
Referenced by SNRThresholdDecider::processNewSignal(), and BaseDecider::processNewSignal().
{
                 const MappingSet::const_iterator itEnd = mappings.end();
                 Argument::mapped_type            res   = refMapping->getValue(pos);
                 for (MappingSet::const_iterator it = mappings.begin(); it != itEnd; ++it) {
                         res = op(res, (*it)->getValue(pos));
                 }
                 return res;
         }
Member Data Documentation
template<class Operator > bool ConcatConstMapping< Operator >::continueOutOfRange protected
Definition at line 1951 of file MappingUtils.h.
Referenced by ConcatConstMapping< Operator >::createConcatenatedMapping().
template<class Operator > MappingSet ConcatConstMapping< Operator >::mappings protected
Definition at line 1948 of file MappingUtils.h.
Referenced by ConcatConstMapping< Operator >::addMapping(), ConcatConstMapping< Operator >::ConcatConstMapping(), ConcatConstMapping< Operator >::createConcatenatedMapping(), ConcatConstMapping< Operator >::createConstIterator(), and ConcatConstMapping< Operator >::getValue().
template<class Operator > Argument::mapped_type ConcatConstMapping< Operator >::oorValue protected
Definition at line 1952 of file MappingUtils.h.
Referenced by ConcatConstMapping< Operator >::createConcatenatedMapping().
template<class Operator > Operator ConcatConstMapping< Operator >::op protected
Definition at line 1954 of file MappingUtils.h.
Referenced by ConcatConstMapping< Operator >::createConcatenatedMapping(), and ConcatConstMapping< Operator >::getValue().
template<class Operator > ConstMapping* ConcatConstMapping< Operator >::refMapping protected
Definition at line 1949 of file MappingUtils.h.
Referenced by ConcatConstMapping< Operator >::getRefMapping().
The documentation for this class was generated from the following file:
MappingUtils.h