Veins Framework: Decider80211p Class Reference
Decider80211p Class Reference
Based on Decider80211.h from Karl Wessel and modifications by Christopher Saloman.
#include <Decider80211p.h>
Public Types
enum Decider80211ControlKinds { NOTHING = 22100, BITERROR, LAST_DECIDER_80211_CONTROL_KIND, RECWHILESEND }
Public Types inherited from BaseDecider
enum BaseDeciderControlKinds { PACKET_DROPPED = 22100, LAST_BASE_DECIDER_CONTROL_KIND }
The kinds of ControlMessages this Decider sends.
Public Member Functions
Decider80211p (DeciderToPhyInterface *phy, double sensitivity, double centerFrequency, int myIndex=-1, bool collectCollisionStatistics=false, bool debug=false)
Initializes the Decider with a pointer to its PhyLayer and specific values for threshold and sensitivity.
void setPath (std::string myPath)
bool cca (simtime_t_cref, AirFrame *)
int getSignalState (AirFrame *frame)
Returns the SignalState for the passed AirFrame.
virtual ~Decider80211p ()
void changeFrequency (double freq)
void setChannelIdleStatus (bool isIdle)
Changes the "isIdle"-status to the passed value.
virtual void finish ()
invoke this method when the phy layer is also finalized, so that statistics recorded by the decider can be written to the output file
Public Member Functions inherited from BaseDecider
BaseDecider (DeciderToPhyInterface *phy, double sensitivity, int myIndex, bool debug)
Initializes the decider with the passed values.
virtual ~BaseDecider ()
virtual simtime_t processSignal (AirFrame *frame)
Processes an AirFrame given by the PhyLayer.
virtual ChannelState getChannelState ()
A function that returns information about the channel state.
virtual simtime_t handleChannelSenseRequest (ChannelSenseRequest *request)
This function is called by the PhyLayer to hand over a ChannelSenseRequest.
Public Member Functions inherited from Decider
Decider (DeciderToPhyInterface *phy)
Initializes the Decider with a pointer to its PhyLayer.
virtual ~Decider ()
virtual void channelChanged (int newChannel)
Called by phy layer to indicate that the channel this radio currently listens to has changed.
Protected Types
enum PACKET_OK_RESULT { DECODED, NOT_DECODED, COLLISION }
tell the outcome of a packetOk() call, which might be correctly decoded, discarded due to low SNR or discarder due to low SINR (i.e.
Protected Types inherited from BaseDecider
enum SignalState { NEW, EXPECT_HEADER, EXPECT_END }
The current state of processing for a signal.
typedef std::pair< AirFrame
*, int > ReceivedSignal
Pair of a AirFrame and the state it is in.
Protected Types inherited from Decider
typedef
DeciderToPhyInterface::AirFrameVector AirFrameVector
Defines what an AirFrameVector shall be here.
Protected Member Functions
virtual DeciderResult * checkIfSignalOk (AirFrame *frame)
Checks a mapping against a specific threshold (element-wise).
virtual simtime_t processNewSignal (AirFrame *frame)
Processes a new Signal.
virtual simtime_t processSignalEnd (AirFrame *frame)
Processes a received AirFrame.
enum PACKET_OK_RESULT packetOk (double snirMin, double snrMin, int lengthMPDU, double bitrate)
computes if packet is ok or has errors
virtual double calcChannelSenseRSSI (simtime_t_cref min, simtime_t_cref max)
Calculates the RSSI value for the passed ChannelSenseRequest.
virtual void calculateSinrAndSnrMapping (AirFrame *frame, Mapping **sinrMap, Mapping **snrMap)
Calculates a SNR-Mapping for a Signal.
Mapping * calculateNoiseRSSIMapping (simtime_t_cref start, simtime_t_cref end, AirFrame *frame)
Calculates a RSSI-Mapping (or Noise-Strength-Mapping) for a Signal.
Protected Member Functions inherited from BaseDecider
virtual simtime_t processSignalHeader (AirFrame *frame)
Processes the end of the header of a received Signal.
virtual simtime_t processUnknownSignal (AirFrame *frame)
Processes any Signal for which no state could be found.
virtual simtime_t handleNewSenseRequest (ChannelSenseRequest *request)
Handles a new incoming ChannelSenseRequest and returns the next (or latest) time to handle the request again.
virtual void handleSenseRequestEnd (CSRInfo &requestInfo)
Handles the timeout or end of a ChannelSenseRequest by calculating the ChannelState and returning the request to the mac layer.
virtual simtime_t canAnswerCSR (const CSRInfo &requestInfo)
Returns point in time when the ChannelSenseRequest of the passed CSRInfo can be answered (e.g.
virtual void answerCSR (CSRInfo &requestInfo)
Answers the ChannelSenseRequest (CSR) from the passed CSRInfo.
virtual void channelStateChanged ()
Checks if the changed channel state enables us to answer any ongoing ChannelSenseRequests.
virtual void getChannelInfo (simtime_t_cref start, simtime_t_cref end, AirFrameVector &out)
Collects the AirFrame on the channel during the passed interval.
virtual Mapping * calculateSnrMapping (AirFrame *frame)
Calculates a SNR-Mapping for a Signal.
virtual Mapping * calculateRSSIMapping (simtime_t_cref start, simtime_t_cref end, AirFrame *exclude=NULL)
Calculates a RSSI-Mapping (or Noise-Strength-Mapping) for a Signal.
Protected Attributes
double snrThreshold
double centerFrequency
The center frequency on which the decider listens for signals.
double myBusyTime
double myStartTime
AirFrame * curSyncFrame
Frame that the NIC card is currently trying to decode.
std::string myPath
Decider80211pToPhy80211pInterface * phy11p
std::map< AirFrame *, int > signalStates
bool collectCollisionStats
enable/disable statistics collection for collisions
unsigned int collisions
count the number of collisions
Protected Attributes inherited from BaseDecider
double sensitivity
sensitivity value for receiving an AirFrame
ReceivedSignal currentSignal
pointer to the currently received AirFrame
bool isChannelIdle
Stores the idle state of the channel.
CSRInfo currentChannelSenseRequest
pointer to the currently running ChannelSenseRequest and its start-time
int myIndex
index for this Decider-instance given by Phy-Layer (mostly Host-index)
bool debug
toggles display of debugging messages
Protected Attributes inherited from Decider
DeciderToPhyInterface * phy
A pointer to the physical layer of this Decider.
const simtime_t notAgain
simtime that tells the Phy-Layer not to pass an AirFrame again
Detailed Description
Based on Decider80211.h from Karl Wessel and modifications by Christopher Saloman.
Author
David Eckhoff
See Also
BaseWaveApplLayer
Mac1609_4
PhyLayer80211p
Decider80211p
Definition at line 51 of file Decider80211p.h.
Member Enumeration Documentation
enum Decider80211p::Decider80211ControlKinds
Enumerator
NOTHING
BITERROR
LAST_DECIDER_80211_CONTROL_KIND
RECWHILESEND
Definition at line 53 of file Decider80211p.h.
{
                         NOTHING = 22100,
                         BITERROR,       //the phy has recognized a bit error in the packet
                         LAST_DECIDER_80211_CONTROL_KIND,
                         RECWHILESEND
                 };
enum Decider80211p::PACKET_OK_RESULT protected
tell the outcome of a packetOk() call, which might be correctly decoded, discarded due to low SNR or discarder due to low SINR (i.e.
collision)
Enumerator
DECODED
NOT_DECODED
COLLISION
Definition at line 92 of file Decider80211p.h.
 {DECODED, NOT_DECODED, COLLISION};
Constructor & Destructor Documentation
Decider80211p::Decider80211p (DeciderToPhyInterface * phy, double sensitivity, double centerFrequency, int myIndex = -1, bool collectCollisionStatistics = false, bool debug = false) inline
Initializes the Decider with a pointer to its PhyLayer and specific values for threshold and sensitivity.
Definition at line 164 of file Decider80211p.h.
                                                  :
                         BaseDecider(phy, sensitivity, myIndex, debug),
                         centerFrequency(centerFrequency),
                         myBusyTime(0),
                         myStartTime(simTime().dbl()),
                         curSyncFrame(0),
                         collectCollisionStats(collectCollisionStatistics),
                         collisions(0) {
                         phy11p = dynamic_cast<Decider80211pToPhy80211pInterface*>(phy);
                         assert(phy11p);
                 }
Decider80211p::~Decider80211p () virtual
Definition at line 529 of file Decider80211p.cc.
 {}
Member Function Documentation
double Decider80211p::calcChannelSenseRSSI (simtime_t_cref min, simtime_t_cref max) protected virtual
Calculates the RSSI value for the passed ChannelSenseRequest.
This method is called by BaseDecider when it answers a ChannelSenseRequest and can be overridden by sub classing Deciders.
Returns the maximum RSSI value inside the ChannelSenseRequest time interval and the channel the Decider currently listens to.
Reimplemented from BaseDecider.
Definition at line 100 of file Decider80211p.cc.
{
         Mapping* rssiMap = calculateRSSIMapping(start, end);
         Argument min(DimensionSet::timeFreqDomain);
         min.setTime(start);
         min.setArgValue(Dimension::frequency_static(), centerFrequency - 5e6);
         Argument max(DimensionSet::timeFreqDomain);
         max.setTime(end);
         max.setArgValue(Dimension::frequency_static(), centerFrequency + 5e6);
         double rssi = MappingUtils::findMax(*rssiMap, min, max);
         delete rssiMap;
         return rssi;
 }
Mapping * Decider80211p::calculateNoiseRSSIMapping (simtime_t_cref start, simtime_t_cref end, AirFrame * frame) protected
Calculates a RSSI-Mapping (or Noise-Strength-Mapping) for a Signal.
This method is taken from the BaseDecider and changed in order to compute the RSSI mapping taking into account only thermal noise
This method can be used to calculate a RSSI-Mapping in case the parameter exclude is omitted OR to calculate a Noise-Strength-Mapping in case the AirFrame of the received Signal is passed as parameter exclude.
Definition at line 147 of file Decider80211p.cc.
Referenced by calculateSinrAndSnrMapping().
{
         // create an empty mapping
         Mapping* resultMap = MappingUtils::createMapping(Argument::MappedZero, DimensionSet::timeDomain);
         // add thermal noise
         ConstMapping* thermalNoise = phy->getThermalNoise(start, end);
         if (thermalNoise) {
                 // FIXME: workaround needed to make *really* sure that the resultMap is defined for the range of the exclude-frame
                 const ConstMapping* excludePwr = exclude ? exclude->getSignal().getReceivingPower() : 0;
                 if (excludePwr) {
                         Mapping* p1 = resultMap;
                         // p2 = exclude + thermal
                         Mapping* p2 = MappingUtils::add(*excludePwr, *thermalNoise);
                         // p3 = p2 - exclude
                         Mapping* p3 = MappingUtils::subtract(*p2, *excludePwr);
                         // result = result + p3
                         resultMap = MappingUtils::add(*resultMap, *p3);
                         delete p3;
                         delete p2;
                         delete p1;
                 }
                 else {
                         Mapping* p1 = resultMap;
                         resultMap = MappingUtils::add(*resultMap, *thermalNoise);
                         delete p1;
                 }
         }
         return resultMap;
 }
void Decider80211p::calculateSinrAndSnrMapping (AirFrame * frame, Mapping ** sinrMap, Mapping ** snrMap) protected virtual
Calculates a SNR-Mapping for a Signal.
This method works as the calculateSnrMapping of the BaseDecider class, but it return the mapping for both SNR and SINR. This method is used to determine the frame reception probability for both SNR and SINR values. In this way we can determine (still probabilistically) if a frame has been dropped due to low signal power or due to a collision
Definition at line 118 of file Decider80211p.cc.
Referenced by checkIfSignalOk().
{
         /* calculate Noise-Strength-Mapping */
         Signal& signal = frame->getSignal();
         simtime_t start = signal.getReceptionStart();
         simtime_t end   = signal.getReceptionEnd();
         //call BaseDecider function to get Noise plus Interference mapping
         Mapping* noiseInterferenceMap = calculateRSSIMapping(start, end, frame);
         assert(noiseInterferenceMap);
         //call calculateNoiseRSSIMapping() to get Noise only mapping
         Mapping* noiseMap = calculateNoiseRSSIMapping(start, end, frame);
         assert(noiseMap);
         //get power map for frame currently under reception
         ConstMapping* recvPowerMap = signal.getReceivingPower();
         assert(recvPowerMap);
         //TODO: handle noise of zero (must not devide with zero!)
         *sinrMap = MappingUtils::divide( *recvPowerMap, *noiseInterferenceMap, Argument::MappedZero );
         *snrMap = MappingUtils::divide( *recvPowerMap, *noiseMap, Argument::MappedZero );
         delete noiseInterferenceMap;
         noiseInterferenceMap = 0;
         delete noiseMap;
         noiseMap = 0;
 }
bool Decider80211p::cca (simtime_t_cref time, AirFrame * exclude)
Definition at line 370 of file Decider80211p.cc.
Referenced by PhyLayer80211p::handleSelfMessage(), processNewSignal(), and processSignalEnd().
{
         AirFrameVector airFrames;
         // collect all AirFrames that intersect with [start, end]
         getChannelInfo(time, time, airFrames);
         Mapping* resultMap = MappingUtils::createMapping(Argument::MappedZero, DimensionSet::timeDomain);
         // iterate over all AirFrames (except exclude)
         // and sum up their receiving-power-mappings
         for (AirFrameVector::const_iterator it = airFrames.begin(); it != airFrames.end(); ++it) {
                 if (*it == exclude) {
                         continue;
                 }
                 // the vector should not contain pointers to 0
                 assert(*it != 0);
                 // if iterator points to exclude (that includes the default-case 'exclude == 0')
                 // then skip this AirFrame
                 // otherwise get the Signal and its receiving-power-mapping
                 Signal& signal = (*it)->getSignal();
                 // backup pointer to result map
                 // Mapping* resultMapOld = resultMap;
                 // TODO1.1: for testing purposes, for now we don't specify an interval
                 // and add the Signal's receiving-power-mapping to resultMap in [start, end],
                 // the operation Mapping::add returns a pointer to a new Mapping
                 const ConstMapping* const recvPowerMap = signal.getReceivingPower();
                 assert(recvPowerMap);
                 // Mapping* resultMapNew = Mapping::add( *(signal.getReceivingPower()), *resultMap, start, end );
                 Mapping* resultMapNew = MappingUtils::add(*recvPowerMap, *resultMap, Argument::MappedZero);
                 // discard old mapping
                 delete resultMap;
                 resultMap = resultMapNew;
                 resultMapNew = 0;
         }
         //add thermal noise
         ConstMapping* thermalNoise = phy->getThermalNoise(time, time);
         if (thermalNoise) {
                 Mapping* tmp = resultMap;
                 resultMap = MappingUtils::add(*resultMap, *thermalNoise);
                 delete tmp;
         }
         Argument min(DimensionSet::timeFreqDomain);
         min.setTime(time);
         min.setArgValue(Dimension::frequency_static(), centerFrequency - 5e6);
         DBG_D11P << MappingUtils::findMin(*resultMap, min, min) << " > " << sensitivity << " = " << (bool)(MappingUtils::findMin(*resultMap, min, min) > sensitivity) << std::endl;
         bool isChannelIdle = MappingUtils::findMin(*resultMap, min, min) < sensitivity;
         delete resultMap;
         return isChannelIdle;
 }
void Decider80211p::changeFrequency (double freq)
Definition at line 517 of file Decider80211p.cc.
Referenced by PhyLayer80211p::changeListeningFrequency().
{
         centerFrequency = freq;
 }
DeciderResult * Decider80211p::checkIfSignalOk (AirFrame * frame) protected virtual
Checks a mapping against a specific threshold (element-wise).
Returns
true , if every entry of the mapping is above threshold false , otherwise
Definition at line 180 of file Decider80211p.cc.
Referenced by processSignalEnd().
{
         Mapping* sinrMap = 0;
         Mapping *snrMap = 0;
         if (collectCollisionStats) {
                 calculateSinrAndSnrMapping(frame, &sinrMap, &snrMap);
                 assert(snrMap);
         }
         else {
                 sinrMap = calculateSnrMapping(frame);
         }
         assert(sinrMap);
         Signal& s = frame->getSignal();
         simtime_t start = s.getReceptionStart();
         simtime_t end = s.getReceptionEnd();
         start = start + PHY_HDR_PREAMBLE_DURATION; //its ok if something in the training phase is broken
         Argument min(DimensionSet::timeFreqDomain);
         min.setTime(start);
         min.setArgValue(Dimension::frequency_static(), centerFrequency - 5e6);
         Argument max(DimensionSet::timeFreqDomain);
         max.setTime(end);
         max.setArgValue(Dimension::frequency_static(), centerFrequency + 5e6);
         double snirMin = MappingUtils::findMin(*sinrMap, min, max);
         double snrMin;
         if (collectCollisionStats) {
                 snrMin = MappingUtils::findMin(*snrMap, min, max);
         }
         else {
                 //just set to any value. if collectCollisionStats != true
                 //it will be ignored by packetOk
                 snrMin = 1e200;
         }
         ConstMappingIterator* bitrateIt = s.getBitrate()->createConstIterator();
         bitrateIt->next(); //iterate to payload bitrate indicator
         double payloadBitrate = bitrateIt->getValue();
         delete bitrateIt;
         DeciderResult80211* result = 0;
         switch (packetOk(snirMin, snrMin, frame->getBitLength(), payloadBitrate)) {
                 case DECODED:
                         DBG_D11P << "Packet is fine! We can decode it" << std::endl;
                         result = new DeciderResult80211(true, payloadBitrate, snirMin);
                         break;
                 case NOT_DECODED:
                         if (!collectCollisionStats) {
                                 DBG_D11P << "Packet has bit Errors. Lost " << std::endl;
                         }
                         else {
                                 DBG_D11P << "Packet has bit Errors due to low power. Lost " << std::endl;
                         }
                         result = new DeciderResult80211(false, payloadBitrate, snirMin);
                         break;
                 case COLLISION:
                         DBG_D11P << "Packet has bit Errors due to collision. Lost " << std::endl;
                         collisions++;
                         result = new DeciderResult80211(false, payloadBitrate, snirMin);
                         break;
                 default:
                         ASSERT2(false, "Impossible packet result returned by packetOk(). Check the code.");
                         break;
         }
         delete sinrMap;
         if (snrMap)
                 delete snrMap;
         return result;
 }
void Decider80211p::finish () virtual
invoke this method when the phy layer is also finalized, so that statistics recorded by the decider can be written to the output file
Reimplemented from Decider.
Definition at line 521 of file Decider80211p.cc.
{
         simtime_t totalTime = simTime() - myStartTime;
         phy->recordScalar("busyTime", myBusyTime / totalTime.dbl());
         if (collectCollisionStats) {
                 phy->recordScalar("ncollisions", collisions);
         }
 }
int Decider80211p::getSignalState (AirFrame * frame) virtual
Returns the SignalState for the passed AirFrame.
The default implementation checks if the passed AirFrame is the "currentSignal" and returns its state or if not "NEW".
Reimplemented from BaseDecider.
Definition at line 90 of file Decider80211p.cc.
{
         if (signalStates.find(frame) == signalStates.end()) {
                 return NEW;
         }
         else {
                 return signalStates[frame];
         }
 }
enum Decider80211p::PACKET_OK_RESULT Decider80211p::packetOk (double snirMin, double snrMin, int lengthMPDU, double bitrate) protected
computes if packet is ok or has errors
Definition at line 260 of file Decider80211p.cc.
Referenced by checkIfSignalOk().
{
         //the lengthMPDU includes the PHY_SIGNAL_LENGTH + PHY_PSDU_HEADER + Payload, while the first is sent with PHY_HEADER_BANDWIDTH
         double packetOkSinr;
         double packetOkSnr;
         if (bitrate == 18E+6) {
                 //According to P. Fuxjaeger et al. "IEEE 802.11p Transmission Using GNURadio"
                 double ber = std::min(0.5 , 1.5 * erfc(0.45 * sqrt(snirMin)));
                 packetOkSinr = pow(1 - ber, lengthMPDU - PHY_HDR_PLCPSIGNAL_LENGTH);
         }
         else if (bitrate == 6E+6) {
                 //According to K. Sjoeberg et al. "Measuring and Using the RSSI of IEEE 802.11p"
                 double ber = std::min(0.5 , 8 * erfc(0.75 *sqrt(snirMin)));
                 packetOkSinr = pow(1 - ber, lengthMPDU - PHY_HDR_PLCPSIGNAL_LENGTH);
         }
         else {
                 opp_error("Currently this 11p-Model only provides accurate BER models for 6Mbit and 18Mbit. Please use one of these frequencies for now.");
         }
         //check if header is broken, BER model for PSK taken from MiXiM 2.2
         double berHeader = 0.5 * exp(-snirMin * 10E+6 / PHY_HDR_BANDWIDTH);
         double headerNoError = pow(1.0 - berHeader, PHY_HDR_PLCPSIGNAL_LENGTH);
         double headerNoErrorSnr;
         //compute PER also for SNR only
         if (collectCollisionStats) {
                 if (bitrate == 18E+6) {
                         //According to P. Fuxjaeger et al. "IEEE 802.11p Transmission Using GNURadio"
                         double ber = std::min(0.5, 1.5 * erfc(0.45 * sqrt(snrMin)));
                         packetOkSnr = pow(1 - ber, lengthMPDU - PHY_HDR_PLCPSIGNAL_LENGTH);
                 }
                 else if (bitrate == 6E+6) {
                         //According to K. Sjoeberg et al. "Measuring and Using the RSSI of IEEE 802.11p"
                         double ber = std::min(0.5, 8 * erfc(0.75 * sqrt(snrMin)));
                         packetOkSnr = pow(1 - ber, lengthMPDU - PHY_HDR_PLCPSIGNAL_LENGTH);
                 }
                 double berHeader = 0.5 * exp(-snrMin * 10E+6 / PHY_HDR_BANDWIDTH);
                 headerNoErrorSnr = pow(1.0 - berHeader, PHY_HDR_PLCPSIGNAL_LENGTH);
                 //the probability of correct reception without considering the interference
                 //MUST be greater or equal than when consider it
                 assert(packetOkSnr >= packetOkSinr);
                 assert(headerNoErrorSnr >= headerNoError);
         }
         //probability of no bit error in the PLCP header
         double rand = dblrand();
         if (!collectCollisionStats) {
                 if (rand > headerNoError)
                         return NOT_DECODED;
         }
         else {
                 if (rand > headerNoError) {
                         //ups, we have a header error. is that due to interference?
                         if (rand > headerNoErrorSnr) {
                                 //no. we would have not been able to receive that even
                                 //without interference
                                 return NOT_DECODED;
                         }
                         else {
                                 //yes. we would have decoded that without interference
                                 return COLLISION;
                         }
                 }
         }
         //probability of no bit error in the rest of the packet
         rand = dblrand();
         if (!collectCollisionStats) {
                 if (rand > packetOkSinr) {
                         return NOT_DECODED;
                 }
                 else {
                         return DECODED;
                 }
         }
         else {
                 if (rand > packetOkSinr) {
                         //ups, we have an error in the payload. is that due to interference?
                         if (rand > packetOkSnr) {
                                 //no. we would have not been able to receive that even
                                 //without interference
                                 return NOT_DECODED;
                         }
                         else {
                                 //yes. we would have decoded that without interference
                                 return COLLISION;
                         }
                 }
                 else {
                         return DECODED;
                 }
         }
 }
simtime_t Decider80211p::processNewSignal (AirFrame * frame) protected virtual
Processes a new Signal.
Returns the time it wants to handle the signal again.
Default implementation checks if the signals receiving power is above the sensitivity of the radio and we are not already trying to receive another AirFrame. If thats the case it waits for the end of the signal.
Reimplemented from BaseDecider.
Definition at line 36 of file Decider80211p.cc.
{
         AirFrame11p *frame = check_and_cast<AirFrame11p *>(msg);
         // get the receiving power of the Signal at start-time and center frequency
         Signal& signal = frame->getSignal();
         Argument start(DimensionSet::timeFreqDomain);
         start.setTime(signal.getReceptionStart());
         start.setArgValue(Dimension::frequency_static(), centerFrequency);
         signalStates[frame] = EXPECT_END;
         double recvPower = signal.getReceivingPower()->getValue(start);
         if (recvPower < sensitivity) {
                 //annotate the frame, so that we won't try decoding it at its end
                 frame->setUnderSensitivity(true);
                 //check channel busy status. a superposition of low power frames might turn channel status to busy
                 if (cca(simTime(), NULL) == false) {
                         setChannelIdleStatus(false);
                 }
                 return signal.getReceptionEnd();
         }
         else {
                 setChannelIdleStatus(false);
                 if (phy11p->getRadioState() == Radio::TX) {
                         frame->setBitError(true);
                         frame->setWasTransmitting(true);
                         DBG_D11P << "AirFrame: " << frame->getId() << " (" << recvPower << ") received, while already sending. Setting BitErrors to true" << std::endl;
                 }
                 else {
                         if (!curSyncFrame) {
                                 //NIC is not yet synced to any frame, so lock and try to decode this frame
                                 curSyncFrame = frame;
                                 DBG_D11P << "AirFrame: " << frame->getId() << " with (" << recvPower << " > " << sensitivity << ") -> Trying to receive AirFrame." << std::endl;
                         }
                         else {
                                 //NIC is currently trying to decode another frame. this frame will be simply treated as interference
                                 DBG_D11P << "AirFrame: " << frame->getId() << " with (" << recvPower << " > " << sensitivity << ") -> Already synced to another AirFrame. Treating AirFrame as interference." << std::endl;
                         }
                         //channel turned busy
                         //measure communication density
                         myBusyTime += signal.getDuration().dbl();
                 }
                 return signal.getReceptionEnd();
         }
 }
simtime_t Decider80211p::processSignalEnd (AirFrame * frame) protected virtual
Processes a received AirFrame.
The SNR-mapping for the Signal is created and checked against the Deciders SNR-threshold. Depending on that the received AirFrame is either sent up to the MAC-Layer or dropped.
Returns
usually return a value for: 'do not pass it again'
Reimplemented from BaseDecider.
Definition at line 433 of file Decider80211p.cc.
{
         AirFrame11p *frame = check_and_cast<AirFrame11p *>(msg);
         // here the Signal is finally processed
         bool whileSending = false;
         //remove this frame from our current signals
         signalStates.erase(frame);
         DeciderResult* result;
         if (frame->getUnderSensitivity()) {
                 //this frame was not even detected by the radio card
                 result = new DeciderResult80211(false,0,0);
         }
         else if (frame->getWasTransmitting() || phy11p->getRadioState() == Radio::TX) {
                 //this frame was received while sending
                 whileSending = true;
                 result = new DeciderResult80211(false,0,0);
         }
         else {
                 //first check whether this is the frame NIC is currently synced on
                 if (frame == curSyncFrame) {
                         // check if the snrMapping is above the Decider's specific threshold,
                         // i.e. the Decider has received it correctly
                         result = checkIfSignalOk(frame);
                         //after having tried to decode the frame, the NIC is no more synced to the frame
                         //and it is ready for syncing on a new one
                         curSyncFrame = 0;
                 }
                 else {
                         //if this is not the frame we are synced on, we cannot receive it
                         result = new DeciderResult80211(false, 0, 0);
                 }
         }
         if (result->isSignalCorrect()) {
                 DBG_D11P << "packet was received correctly, it is now handed to upper layer...\n";
                 // go on with processing this AirFrame, send it to the Mac-Layer
                 phy->sendUp(frame, result);
         }
         else {
                 if (frame->getUnderSensitivity()) {
                         DBG_D11P << "packet was not detected by the card. power was under sensitivity threshold\n";
                 }
                 else if (whileSending) {
                         DBG_D11P << "packet was received while sending, sending it as control message to upper layer\n";
                         phy->sendControlMsgToMac(new cMessage("Error",RECWHILESEND));
                 }
                 else {
                         DBG_D11P << "packet was not received correctly, sending it as control message to upper layer\n";
                         phy->sendControlMsgToMac(new cMessage("Error",BITERROR));
                 }
                 delete result;
         }
         if (phy11p->getRadioState() == Radio::TX) {
                 DBG_D11P << "I'm currently sending\n";
         }
         //check if channel is idle now
         else if (cca(simTime(), frame) == false) {
                 DBG_D11P << "Channel not yet idle!\n";
         }
         else {
                 //might have been idle before (when the packet rxpower was below sens)
                 if (isChannelIdle != true) {
                         DBG_D11P << "Channel idle now!\n";
                         setChannelIdleStatus(true);
                 }
         }
         return notAgain;
 }
void Decider80211p::setChannelIdleStatus (bool isIdle) virtual
Changes the "isIdle"-status to the passed value.
This method further checks if there are any ChannelSenseRequests which can be answered because of the idle state changed.
Reimplemented from BaseDecider.
Definition at line 510 of file Decider80211p.cc.
Referenced by PhyLayer80211p::handleSelfMessage(), processNewSignal(), and processSignalEnd().
{
         isChannelIdle = isIdle;
         channelStateChanged();
         if (isIdle) phy->sendControlMsgToMac(new cMessage("ChannelStatus",Mac80211pToPhy11pInterface::CHANNEL_IDLE));
         else phy->sendControlMsgToMac(new cMessage("ChannelStatus",Mac80211pToPhy11pInterface::CHANNEL_BUSY));
 }
void Decider80211p::setPath (std::string myPath) inline
Definition at line 182 of file Decider80211p.h.
Referenced by PhyLayer80211p::initializeDecider80211p().
{
                         this->myPath = myPath;
                 }
Member Data Documentation
double Decider80211p::centerFrequency protected
The center frequency on which the decider listens for signals.
Definition at line 64 of file Decider80211p.h.
Referenced by calcChannelSenseRSSI(), cca(), changeFrequency(), checkIfSignalOk(), and processNewSignal().
bool Decider80211p::collectCollisionStats protected
enable/disable statistics collection for collisions
For collecting statistics about collisions, we compute the Packet Error Rate for both SNR and SINR values. This might increase the simulation time, so if statistics about collisions are not needed, this variable should be set to false
Definition at line 83 of file Decider80211p.h.
Referenced by checkIfSignalOk(), finish(), and packetOk().
unsigned int Decider80211p::collisions protected
count the number of collisions
Definition at line 85 of file Decider80211p.h.
Referenced by checkIfSignalOk(), and finish().
AirFrame* Decider80211p::curSyncFrame protected
Frame that the NIC card is currently trying to decode.
Definition at line 70 of file Decider80211p.h.
Referenced by processNewSignal(), and processSignalEnd().
double Decider80211p::myBusyTime protected
Definition at line 66 of file Decider80211p.h.
Referenced by finish(), and processNewSignal().
std::string Decider80211p::myPath protected
Definition at line 72 of file Decider80211p.h.
Referenced by setPath().
double Decider80211p::myStartTime protected
Definition at line 67 of file Decider80211p.h.
Referenced by finish().
Decider80211pToPhy80211pInterface* Decider80211p::phy11p protected
Definition at line 73 of file Decider80211p.h.
Referenced by Decider80211p(), processNewSignal(), and processSignalEnd().
std::map<AirFrame*,int> Decider80211p::signalStates protected
Definition at line 74 of file Decider80211p.h.
Referenced by getSignalState(), processNewSignal(), and processSignalEnd().
double Decider80211p::snrThreshold protected
Definition at line 61 of file Decider80211p.h.
The documentation for this class was generated from the following files:
Decider80211p.h
Decider80211p.cc