Veins Framework: Veins::TraCIScenarioManager Class Reference
Veins::TraCIScenarioManager Class Reference
#include <TraCIScenarioManager.h>
Public Types
enum VehicleSignal {
VEH_SIGNAL_UNDEF = -1, VEH_SIGNAL_NONE = 0, VEH_SIGNAL_BLINKER_RIGHT = 1, VEH_SIGNAL_BLINKER_LEFT = 2,
VEH_SIGNAL_BLINKER_EMERGENCY = 4, VEH_SIGNAL_BRAKELIGHT = 8, VEH_SIGNAL_FRONTLIGHT = 16, VEH_SIGNAL_FOGLIGHT = 32,
VEH_SIGNAL_HIGHBEAM = 64, VEH_SIGNAL_BACKDRIVE = 128, VEH_SIGNAL_WIPER = 256, VEH_SIGNAL_DOOR_OPEN_LEFT = 512,
VEH_SIGNAL_DOOR_OPEN_RIGHT = 1024, VEH_SIGNAL_EMERGENCY_BLUE = 2048, VEH_SIGNAL_EMERGENCY_RED = 4096, VEH_SIGNAL_EMERGENCY_YELLOW = 8192
}
Public Member Functions
TraCIScenarioManager ()
~TraCIScenarioManager ()
virtual int numInitStages () const
virtual void initialize (int stage)
virtual void finish ()
virtual void handleMessage (cMessage *msg)
virtual void handleSelfMsg (cMessage *msg)
bool isConnected () const
TraCICommandInterface * getCommandInterface () const
bool getAutoShutdownTriggered ()
const std::map< std::string,
cModule * > & getManagedHosts ()
Coord traci2omnet (TraCICoord coord) const
convert TraCI coordinates to OMNeT++ coordinates
std::list< Coord > traci2omnet (const std::list< TraCICoord > &) const
TraCICoord omnet2traci (Coord coord) const
convert OMNeT++ coordinates to TraCI coordinates
std::list< TraCICoord > omnet2traci (const std::list< Coord > &) const
Protected Member Functions
uint32_t getCurrentTimeMs ()
get current simulation time (in ms)
void executeOneTimestep ()
read and execute all commands for the next timestep
virtual void init_traci ()
void addModule (std::string nodeId, std::string type, std::string name, std::string displayString, const Coord &position, std::string road_id="", double speed=-1, double angle=-1)
cModule * getManagedModule (std::string nodeId)
returns a pointer to the managed module named moduleName, or 0 if no module can be found
void deleteModule (std::string nodeId)
bool isModuleUnequipped (std::string nodeId)
returns true if this vehicle is Unequipped
bool isInRegionOfInterest (const TraCICoord &position, std::string road_id, double speed, double angle)
returns whether a given position lies within the simulation's region of interest.
double traci2omnetAngle (double angle) const
convert TraCI angle to OMNeT++ angle (in rad)
double omnet2traciAngle (double angle) const
convert OMNeT++ angle (in rad) to TraCI angle
void insertNewVehicle ()
adds a new vehicle to the queue which are tried to be inserted at the next SUMO time step;
void insertVehicles ()
tries to add all vehicles in the vehicle queue to SUMO;
void subscribeToVehicleVariables (std::string vehicleId)
void unsubscribeFromVehicleVariables (std::string vehicleId)
void processSimSubscription (std::string objectId, TraCIBuffer &buf)
void processVehicleSubscription (std::string objectId, TraCIBuffer &buf)
void processSubcriptionResult (TraCIBuffer &buf)
Protected Attributes
bool debug
whether to emit debug messages
simtime_t connectAt
when to connect to TraCI server (must be the initial timestep of the server)
simtime_t firstStepAt
when to start synchronizing with the TraCI server (-1: immediately after connecting)
simtime_t updateInterval
time interval of hosts' position updates
std::string moduleType
module type to be used in the simulation for each managed vehicle
std::string moduleName
module name to be used in the simulation for each managed vehicle
std::string moduleDisplayString
module displayString to be used in the simulation for each managed vehicle
std::string host
int port
uint32_t vehicleNameCounter
cMessage * myAddVehicleTimer
std::vector< std::string > vehicleTypeIds
std::map< int, std::queue
< std::string > > vehicleInsertQueue
std::set< std::string > queuedVehicles
std::vector< std::string > routeIds
int vehicleRngIndex
int numVehicles
cRNG * mobRng
bool autoShutdown
Shutdown module as soon as no more vehicles are in the simulation.
int margin
double penetrationRate
std::list< std::string > roiRoads
which roads (e.g.
std::list< std::pair
< TraCICoord, TraCICoord > > roiRects
which rectangles (e.g.
TraCIConnection * connection
TraCICommandInterface * commandIfc
TraCICoord netbounds1
TraCICoord netbounds2
size_t nextNodeVectorIndex
next OMNeT++ module vector index to use
std::map< std::string, cModule * > hosts
vector of all hosts managed by us
std::set< std::string > unEquippedHosts
std::set< std::string > subscribedVehicles
all vehicles we have already subscribed to
uint32_t activeVehicleCount
number of vehicles, be it parking or driving
uint32_t parkingVehicleCount
number of parking vehicles, derived from parking start/end events
uint32_t drivingVehicleCount
number of driving, as reported by sumo
bool autoShutdownTriggered
cMessage * connectAndStartTrigger
self-message scheduled for when to connect to TraCI server and start running
cMessage * executeOneTimestepTrigger
self-message scheduled for when to next call executeOneTimestep
BaseWorldUtility * world
BaseConnectionManager * cc
Detailed Description
Definition at line 61 of file TraCIScenarioManager.h.
Member Enumeration Documentation
enum Veins::TraCIScenarioManager::VehicleSignal
Enumerator
VEH_SIGNAL_UNDEF
VEH_SIGNAL_NONE
VEH_SIGNAL_BLINKER_RIGHT
VEH_SIGNAL_BLINKER_LEFT
VEH_SIGNAL_BLINKER_EMERGENCY
VEH_SIGNAL_BRAKELIGHT
VEH_SIGNAL_FRONTLIGHT
VEH_SIGNAL_FOGLIGHT
VEH_SIGNAL_HIGHBEAM
VEH_SIGNAL_BACKDRIVE
VEH_SIGNAL_WIPER
VEH_SIGNAL_DOOR_OPEN_LEFT
VEH_SIGNAL_DOOR_OPEN_RIGHT
VEH_SIGNAL_EMERGENCY_BLUE
VEH_SIGNAL_EMERGENCY_RED
VEH_SIGNAL_EMERGENCY_YELLOW
Definition at line 65 of file TraCIScenarioManager.h.
{
                         VEH_SIGNAL_UNDEF = -1,
                         VEH_SIGNAL_NONE = 0,
                         VEH_SIGNAL_BLINKER_RIGHT = 1,
                         VEH_SIGNAL_BLINKER_LEFT = 2,
                         VEH_SIGNAL_BLINKER_EMERGENCY = 4,
                         VEH_SIGNAL_BRAKELIGHT = 8,
                         VEH_SIGNAL_FRONTLIGHT = 16,
                         VEH_SIGNAL_FOGLIGHT = 32,
                         VEH_SIGNAL_HIGHBEAM = 64,
                         VEH_SIGNAL_BACKDRIVE = 128,
                         VEH_SIGNAL_WIPER = 256,
                         VEH_SIGNAL_DOOR_OPEN_LEFT = 512,
                         VEH_SIGNAL_DOOR_OPEN_RIGHT = 1024,
                         VEH_SIGNAL_EMERGENCY_BLUE = 2048,
                         VEH_SIGNAL_EMERGENCY_RED = 4096,
                         VEH_SIGNAL_EMERGENCY_YELLOW = 8192
                 };
Constructor & Destructor Documentation
TraCIScenarioManager::TraCIScenarioManager ()
Definition at line 53 of file TraCIScenarioManager.cc.
                                            :
                 myAddVehicleTimer(0),
                 mobRng(0),
                 connection(0),
                 connectAndStartTrigger(0),
                 executeOneTimestepTrigger(0),
                 world(0),
                 cc(0)
 {
 }
TraCIScenarioManager::~TraCIScenarioManager ()
Definition at line 64 of file TraCIScenarioManager.cc.
{
         cancelAndDelete(connectAndStartTrigger);
         cancelAndDelete(executeOneTimestepTrigger);
         cancelAndDelete(myAddVehicleTimer);
         delete commandIfc;
         delete connection;
 }
Member Function Documentation
void TraCIScenarioManager::addModule (std::string nodeId, std::string type, std::string name, std::string displayString, const Coord & position, std::string road_id = "", double speed = -1, double angle = -1) protected
Definition at line 297 of file TraCIScenarioManager.cc.
Referenced by processVehicleSubscription().
{
         if (hosts.find(nodeId) != hosts.end()) error("tried adding duplicate module");
         if (queuedVehicles.find(nodeId) != queuedVehicles.end()) {
             queuedVehicles.erase(nodeId);
         }
         double option1 = hosts.size() / (hosts.size() + unEquippedHosts.size() + 1.0);
         double option2 = (hosts.size() + 1) / (hosts.size() + unEquippedHosts.size() + 1.0);
         if (fabs(option1 - penetrationRate) < fabs(option2 - penetrationRate)) {
                 unEquippedHosts.insert(nodeId);
                 return;
         }
         int32_t nodeVectorIndex = nextNodeVectorIndex++;
         cModule* parentmod = getParentModule();
         if (!parentmod) error("Parent Module not found");
         cModuleType* nodeType = cModuleType::get(type.c_str());
         if (!nodeType) error("Module Type \"%s\" not found", type.c_str());
         //TODO: this trashes the vectsize member of the cModule, although nobody seems to use it
         cModule* mod = nodeType->create(name.c_str(), parentmod, nodeVectorIndex, nodeVectorIndex);
         mod->finalizeParameters();
         mod->getDisplayString().parse(displayString.c_str());
         mod->buildInside();
         mod->scheduleStart(simTime() + updateInterval);
         // pre-initialize TraCIMobility
         for (cModule::SubmoduleIterator iter(mod); !iter.end(); iter++) {
                 cModule* submod = iter();
                 ifInetTraCIMobilityCallPreInitialize(submod, nodeId, position, road_id, speed, angle);
                 TraCIMobility* mm = dynamic_cast<TraCIMobility*>(submod);
                 if (!mm) continue;
                 mm->preInitialize(nodeId, position, road_id, speed, angle);
         }
         mod->callInitialize();
         hosts[nodeId] = mod;
         // post-initialize TraCIMobility
         for (cModule::SubmoduleIterator iter(mod); !iter.end(); iter++) {
                 cModule* submod = iter();
                 TraCIMobility* mm = dynamic_cast<TraCIMobility*>(submod);
                 if (!mm) continue;
                 mm->changePosition();
         }
 }
void TraCIScenarioManager::deleteModule (std::string nodeId) protected
Definition at line 358 of file TraCIScenarioManager.cc.
Referenced by finish(), processSimSubscription(), and processVehicleSubscription().
{
         cModule* mod = getManagedModule(nodeId);
         if (!mod) error("no vehicle with Id \"%s\" found", nodeId.c_str());
         cc->unregisterNic(mod->getSubmodule("nic"));
         hosts.erase(nodeId);
         mod->callFinish();
         mod->deleteModule();
 }
void TraCIScenarioManager::executeOneTimestep () protected
read and execute all commands for the next timestep
Definition at line 388 of file TraCIScenarioManager.cc.
Referenced by handleSelfMsg().
{
         MYDEBUG << "Triggering TraCI server simulation advance to t=" << simTime() <<endl;
         uint32_t targetTime = getCurrentTimeMs();
         if (targetTime > round(connectAt.dbl() * 1000)) {
                 insertVehicles();
                 TraCIBuffer buf = connection->query(CMD_SIMSTEP2, TraCIBuffer() << targetTime);
                 uint32_t count; buf >> count;
                 MYDEBUG << "Getting " << count << " subscription results" << endl;
                 for (uint32_t i = 0; i < count; ++i) {
                         processSubcriptionResult(buf);
                 }
         }
         if (!autoShutdownTriggered) scheduleAt(simTime()+updateInterval, executeOneTimestepTrigger);
 }
void TraCIScenarioManager::finish () virtual
Reimplemented in Veins::TraCIScenarioManagerLaunchd.
Definition at line 235 of file TraCIScenarioManager.cc.
Referenced by Veins::TraCIScenarioManagerLaunchd::finish().
{
         if (connection) {
                 TraCIBuffer buf = connection->query(CMD_CLOSE, TraCIBuffer());
         }
         while (hosts.begin() != hosts.end()) {
                 deleteModule(hosts.begin()->first);
         }
 }
bool Veins::TraCIScenarioManager::getAutoShutdownTriggered () inline
Definition at line 96 of file TraCIScenarioManager.h.
{
                         return autoShutdownTriggered;
                 }
TraCICommandInterface* Veins::TraCIScenarioManager::getCommandInterface () const inline
Definition at line 94 of file TraCIScenarioManager.h.
Referenced by Veins::TraCIMobility::getCommandInterface(), handleSelfMsg(), Veins::AnnotationManager::hide(), Veins::TraCIScenarioManagerLaunchd::init_traci(), init_traci(), insertVehicles(), and Veins::AnnotationManager::show().
 { return commandIfc; }
uint32_t TraCIScenarioManager::getCurrentTimeMs () protected
get current simulation time (in ms)
Definition at line 384 of file TraCIScenarioManager.cc.
Referenced by executeOneTimestep(), and processSimSubscription().
{
         return static_cast<uint32_t>(round(simTime().dbl() * 1000));
 }
const std::map<std::string, cModule*>& Veins::TraCIScenarioManager::getManagedHosts () inline
Definition at line 100 of file TraCIScenarioManager.h.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), Veins::mfcv_epidemic_app::handlePositionUpdate(), and Veins::epidemic_app::handlePositionUpdate().
{
                         return hosts;
                 }
cModule * TraCIScenarioManager::getManagedModule (std::string nodeId) protected
returns a pointer to the managed module named moduleName, or 0 if no module can be found
Definition at line 348 of file TraCIScenarioManager.cc.
Referenced by deleteModule(), processSimSubscription(), and processVehicleSubscription().
{
         if (hosts.find(nodeId) == hosts.end()) return 0;
         return hosts[nodeId];
 }
void TraCIScenarioManager::handleMessage (cMessage * msg) virtual
Definition at line 244 of file TraCIScenarioManager.cc.
{
         if (msg->isSelfMessage()) {
                 handleSelfMsg(msg);
                 return;
         }
         error("TraCIScenarioManager doesn't handle messages from other modules");
 }
void TraCIScenarioManager::handleSelfMsg (cMessage * msg) virtual
Definition at line 252 of file TraCIScenarioManager.cc.
Referenced by handleMessage().
{
         if (msg == connectAndStartTrigger) {
                 connection = TraCIConnection::connect(host.c_str(), port);
                 commandIfc = new TraCICommandInterface(*connection);
                 init_traci();
                 return;
         }
         if (msg == executeOneTimestepTrigger) {
                 if (simTime() > 1) {
                         if (vehicleTypeIds.size()==0) {
                                 std::list<std::string> vehTypes = getCommandInterface()->getVehicleTypeIds();
                                 for (std::list<std::string>::const_iterator i = vehTypes.begin(); i != vehTypes.end(); ++i) {
                                         if (i->compare("DEFAULT_VEHTYPE")!=0) {
                                                 MYDEBUG  << *i << std::endl;
                                                 vehicleTypeIds.push_back(*i);
                                         }
                                 }
                         }
                         if (routeIds.size()==0) {
                                 std::list<std::string> routes = getCommandInterface()->getRouteIds();
                                 for (std::list<std::string>::const_iterator i = routes.begin(); i != routes.end(); ++i) {
                                         std::string routeId = *i;
                                         if (par("useRouteDistributions").boolValue() == true) {
                                                 if (std::count(routeId.begin(), routeId.end(), '#') >= 1) {
                                                         MYDEBUG << "Omitting route " << routeId << " as it seems to be a member of a route distribution (found '#' in name)" << std::endl;
                                                         continue;
                                                 }
                                         }
                                         MYDEBUG << "Adding " << routeId << " to list of possible routes" << std::endl;
                                         routeIds.push_back(routeId);
                                 }
                         }
                         for (int i = activeVehicleCount + queuedVehicles.size(); i< numVehicles; i++) {
                                 insertNewVehicle();
                         }
                 }
                 executeOneTimestep();
                 return;
         }
         error("TraCIScenarioManager received unknown self-message");
 }
void TraCIScenarioManager::init_traci () protected virtual
Reimplemented in Veins::TraCIScenarioManagerLaunchd.
Definition at line 149 of file TraCIScenarioManager.cc.
Referenced by handleSelfMsg(), and Veins::TraCIScenarioManagerLaunchd::init_traci().
{
         {
                 std::pair<uint32_t, std::string> version = getCommandInterface()->getVersion();
                 uint32_t apiVersion = version.first;
                 std::string serverVersion = version.second;
                 if ((apiVersion == 8)) {
                         MYDEBUG << "TraCI server \"" << serverVersion << "\" reports API version " << apiVersion << endl;
                 }
                 else {
                         error("TraCI server \"%s\" reports API version %d, which is unsupported. We recommend using SUMO 0.21.0.", serverVersion.c_str(), apiVersion);
                 }
         }
         {
                 // query road network boundaries
                 TraCIBuffer buf = connection->query(CMD_GET_SIM_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(VAR_NET_BOUNDING_BOX) << std::string("sim0"));
                 uint8_t cmdLength_resp; buf >> cmdLength_resp;
                 uint8_t commandId_resp; buf >> commandId_resp; ASSERT(commandId_resp == RESPONSE_GET_SIM_VARIABLE);
                 uint8_t variableId_resp; buf >> variableId_resp; ASSERT(variableId_resp == VAR_NET_BOUNDING_BOX);
                 std::string simId; buf >> simId;
                 uint8_t typeId_resp; buf >> typeId_resp; ASSERT(typeId_resp == TYPE_BOUNDINGBOX);
                 double x1; buf >> x1;
                 double y1; buf >> y1;
                 double x2; buf >> x2;
                 double y2; buf >> y2;
                 ASSERT(buf.eof());
                 netbounds1 = TraCICoord(x1, y1);
                 netbounds2 = TraCICoord(x2, y2);
                 MYDEBUG << "TraCI reports network boundaries (" << x1 << ", " << y1 << ")-(" << x2 << ", " << y2 << ")" << endl;
                 if ((traci2omnet(netbounds2).x > world->getPgs()->x) || (traci2omnet(netbounds1).y > world->getPgs()->y)) MYDEBUG << "WARNING: Playground size (" << world->getPgs()->x << ", " << world->getPgs()->y << ") might be too small for vehicle at network bounds (" << traci2omnet(netbounds2).x << ", " << traci2omnet(netbounds1).y << ")" << endl;
         }
         {
                 // subscribe to list of departed and arrived vehicles, as well as simulation time
                 uint32_t beginTime = 0;
                 uint32_t endTime = 0x7FFFFFFF;
                 std::string objectId = "";
                 uint8_t variableNumber = 7;
                 uint8_t variable1 = VAR_DEPARTED_VEHICLES_IDS;
                 uint8_t variable2 = VAR_ARRIVED_VEHICLES_IDS;
                 uint8_t variable3 = VAR_TIME_STEP;
                 uint8_t variable4 = VAR_TELEPORT_STARTING_VEHICLES_IDS;
                 uint8_t variable5 = VAR_TELEPORT_ENDING_VEHICLES_IDS;
                 uint8_t variable6 = VAR_PARKING_STARTING_VEHICLES_IDS;
                 uint8_t variable7 = VAR_PARKING_ENDING_VEHICLES_IDS;
                 TraCIBuffer buf = connection->query(CMD_SUBSCRIBE_SIM_VARIABLE, TraCIBuffer() << beginTime << endTime << objectId << variableNumber << variable1 << variable2 << variable3 << variable4 << variable5 << variable6 << variable7);
                 processSubcriptionResult(buf);
                 ASSERT(buf.eof());
         }
         {
                 // subscribe to list of vehicle ids
                 uint32_t beginTime = 0;
                 uint32_t endTime = 0x7FFFFFFF;
                 std::string objectId = "";
                 uint8_t variableNumber = 1;
                 uint8_t variable1 = ID_LIST;
                 TraCIBuffer buf = connection->query(CMD_SUBSCRIBE_VEHICLE_VARIABLE, TraCIBuffer() << beginTime << endTime << objectId << variableNumber << variable1);
                 processSubcriptionResult(buf);
                 ASSERT(buf.eof());
         }
         ObstacleControl* obstacles = ObstacleControlAccess().getIfExists();
         if (obstacles) {
                 {
                         // get list of polygons
                         std::list<std::string> ids = getCommandInterface()->getPolygonIds();
                         for (std::list<std::string>::iterator i = ids.begin(); i != ids.end(); ++i) {
                                 std::string id = *i;
                                 std::string typeId = getCommandInterface()->getPolygonTypeId(id);
                                 if (typeId == "building") {
                                         std::list<TraCICoord> coords = getCommandInterface()->getPolygonShape(id);
                                         Obstacle obs(id, 9, .4); // each building gets attenuation of 9 dB per wall, 0.4 dB per meter
                                         std::vector<Coord> shape;
                                         std::transform(coords.begin(), coords.end(), std::back_inserter(shape), traci2omnet_functor(*this));
                                         obs.setShape(shape);
                                         obstacles->add(obs);
                                 }
                         }
                 }
         }
 }
void TraCIScenarioManager::initialize (int stage) virtual
Reimplemented in Veins::TraCIScenarioManagerLaunchd.
Definition at line 72 of file TraCIScenarioManager.cc.
Referenced by Veins::TraCIScenarioManagerLaunchd::initialize().
{
         cSimpleModule::initialize(stage);
         if (stage != 1) {
                 return;
         }
         debug = par("debug");
         connectAt = par("connectAt");
         firstStepAt = par("firstStepAt");
         updateInterval = par("updateInterval");
         if (firstStepAt == -1) firstStepAt = connectAt + updateInterval;
         moduleType = par("moduleType").stdstringValue();
         moduleName = par("moduleName").stdstringValue();
         moduleDisplayString = par("moduleDisplayString").stdstringValue();
         penetrationRate = par("penetrationRate").doubleValue();
         host = par("host").stdstringValue();
         port = par("port");
         autoShutdown = par("autoShutdown");
         margin = par("margin");
         std::string roiRoads_s = par("roiRoads");
         std::string roiRects_s = par("roiRects");
         vehicleNameCounter = 0;
         vehicleRngIndex = par("vehicleRngIndex");
         numVehicles = par("numVehicles").longValue();
         mobRng = getRNG(vehicleRngIndex);
         myAddVehicleTimer = new cMessage("myAddVehicleTimer");
         // parse roiRoads
         roiRoads.clear();
         std::istringstream roiRoads_i(roiRoads_s);
         std::string road;
         while (std::getline(roiRoads_i, road, ' ')) {
                 roiRoads.push_back(road);
         }
         // parse roiRects
         roiRects.clear();
         std::istringstream roiRects_i(roiRects_s);
         std::string rect;
         while (std::getline(roiRects_i, rect, ' ')) {
                 std::istringstream rect_i(rect);
                 double x1; rect_i >> x1; ASSERT(rect_i);
                 char c1; rect_i >> c1; ASSERT(rect_i);
                 double y1; rect_i >> y1; ASSERT(rect_i);
                 char c2; rect_i >> c2; ASSERT(rect_i);
                 double x2; rect_i >> x2; ASSERT(rect_i);
                 char c3; rect_i >> c3; ASSERT(rect_i);
                 double y2; rect_i >> y2; ASSERT(rect_i);
                 roiRects.push_back(std::pair<TraCICoord, TraCICoord>(TraCICoord(x1, y1), TraCICoord(x2, y2)));
         }
         nextNodeVectorIndex = 0;
         hosts.clear();
         subscribedVehicles.clear();
         activeVehicleCount = 0;
         parkingVehicleCount = 0;
         drivingVehicleCount = 0;
         autoShutdownTriggered = false;
         world = FindModule<BaseWorldUtility*>::findGlobalModule();
         if (world == NULL) error("Could not find BaseWorldUtility module");
         cc = FindModule<BaseConnectionManager*>::findGlobalModule();
         if (cc == NULL) error("Could not find BaseConnectionManager module");
         ASSERT(firstStepAt > connectAt);
         connectAndStartTrigger = new cMessage("connect");
         scheduleAt(connectAt, connectAndStartTrigger);
         executeOneTimestepTrigger = new cMessage("step");
         scheduleAt(firstStepAt, executeOneTimestepTrigger);
         MYDEBUG << "initialized TraCIScenarioManager" << endl;
 }
void TraCIScenarioManager::insertNewVehicle () protected
adds a new vehicle to the queue which are tried to be inserted at the next SUMO time step;
Definition at line 409 of file TraCIScenarioManager.cc.
Referenced by handleSelfMsg().
{
         int vehTypeId = mobRng->intRand(vehicleTypeIds.size());
         std::string type = vehicleTypeIds[vehTypeId];
         int routeId = mobRng->intRand(routeIds.size());
         vehicleInsertQueue[routeId].push(type);
 }
void TraCIScenarioManager::insertVehicles () protected
tries to add all vehicles in the vehicle queue to SUMO;
Definition at line 416 of file TraCIScenarioManager.cc.
Referenced by executeOneTimestep().
{
         for (std::map<int, std::queue<std::string> >::iterator i = vehicleInsertQueue.begin(); i != vehicleInsertQueue.end(); ) {
                 std::string route = routeIds[i->first];
                 MYDEBUG << "process " << route << std::endl;
                 std::queue<std::string> vehicles = i->second;
                 while (!i->second.empty()) {
                         bool suc = false;
                         std::string type = i->second.front();
                         std::stringstream veh;
                         veh << type << "_" << vehicleNameCounter;
                         MYDEBUG << "trying to add " << veh.str() << " with " << route << " vehicle type " << type << std::endl;
                         suc = getCommandInterface()->addVehicle(veh.str(), type, route, simTime());
                         if (!suc) {
                                 i->second.pop();
                         }
                         else {
                                 MYDEBUG << "successful inserted " << veh.str() << std::endl;
                                 queuedVehicles.insert(veh.str());
                                 i->second.pop();
                                 vehicleNameCounter++;
                         }
                 }
                 std::map<int, std::queue<std::string> >::iterator tmp = i;
                 ++tmp;
                 vehicleInsertQueue.erase(i);
                 i = tmp;
         }
 }
bool Veins::TraCIScenarioManager::isConnected () const inline
Definition at line 92 of file TraCIScenarioManager.h.
Referenced by Veins::AnnotationManager::hide(), and Veins::AnnotationManager::show().
 { return (connection); }
bool TraCIScenarioManager::isInRegionOfInterest (const TraCICoord & position, std::string road_id, double speed, double angle) protected
returns whether a given position lies within the simulation's region of interest.
Modules are destroyed and re-created as managed vehicles leave and re-enter the ROI
Definition at line 369 of file TraCIScenarioManager.cc.
Referenced by processVehicleSubscription().
{
         if ((roiRoads.size() == 0) && (roiRects.size() == 0)) return true;
         if (roiRoads.size() > 0) {
                 for (std::list<std::string>::const_iterator i = roiRoads.begin(); i != roiRoads.end(); ++i) {
                         if (road_id == *i) return true;
                 }
         }
         if (roiRects.size() > 0) {
                 for (std::list<std::pair<TraCICoord, TraCICoord> >::const_iterator i = roiRects.begin(); i != roiRects.end(); ++i) {
                         if ((position.x >= i->first.x) && (position.y >= i->first.y) && (position.x <= i->second.x) && (position.y <= i->second.y)) return true;
                 }
         }
         return false;
 }
bool TraCIScenarioManager::isModuleUnequipped (std::string nodeId) protected
returns true if this vehicle is Unequipped
Definition at line 353 of file TraCIScenarioManager.cc.
Referenced by processVehicleSubscription().
{
         if (unEquippedHosts.find(nodeId) == unEquippedHosts.end()) return false;
         return true;
 }
virtual int Veins::TraCIScenarioManager::numInitStages () const inline virtual
Definition at line 86 of file TraCIScenarioManager.h.
 { return std::max(cSimpleModule::numInitStages(), 2); }
TraCICoord TraCIScenarioManager::omnet2traci (Coord coord) const
convert OMNeT++ coordinates to TraCI coordinates
Definition at line 458 of file TraCIScenarioManager.cc.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::mfcv_epidemic_app::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), Veins::epidemic_app::handlePositionUpdate(), omnet2traci(), and Veins::AnnotationManager::show().
{
         return TraCICoord(coord.x + netbounds1.x - margin, (netbounds2.y - netbounds1.y) - (coord.y - netbounds1.y) + margin);
 }
std::list< TraCICoord > TraCIScenarioManager::omnet2traci (const std::list< Coord > & list) const
Definition at line 462 of file TraCIScenarioManager.cc.
{
         std::list<TraCICoord> result;
         std::transform(list.begin(), list.end(), std::back_inserter(result),
                         std::bind1st(std::mem_fun<TraCICoord, TraCIScenarioManager, Coord>(&TraCIScenarioManager::omnet2traci), this));
         return result;
 }
double TraCIScenarioManager::omnet2traciAngle (double angle) const protected
convert OMNeT++ angle (in rad) to TraCI angle
Definition at line 484 of file TraCIScenarioManager.cc.
{
         // convert to degrees
         angle = angle * 180 / M_PI;
         // rotate angle so 0 is south (in OMNeT++'s angle interpretation 0 is east)
         angle = angle + 90;
         // normalize angle to -180 <= angle < 180
         while (angle < -180) angle += 360;
         while (angle >= 180) angle -= 360;
         return angle;
 }
void TraCIScenarioManager::processSimSubscription (std::string objectId, TraCIBuffer & buf) protected
Definition at line 527 of file TraCIScenarioManager.cc.
Referenced by processSubcriptionResult().
{
         uint8_t variableNumber_resp; buf >> variableNumber_resp;
         for (uint8_t j = 0; j < variableNumber_resp; ++j) {
                 uint8_t variable1_resp; buf >> variable1_resp;
                 uint8_t isokay; buf >> isokay;
                 if (isokay != RTYPE_OK) {
                         uint8_t varType; buf >> varType;
                         ASSERT(varType == TYPE_STRING);
                         std::string description; buf >> description;
                         if (isokay == RTYPE_NOTIMPLEMENTED) error("TraCI server reported subscribing to variable 0x%2x not implemented (\"%s\"). Might need newer version.", variable1_resp, description.c_str());
                         error("TraCI server reported error subscribing to variable 0x%2x (\"%s\").", variable1_resp, description.c_str());
                 }
                 if (variable1_resp == VAR_DEPARTED_VEHICLES_IDS) {
                         uint8_t varType; buf >> varType;
                         ASSERT(varType == TYPE_STRINGLIST);
                         uint32_t count; buf >> count;
                         MYDEBUG << "TraCI reports " << count << " departed vehicles." << endl;
                         for (uint32_t i = 0; i < count; ++i) {
                                 std::string idstring; buf >> idstring;
                                 // adding modules is handled on the fly when entering/leaving the ROI
                         }
                         activeVehicleCount += count;
                         drivingVehicleCount += count;
                 } else if (variable1_resp == VAR_ARRIVED_VEHICLES_IDS) {
                         uint8_t varType; buf >> varType;
                         ASSERT(varType == TYPE_STRINGLIST);
                         uint32_t count; buf >> count;
                         MYDEBUG << "TraCI reports " << count << " arrived vehicles." << endl;
                         for (uint32_t i = 0; i < count; ++i) {
                                 std::string idstring; buf >> idstring;
                                 if (subscribedVehicles.find(idstring) != subscribedVehicles.end()) {
                                         subscribedVehicles.erase(idstring);
                                         unsubscribeFromVehicleVariables(idstring);
                                 }
                                 // check if this object has been deleted already (e.g. because it was outside the ROI)
                                 cModule* mod = getManagedModule(idstring);
                                 if (mod) deleteModule(idstring);
                                 if(unEquippedHosts.find(idstring) != unEquippedHosts.end()) {
                                         unEquippedHosts.erase(idstring);
                                 }
                         }
                         if ((count > 0) && (count >= activeVehicleCount) && autoShutdown) autoShutdownTriggered = true;
                         activeVehicleCount -= count;
                         drivingVehicleCount -= count;
                 } else if (variable1_resp == VAR_TELEPORT_STARTING_VEHICLES_IDS) {
                         uint8_t varType; buf >> varType;
                         ASSERT(varType == TYPE_STRINGLIST);
                         uint32_t count; buf >> count;
                         MYDEBUG << "TraCI reports " << count << " vehicles starting to teleport." << endl;
                         for (uint32_t i = 0; i < count; ++i) {
                                 std::string idstring; buf >> idstring;
                                 // check if this object has been deleted already (e.g. because it was outside the ROI)
                                 cModule* mod = getManagedModule(idstring);
                                 if (mod) deleteModule(idstring);
                                 if(unEquippedHosts.find(idstring) != unEquippedHosts.end()) {
                                         unEquippedHosts.erase(idstring);
                                 }
                         }
                         activeVehicleCount -= count;
                         drivingVehicleCount -= count;
                 } else if (variable1_resp == VAR_TELEPORT_ENDING_VEHICLES_IDS) {
                         uint8_t varType; buf >> varType;
                         ASSERT(varType == TYPE_STRINGLIST);
                         uint32_t count; buf >> count;
                         MYDEBUG << "TraCI reports " << count << " vehicles ending teleport." << endl;
                         for (uint32_t i = 0; i < count; ++i) {
                                 std::string idstring; buf >> idstring;
                                 // adding modules is handled on the fly when entering/leaving the ROI
                         }
                         activeVehicleCount += count;
                         drivingVehicleCount += count;
                 } else if (variable1_resp == VAR_PARKING_STARTING_VEHICLES_IDS) {
                         uint8_t varType; buf >> varType;
                         ASSERT(varType == TYPE_STRINGLIST);
                         uint32_t count; buf >> count;
                         MYDEBUG << "TraCI reports " << count << " vehicles starting to park." << endl;
                         for (uint32_t i = 0; i < count; ++i) {
                                 std::string idstring; buf >> idstring;
                                 cModule* mod = getManagedModule(idstring);
                                 for (cModule::SubmoduleIterator iter(mod); !iter.end(); iter++) {
                                         cModule* submod = iter();
                                         TraCIMobility* mm = dynamic_cast<TraCIMobility*>(submod);
                                         if (!mm) continue;
                                         mm->changeParkingState(true);
                                 }
                         }
                         parkingVehicleCount += count;
                         drivingVehicleCount -= count;
                 } else if (variable1_resp == VAR_PARKING_ENDING_VEHICLES_IDS) {
                         uint8_t varType; buf >> varType;
                         ASSERT(varType == TYPE_STRINGLIST);
                         uint32_t count; buf >> count;
                         MYDEBUG << "TraCI reports " << count << " vehicles ending to park." << endl;
                         for (uint32_t i = 0; i < count; ++i) {
                                 std::string idstring; buf >> idstring;
                                 cModule* mod = getManagedModule(idstring);
                                 for (cModule::SubmoduleIterator iter(mod); !iter.end(); iter++) {
                                         cModule* submod = iter();
                                         TraCIMobility* mm = dynamic_cast<TraCIMobility*>(submod);
                                         if (!mm) continue;
                                         mm->changeParkingState(false);
                                 }
                         }
                         parkingVehicleCount -= count;
                         drivingVehicleCount += count;
                 } else if (variable1_resp == VAR_TIME_STEP) {
                         uint8_t varType; buf >> varType;
                         ASSERT(varType == TYPE_INTEGER);
                         uint32_t serverTimestep; buf >> serverTimestep;
                         MYDEBUG << "TraCI reports current time step as " << serverTimestep << "ms." << endl;
                         uint32_t omnetTimestep = getCurrentTimeMs();
                         ASSERT(omnetTimestep == serverTimestep);
                 } else {
                         error("Received unhandled sim subscription result");
                 }
         }
 }
void TraCIScenarioManager::processSubcriptionResult (TraCIBuffer & buf) protected
Definition at line 798 of file TraCIScenarioManager.cc.
Referenced by executeOneTimestep(), init_traci(), and subscribeToVehicleVariables().
{
         uint8_t cmdLength_resp; buf >> cmdLength_resp;
         uint32_t cmdLengthExt_resp; buf >> cmdLengthExt_resp;
         uint8_t commandId_resp; buf >> commandId_resp;
         std::string objectId_resp; buf >> objectId_resp;
         if (commandId_resp == RESPONSE_SUBSCRIBE_VEHICLE_VARIABLE) processVehicleSubscription(objectId_resp, buf);
         else if (commandId_resp == RESPONSE_SUBSCRIBE_SIM_VARIABLE) processSimSubscription(objectId_resp, buf);
         else {
                 error("Received unhandled subscription result");
         }
 }
void TraCIScenarioManager::processVehicleSubscription (std::string objectId, TraCIBuffer & buf) protected
Definition at line 668 of file TraCIScenarioManager.cc.
Referenced by processSubcriptionResult().
{
         bool isSubscribed = (subscribedVehicles.find(objectId) != subscribedVehicles.end());
         double px;
         double py;
         std::string edge;
         double speed;
         double angle_traci;
         int signals;
         int numRead = 0;
         uint8_t variableNumber_resp; buf >> variableNumber_resp;
         for (uint8_t j = 0; j < variableNumber_resp; ++j) {
                 uint8_t variable1_resp; buf >> variable1_resp;
                 uint8_t isokay; buf >> isokay;
                 if (isokay != RTYPE_OK) {
                         uint8_t varType; buf >> varType;
                         ASSERT(varType == TYPE_STRING);
                         std::string errormsg; buf >> errormsg;
                         if (isSubscribed) {
                                 if (isokay == RTYPE_NOTIMPLEMENTED) error("TraCI server reported subscribing to vehicle variable 0x%2x not implemented (\"%s\"). Might need newer version.", variable1_resp, errormsg.c_str());
                                 error("TraCI server reported error subscribing to vehicle variable 0x%2x (\"%s\").", variable1_resp, errormsg.c_str());
                         }
                 } else if (variable1_resp == ID_LIST) {
                         uint8_t varType; buf >> varType;
                         ASSERT(varType == TYPE_STRINGLIST);
                         uint32_t count; buf >> count;
                         MYDEBUG << "TraCI reports " << count << " active vehicles." << endl;
                         ASSERT(count == drivingVehicleCount);
                         std::set<std::string> drivingVehicles;
                         for (uint32_t i = 0; i < count; ++i) {
                                 std::string idstring; buf >> idstring;
                                 drivingVehicles.insert(idstring);
                         }
                         // check for vehicles that need subscribing to
                         std::set<std::string> needSubscribe;
                         std::set_difference(drivingVehicles.begin(), drivingVehicles.end(), subscribedVehicles.begin(), subscribedVehicles.end(), std::inserter(needSubscribe, needSubscribe.begin()));
                         for (std::set<std::string>::const_iterator i = needSubscribe.begin(); i != needSubscribe.end(); ++i) {
                                 subscribedVehicles.insert(*i);
                                 subscribeToVehicleVariables(*i);
                         }
                         // check for vehicles that need unsubscribing from
                         std::set<std::string> needUnsubscribe;
                         std::set_difference(subscribedVehicles.begin(), subscribedVehicles.end(), drivingVehicles.begin(), drivingVehicles.end(), std::inserter(needUnsubscribe, needUnsubscribe.begin()));
                         for (std::set<std::string>::const_iterator i = needUnsubscribe.begin(); i != needUnsubscribe.end(); ++i) {
                                 subscribedVehicles.erase(*i);
                                 unsubscribeFromVehicleVariables(*i);
                         }
                 } else if (variable1_resp == VAR_POSITION) {
                         uint8_t varType; buf >> varType;
                         ASSERT(varType == POSITION_2D);
                         buf >> px;
                         buf >> py;
                         numRead++;
                 } else if (variable1_resp == VAR_ROAD_ID) {
                         uint8_t varType; buf >> varType;
                         ASSERT(varType == TYPE_STRING);
                         buf >> edge;
                         numRead++;
                 } else if (variable1_resp == VAR_SPEED) {
                         uint8_t varType; buf >> varType;
                         ASSERT(varType == TYPE_DOUBLE);
                         buf >> speed;
                         numRead++;
                 } else if (variable1_resp == VAR_ANGLE) {
                         uint8_t varType; buf >> varType;
                         ASSERT(varType == TYPE_DOUBLE);
                         buf >> angle_traci;
                         numRead++;
                 } else if (variable1_resp == VAR_SIGNALS) {
                         uint8_t varType; buf >> varType;
                         ASSERT(varType == TYPE_INTEGER);
                         buf >> signals;
                         numRead++;
                 } else {
                         error("Received unhandled vehicle subscription result");
                 }
         }
         // bail out if we didn't want to receive these subscription results
         if (!isSubscribed) return;
         // make sure we got updates for all attributes
         if (numRead != 5) return;
         Coord p = traci2omnet(TraCICoord(px, py));
         if ((p.x < 0) || (p.y < 0)) error("received bad node position (%.2f, %.2f), translated to (%.2f, %.2f)", px, py, p.x, p.y);
         double angle = traci2omnetAngle(angle_traci);
         cModule* mod = getManagedModule(objectId);
         // is it in the ROI?
         bool inRoi = isInRegionOfInterest(TraCICoord(px, py), edge, speed, angle);
         if (!inRoi) {
                 if (mod) {
                         deleteModule(objectId);
                         MYDEBUG << "Vehicle #" << objectId << " left region of interest" << endl;
                 }
                 else if(unEquippedHosts.find(objectId) != unEquippedHosts.end()) {
                         unEquippedHosts.erase(objectId);
                         MYDEBUG << "Vehicle (unequipped) # " << objectId<< " left region of interest" << endl;
                 }
                 return;
         }
         if (isModuleUnequipped(objectId)) {
                 return;
         }
         if (!mod) {
                 // no such module - need to create
                 addModule(objectId, moduleType, moduleName, moduleDisplayString, p, edge, speed, angle);
                 MYDEBUG << "Added vehicle #" << objectId << endl;
         } else {
                 // module existed - update position
                 for (cModule::SubmoduleIterator iter(mod); !iter.end(); iter++) {
                         cModule* submod = iter();
                         ifInetTraCIMobilityCallNextPosition(submod, p, edge, speed, angle);
                         TraCIMobility* mm = dynamic_cast<TraCIMobility*>(submod);
                         if (!mm) continue;
                         MYDEBUG << "module " << objectId << " moving to " << p.x << "," << p.y << endl;
                         mm->nextPosition(p, edge, speed, angle);
                 }
         }
 }
void TraCIScenarioManager::subscribeToVehicleVariables (std::string vehicleId) protected
Definition at line 499 of file TraCIScenarioManager.cc.
Referenced by processVehicleSubscription().
{
         // subscribe to some attributes of the vehicle
         uint32_t beginTime = 0;
         uint32_t endTime = 0x7FFFFFFF;
         std::string objectId = vehicleId;
         uint8_t variableNumber = 5;
         uint8_t variable1 = VAR_POSITION;
         uint8_t variable2 = VAR_ROAD_ID;
         uint8_t variable3 = VAR_SPEED;
         uint8_t variable4 = VAR_ANGLE;
         uint8_t variable5 = VAR_SIGNALS;
         TraCIBuffer buf = connection->query(CMD_SUBSCRIBE_VEHICLE_VARIABLE, TraCIBuffer() << beginTime << endTime << objectId << variableNumber << variable1 << variable2 << variable3 << variable4 << variable5);
         processSubcriptionResult(buf);
         ASSERT(buf.eof());
 }
Coord TraCIScenarioManager::traci2omnet (TraCICoord coord) const
convert TraCI coordinates to OMNeT++ coordinates
Definition at line 448 of file TraCIScenarioManager.cc.
Referenced by Veins::TraCIMobility::commandGetPolygonShape(), Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), Veins::epidemic_app::handlePositionUpdate(), Veins::mfcv_epidemic_app::handlePositionUpdate(), init_traci(), traci2omnet_functor::operator()(), and processVehicleSubscription().
{
         return Coord(coord.x - netbounds1.x + margin, (netbounds2.y - netbounds1.y) - (coord.y - netbounds1.y) + margin);
 }
std::list< Coord > TraCIScenarioManager::traci2omnet (const std::list< TraCICoord > & list) const
Definition at line 452 of file TraCIScenarioManager.cc.
{
         std::list<Coord> result;
         std::transform(list.begin(), list.end(), std::back_inserter(result), traci2omnet_functor(*this));
         return result;
 }
double TraCIScenarioManager::traci2omnetAngle (double angle) const protected
convert TraCI angle to OMNeT++ angle (in rad)
Definition at line 469 of file TraCIScenarioManager.cc.
Referenced by processVehicleSubscription().
{
         // rotate angle so 0 is east (in TraCI's angle interpretation 0 is south)
         angle = angle - 90;
         // convert to rad
         angle = angle * M_PI / 180.0;
         // normalize angle to -M_PI <= angle < M_PI
         while (angle < -M_PI) angle += 2 * M_PI;
         while (angle >= M_PI) angle -= 2 * M_PI;
         return angle;
 }
void TraCIScenarioManager::unsubscribeFromVehicleVariables (std::string vehicleId) protected
Definition at line 516 of file TraCIScenarioManager.cc.
Referenced by processSimSubscription(), and processVehicleSubscription().
{
         // subscribe to some attributes of the vehicle
         uint32_t beginTime = 0;
         uint32_t endTime = 0x7FFFFFFF;
         std::string objectId = vehicleId;
         uint8_t variableNumber = 0;
         TraCIBuffer buf = connection->query(CMD_SUBSCRIBE_VEHICLE_VARIABLE, TraCIBuffer() << beginTime << endTime << objectId << variableNumber);
         ASSERT(buf.eof());
 }
Member Data Documentation
uint32_t Veins::TraCIScenarioManager::activeVehicleCount protected
number of vehicles, be it parking or driving
Definition at line 153 of file TraCIScenarioManager.h.
Referenced by handleSelfMsg(), initialize(), and processSimSubscription().
bool Veins::TraCIScenarioManager::autoShutdown protected
Shutdown module as soon as no more vehicles are in the simulation.
Definition at line 138 of file TraCIScenarioManager.h.
Referenced by initialize(), and processSimSubscription().
bool Veins::TraCIScenarioManager::autoShutdownTriggered protected
Definition at line 156 of file TraCIScenarioManager.h.
Referenced by executeOneTimestep(), getAutoShutdownTriggered(), initialize(), and processSimSubscription().
BaseConnectionManager* Veins::TraCIScenarioManager::cc protected
Definition at line 161 of file TraCIScenarioManager.h.
Referenced by deleteModule(), and initialize().
TraCICommandInterface* Veins::TraCIScenarioManager::commandIfc protected
Definition at line 145 of file TraCIScenarioManager.h.
Referenced by getCommandInterface(), handleSelfMsg(), and ~TraCIScenarioManager().
cMessage* Veins::TraCIScenarioManager::connectAndStartTrigger protected
self-message scheduled for when to connect to TraCI server and start running
Definition at line 157 of file TraCIScenarioManager.h.
Referenced by handleSelfMsg(), initialize(), and ~TraCIScenarioManager().
simtime_t Veins::TraCIScenarioManager::connectAt protected
when to connect to TraCI server (must be the initial timestep of the server)
Definition at line 118 of file TraCIScenarioManager.h.
Referenced by executeOneTimestep(), and initialize().
TraCIConnection* Veins::TraCIScenarioManager::connection protected
Definition at line 144 of file TraCIScenarioManager.h.
Referenced by executeOneTimestep(), finish(), handleSelfMsg(), Veins::TraCIScenarioManagerLaunchd::init_traci(), init_traci(), isConnected(), subscribeToVehicleVariables(), unsubscribeFromVehicleVariables(), and ~TraCIScenarioManager().
bool Veins::TraCIScenarioManager::debug protected
whether to emit debug messages
Definition at line 117 of file TraCIScenarioManager.h.
Referenced by initialize().
uint32_t Veins::TraCIScenarioManager::drivingVehicleCount protected
number of driving, as reported by sumo
Definition at line 155 of file TraCIScenarioManager.h.
Referenced by initialize(), processSimSubscription(), and processVehicleSubscription().
cMessage* Veins::TraCIScenarioManager::executeOneTimestepTrigger protected
self-message scheduled for when to next call executeOneTimestep
Definition at line 158 of file TraCIScenarioManager.h.
Referenced by executeOneTimestep(), handleSelfMsg(), initialize(), and ~TraCIScenarioManager().
simtime_t Veins::TraCIScenarioManager::firstStepAt protected
when to start synchronizing with the TraCI server (-1: immediately after connecting)
Definition at line 119 of file TraCIScenarioManager.h.
Referenced by initialize().
std::string Veins::TraCIScenarioManager::host protected
Definition at line 124 of file TraCIScenarioManager.h.
Referenced by handleSelfMsg(), and initialize().
std::map<std::string, cModule*> Veins::TraCIScenarioManager::hosts protected
vector of all hosts managed by us
Definition at line 150 of file TraCIScenarioManager.h.
Referenced by addModule(), deleteModule(), finish(), getManagedHosts(), getManagedModule(), and initialize().
int Veins::TraCIScenarioManager::margin protected
Definition at line 139 of file TraCIScenarioManager.h.
Referenced by initialize(), omnet2traci(), and traci2omnet().
cRNG* Veins::TraCIScenarioManager::mobRng protected
Definition at line 136 of file TraCIScenarioManager.h.
Referenced by initialize(), and insertNewVehicle().
std::string Veins::TraCIScenarioManager::moduleDisplayString protected
module displayString to be used in the simulation for each managed vehicle
Definition at line 123 of file TraCIScenarioManager.h.
Referenced by initialize(), and processVehicleSubscription().
std::string Veins::TraCIScenarioManager::moduleName protected
module name to be used in the simulation for each managed vehicle
Definition at line 122 of file TraCIScenarioManager.h.
Referenced by initialize(), and processVehicleSubscription().
std::string Veins::TraCIScenarioManager::moduleType protected
module type to be used in the simulation for each managed vehicle
Definition at line 121 of file TraCIScenarioManager.h.
Referenced by initialize(), and processVehicleSubscription().
cMessage* Veins::TraCIScenarioManager::myAddVehicleTimer protected
Definition at line 128 of file TraCIScenarioManager.h.
Referenced by initialize(), and ~TraCIScenarioManager().
TraCICoord Veins::TraCIScenarioManager::netbounds1 protected
Definition at line 146 of file TraCIScenarioManager.h.
Referenced by init_traci(), omnet2traci(), and traci2omnet().
TraCICoord Veins::TraCIScenarioManager::netbounds2 protected
Definition at line 147 of file TraCIScenarioManager.h.
Referenced by init_traci(), omnet2traci(), and traci2omnet().
size_t Veins::TraCIScenarioManager::nextNodeVectorIndex protected
next OMNeT++ module vector index to use
Definition at line 149 of file TraCIScenarioManager.h.
Referenced by addModule(), and initialize().
int Veins::TraCIScenarioManager::numVehicles protected
Definition at line 134 of file TraCIScenarioManager.h.
Referenced by handleSelfMsg(), and initialize().
uint32_t Veins::TraCIScenarioManager::parkingVehicleCount protected
number of parking vehicles, derived from parking start/end events
Definition at line 154 of file TraCIScenarioManager.h.
Referenced by initialize(), and processSimSubscription().
double Veins::TraCIScenarioManager::penetrationRate protected
Definition at line 140 of file TraCIScenarioManager.h.
Referenced by addModule(), and initialize().
int Veins::TraCIScenarioManager::port protected
Definition at line 125 of file TraCIScenarioManager.h.
Referenced by handleSelfMsg(), and initialize().
std::set<std::string> Veins::TraCIScenarioManager::queuedVehicles protected
Definition at line 131 of file TraCIScenarioManager.h.
Referenced by addModule(), handleSelfMsg(), and insertVehicles().
std::list<std::pair<TraCICoord, TraCICoord> > Veins::TraCIScenarioManager::roiRects protected
which rectangles (e.g.
"0,0-10,10 20,20-30,30) are considered to consitute the region of interest, if not empty
Definition at line 142 of file TraCIScenarioManager.h.
Referenced by initialize(), and isInRegionOfInterest().
std::list<std::string> Veins::TraCIScenarioManager::roiRoads protected
which roads (e.g.
"hwy1 hwy2") are considered to consitute the region of interest, if not empty
Definition at line 141 of file TraCIScenarioManager.h.
Referenced by initialize(), and isInRegionOfInterest().
std::vector<std::string> Veins::TraCIScenarioManager::routeIds protected
Definition at line 132 of file TraCIScenarioManager.h.
Referenced by handleSelfMsg(), insertNewVehicle(), and insertVehicles().
std::set<std::string> Veins::TraCIScenarioManager::subscribedVehicles protected
all vehicles we have already subscribed to
Definition at line 152 of file TraCIScenarioManager.h.
Referenced by initialize(), processSimSubscription(), and processVehicleSubscription().
std::set<std::string> Veins::TraCIScenarioManager::unEquippedHosts protected
Definition at line 151 of file TraCIScenarioManager.h.
Referenced by addModule(), isModuleUnequipped(), processSimSubscription(), and processVehicleSubscription().
simtime_t Veins::TraCIScenarioManager::updateInterval protected
time interval of hosts' position updates
Definition at line 120 of file TraCIScenarioManager.h.
Referenced by addModule(), executeOneTimestep(), and initialize().
std::map<int, std::queue<std::string> > Veins::TraCIScenarioManager::vehicleInsertQueue protected
Definition at line 130 of file TraCIScenarioManager.h.
Referenced by insertNewVehicle(), and insertVehicles().
uint32_t Veins::TraCIScenarioManager::vehicleNameCounter protected
Definition at line 127 of file TraCIScenarioManager.h.
Referenced by initialize(), and insertVehicles().
int Veins::TraCIScenarioManager::vehicleRngIndex protected
Definition at line 133 of file TraCIScenarioManager.h.
Referenced by initialize().
std::vector<std::string> Veins::TraCIScenarioManager::vehicleTypeIds protected
Definition at line 129 of file TraCIScenarioManager.h.
Referenced by handleSelfMsg(), and insertNewVehicle().
BaseWorldUtility* Veins::TraCIScenarioManager::world protected
Definition at line 160 of file TraCIScenarioManager.h.
Referenced by init_traci(), and initialize().
The documentation for this class was generated from the following files:
TraCIScenarioManager.h
TraCIScenarioManager.cc