Veins Framework: InterpolateableMap< TInterpolator, TContainer > Class Template Reference
InterpolateableMap< TInterpolator, TContainer > Class Template Reference
Represents a std::map which is able to interpolate.
#include <Interpolation.h>
Public Types
typedef TContainer container_type
typedef TInterpolator interpolator_type
typedef container_type base_class_type
typedef base_class_type::key_type key_type
typedef const key_type & key_cref_type
typedef
base_class_type::mapped_type mapped_type
typedef base_class_type::value_type pair_type
typedef const mapped_type & mapped_cref_type
typedef
interpolator_type::interpolated interpolated
typedef for the returned Interpolated value of this class.
typedef
base_class_type::const_iterator const_iterator
typedef base_class_type::iterator iterator
typedef
InterpolateableIterator
< TInterpolator > iterator_intpl
typedef
ConstInterpolateableIterator
< TInterpolator > const_iterator_intpl
Public Member Functions
InterpolateableMap ()
InterpolateableMap (mapped_cref_type oorv)
void setOutOfRangeVal (mapped_cref_type oorv)
interpolated getIntplValue (key_cref_type pos) const
const_iterator_intpl findIntpl (key_cref_type pos) const
const_iterator_intpl beginIntpl () const
iterator_intpl findIntpl (key_cref_type pos) __attribute__((noinline))
iterator_intpl beginIntpl ()
Protected Attributes
interpolator_type interpolate
Detailed Description
template<class TInterpolator, class TContainer = typename TInterpolator::container_type>
class InterpolateableMap< TInterpolator, TContainer >
Represents a std::map which is able to interpolate.
Returns interpolated values if accessed at position without keys.
Used to represent Mappings
Author
Karl Wessel
See Also
Mapping
Definition at line 776 of file Interpolation.h.
Member Typedef Documentation
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> typedef container_type InterpolateableMap< TInterpolator, TContainer >::base_class_type
Definition at line 780 of file Interpolation.h.
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> typedef base_class_type::const_iterator InterpolateableMap< TInterpolator, TContainer >::const_iterator
Definition at line 790 of file Interpolation.h.
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> typedef ConstInterpolateableIterator<TInterpolator> InterpolateableMap< TInterpolator, TContainer >::const_iterator_intpl
Definition at line 794 of file Interpolation.h.
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> typedef TContainer InterpolateableMap< TInterpolator, TContainer >::container_type
Definition at line 778 of file Interpolation.h.
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> typedef interpolator_type::interpolated InterpolateableMap< TInterpolator, TContainer >::interpolated
typedef for the returned Interpolated value of this class.
Definition at line 789 of file Interpolation.h.
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> typedef TInterpolator InterpolateableMap< TInterpolator, TContainer >::interpolator_type
Definition at line 779 of file Interpolation.h.
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> typedef base_class_type::iterator InterpolateableMap< TInterpolator, TContainer >::iterator
Definition at line 791 of file Interpolation.h.
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> typedef InterpolateableIterator<TInterpolator> InterpolateableMap< TInterpolator, TContainer >::iterator_intpl
Definition at line 793 of file Interpolation.h.
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> typedef const key_type& InterpolateableMap< TInterpolator, TContainer >::key_cref_type
Definition at line 782 of file Interpolation.h.
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> typedef base_class_type::key_type InterpolateableMap< TInterpolator, TContainer >::key_type
Definition at line 781 of file Interpolation.h.
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> typedef const mapped_type& InterpolateableMap< TInterpolator, TContainer >::mapped_cref_type
Definition at line 785 of file Interpolation.h.
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> typedef base_class_type::mapped_type InterpolateableMap< TInterpolator, TContainer >::mapped_type
Definition at line 783 of file Interpolation.h.
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> typedef base_class_type::value_type InterpolateableMap< TInterpolator, TContainer >::pair_type
Definition at line 784 of file Interpolation.h.
Constructor & Destructor Documentation
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> InterpolateableMap< TInterpolator, TContainer >::InterpolateableMap () inline
Definition at line 801 of file Interpolation.h.
 {}
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> InterpolateableMap< TInterpolator, TContainer >::InterpolateableMap (mapped_cref_type oorv) inline
Definition at line 803 of file Interpolation.h.
                                                  :
                 interpolate(oorv) {}
Member Function Documentation
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> const_iterator_intpl InterpolateableMap< TInterpolator, TContainer >::beginIntpl () const inline
Definition at line 822 of file Interpolation.h.
Referenced by TimeMapping< Interpolator >::createIterator().
{
                 const_iterator_intpl it(this->begin(), this->end(), interpolate);
                 return it;
         }
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> iterator_intpl InterpolateableMap< TInterpolator, TContainer >::beginIntpl () inline
Definition at line 836 of file Interpolation.h.
{
                 iterator_intpl it(*this, interpolate);
                 return it;
         }
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> const_iterator_intpl InterpolateableMap< TInterpolator, TContainer >::findIntpl (key_cref_type pos) const inline
Definition at line 814 of file Interpolation.h.
Referenced by TimeMapping< Interpolator >::createIterator().
{
                 const_iterator_intpl it(this->begin(), this->end(), interpolate);
                 it.jumpTo(pos);
                 return it;
         }
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> iterator_intpl InterpolateableMap< TInterpolator, TContainer >::findIntpl (key_cref_type pos) inline
Definition at line 828 of file Interpolation.h.
{
                 iterator_intpl it(*this, interpolate);
                 it.jumpTo(pos);
                 return it;
         }
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> interpolated InterpolateableMap< TInterpolator, TContainer >::getIntplValue (key_cref_type pos) const inline
Definition at line 810 of file Interpolation.h.
Referenced by TimeMapping< Interpolator >::getValue(), and MultiDimMapping< Linear >::getValue().
{
                 return interpolate(this->begin(), this->end(), pos, this->upper_bound(pos));
         }
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> void InterpolateableMap< TInterpolator, TContainer >::setOutOfRangeVal (mapped_cref_type oorv) inline
Definition at line 806 of file Interpolation.h.
Referenced by MultiDimMapping< Linear >::MultiDimMapping(), and MultiDimMapping< Linear >::operator=().
{
                 interpolate.setOutOfRangeVal(oorv);
         }
Member Data Documentation
template<class TInterpolator, class TContainer = typename TInterpolator::container_type> interpolator_type InterpolateableMap< TInterpolator, TContainer >::interpolate protected
Definition at line 798 of file Interpolation.h.
Referenced by InterpolateableMap< Interpolator< std::map< simtime_t, argument_value_t > > >::beginIntpl(), InterpolateableMap< Interpolator< std::map< simtime_t, argument_value_t > > >::findIntpl(), InterpolateableMap< Interpolator< std::map< simtime_t, argument_value_t > > >::getIntplValue(), and InterpolateableMap< Interpolator< std::map< simtime_t, argument_value_t > > >::setOutOfRangeVal().
The documentation for this class was generated from the following file:
Interpolation.h