Veins Framework: ConstMapping Class Reference
ConstMapping Class Reference abstract
Represents a not changeable mapping (mathematical function) from domain with at least the time to a Argument::mapped_type value.
#include <MappingBase.h>
Public Types
typedef Argument::mapped_type argument_value_t
typedef Argument::mapped_type_cref argument_value_cref_t
Public Member Functions
ConstMapping ()
Initializes the ConstMapping with a the time dimension as domain.
ConstMapping (const DimensionSet &dimSet)
Initializes the ConstMapping with the passed DimensionSet as Domain.
virtual ~ConstMapping ()
virtual argument_value_t getValue (const Argument &pos) const =0
Returns the value of this Mapping at the position specified by the passed Argument.
virtual ConstMappingIterator * createConstIterator () const =0
Returns a pointer of a new Iterator which is able to iterate over this Mapping.
virtual ConstMappingIterator * createConstIterator (const Argument &pos) const =0
Returns a pointer of a new Iterator which is able to iterate over the function.
virtual ConstMapping * constClone () const =0
returns a deep copy of this mapping instance.
argument_value_t operator[] (const Argument &pos) const
Returns the value of this Mapping at the position specified by the passed Argument.
const DimensionSet & getDimensionSet () const
Returns this Mappings domain as DimensionSet.
template<class stream >
stream & print (stream &out, argument_value_cref_t lTimeScale=argument_value_t(1000), argument_value_cref_t lLeftColScale=Argument::MappedOne, const std::string &sTableHead=std::string("o\\ms"), const Dimension *const pOnlyDim=NULL) const
Prints the Mapping to an output stream.
Protected Attributes
DimensionSet dimensions
The dimensions of this mappings domain.
Private Member Functions
template<class T >
std::string toString (T v, unsigned int length) const
std::string toString (simtime_t_cref v, unsigned int length) const
Friends
std::ostream & operator<< (std::ostream &out, const ConstMapping &rMapToPrint)
Detailed Description
Represents a not changeable mapping (mathematical function) from domain with at least the time to a Argument::mapped_type value.
This class is an interface which describes a mapping (math.) from a arbitrary dimensional domain (represented by a DimensionSet) to a Argument::mapped_type value.
Author
Karl Wessel
Definition at line 696 of file MappingBase.h.
Member Typedef Documentation
typedef Argument::mapped_type_cref ConstMapping::argument_value_cref_t
Definition at line 699 of file MappingBase.h.
typedef Argument::mapped_type ConstMapping::argument_value_t
Definition at line 698 of file MappingBase.h.
Constructor & Destructor Documentation
ConstMapping::ConstMapping () inline
Initializes the ConstMapping with a the time dimension as domain.
Definition at line 727 of file MappingBase.h.
                       :
                 dimensions(Dimension::time) {}
ConstMapping::ConstMapping (const DimensionSet & dimSet) inline
Initializes the ConstMapping with the passed DimensionSet as Domain.
The passed DimensionSet has to contain the time dimension!
Definition at line 736 of file MappingBase.h.
                                                 :
                 dimensions(dimSet) {
                 assert(dimSet.hasDimension(Dimension::time));
         }
virtual ConstMapping::~ConstMapping () inline virtual
Definition at line 742 of file MappingBase.h.
 {}
Member Function Documentation
virtual ConstMapping* ConstMapping::constClone () const pure virtual
returns a deep copy of this mapping instance.
Implemented in ConstDelayedMapping, ConcatConstMapping< Operator >, SimpleConstMapping, Mapping, ConstMappingWrapper, ConstantSimpleConstMapping, RSAMMapping, TwoRayInterferenceModel::Mapping, JakesFadingMapping, and SimplePathlossConstMapping.
Referenced by ConstMappingWrapper::constClone(), Signal::operator=(), and Signal::Signal().
virtual ConstMappingIterator* ConstMapping::createConstIterator () const pure virtual
Returns a pointer of a new Iterator which is able to iterate over this Mapping.
See class ConstIterator for details.
Implemented in BaseDelayedMapping< ConstMapping >, BaseDelayedMapping< Mapping >, ConcatConstMapping< Operator >, SimpleConstMapping, Mapping, ConstMappingWrapper, and RSAMMapping.
Referenced by MappingUtils::applyElementWiseOperator(), SNRThresholdDecider::canAnswerCSR(), MappingUtils::createCompatibleMapping(), ConcatConstMapping< Operator >::createConstIterator(), FilledUpMapping::FilledUpMapping(), MappingUtils::findMax(), MappingUtils::findMin(), and print().
virtual ConstMappingIterator* ConstMapping::createConstIterator (const Argument & pos) const pure virtual
Returns a pointer of a new Iterator which is able to iterate over the function.
The iterator starts at the passed position.
See class ConstIterator for details.
Implemented in BaseDelayedMapping< ConstMapping >, BaseDelayedMapping< Mapping >, ConcatConstMapping< Operator >, SimpleConstMapping, Mapping, ConstMappingWrapper, and RSAMMapping.
const DimensionSet& ConstMapping::getDimensionSet () const inline
Returns this Mappings domain as DimensionSet.
Definition at line 784 of file MappingBase.h.
Referenced by MappingUtils::applyElementWiseOperator(), SNRThresholdDecider::canAnswerCSR(), MappingUtils::createCompatibleMapping(), TwoRayInterferenceModel::filterSignal(), SimpleObstacleShadowing::filterSignal(), SimplePathlossModel::filterSignal(), MappingUtils::findMax(), MappingUtils::findMin(), and print().
{
                 return dimensions;
         }
virtual argument_value_t ConstMapping::getValue (const Argument & pos) const pure virtual
Returns the value of this Mapping at the position specified by the passed Argument.
The complexity of this method depends on the actual implementation.
Implemented in BaseDelayedMapping< ConstMapping >, BaseDelayedMapping< Mapping >, ConcatConstMapping< Operator >, MultiDimMapping< Interpolator >, MultiDimMapping< Linear >, SimpleConstMapping, ConstMappingWrapper, ConstantSimpleConstMapping, RSAMMapping, LinearIntplMapping, TimeMapping< Interpolator >, TwoRayInterferenceModel::Mapping, JakesFadingMapping, and SimplePathlossConstMapping.
Referenced by ConcatConstMapping< Operator >::getValue().
argument_value_t ConstMapping::operator[] (const Argument & pos) const inline
Returns the value of this Mapping at the position specified by the passed Argument.
Definition at line 777 of file MappingBase.h.
{
                 return getValue(pos);
         }
template<class stream > stream& ConstMapping::print (stream & out, argument_value_cref_t lTimeScale = argument_value_t(1000), argument_value_cref_t lLeftColScale = Argument::MappedOne, const std::string & sTableHead = std::string("o\\ms"), const Dimension *const pOnlyDim = NULL) const inline
Prints the Mapping to an output stream.
Parameters
out The output stream to print.
lTimeScale The scaling factor for the time header values (default 1000).
lLeftColScale The scaling factor for the left column values (default 1, unscaled).
sTableHead The header string for the left column (default: "o\\ms").
pOnlyDim Pointer to a specific dimension which should be used as the left column (should not be the Dimension::time).
Definition at line 798 of file MappingBase.h.
{
                 const ConstMapping&      m = *this;
                 DimensionSet::value_type otherDim;
                 const DimensionSet&      dims = m.getDimensionSet();
                 bool                     bOnlyDimFound = false;
                 using std::operator<<;
                 std::stringstream            osDimHead(std::stringstream::out);
                 bool                         bTimeIsIn = false;
                 const DimensionSet::iterator dimsEnd   = dims.end();
                 for(DimensionSet::iterator it = dims.begin(); it != dimsEnd; ++it) {
                         if(*it != Dimension::time) {
                                 if (pOnlyDim && *it == *pOnlyDim) {
                                         otherDim      = *it;
                                         bOnlyDimFound = pOnlyDim != NULL;
                                 }
                                 else if (!pOnlyDim) {
                                         otherDim      = *it;
                                 }
                                 if (!osDimHead.str().empty())
                                         osDimHead << ", ";
                                 osDimHead << *it;
                         }
                         else
                                 bTimeIsIn = true;
                 }
                 if (bTimeIsIn || !osDimHead.str().empty()) {
                         out << "Mapping domain: ";
                         if (bTimeIsIn) {
                                 out << "time";
                                 if (!osDimHead.str().empty())
                                         out << ", ";
                         }
                         out << osDimHead.str() << endl;
                 }
                 ConstMappingIterator* it = m.createConstIterator();
                 if(!it->inRange()) {
                         out << "Mapping is empty." << endl;
                         return out;
                 }
                 Argument min = it->getPosition();
                 Argument max = it->getPosition();
                 typedef std::set<simtime_t>         t_time_container_type;
                 typedef std::set<argument_value_t>  t_value_container_type;
                 t_time_container_type  timePositions;
                 t_value_container_type otherPositions;
                 std::size_t            iMaxHeaderItemLen = m.toString(it->getPosition().getTime() * lTimeScale, 2).length();
                 std::size_t            iMaxLeftItemLen   = 5 > sTableHead.length() ? 5 : sTableHead.length();
                 const bool             bIs2Dim           = dims.size() == 2;
                 if (bIs2Dim && bOnlyDimFound)
                         bOnlyDimFound = false; // we have only the time and the requested dimension (fallback to normal case)
                 timePositions.insert(it->getPosition().getTime());
                 if(bIs2Dim || bOnlyDimFound) {
                         Argument::const_iterator posValIt;
                         if (bOnlyDimFound && (posValIt = it->getPosition().find(otherDim)) != it->getPosition().end()) {
                                 otherPositions.insert(it->getPosition().getArgValue(otherDim));
                                 iMaxLeftItemLen = std::max(iMaxLeftItemLen, m.toString(posValIt->second*lLeftColScale, 2).length());
                         }
                         else if (!bOnlyDimFound) {
                                 otherPositions.insert(it->getPosition().begin()->second);
                                 iMaxLeftItemLen = std::max(iMaxLeftItemLen, m.toString(it->getPosition().begin()->second*lLeftColScale, 2).length());
                         }
                 }
                 while(it->hasNext()) {
                         it->next();
                         const Argument&                pos         = it->getPosition();
                         const Argument::const_iterator posValItEnd = pos.end();
                         Argument::const_iterator       posValIt;
                         min.setTime(std::min(min.getTime(), pos.getTime()));
                         max.setTime(std::max(max.getTime(), pos.getTime()));
                         timePositions.insert(pos.getTime());
                         iMaxHeaderItemLen = std::max(iMaxHeaderItemLen, m.toString(pos.getTime() * lTimeScale, 2).length());
                         if (bOnlyDimFound && (posValIt = pos.find(otherDim)) != posValItEnd) {
                                 iMaxLeftItemLen = std::max(iMaxLeftItemLen, m.toString(posValIt->second*lLeftColScale, 2).length());
                         }
                         for(Argument::const_iterator itA = pos.begin(); itA != posValItEnd; ++itA) {
                                 if(bIs2Dim || bOnlyDimFound) {
                                         if (!bOnlyDimFound || itA->first == otherDim) {
                                                 otherPositions.insert(itA->second);
                                                 iMaxLeftItemLen = std::max(iMaxLeftItemLen, m.toString(itA->second*lLeftColScale, 2).length());
                                         }
                                 }
                                 min.setArgValue(itA->first, std::min(min.getArgValue(itA->first), itA->second));
                                 max.setArgValue(itA->first, std::max(max.getArgValue(itA->first), itA->second));
                         }
                 }
                 delete it;
                 if(!bIs2Dim && !bOnlyDimFound) {
                         if (!bOnlyDimFound && pOnlyDim != NULL) {
                                 out << "map contains no " << pOnlyDim->getName() << " dimension!" << endl;
                         }
                         else
                                 out << "domain - min=" << min << " max=" << max << endl;
                         return out;
                 }
                 if (bOnlyDimFound && otherPositions.empty()) {
                         out << "Defines no own key entries for " << pOnlyDim->getName() << " dimension! That does NOT mean it doesn't define any attenuation." << endl;
                         return out;
                 }
                 t_time_container_type::const_iterator       tIt;
                 const t_time_container_type::const_iterator tItEnd = timePositions.end();
                 std::stringstream                           osBorder(std::stringstream::out);
                 std::stringstream                           osHeader(std::stringstream::out);
                 mixim::math::mW2dBm<argument_value_t>       fctor2dBm;
                 for(tIt = timePositions.begin(); tIt != tItEnd; ++tIt) {
                         osHeader << m.toString(*tIt * 1000, iMaxHeaderItemLen) << osHeader.fill();
                 }
                 osBorder.fill('-');
                 osBorder << std::setw(iMaxLeftItemLen) << "" << osBorder.fill() << "+" << osBorder.fill() << std::setw(osHeader.str().length()) << "";
                 out << osBorder.str() << std::endl;
                 out << std::setw(iMaxLeftItemLen) << std::left << sTableHead << out.fill() << "|" << out.fill();
                 out << osHeader.str() << std::endl;
                 out << osBorder.str() << std::endl;
                 it = m.createConstIterator();
                 if(dims.size() == 1) {
                         out << std::setw(iMaxLeftItemLen) << "value" << out.fill() << "|" << out.fill();
                         while(it->inRange()) {
                                 out << m.toString(fctor2dBm(it->getValue()), iMaxHeaderItemLen) << out.fill();
                                 if(!it->hasNext()) {
                                         break;
                                 }
                                 it->next();
                         }
                 } else {
                         t_value_container_type::const_iterator fIt = otherPositions.begin();
                         tIt = timePositions.begin();
                         out << m.toString((*fIt)*lLeftColScale, iMaxLeftItemLen) << out.fill() << "|" << out.fill();
                         while(it->inRange()) {
                                 if(*fIt != it->getPosition().getArgValue(otherDim)) {
                                         ++fIt;
                                         out << std::endl << m.toString((*fIt)*lLeftColScale, iMaxLeftItemLen) << out.fill() << "|" << out.fill();
                                         tIt = timePositions.begin();
                                         assert(*fIt == it->getPosition().getArgValue(otherDim));
                                 }
                                 while( tIt != tItEnd && *tIt < it->getPosition().getTime() ) {
                                         // blank item because the header time does not match
                                         ++tIt;
                                         out << std::setw(iMaxHeaderItemLen+1) << "";
                                 }
                                 if ( tIt != tItEnd ) {
                                         // jump to next header item
                                         ++tIt;
                                 }
                                 out << m.toString(fctor2dBm(it->getValue()), iMaxHeaderItemLen) << out.fill();
                                 if(!it->hasNext()) {
                                         break;
                                 }
                                 it->next();
                         }
                 }
                 out << std::endl << osBorder.str() << std::endl;
                 return out;
         }
template<class T > std::string ConstMapping::toString (T v, unsigned int length) const inline private
Definition at line 707 of file MappingBase.h.
Referenced by print().
{
                 std::stringstream osToStr(std::stringstream::out);
                 using std::operator<<;
                 osToStr << std::fixed; osToStr.precision(2); osToStr.width(length);
                 osToStr << std::right << v;
                 return osToStr.str();
         }
std::string ConstMapping::toString (simtime_t_cref v, unsigned int length) const inline private
Definition at line 718 of file MappingBase.h.
{
                 return toString(SIMTIME_DBL(v), length);
         }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const ConstMapping & rMapToPrint) friend
Definition at line 977 of file MappingBase.h.
{
                 return rMapToPrint.print(out);
         }
Member Data Documentation
DimensionSet ConstMapping::dimensions protected
The dimensions of this mappings domain.
Definition at line 703 of file MappingBase.h.
Referenced by MultiDimMapping< Linear >::copySubMappings(), MultiDimMapping< Linear >::createSubSignal(), SimpleConstMapping::initializeArguments(), MultiDimMapping< Linear >::MultiDimMapping(), MultiDimMappingIterator< Linear >::MultiDimMappingIterator(), and MultiDimMapping< Linear >::operator=().
The documentation for this class was generated from the following file:
MappingBase.h