Veins Framework: Veins::AnnotationManagerAccess Class Reference
Veins::AnnotationManagerAccess Class Reference
#include <AnnotationManager.h>
Public Member Functions
AnnotationManager * getIfExists ()
Detailed Description
Definition at line 144 of file AnnotationManager.h.
Member Function Documentation
AnnotationManager* Veins::AnnotationManagerAccess::getIfExists () inline
Definition at line 147 of file AnnotationManager.h.
Referenced by osdp_RSU::initialize(), service_discovery_RSU::initialize(), test1_rsu::initialize(), mfcv_rsu::initialize(), default_veins_TraCI_RSU::initialize(), minicurso_UFPI_TraCI_RSU::initialize(), default_veins_TraCI::initialize(), minicurso_UFPI_TraCI::initialize(), mfcv::initialize(), and Veins::ObstacleControl::initialize().
{
                         return FindModule<AnnotationManager*>::findGlobalModule();
                 };
The documentation for this class was generated from the following file:
AnnotationManager.h