Veins Framework: AirFrame11p Class Reference
AirFrame11p Class Reference
Class generated from modules/messages/AirFrame11p.msg:25 by nedtool.
#include <AirFrame11p_m.h>
Public Member Functions
AirFrame11p (const char *name=NULL, int kind=0)
AirFrame11p (const AirFrame11p &other)
virtual ~AirFrame11p ()
AirFrame11p & operator= (const AirFrame11p &other)
virtual AirFrame11p * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getUnderSensitivity () const
virtual void setUnderSensitivity (bool underSensitivity)
virtual bool getWasTransmitting () const
virtual void setWasTransmitting (bool wasTransmitting)
Public Member Functions inherited from Veins::AirFrame
AirFrame (const char *name=NULL, int kind=0)
AirFrame (const AirFrame &other)
virtual ~AirFrame ()
AirFrame & operator= (const AirFrame &other)
virtual Signal & getSignal ()
virtual const Signal & getSignal () const
virtual void setSignal (const Signal &signal)
virtual simtime_t getDuration () const
virtual void setDuration (simtime_t duration)
virtual int getState () const
virtual void setState (int state)
virtual int getType () const
virtual void setType (int type)
virtual long getId () const
virtual void setId (long id)
virtual int getProtocolId () const
virtual void setProtocolId (int protocolId)
virtual int getChannel () const
virtual void setChannel (int channel)
Protected Member Functions
bool operator== (const AirFrame11p &)
Protected Member Functions inherited from Veins::AirFrame
bool operator== (const AirFrame &)
Protected Attributes
bool underSensitivity_var
bool wasTransmitting_var
Protected Attributes inherited from Veins::AirFrame
Signal signal_var
simtime_t duration_var
int state_var
int type_var
long id_var
int protocolId_var
int channel_var
Private Member Functions
void copy (const AirFrame11p &other)
Detailed Description
Class generated from modules/messages/AirFrame11p.msg:25 by nedtool.
//
// Extension of base AirFrame message to have the underSensitivity field
//
message AirFrame11p extends AirFrame
{
    bool underSensitivity = false;
    bool wasTransmitting = false;
}
Definition at line 36 of file AirFrame11p_m.h.
Constructor & Destructor Documentation
AirFrame11p::AirFrame11p (const char * name = NULL, int kind = 0)
Referenced by dup().
AirFrame11p::AirFrame11p (const AirFrame11p & other)
virtual AirFrame11p::~AirFrame11p () virtual
Member Function Documentation
void AirFrame11p::copy (const AirFrame11p & other) private
virtual AirFrame11p* AirFrame11p::dup () const inline virtual
Reimplemented from Veins::AirFrame.
Definition at line 54 of file AirFrame11p_m.h.
 {return new AirFrame11p(*this);}
virtual bool AirFrame11p::getUnderSensitivity () const virtual
Referenced by Decider80211p::processSignalEnd().
virtual bool AirFrame11p::getWasTransmitting () const virtual
Referenced by Decider80211p::processSignalEnd().
AirFrame11p& AirFrame11p::operator= (const AirFrame11p & other)
bool AirFrame11p::operator== (const AirFrame11p &) protected
virtual void AirFrame11p::parsimPack (cCommBuffer * b) virtual
Reimplemented from Veins::AirFrame.
Referenced by doPacking().
virtual void AirFrame11p::parsimUnpack (cCommBuffer * b) virtual
Reimplemented from Veins::AirFrame.
Referenced by doUnpacking().
virtual void AirFrame11p::setUnderSensitivity (bool underSensitivity) virtual
Referenced by Decider80211p::processNewSignal().
virtual void AirFrame11p::setWasTransmitting (bool wasTransmitting) virtual
Referenced by Decider80211p::processNewSignal().
Member Data Documentation
bool AirFrame11p::underSensitivity_var protected
Definition at line 39 of file AirFrame11p_m.h.
bool AirFrame11p::wasTransmitting_var protected
Definition at line 40 of file AirFrame11p_m.h.
The documentation for this class was generated from the following file:
AirFrame11p_m.h