Veins Framework: BaseWorldUtility Class Reference
BaseWorldUtility Class Reference
Provides information and utility methods for the whole simulation.
#include <BaseWorldUtility.h>
Public Member Functions
BaseWorldUtility ()
virtual void initialize (int stage)
const Coord * getPgs ()
Returns the playgroundSize.
bool useTorus ()
Returns true if our playground represents a torus (borders are connected)
virtual Coord getRandomPosition ()
Random position somewhere in the playground.
bool use2D ()
Returns true if the world is 2-dimensional.
long getUniqueAirFrameId ()
Returns an Id for an AirFrame, at the moment simply an incremented long-value.
Static Public Attributes
static const double speedOfLight = 299792458.0
Speed of light in meters per second.
Protected Member Functions
virtual void initializeIfNecessary ()
Initializes all members accessible by other modules.
Protected Attributes
Coord playgroundSize
Size of the area the nodes are in (in meters)
bool useTorusFlag
Should the playground be treatend as a torus?
bool use2DFlag
Should the world be 2-dimensional?
long airFrameId
Provides a unique number for AirFrames per simulation.
bool isInitialized
Stores if members are already initialized.
Detailed Description
Provides information and utility methods for the whole simulation.
Definition at line 32 of file BaseWorldUtility.h.
Constructor & Destructor Documentation
BaseWorldUtility::BaseWorldUtility ()
Definition at line 30 of file BaseWorldUtility.cc.
                                   :
                 isInitialized(false)
 {}
Member Function Documentation
const Coord* BaseWorldUtility::getPgs () inline
Returns the playgroundSize.
Note: The playground is in the range [0, playground size]. Meaning the upper borders (at pg-size) as well as the lower borders (at 0) are part of the playground.
Definition at line 81 of file BaseWorldUtility.h.
Referenced by Veins::TraCIScenarioManager::init_traci(), BaseMobility::initialize(), BaseConnectionManager::initialize(), PhyLayer80211p::initializeBreakpointPathlossModel(), PhyLayer80211p::initializeSimpleObstacleShadowing(), and PhyLayer80211p::initializeSimplePathlossModel().
{
         initializeIfNecessary();
         return &playgroundSize;
     };
Coord BaseWorldUtility::getRandomPosition () virtual
Random position somewhere in the playground.
Definition at line 77 of file BaseWorldUtility.cc.
Referenced by BaseMobility::initialize(), and BaseMobility::placeRandomlyIfOutside().
 {
         initializeIfNecessary();
         return Coord(uniform(0, playgroundSize.x),
                      uniform(0, playgroundSize.y),
                      use2DFlag ? 0. : uniform(0, playgroundSize.z));
 }
long BaseWorldUtility::getUniqueAirFrameId () inline
Returns an Id for an AirFrame, at the moment simply an incremented long-value.
Definition at line 103 of file BaseWorldUtility.h.
Referenced by PhyLayer80211p::encapsMsg(), and BasePhyLayer::encapsMsg().
     {
         initializeIfNecessary();
         // if counter has done one complete cycle and will be set to a value it already had
         if (airFrameId == -1){
                 // print a warning
                 ev << "WARNING: AirFrameId-Counter has done one complete cycle."
                 << " AirFrameIds are repeating now and may not be unique anymore." << endl;
         }
         return airFrameId++;
     }
void BaseWorldUtility::initialize (int stage) virtual
Definition at line 34 of file BaseWorldUtility.cc.
{
         if (stage == 0) {
         initializeIfNecessary();
         }
         else if(stage == 1) {
                 //check if necessary modules are there
                 //Connection Manager
                 if(!FindModule<BaseConnectionManager*>::findGlobalModule()) {
                         opp_warning("Could not find a connection manager module in the network!");
                 }
         }
 }
void BaseWorldUtility::initializeIfNecessary () protected virtual
Initializes all members accessible by other modules.
Called once the first time another module accesses a member or during initialize stage 0 at the latest.
Definition at line 47 of file BaseWorldUtility.cc.
Referenced by getRandomPosition(), and initialize().
 {
         if(isInitialized)
                 return;
         use2DFlag      = par("use2D");
         playgroundSize = Coord(par("playgroundSizeX").doubleValue(),
                                par("playgroundSizeY").doubleValue(),
                                use2DFlag ? 0. : par("playgroundSizeZ").doubleValue());
         if(playgroundSize.x < 0) {
                 opp_error("Playground size in X direction is invalid: "\
                                   "(%f). Should be greater than or equal to zero.", playgroundSize.x);
         }
         if(playgroundSize.y < 0) {
                 opp_error("Playground size in Y direction is invalid: "\
                                   "(%f). Should be greater than or equal to zero.", playgroundSize.y);
         }
         if(!use2DFlag && playgroundSize.z < 0) {
                 opp_error("Playground size in Z direction is invalid: "\
                                   "(%f). Should be greater than or equal to zero.", playgroundSize.z);
         }
         useTorusFlag = par("useTorus");
         airFrameId = 0;
         isInitialized = true;
 }
bool BaseWorldUtility::use2D () inline
Returns true if the world is 2-dimensional.
Definition at line 96 of file BaseWorldUtility.h.
Referenced by BaseMobility::checkIfOutside(), Veins::TraCIMobility::fixIfHostGetsOutside(), PhyLayer80211p::getAnalogueModelFromName(), BaseMobility::goToBorder(), BaseMobility::initialize(), and BaseMobility::updatePosition().
     {
         initializeIfNecessary();
         return use2DFlag;
     }
bool BaseWorldUtility::useTorus () inline
Returns true if our playground represents a torus (borders are connected)
Definition at line 87 of file BaseWorldUtility.h.
Referenced by BaseConnectionManager::initialize(), PhyLayer80211p::initializeBreakpointPathlossModel(), PhyLayer80211p::initializeSimpleObstacleShadowing(), and PhyLayer80211p::initializeSimplePathlossModel().
                    {
         initializeIfNecessary();
         return useTorusFlag;
     };
Member Data Documentation
long BaseWorldUtility::airFrameId protected
Provides a unique number for AirFrames per simulation.
Definition at line 51 of file BaseWorldUtility.h.
Referenced by initializeIfNecessary().
bool BaseWorldUtility::isInitialized protected
Stores if members are already initialized.
Definition at line 54 of file BaseWorldUtility.h.
Referenced by initializeIfNecessary().
Coord BaseWorldUtility::playgroundSize protected
Size of the area the nodes are in (in meters)
Note: The playground is in the range [0, playground size]. Meaning the upper borders (at pg-size) as well as the lower borders (at 0) are part of the playground.
Definition at line 42 of file BaseWorldUtility.h.
Referenced by getRandomPosition(), and initializeIfNecessary().
const double BaseWorldUtility::speedOfLight = 299792458.0 static
Speed of light in meters per second.
meters per second
Definition at line 58 of file BaseWorldUtility.h.
Referenced by ConnectionManager::calcInterfDist(), SimplePathlossModel::calcPathloss(), Veins::ChannelAccess::calculatePropagationDelay(), SimplePathlossModel::filterSignal(), SimplePathlossConstMapping::getValue(), JakesFadingMapping::getValue(), and TwoRayInterferenceModel::Mapping::getValue().
bool BaseWorldUtility::use2DFlag protected
Should the world be 2-dimensional?
Definition at line 48 of file BaseWorldUtility.h.
Referenced by getRandomPosition(), and initializeIfNecessary().
bool BaseWorldUtility::useTorusFlag protected
Should the playground be treatend as a torus?
Definition at line 45 of file BaseWorldUtility.h.
Referenced by initializeIfNecessary().
The documentation for this class was generated from the following files:
BaseWorldUtility.h
BaseWorldUtility.cc