Veins Framework: BaseMobility Class Reference
BaseMobility Class Reference
Base module for all mobility modules.
#include <BaseMobility.h>
Public Types
enum BorderPolicy { REFLECT, WRAP, PLACERANDOMLY, RAISEERROR }
Selects how a node should behave if it reaches the edge of the playground.
enum BaseMobilityMsgKinds { MOVE_HOST = 21311, MOVE_TO_BORDER, LAST_BASE_MOBILITY_KIND }
The kind field of messages.
enum BorderHandling {
NOWHERE, X_SMALLER, X_BIGGER, Y_SMALLER,
Y_BIGGER, Z_SMALLER, Z_BIGGER
}
Specifies which border actually has been reached.
Public Member Functions
BaseMobility ()
BaseMobility (unsigned stacksize)
virtual void handleMessage (cMessage *msg)
This modules should only receive self-messages.
virtual void initialize (int)
Initializes mobility model parameters.
virtual void finish ()
Delete dynamically allocated objects.
virtual Coord getCurrentPosition () const
Returns the current position at the current simulation time.
virtual Coord getCurrentSpeed () const
Returns the current speed at the current simulation time.
Public Member Functions inherited from Veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from BaseModule
BaseModule ()
Function to get the logging name of id.
BaseModule (unsigned stacksize)
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed.
Protected Member Functions
virtual int iconSizeTagToSize (const char *tag)
Maps the passed icon size tag (is) to an actual size in pixels.
virtual const char * iconSizeToTag (double size)
Maps the passed size in pixels to an appropriate icon size tag (is).
virtual void handleSelfMsg (cMessage *)
Called upon arrival of a self messages.
virtual void handleBorderMsg (cMessage *)
Called upon arrival of a border messages.
virtual void makeMove ()
Moves the host.
virtual void updatePosition ()
Update the position information for this node.
double playgroundSizeX () const
Returns the width of the playground.
double playgroundSizeY () const
Returns the height of the playground.
double playgroundSizeZ () const
Returns the height of the playground.
Coord getRandomPosition ()
Random position somewhere in the playground.
Border handling
Utility functions to handle hosts that move outside the playground
bool handleIfOutside (BorderPolicy, Coord &, Coord &, Coord &, double &)
Main border handling function.
virtual void fixIfHostGetsOutside ()
Should be redefined in subclasses.
BorderHandling checkIfOutside (Coord, Coord &)
Checks whether the host is outside the playground and returns where.
void goToBorder (BorderPolicy, BorderHandling, Coord &, Coord &)
calculate the step to reach the border
void reflectCoordinate (BorderHandling border, Coord &c)
helperfunction for reflectIfOutside() to reflect a Coordinate at a given border
void reflectIfOutside (BorderHandling, Coord &, Coord &, Coord &, double &)
Utility function to reflect the node if it goes outside the playground.
void wrapIfOutside (BorderHandling, Coord &, Coord &)
Utility function to wrap the node to the opposite edge (torus) if it goes outside the playground.
void placeRandomlyIfOutside (Coord &)
Utility function to place the node randomly if it goes outside the playground.
Protected Member Functions inherited from Veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
Protected Attributes
BaseWorldUtility * world
Pointer to BaseWorldUtility – these two must know each other.
Move move
Stores the current position and move pattern of the host.
simtime_t updateInterval
Time interval (in seconds) to update the hosts position.
cMessage * moveMsg
Self message to trigger movement.
bool coreDebug
debug this core module?
bool scaleNodeByDepth
Enable depth dependent scaling of nodes when 3d and tkenv is used.
double playgroundScaleX
Scaling of the playground in X direction.
double playgroundScaleY
Scaling of the playground in Y direction.
double origDisplayWidth
The original width the node is displayed width.
double origDisplayHeight
The original height the node is displayed width.
double origIconSize
The original size of the icon of the node.
Protected Attributes inherited from Veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from BaseModule
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Static Protected Attributes
static const simsignalwrap_t mobilityStateChangedSignal = simsignalwrap_t(MIXIM_SIGNAL_MOBILITY_CHANGE_NAME)
Store the category of HostMove.
Static Protected Attributes inherited from BaseModule
static const simsignalwrap_t catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME)
Stores the category of the HostState.
Detailed Description
Base module for all mobility modules.
It does not provide mobility at all, so you can use it if you only want to simulate static networks.
BaseMobility provides random placement of hosts and display updates. Change notifications about position changes are also posted to the Blackboard.
Another service provided by BaseMobility is border handling. If a host wants to move outside the playground, this situation has to be handled somehow. BaseMobility provides handling for the 4 most common ways for that: reflection, wrapping, random placement and raising an error. The only thing you have to do is to specify your desired border handling in fixIfHostGetsOutside and call it in makeMove.
For most mobility modules the only two functions you need to implement to define your own mobility module are makeMove and fixIfHostGetsOutside..
This file contains 3D implementations from Michael Swigulski.
Author
Daniel Willkomm, Andras Varga
Definition at line 63 of file BaseMobility.h.
Member Enumeration Documentation
enum BaseMobility::BaseMobilityMsgKinds
The kind field of messages.
that are used internally by this class have one of these values
Enumerator
MOVE_HOST
MOVE_TO_BORDER
LAST_BASE_MOBILITY_KIND
Stores the id on which classes extending BaseMobility should continue their own kinds.
Definition at line 84 of file BaseMobility.h.
{
         MOVE_HOST = 21311,
         MOVE_TO_BORDER,
                 LAST_BASE_MOBILITY_KIND,
     };
enum BaseMobility::BorderHandling
Specifies which border actually has been reached.
Enumerator
NOWHERE
not outside the playground
X_SMALLER
x smaller than 0
X_BIGGER
x bigger or equal than playground size
Y_SMALLER
y smaller than 0
Y_BIGGER
y bigger or equal than playground size
Z_SMALLER
z smaller than 0
Z_BIGGER
z bigger or equal than playground size
Definition at line 95 of file BaseMobility.h.
{
         NOWHERE,
         X_SMALLER,
                 X_BIGGER,
                 Y_SMALLER,
                 Y_BIGGER,
                 Z_SMALLER,
                 Z_BIGGER
     };
enum BaseMobility::BorderPolicy
Selects how a node should behave if it reaches the edge of the playground.
See Also
handleIfOutside()
Enumerator
REFLECT
reflect off the wall
WRAP
reappear at the opposite edge (torus)
PLACERANDOMLY
placed at a randomly chosen position on the playground
RAISEERROR
stop the simulation with error
Definition at line 72 of file BaseMobility.h.
                       {
         REFLECT,
         WRAP,
         PLACERANDOMLY,
         RAISEERROR
     };
Constructor & Destructor Documentation
BaseMobility::BaseMobility ()
Definition at line 47 of file BaseMobility.cc.
                           :
                 BatteryAccess(),
                 move(),
                 playgroundScaleX(1),
                 playgroundScaleY(1),
                 origDisplayWidth(0),
                 origDisplayHeight(0),
                 origIconSize(0)
 {}
BaseMobility::BaseMobility (unsigned stacksize)
Definition at line 57 of file BaseMobility.cc.
                                             :
                 BatteryAccess(stacksize),
                 move(),
                 playgroundScaleX(1),
                 playgroundScaleY(1),
                 origDisplayWidth(0),
                 origDisplayHeight(0),
                 origIconSize(0)
 {}
Member Function Documentation
BaseMobility::BorderHandling BaseMobility::checkIfOutside (Coord targetPos, Coord & borderStep) protected
Checks whether the host is outside the playground and returns where.
Checks whether the host moved outside and return the border it crossed.
Additionally the calculation of the step to reach the border is started.
Definition at line 454 of file BaseMobility.cc.
Referenced by handleIfOutside().
 {
     BorderHandling outside = NOWHERE;
     // Testing x-value
     if (targetPos.x < 0){
                 borderStep.x = (-move.getStartPos().x);
                 outside = X_SMALLER;
     }
     else if (targetPos.x >= playgroundSizeX()){
         borderStep.x = (playgroundSizeX() - move.getStartPos().x);
         outside = X_BIGGER;
     }
     // Testing y-value
     if (targetPos.y < 0){
         borderStep.y = (-move.getStartPos().y);
                 if( outside == NOWHERE
                         || fabs(borderStep.x/move.getDirection().x)
                            > fabs(borderStep.y/move.getDirection().y) )
                 {
                         outside = Y_SMALLER;
                 }
     }
     else if (targetPos.y >= playgroundSizeY()){
         borderStep.y = (playgroundSizeY() - move.getStartPos().y);
                 if( outside == NOWHERE
                         || fabs(borderStep.x/move.getDirection().x)
                            > fabs(borderStep.y/move.getDirection().y) )
                 {
                         outside = Y_BIGGER;
                 }
     }
     // Testing z-value
     if (!world->use2D())
     {
             // going to reach the lower z-border
         if (targetPos.z < 0)
             {
                 borderStep.z = (-move.getStartPos().z);
                 // no border reached so far
                 if( outside==NOWHERE )
                 {
                         outside = Z_SMALLER;
                 }
                 // an y-border is reached earliest so far, test whether z-border
                 // is reached even earlier
                 else if( (outside == Y_SMALLER || outside == Y_BIGGER)
                                  && fabs(borderStep.y/move.getDirection().y)
                                     > fabs(borderStep.z/move.getDirection().z) )
                 {
                         outside = Z_SMALLER;
                 }
                 // an x-border is reached earliest so far, test whether z-border
                 // is reached even earlier
                 else if( (outside == X_SMALLER || outside == X_BIGGER)
                                  && fabs(borderStep.x/move.getDirection().x)
                                     > fabs(borderStep.z/move.getDirection().z) )
                 {
                         outside = Z_SMALLER;
                 }
             }
         // going to reach the upper z-border
             else if (targetPos.z >= playgroundSizeZ())
             {
                 borderStep.z = (playgroundSizeZ() - move.getStartPos().z);
                 // no border reached so far
                 if( outside==NOWHERE )
                 {
                         outside = Z_BIGGER;
                 }
                 // an y-border is reached earliest so far, test whether z-border
                 // is reached even earlier
                 else if( (outside==Y_SMALLER || outside==Y_BIGGER)
                                  && fabs(borderStep.y/move.getDirection().y)
                                     > fabs(borderStep.z/move.getDirection().z) )
                 {
                         outside = Z_BIGGER;
                 }
                 // an x-border is reached earliest so far, test whether z-border
                 // is reached even earlier
                 else if( (outside==X_SMALLER || outside==X_BIGGER)
                                   && fabs(borderStep.x/move.getDirection().x)
                                      > fabs(borderStep.z/move.getDirection().z) )
                 {
                         outside = Z_BIGGER;
                 }
             }
     }
     coreEV << "checkIfOutside, outside="<<outside<<" borderStep: " << borderStep.info() << endl;
     return outside;
 }
virtual void BaseMobility::finish () inline virtual
Delete dynamically allocated objects.
Reimplemented in Veins::TraCIMobility.
Definition at line 170 of file BaseMobility.h.
 {};
virtual void BaseMobility::fixIfHostGetsOutside () inline protected virtual
Should be redefined in subclasses.
Should invoke handleIfOutside() and pass the references to the parameters to be modified.
Additional action after border handling (such as choosing a new target position if the BorderPolicy is PLACERANDOMLY) should be implemented here.
See Also
HandleIfOutside
Reimplemented in Veins::TraCIMobility.
Definition at line 308 of file BaseMobility.h.
Referenced by handleBorderMsg().
{
         error("fixIfHostGetsOutside has to be redefined by the user");
     };
virtual Coord BaseMobility::getCurrentPosition () const inline virtual
Returns the current position at the current simulation time.
Definition at line 173 of file BaseMobility.h.
Referenced by default_veins_TraCI::handleParkingUpdate(), mfcv::handleParkingUpdate(), minicurso_UFPI_TraCI::handleParkingUpdate(), mfcv_rsu::onData(), minicurso_UFPI_TraCI_RSU::onData(), and default_veins_TraCI_RSU::onData().
{
         //return move.getPositionAt(stWhen);
         return move.getStartPos();
     }
virtual Coord BaseMobility::getCurrentSpeed () const inline virtual
Returns the current speed at the current simulation time.
Definition at line 179 of file BaseMobility.h.
{
         return move.getDirection() * move.getSpeed();
     }
Coord BaseMobility::getRandomPosition () inline protected
Random position somewhere in the playground.
DEPRECATED: Use BaseWorldUtility::getRandomPosition() instead
Definition at line 256 of file BaseMobility.h.
 { return world->getRandomPosition();}
void BaseMobility::goToBorder (BorderPolicy policy, BorderHandling wo, Coord & borderStep, Coord & borderStart) protected
calculate the step to reach the border
Calculate the step to reach the border. Additionally for the WRAP policy the new start position after reaching the border is calculated.
Definition at line 560 of file BaseMobility.cc.
Referenced by handleIfOutside().
 {
     double factor;
     coreEV << "goToBorder: startPos: " << move.getStartPos().info()
            << " borderStep: " << borderStep.info()
            << " BorderPolicy: " << policy
            << " BorderHandling: " << wo << endl;
     switch( wo ) {
     case X_SMALLER:
                 factor = borderStep.x / move.getDirection().x;
                 borderStep.y = (factor * move.getDirection().y);
                 if (!world->use2D())
                 {
                         borderStep.z = (factor * move.getDirection().z); // 3D case
                 }
                 if( policy == WRAP )
                 {
                         borderStart.x = (playgroundSizeX());
                         borderStart.y = (move.getStartPos().y + borderStep.y);
                         if (!world->use2D())
{
                                 borderStart.z = (move.getStartPos().z
                                                                  + borderStep.z); // 3D case
                         }
                 }
                 break;
     case X_BIGGER:
                 factor = borderStep.x / move.getDirection().x;
                 borderStep.y = (factor * move.getDirection().y);
                 if (!world->use2D())
                 {
                         borderStep.z = (factor * move.getDirection().z); // 3D case
                 }
                 if( policy == WRAP )
                 {
                         borderStart.x = (0);
                         borderStart.y = (move.getStartPos().y + borderStep.y);
                         if (!world->use2D())
{
                                 borderStart.z = (move.getStartPos().z
                                                                  + borderStep.z); // 3D case
                         }
                 }
                 break;
     case Y_SMALLER:
                 factor = borderStep.y / move.getDirection().y;
                 borderStep.x = (factor * move.getDirection().x);
                 if (!world->use2D())
                 {
                         borderStep.z = (factor * move.getDirection().z); // 3D case
                 }
                 if( policy == WRAP )
                 {
                         borderStart.y = (playgroundSizeY());
                         borderStart.x = (move.getStartPos().x + borderStep.x);
                         if (!world->use2D())
{
                                 borderStart.z = (move.getStartPos().z
                                                                  + borderStep.z); // 3D case
                         }
                 }
                 break;
     case Y_BIGGER:
                 factor = borderStep.y / move.getDirection().y;
                 borderStep.x = (factor * move.getDirection().x);
                 if (!world->use2D())
                 {
                         borderStep.z = (factor * move.getDirection().z); // 3D case
                 }
                 if( policy == WRAP )
                 {
                         borderStart.y = (0);
                         borderStart.x = (move.getStartPos().x + borderStep.x);
                         if (!world->use2D())
{
                                 borderStart.z = (move.getStartPos().z
                                                                  + borderStep.z); // 3D case
                         }
                 }
                 break;
     case Z_SMALLER: // here we are definitely in 3D
                 factor = borderStep.z / move.getDirection().z;
                 borderStep.x = (factor * move.getDirection().x);
                 borderStep.y = (factor * move.getDirection().y);
                 if( policy == WRAP )
                 {
                         borderStart.z = (playgroundSizeZ());
                         borderStart.x = (move.getStartPos().x + borderStep.x);
                         borderStart.y = (move.getStartPos().y + borderStep.y);
                 }
                 break;
     case Z_BIGGER: // here we are definitely in 3D
                 factor = borderStep.z / move.getDirection().z;
                 borderStep.x = (factor * move.getDirection().x);
                 borderStep.y = (factor * move.getDirection().y);
                 if( policy == WRAP )
                 {
                         borderStart.z = (0);
                         borderStart.x = (move.getStartPos().x + borderStep.x);
                         borderStart.y = (move.getStartPos().y + borderStep.y);
                 }
                 break;
     default:
         factor = 0;
         error("invalid state in goToBorder switch!");
         break;
     }
     coreEV << "goToBorder: startPos: " << move.getStartPos().info()
            << " borderStep: " << borderStep.info()
            << " borderStart: " << borderStart.info()
            << " factor: " << factor << endl;
 }
void BaseMobility::handleBorderMsg (cMessage * msg) protected virtual
Called upon arrival of a border messages.
The host actually reached the border, so the startPos and startTime has to be updated.
Additionally fixIfHostGetsOutside has to be called again to catch cases where the host moved in both (x and y) direction outside the playground.
Definition at line 240 of file BaseMobility.cc.
Referenced by handleMessage().
 {
     coreEV << "start MOVE_TO_BORDER:" << move.info() << endl;
     BorderMsg* bMsg = static_cast<BorderMsg*>(msg);
     switch( bMsg->getPolicy() ){
     case REFLECT:
                 move.setStart(bMsg->getStartPos());
                 move.setDirectionByVector(bMsg->getDirection());
                 break;
     case WRAP:
                 move.setStart(bMsg->getStartPos());
                 break;
     case PLACERANDOMLY:
                 move.setStart(bMsg->getStartPos());
                 coreEV << "new random position: " << move.getStartPos().info() << endl;
                 break;
     case RAISEERROR:
                 error("node moved outside the playground");
                 break;
     default:
         error("Unknown BorderPolicy!");
         break;
     }
     fixIfHostGetsOutside();
     updatePosition();
     delete bMsg;
     coreEV << "end MOVE_TO_BORDER:" << move.info() << endl;
 }
bool BaseMobility::handleIfOutside (BorderPolicy policy, Coord & stepTarget, Coord & targetPos, Coord & step, double & angle) protected
Main border handling function.
This function takes the BorderPolicy and all variables to be modified in case a border is reached and invokes the appropriate action. Pass dummy variables if you do not need them.
The supported border policies are REFLECT, WRAP, PLACERANDOMLY, and RAISEERROR.
The policy and stepTarget are mandatory parameters to pass. stepTarget is used to check whether the host actually moved outside the playground.
Additional parameters to pass (in case of non atomic movements) can be targetPos (the target the host is moving to) and step (the size of a step).
Angle is the direction in which the host is moving.
Parameters
policy BorderPolicy to use
stepTarget target position of the next step of the host
targetPos target position of the host (for non atomic movement)
step step size of the host (for non atomic movement)
angle direction in which the host is moving
Returns
true if host was outside, false otherwise.
Definition at line 691 of file BaseMobility.cc.
Referenced by Veins::TraCIMobility::fixIfHostGetsOutside().
 {
     // where did the host leave the playground?
     BorderHandling wo;
     // step to reach the border
     Coord borderStep;
     wo = checkIfOutside(stepTarget, borderStep);
     // just return if the next step is not outside the playground
     if( wo == NOWHERE )
         return false;
     coreEV << "handleIfOutside:stepTarget = " << stepTarget.info() << endl;
     // new start position after the host reaches the border
     Coord borderStart;
     // new direction the host has to move to
     Coord borderDirection;
     // time to reach the border
     simtime_t borderInterval;
     coreEV << "old values: stepTarget: " << stepTarget.info()
            << " step: " << step.info()
            << " targetPos: " << targetPos.info()
            << " angle: " << angle << endl;
     // which border policy is to be followed
     switch (policy){
     case REFLECT:
                 reflectIfOutside( wo, stepTarget, targetPos, step, angle );
                 break;
     case WRAP:
                 wrapIfOutside( wo, stepTarget, targetPos );
                 break;
     case PLACERANDOMLY:
                 placeRandomlyIfOutside( targetPos );
                 break;
     case RAISEERROR:
         break;
     }
     coreEV << "new values: stepTarget: " << stepTarget.info()
            << " step: " << step.info()
            << " angle: " << angle << endl;
     // calculate the step to reach the border
     goToBorder(policy, wo, borderStep, borderStart);
     // calculate the time to reach the border
     borderInterval = (borderStep.length()) / move.getSpeed();
     // calculate new start position
     // NOTE: for WRAP this is done in goToBorder
     switch( policy ){
     case REFLECT:
     {
         borderStart = move.getStartPos() + borderStep;
         double d = stepTarget.distance( borderStart );
                 borderDirection = (stepTarget - borderStart) / d;
                 break;
     }
     case PLACERANDOMLY:
                 borderStart = targetPos;
                 stepTarget = targetPos;
                 break;
     case WRAP:
     case RAISEERROR:
         break;
     default:
         error("unknown BorderPolicy");
         break;
     }
     coreEV << "border handled, borderStep: "<< borderStep.info()
            << "borderStart: " << borderStart.info()
            << " stepTarget " << stepTarget.info() << endl;
     // create a border self message and schedule it appropriately
     BorderMsg *bMsg = new BorderMsg("borderMove", MOVE_TO_BORDER);
     bMsg->setPolicy(policy);
     bMsg->setStartPos(borderStart);
     bMsg->setDirection(borderDirection);
     scheduleAt(simTime() + borderInterval, bMsg);
     return true;
 }
void BaseMobility::handleMessage (cMessage * msg) virtual
This modules should only receive self-messages.
Dispatches border messages to handleBorderMsg() and all other self-messages to handleSelfMsg()
Definition at line 211 of file BaseMobility.cc.
 {
     if (!msg->isSelfMessage())
         error("mobility modules can only receive self messages");
     if(msg->getKind() == MOVE_TO_BORDER){
         handleBorderMsg(msg);
     } else {
         handleSelfMsg(msg);
     }
 }
void BaseMobility::handleSelfMsg (cMessage * msg) protected virtual
Called upon arrival of a self messages.
The only self message possible is to indicate a new movement. If the host is stationary this function is never called.
every time a self message arrives makeMove is called to handle the movement. Afterward updatePosition updates the position with the display.
Reimplemented in Veins::TraCIMobility.
Definition at line 225 of file BaseMobility.cc.
Referenced by handleMessage().
 {
     makeMove();
     updatePosition();
     if( !moveMsg->isScheduled() && move.getSpeed() > 0) {
         scheduleAt(simTime() + updateInterval, msg);
     } else {
         delete msg;
         moveMsg = NULL;
     }
 }
int BaseMobility::iconSizeTagToSize (const char * tag) protected virtual
Maps the passed icon size tag (is) to an actual size in pixels.
Parameters
tag - the icon size tag to get the pixel size for
Returns
the size of the icon in pixels or -1 if the tag is unknown
Definition at line 177 of file BaseMobility.cc.
Referenced by initialize().
 {
         if(strcmp(tag, "vs") == 0) {
                 return 16;
         } else if(strcmp(tag, "s") == 0) {
                 return 24;
         } else if(strcmp(tag, "n") == 0 || strcmp(tag, "") == 0) {
                 return 40;
         } else if(strcmp(tag, "l") == 0) {
                 return 60;
         } else if(strcmp(tag, "vl") == 0) {
                 return 100;
         }
         return -1;
 }
const char * BaseMobility::iconSizeToTag (double size) protected virtual
Maps the passed size in pixels to an appropriate icon size tag (is).
Parameters
size - the icon size to get an appropriate tag for
Returns
an icon size tag
Definition at line 194 of file BaseMobility.cc.
Referenced by updatePosition().
 {
         //returns the biggest icon smaller than the passed size (except sizes
         //smaller than the smallest icon
         if(size < 24) {
                 return "vs";
         } else if(size < 40) {
                 return "s";
         } else if(size < 60) {
                 return "n";
         } else if(size < 100) {
                 return "l";
         } else {
                 return "vl";
         }
 }
void BaseMobility::initialize (int stage) virtual
Initializes mobility model parameters.
Assigns a pointer to ConnectionManager and gets a pointer to its host.
Creates a random position for a host if the position is not given as a parameter in "omnetpp.ini".
Additionally the registration with ConnectionManager is done and it is assured that the position display string tag (p) exists and contains the exact (x) tag.
If the speed of the host is bigger than 0 a first MOVE_HOST self message is scheduled in stage 1
Reimplemented from BaseModule.
Reimplemented in Veins::TraCIMobility.
Definition at line 67 of file BaseMobility.cc.
Referenced by Veins::TraCIMobility::initialize().
 {
     BaseModule::initialize(stage);
     if (stage == 0){
         hasPar("coreDebug") ? coreDebug = par("coreDebug").boolValue() : coreDebug = false;
         coreEV << "initializing BaseMobility stage " << stage << endl;
         hasPar("scaleNodeByDepth") ? scaleNodeByDepth
                         = par("scaleNodeByDepth").boolValue()
                         : scaleNodeByDepth = true;
         // get utility pointers (world and host)
                 world = FindModule<BaseWorldUtility*>::findGlobalModule();
         if (world == NULL)
             error("Could not find BaseWorldUtility module");
         coreEV << "initializing BaseUtility stage " << stage << endl; // for node position
         if (hasPar("updateInterval")) {
                 updateInterval = par("updateInterval");
         } else {
             updateInterval = 0;
         }
                 // initialize Move parameter
         bool use2D = world->use2D();
         //initalize position with random values
         Coord pos = world->getRandomPosition();
         //read coordinates from parameters if available
         double x = hasPar("x") ? par("x").doubleValue() : -1;
         double y = hasPar("y") ? par("y").doubleValue() : -1;
         double z = hasPar("z") ? par("z").doubleValue() : -1;
         //set position with values from parameters if available
         if(x > -1) pos.x = x;
         if(y > -1) pos.y = y;
         if(!use2D && z > -1) pos.z = z;
         // set start-position and start-time (i.e. current simulation-time) of the Move
         move.setStart(pos);
                 coreEV << "start pos: " << move.getStartPos().info() << endl;
         //check whether position is within the playground
         if (!isInBoundary(move.getStartPos(), Coord::ZERO, *world->getPgs())) {
             error("node position specified in omnetpp.ini exceeds playgroundsize");
         }
         // set speed and direction of the Move
         move.setSpeed(0);
         move.setDirectionByVector(Coord::ZERO);
     }
     else if (stage == 1){
         coreEV << "initializing BaseMobility stage " << stage << endl;
         //get playground scaling
         if (world->getParentModule() != NULL )
         {
                 const cDisplayString& dispWorldOwner
                                         = world->getParentModule()->getDisplayString();
                 if( dispWorldOwner.containsTag("bgb") )
{
                         double origPGWidth = 0.0;
                         double origPGHeight= 0.0;
                         // normally this should be equal to playground size
                                 std::istringstream(dispWorldOwner.getTagArg("bgb", 0))
                                                 >> origPGWidth;
                                 std::istringstream(dispWorldOwner.getTagArg("bgb", 1))
                                                 >> origPGHeight;
                                 //bgb of zero means size isn't set manually
                                 if(origPGWidth > 0) {
                                         playgroundScaleX = origPGWidth / playgroundSizeX();
                                 }
                                 if(origPGHeight > 0) {
                                         playgroundScaleY = origPGHeight / playgroundSizeY();
                                 }
                         }
         }
         //get original display of host
                 cDisplayString& disp = findHost()->getDisplayString();
         //get host width and height
                 if (disp.containsTag("b")) {
                         std::istringstream(disp.getTagArg("b", 0)) >> origDisplayWidth;
                         std::istringstream(disp.getTagArg("b", 1)) >> origDisplayHeight;
                 }
                 //get hosts icon size
                 if (disp.containsTag("i")) {
                         // choose a appropriate icon size (only if a icon is specified)
                         origIconSize = iconSizeTagToSize(disp.getTagArg("is", 0));
                 }
         // print new host position on the screen and update bb info
         updatePosition();
         if (move.getSpeed() > 0 && updateInterval > 0)
         {
                 coreEV << "Host is moving, speed=" << move.getSpeed() << " updateInterval=" << updateInterval << endl;
                 moveMsg = new cMessage("move", MOVE_HOST);
                 //host moves the first time after some random delay to avoid synchronized movements
             scheduleAt(simTime() + uniform(0, updateInterval), moveMsg);
         }
     }
 }
virtual void BaseMobility::makeMove () inline protected virtual
Moves the host.
This function is called every time a MOVE_HOST self message arrives. Here you can define the movement pattern for your host.
You should call fixIfHostGetsOutside here for border handling
Definition at line 231 of file BaseMobility.h.
Referenced by handleSelfMsg().
{
         error("BaseMobility does not move the host");
     };
void BaseMobility::placeRandomlyIfOutside (Coord & targetPos) protected
Utility function to place the node randomly if it goes outside the playground.
Start the host at a new random position. Here the target position is set to the new start position.
You have to define a new target postion in fixIfHostGetsOutside to keep the host moving.
Definition at line 447 of file BaseMobility.cc.
Referenced by handleIfOutside().
 {
     targetPos = world->getRandomPosition();
 }
double BaseMobility::playgroundSizeX () const inline protected
Returns the width of the playground.
Definition at line 247 of file BaseMobility.h.
Referenced by checkIfOutside(), Veins::TraCIMobility::fixIfHostGetsOutside(), goToBorder(), initialize(), reflectCoordinate(), and wrapIfOutside().
 {return world->getPgs()->x;}
double BaseMobility::playgroundSizeY () const inline protected
Returns the height of the playground.
Definition at line 250 of file BaseMobility.h.
Referenced by checkIfOutside(), Veins::TraCIMobility::fixIfHostGetsOutside(), goToBorder(), initialize(), reflectCoordinate(), and wrapIfOutside().
 {return world->getPgs()->y;}
double BaseMobility::playgroundSizeZ () const inline protected
Returns the height of the playground.
Definition at line 253 of file BaseMobility.h.
Referenced by checkIfOutside(), Veins::TraCIMobility::fixIfHostGetsOutside(), goToBorder(), reflectCoordinate(), updatePosition(), and wrapIfOutside().
 {return world->getPgs()->z;}
void BaseMobility::reflectCoordinate (BorderHandling border, Coord & c) protected
helperfunction for reflectIfOutside() to reflect a Coordinate at a given border
Helper function for BaseMobility::reflectIfOutside().
Reflects a given coordinate according to the given BorderHandling.
Definition at line 351 of file BaseMobility.cc.
Referenced by reflectIfOutside().
 {
     switch( border ) {
     case X_SMALLER:
         c.x = (-c.x);
             break;
     case X_BIGGER:
         c.x = (2 * playgroundSizeX() - c.x);
             break;
     case Y_SMALLER:
         c.y = (-c.y);
             break;
     case Y_BIGGER:
         c.y = (2 * playgroundSizeY() - c.y);
         break;
     case Z_SMALLER:
         c.z = (-c.z);
         break;
     case Z_BIGGER:
         c.z = (2 * playgroundSizeZ() - c.z);
             break;
     case NOWHERE:
     default:
             error("wrong border handling case!");
             break;
     }
 }
void BaseMobility::reflectIfOutside (BorderHandling wo, Coord & stepTarget, Coord & targetPos, Coord & step, double & angle) protected
Utility function to reflect the node if it goes outside the playground.
Reflects the host from the playground border.
This function can update the target position, the step (for non atomic movements) and the angle.
Parameters
wo defines the border at which to reflect
stepTarget target position of the current step of the host
targetPos target position of the host (for non atomic movements)
step step size and direction of the host (for non atomic movements)
angle direction to which the host is moving
Definition at line 383 of file BaseMobility.cc.
Referenced by handleIfOutside().
{
     reflectCoordinate(wo, targetPos);
     reflectCoordinate(wo, stepTarget);
     switch( wo ) {
     case X_SMALLER:
     case X_BIGGER:
         step.x = (-step.x);
             angle = 180 - angle;
             break;
     case Y_SMALLER:
     case Y_BIGGER:
         step.y = (-step.y);
             angle = -angle;
             break;
     case Z_SMALLER:
     case Z_BIGGER:
         step.z = (-step.z);
             angle = -angle;
             break;
     case NOWHERE:
     default:
             error("wrong border handling case!");
             break;
     }
 }
void BaseMobility::updatePosition () protected virtual
Update the position information for this node.
This function tells the Blackboard that the position has changed, and it also moves the host's icon to the new position on the screen.
This function has to be called every time the position of the host changes!
Definition at line 281 of file BaseMobility.cc.
Referenced by Veins::TraCIMobility::changePosition(), handleBorderMsg(), handleSelfMsg(), and initialize().
{
     EV << "updatePosition: " << move.info() << endl;
     //publish the the new move
     emit(mobilityStateChangedSignal, this);
     if(ev.isGUI())
     {
         std::ostringstream osDisplayTag;
 #ifdef __APPLE__
         const int          iPrecis        = 0;
 #else
         const int          iPrecis        = 5;
 #endif
         cDisplayString&    disp           = findHost()->getDisplayString();
         // setup output stream
         osDisplayTag << std::fixed; osDisplayTag.precision(iPrecis);
         if (playgroundScaleX != 1.0) {
                 osDisplayTag << (move.getStartPos().x * playgroundScaleX);
         }
         else {
                 osDisplayTag << (move.getStartPos().x);
         }
                 disp.setTagArg("p", 0, osDisplayTag.str().data());
                 osDisplayTag.str(""); // reset
         if (playgroundScaleY != 1.0) {
                 osDisplayTag << (move.getStartPos().y * playgroundScaleY);
         }
         else {
                 osDisplayTag << (move.getStartPos().y);
         }
                 disp.setTagArg("p", 1, osDisplayTag.str().data());
         if(!world->use2D() && scaleNodeByDepth)
         {
                 const double minScale = 0.25;
                 const double maxScale = 1.0;
                 //scale host dependent on their z coordinate to simulate a depth
                 //effect
                         //z-coordinate of zero maps to a scale of maxScale (very close)
                         //z-coordinate of playground size z maps to size of minScale (far away)
                 double depthScale = minScale
                                             + (maxScale - minScale)
                                               * (1.0 - move.getStartPos().z
                                                        / playgroundSizeZ());
                 if (origDisplayWidth > 0.0 && origDisplayHeight > 0.0) {
                                 osDisplayTag.str(""); // reset
                                 osDisplayTag << (origDisplayWidth * depthScale);
                                 disp.setTagArg("b", 0, osDisplayTag.str().data());
                                 osDisplayTag.str(""); // reset
                                 osDisplayTag << (origDisplayHeight * depthScale);
                                 disp.setTagArg("b", 1, osDisplayTag.str().data());
                         }
                 if (origIconSize > 0) {
                         // choose a appropriate icon size (only if a icon is specified)
                                 disp.setTagArg("is", 0,
                                                iconSizeToTag(origIconSize * depthScale));
                 }
         }
     }
 }
void BaseMobility::wrapIfOutside (BorderHandling wo, Coord & stepTarget, Coord & targetPos) protected
Utility function to wrap the node to the opposite edge (torus) if it goes outside the playground.
Wraps the host to the other playground size. Updates the target position.
Parameters
wo defines the border at which to reflect
stepTarget target position of the current step of the host
targetPos target position of the host (for non atomic movements)
Definition at line 418 of file BaseMobility.cc.
Referenced by handleIfOutside().
{
     switch( wo ) {
     case X_SMALLER:
     case X_BIGGER:
         targetPos.x = (FWMath::modulo(targetPos.x, playgroundSizeX()));
         stepTarget.x = (FWMath::modulo(stepTarget.x, playgroundSizeX()));
             break;
     case Y_SMALLER:
     case Y_BIGGER:
         targetPos.y = (FWMath::modulo(targetPos.y, playgroundSizeY()));
         stepTarget.y = (FWMath::modulo(stepTarget.y, playgroundSizeY()));
             break;
     case Z_SMALLER:
     case Z_BIGGER:
         targetPos.z = (FWMath::modulo(targetPos.z, playgroundSizeZ()));
         stepTarget.z = (FWMath::modulo(stepTarget.z, playgroundSizeZ()));
             break;
     case NOWHERE:
     default:
             error("wrong border handling case!");
             break;
     }
 }
Member Data Documentation
bool BaseMobility::coreDebug protected
debug this core module?
Definition at line 123 of file BaseMobility.h.
Referenced by initialize().
const simsignalwrap_t BaseMobility::mobilityStateChangedSignal = simsignalwrap_t(MIXIM_SIGNAL_MOBILITY_CHANGE_NAME) static protected
Store the category of HostMove.
Definition at line 114 of file BaseMobility.h.
Referenced by updatePosition().
Move BaseMobility::move protected
Stores the current position and move pattern of the host.
Definition at line 111 of file BaseMobility.h.
Referenced by Veins::TraCIMobility::changePosition(), checkIfOutside(), Veins::TraCIMobility::fixIfHostGetsOutside(), Veins::TraCIMobility::getPositionAt(), goToBorder(), handleBorderMsg(), handleIfOutside(), handleSelfMsg(), Veins::TraCIMobility::initialize(), initialize(), Veins::TraCIMobility::preInitialize(), and updatePosition().
cMessage* BaseMobility::moveMsg protected
Self message to trigger movement.
Definition at line 120 of file BaseMobility.h.
Referenced by handleSelfMsg(), and initialize().
double BaseMobility::origDisplayHeight protected
The original height the node is displayed width.
Definition at line 137 of file BaseMobility.h.
Referenced by initialize(), and updatePosition().
double BaseMobility::origDisplayWidth protected
The original width the node is displayed width.
Definition at line 135 of file BaseMobility.h.
Referenced by initialize(), and updatePosition().
double BaseMobility::origIconSize protected
The original size of the icon of the node.
Definition at line 140 of file BaseMobility.h.
Referenced by initialize(), and updatePosition().
double BaseMobility::playgroundScaleX protected
Scaling of the playground in X direction.
Definition at line 130 of file BaseMobility.h.
Referenced by initialize(), and updatePosition().
double BaseMobility::playgroundScaleY protected
Scaling of the playground in Y direction.
Definition at line 132 of file BaseMobility.h.
Referenced by initialize(), and updatePosition().
bool BaseMobility::scaleNodeByDepth protected
Enable depth dependent scaling of nodes when 3d and tkenv is used.
Definition at line 127 of file BaseMobility.h.
Referenced by initialize(), and updatePosition().
simtime_t BaseMobility::updateInterval protected
Time interval (in seconds) to update the hosts position.
Definition at line 117 of file BaseMobility.h.
Referenced by Veins::TraCIMobility::changePosition(), handleSelfMsg(), and initialize().
BaseWorldUtility* BaseMobility::world protected
Pointer to BaseWorldUtility – these two must know each other.
Definition at line 108 of file BaseMobility.h.
Referenced by checkIfOutside(), Veins::TraCIMobility::fixIfHostGetsOutside(), goToBorder(), initialize(), placeRandomlyIfOutside(), and updatePosition().
The documentation for this class was generated from the following files:
BaseMobility.h
BaseMobility.cc