Veins Framework: FloodingMessage Class Reference
FloodingMessage Class Reference
Class generated from modules/messages/FloodingMessage.msg:10 by nedtool.
#include <FloodingMessage_m.h>
Public Member Functions
FloodingMessage (const char *name=NULL, int kind=0)
FloodingMessage (const FloodingMessage &other)
virtual ~FloodingMessage ()
FloodingMessage & operator= (const FloodingMessage &other)
virtual FloodingMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned int getSrcAddr () const
virtual void setSrcAddr (unsigned int srcAddr)
virtual unsigned int getMsgId () const
virtual void setMsgId (unsigned int msgId)
Public Member Functions inherited from WaveShortMessage
WaveShortMessage (const char *name=NULL, int kind=0)
WaveShortMessage (const WaveShortMessage &other)
virtual ~WaveShortMessage ()
WaveShortMessage & operator= (const WaveShortMessage &other)
virtual int getWsmVersion () const
virtual void setWsmVersion (int wsmVersion)
virtual int getSecurityType () const
virtual void setSecurityType (int securityType)
virtual int getChannelNumber () const
virtual void setChannelNumber (int channelNumber)
virtual int getDataRate () const
virtual void setDataRate (int dataRate)
virtual int getPriority () const
virtual void setPriority (int priority)
virtual int getPsid () const
virtual void setPsid (int psid)
virtual const char * getPsc () const
virtual void setPsc (const char *psc)
virtual int getWsmLength () const
virtual void setWsmLength (int wsmLength)
virtual const char * getWsmData () const
virtual void setWsmData (const char *wsmData)
virtual int getSerial () const
virtual void setSerial (int serial)
virtual Coord & getSenderPos ()
virtual const Coord & getSenderPos () const
virtual void setSenderPos (const Coord &senderPos)
virtual simtime_t getTimestamp () const
virtual void setTimestamp (simtime_t timestamp)
virtual unsigned int getSenderAddress () const
virtual void setSenderAddress (unsigned int senderAddress)
virtual unsigned int getRecipientAddress () const
virtual void setRecipientAddress (unsigned int recipientAddress)
virtual const char * getSource () const
virtual void setSource (const char *source)
virtual const char * getTarget () const
virtual void setTarget (const char *target)
virtual bool getSummaryVector () const
virtual void setSummaryVector (bool summaryVector)
virtual bool getRequestMessages () const
virtual void setRequestMessages (bool requestMessages)
virtual const char * getGlobalMessageIdentificaton () const
virtual void setGlobalMessageIdentificaton (const char *globalMessageIdentificaton)
virtual const char * getLocalMessageIdentificaton () const
virtual void setLocalMessageIdentificaton (const char *localMessageIdentificaton)
virtual unsigned int getHopCount () const
virtual void setHopCount (unsigned int hopCount)
virtual bool getAckRequest () const
virtual void setAckRequest (bool ackRequest)
virtual const char * getRoadId () const
virtual void setRoadId (const char *roadId)
virtual double getSenderSpeed () const
virtual void setSenderSpeed (double senderSpeed)
virtual unsigned short getCategory () const
virtual void setCategory (unsigned short category)
virtual int getVehicleId () const
virtual void setVehicleId (int vehicleId)
virtual unsigned short getHeading () const
virtual void setHeading (unsigned short heading)
virtual Coord & getTargetPos ()
virtual const Coord & getTargetPos () const
virtual void setTargetPos (const Coord &TargetPos)
virtual Coord & getSenderPosBack ()
virtual const Coord & getSenderPosBack () const
virtual void setSenderPosBack (const Coord &senderPosBack)
virtual simtime_t getMessageTimestampGenerate () const
virtual void setMessageTimestampGenerate (simtime_t messageTimestampGenerate)
Protected Member Functions
bool operator== (const FloodingMessage &)
Protected Member Functions inherited from WaveShortMessage
bool operator== (const WaveShortMessage &)
Protected Attributes
unsigned int srcAddr_var
unsigned int msgId_var
Protected Attributes inherited from WaveShortMessage
int wsmVersion_var
int securityType_var
int channelNumber_var
int dataRate_var
int priority_var
int psid_var
opp_string psc_var
int wsmLength_var
opp_string wsmData_var
int serial_var
Coord senderPos_var
simtime_t timestamp_var
unsigned int senderAddress_var
unsigned int recipientAddress_var
opp_string source_var
opp_string target_var
bool summaryVector_var
bool requestMessages_var
opp_string globalMessageIdentificaton_var
opp_string localMessageIdentificaton_var
unsigned int hopCount_var
bool ackRequest_var
opp_string roadId_var
double senderSpeed_var
unsigned short category_var
int vehicleId_var
unsigned short heading_var
Coord TargetPos_var
Coord senderPosBack_var
simtime_t messageTimestampGenerate_var
Private Member Functions
void copy (const FloodingMessage &other)
Detailed Description
Class generated from modules/messages/FloodingMessage.msg:10 by nedtool.
message FloodingMessage extends WaveShortMessage
{
    unsigned int srcAddr;
    unsigned int msgId;
    // TODO
}
Definition at line 34 of file FloodingMessage_m.h.
Constructor & Destructor Documentation
FloodingMessage::FloodingMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
FloodingMessage::FloodingMessage (const FloodingMessage & other)
virtual FloodingMessage::~FloodingMessage () virtual
Member Function Documentation
void FloodingMessage::copy (const FloodingMessage & other) private
virtual FloodingMessage* FloodingMessage::dup () const inline virtual
Reimplemented from WaveShortMessage.
Definition at line 52 of file FloodingMessage_m.h.
 {return new FloodingMessage(*this);}
virtual unsigned int FloodingMessage::getMsgId () const virtual
virtual unsigned int FloodingMessage::getSrcAddr () const virtual
FloodingMessage& FloodingMessage::operator= (const FloodingMessage & other)
bool FloodingMessage::operator== (const FloodingMessage &) protected
virtual void FloodingMessage::parsimPack (cCommBuffer * b) virtual
Reimplemented from WaveShortMessage.
Referenced by doPacking().
virtual void FloodingMessage::parsimUnpack (cCommBuffer * b) virtual
Reimplemented from WaveShortMessage.
Referenced by doUnpacking().
virtual void FloodingMessage::setMsgId (unsigned int msgId) virtual
Referenced by Flooding::generateMessage(), and AdvancedFlooding::generateMessage().
virtual void FloodingMessage::setSrcAddr (unsigned int srcAddr) virtual
Member Data Documentation
unsigned int FloodingMessage::msgId_var protected
Definition at line 38 of file FloodingMessage_m.h.
unsigned int FloodingMessage::srcAddr_var protected
Definition at line 37 of file FloodingMessage_m.h.
The documentation for this class was generated from the following file:
FloodingMessage_m.h