Veins Framework: Dimension Class Reference
Dimension Class Reference
Specifies a dimension for mappings (like time, frequency, etc.)
#include <MappingBase.h>
Public Types
typedef std::map< std::string,
int > DimensionIDMap
Type for map from dimension name to ID.
typedef DimensionIDMap::key_type DimensionNameType
typedef DimensionIDMap::mapped_type DimensionIdType
Public Member Functions
Dimension ()
Dimension (const DimensionNameType &name)
Creates a new dimension instance representing the dimension with the passed name.
bool operator== (const Dimension &other) const
Returns true if the ids of the two dimensions are equal.
bool operator< (const Dimension &other) const
Returns true if the id of the other dimension is greater then the id of this dimension.
bool operator<= (const Dimension &other) const
Sorting operator by dimension ID.
bool operator> (const Dimension &other) const
Sorting operator by dimension ID.
bool operator>= (const Dimension &other) const
Sorting operator by dimension ID.
bool operator!= (const Dimension &other) const
Sorting operator by dimension ID.
DimensionNameType getName () const
Returns the name of this dimension.
DimensionIdType getID () const
Returns the unique id of the dimension this instance represents.
Static Public Member Functions
static Dimension & time_static ()
Shortcut to the time Dimension, same as 'Dimension("time")', but spares the parsing of a string.
static Dimension & frequency_static ()
Shortcut to the frequency Dimension, same as 'Dimension("frequency")', but spares the parsing of a string.
Static Public Attributes
static const Dimension time = Dimension::time_static()
Shortcut to the time Dimension, same as 'Dimension("time")', but spares the parsing of a string.
static const Dimension frequency = Dimension::frequency_static()
Shortcut to the frequency Dimension, same as 'Dimension("frequency")', but spares the parsing of a string.
Protected Types
typedef std::map
< DimensionIdType,
DimensionNameType > DimensionNameMap
Type for map from ID to dimension name.
Static Protected Member Functions
static DimensionIDMap & dimensionIDs ()
stores the registered dimensions ids.
static DimensionNameMap & dimensionNames ()
ConstMapping from id to name of registered dimensions.
static DimensionIdType & nextFreeID ()
Stores the next free ID for a new dimension.
static int getDimensionID (const DimensionNameType &name)
Returns an instance of dimension which represents the dimension with the passed name.
Protected Attributes
DimensionIdType id
The unique id of the dimension this instance represents.
Friends
std::ostream & operator<< (std::ostream &out, const Dimension &d)
Output operator for a dimension.
Detailed Description
Specifies a dimension for mappings (like time, frequency, etc.)
The dimension is represented external by a string (like "time") and internally by an unique ID.
Note: Since the ID for a Dimensions is set the first time an instance of this dimensions is created and the id is used to provide a defined ordering of the Dimensions it DOES matter which dimensions are instantiated the first time. Only the time dimension will always have zero as unique id.
Author
Karl Wessel
Definition at line 31 of file MappingBase.h.
Member Typedef Documentation
typedef std::map<std::string, int> Dimension::DimensionIDMap
Type for map from dimension name to ID.
Definition at line 34 of file MappingBase.h.
typedef DimensionIDMap::mapped_type Dimension::DimensionIdType
Definition at line 36 of file MappingBase.h.
typedef std::map< DimensionIdType , DimensionNameType> Dimension::DimensionNameMap protected
Type for map from ID to dimension name.
Definition at line 40 of file MappingBase.h.
typedef DimensionIDMap::key_type Dimension::DimensionNameType
Definition at line 35 of file MappingBase.h.
Constructor & Destructor Documentation
Dimension::Dimension () inline
Definition at line 87 of file MappingBase.h.
Referenced by frequency_static(), and time_static().
                    :
                 id(0)
         {}
Dimension::Dimension (const DimensionNameType & name)
Creates a new dimension instance representing the dimension with the passed name.
Definition at line 63 of file MappingBase.cc.
         : id(getDimensionID(name))
 {}
Member Function Documentation
Dimension::DimensionIDMap & Dimension::dimensionIDs () static protected
stores the registered dimensions ids.
Uses "construct-on-first-use" idiom to ensure correct initialization of static members.
Definition at line 15 of file MappingBase.cc.
Referenced by getDimensionID().
{
         //use "construct-on-first-use" idiom to ensure correct order of
         //static initialization
         static DimensionIDMap* dimIDs = new DimensionIDMap();
         return *dimIDs;
 }
Dimension::DimensionNameMap & Dimension::dimensionNames () static protected
ConstMapping from id to name of registered dimensions.
Uses "construct-on-first-use" idiom to ensure correct initialization of static members.
Definition at line 22 of file MappingBase.cc.
Referenced by getDimensionID(), and getName().
{
         //use "construct-on-first-use" idiom to ensure correct order of
         //static initialization
         static DimensionNameMap* names = new DimensionNameMap();
         return *names;
 }
Dimension & Dimension::frequency_static () static
Shortcut to the frequency Dimension, same as 'Dimension("frequency")', but spares the parsing of a string.
This method should be used instead of the static "frequency" member when used during initialization of static variables since it assures the correct order of initialization.
Definition at line 36 of file MappingBase.cc.
Referenced by Decider80211p::calcChannelSenseRSSI(), Decider80211p::cca(), Decider80211p::checkIfSignalOk(), and Decider80211p::processNewSignal().
{
         static Dimension* freq = new Dimension("frequency");
         return *freq;
 }
Dimension::DimensionIdType Dimension::getDimensionID (const DimensionNameType & name) static protected
Returns an instance of dimension which represents the dimension with the passed name.
Definition at line 41 of file MappingBase.cc.
 {
         //get static members one time during initialization
         static DimensionIDMap&   dimensionIDs   = Dimension::dimensionIDs();
         static DimensionIdType&  nextFreeID     = Dimension::nextFreeID();
         static DimensionNameMap& dimensionNames = Dimension::dimensionNames();
         DimensionIDMap::iterator it             = dimensionIDs.lower_bound(name);
         if(it == dimensionIDs.end() || dimensionIDs.key_comp()(name, it->first)) {
                 DimensionIdType newID = 0;
                 //time gets its own id to make sure it has the smallest
                 if( dimensionIDs.key_comp()(name, "time") || dimensionIDs.key_comp()("time", name) )
                         newID = nextFreeID++;
                 it = dimensionIDs.insert(it, DimensionIDMap::value_type(name, newID));
                 dimensionNames[newID] = name;
         }
         return it->second;
 }
DimensionIdType Dimension::getID () const inline
Returns the unique id of the dimension this instance represents.
The id is used to uniquely identify dimensions as well as to provide a sorting of dimensions. Note: The "time"-dimension will always have the ID zero.
Definition at line 155 of file MappingBase.h.
 { return id; }
DimensionNameType Dimension::getName () const inline
Returns the name of this dimension.
Definition at line 142 of file MappingBase.h.
{
                 static DimensionNameMap& dimensionNames = Dimension::dimensionNames();
                 return dimensionNames.find(id)->second;
         }
Dimension::DimensionIdType & Dimension::nextFreeID () static protected
Stores the next free ID for a new dimension.
Uses "construct-on-first-use" idiom to ensure correct initialization of static members.
Definition at line 10 of file MappingBase.cc.
Referenced by getDimensionID().
{
         static Dimension::DimensionIdType* nextID = new Dimension::DimensionIdType(1);
         return *nextID;
 }
bool Dimension::operator!= (const Dimension & other) const inline
Sorting operator by dimension ID.
Definition at line 137 of file MappingBase.h.
 { return id != other.id; }
bool Dimension::operator< (const Dimension & other) const inline
Returns true if the id of the other dimension is greater then the id of this dimension.
This is needed to be able to use Dimension as a key in std::map.
Definition at line 128 of file MappingBase.h.
 { return id  < other.id; }
bool Dimension::operator<= (const Dimension & other) const inline
Sorting operator by dimension ID.
Definition at line 131 of file MappingBase.h.
 { return id <= other.id; }
bool Dimension::operator== (const Dimension & other) const inline
Returns true if the ids of the two dimensions are equal.
Definition at line 120 of file MappingBase.h.
 { return id == other.id; }
bool Dimension::operator> (const Dimension & other) const inline
Sorting operator by dimension ID.
Definition at line 133 of file MappingBase.h.
 { return id  > other.id; }
bool Dimension::operator>= (const Dimension & other) const inline
Sorting operator by dimension ID.
Definition at line 135 of file MappingBase.h.
 { return id >= other.id; }
Dimension & Dimension::time_static () static
Shortcut to the time Dimension, same as 'Dimension("time")', but spares the parsing of a string.
This method should be used instead of the static "time" member when used during initialization of static variables since it assures the correct order of initialization.
Definition at line 29 of file MappingBase.cc.
{
         //use "construct-on-first-use" idiom to ensure correct order of
         //static initialization
         static Dimension* time = new Dimension("time");
         return *time;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Dimension & d) friend
Output operator for a dimension.
Definition at line 158 of file MappingBase.h.
{
         return (out << d.getName() << "(" << d.id << ")");
     }
Member Data Documentation
const Dimension Dimension::frequency = Dimension::frequency_static() static
Shortcut to the frequency Dimension, same as 'Dimension("frequency")', but spares the parsing of a string.
Definition at line 84 of file MappingBase.h.
Referenced by BaseMacLayer::createSingleFrequencyMapping(), TwoRayInterferenceModel::filterSignal(), SimpleObstacleShadowing::filterSignal(), SimplePathlossModel::filterSignal(), SimplePathlossConstMapping::getValue(), and TwoRayInterferenceModel::Mapping::getValue().
DimensionIdType Dimension::id protected
The unique id of the dimension this instance represents.
Definition at line 73 of file MappingBase.h.
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
const Dimension Dimension::time = Dimension::time_static() static
Shortcut to the time Dimension, same as 'Dimension("time")', but spares the parsing of a string.
Definition at line 80 of file MappingBase.h.
Referenced by ConstMapping::ConstMapping(), MultiDimMapping< Linear >::copySubMappings(), SimpleConstMapping::createKeyEntries(), MappingUtils::createMapping(), MultiDimMapping< Linear >::createSubSignal(), FilledUpMapping::createSubSignal(), Argument::getDimensions(), ConstMapping::print(), and time_static().
The documentation for this class was generated from the following files:
MappingBase.h
MappingBase.cc