Veins Framework: Signal Class Reference
Signal Class Reference
The signal class stores the physical representation of the signal of an AirFrame.
#include <Signal_.h>
Public Types
typedef ConcatConstMapping
< std::multiplies< double > > MultipliedMapping
Shortcut type for a concatenated Mapping using multiply operator.
typedef std::list< ConstMapping * > ConstMappingList
Shortcut type for a list of ConstMappings.
Public Member Functions
Signal (simtime_t_cref start=-1.0, simtime_t_cref length=-1.0)
Initializes a signal with the specified start and length.
Signal (const Signal &o)
Overwrites the copy constructor to make sure that the mappings are cloned correct.
const Signal & operator= (const Signal &o)
Overwrites the copy operator to make sure that the mappings are cloned correct.
~Signal ()
Delete the functions of this signal.
simtime_t_cref getSendingStart () const
Returns the point in time when the sending of the Signal started at the sender module.
simtime_t getSendingEnd () const
Returns the point in time when the sending of the Signal ended at the sender module.
simtime_t getReceptionStart () const
Returns the point in time when the receiving of the Signal started at the receiver module.
simtime_t getReceptionEnd () const
Returns the point in time when the receiving of the Signal ended at the receiver module.
simtime_t_cref getDuration () const
Returns the duration of the signal transmission.
simtime_t_cref getPropagationDelay () const
Returns the propagation delay of the signal.
void setPropagationDelay (simtime_t_cref delay)
Sets the propagation delay of the signal.
void setTransmissionPower (ConstMapping *power)
Sets the function representing the transmission power of the signal.
void setBitrate (Mapping *bitrate)
Sets the function representing the bitrate of the signal.
void addAttenuation (ConstMapping *att)
Adds a function representing an attenuation of the signal.
ConstMapping * getTransmissionPower ()
Returns the function representing the transmission power of the signal.
const ConstMapping * getTransmissionPower () const
Returns the function representing the transmission power of the signal.
Mapping * getBitrate ()
Returns the function representing the bitrate of the signal.
const ConstMappingList & getAttenuation () const
Returns a list of functions representing the attenuations of the signal.
MultipliedMapping * getReceivingPower ()
Calculates and returns the receiving power of this Signal.
cModule * getReceptionModule () const
Returns a pointer to the arrival module.
cGate * getReceptionGate () const
Returns pointers to the gate from which the signal was sent and on which gate it arrived.
cModule * getSendingModule () const
Returns a pointer to the sender module.
cGate * getSendingGate () const
Returns pointers to the gate from which the signal was sent and on which gate it arrived.
void setReceptionSenderInfo (const cMessage *const pMsg)
Saves the arrival sender module information form message.
Protected Member Functions
void markRcvPowerOutdated ()
Deletes the rcvPower mapping member because it became out-dated.
Protected Attributes
int senderModuleID
Sender module id, additional definition here because BasePhyLayer will do some selfMessages with AirFrame.
int senderFromGateID
Sender gate id, additional definition here because BasePhyLayer will do some selfMessages with AirFrame.
int receiverModuleID
Receiver module id, additional definition here because BasePhyLayer will do some selfMessages with AirFrame.
int receiverToGateID
Receiver gate id, additional definition here because BasePhyLayer will do some selfMessages with AirFrame.
simtime_t sendingStart
The start of the signal transmission at the sender module.
simtime_t duration
The duration of the signal transmission.
simtime_t propagationDelay
The propagation delay of the transmission.
ConstMapping * power
Stores the function which describes the power of the signal.
Mapping * bitrate
Stores the function which describes the bitrate of the signal.
Mapping * txBitrate
If propagation delay is not zero this stores the undelayed bitrate.
ConstMappingList attenuations
Stores the functions describing the attenuations of the signal.
MultipliedMapping * rcvPower
Stores the mapping defining the receiving power of the signal.
Detailed Description
The signal class stores the physical representation of the signal of an AirFrame.
This includes start, duration and propagation delay of the signal, Mappings which represent the transmission power, bitrate, attenuations caused by effects of the channel on the signal during its transmission and the receiving power.
Note: Although the Signal itself has a signalSendingStart parameter the Mappings it contains should use absolute time positions to store the values at (NOT relative to the start time of the signal).
The Signal is created at the senders MAC layer which has to define the TX-power- and the bitrate Mapping. Sending start time and duration is added at the sender's physical layer. Attenuation Mappings are added to the Signal by the AnalogueModels of the receiver's physical layer. The RX-power Mapping is calculated on demand by multiplying the TX-power Mapping with every attenuation Mapping of the signal.
Definition at line 33 of file Signal_.h.
Member Typedef Documentation
typedef std::list<ConstMapping*> Signal::ConstMappingList
Shortcut type for a list of ConstMappings.
Definition at line 42 of file Signal_.h.
typedef ConcatConstMapping<std::multiplies<double> > Signal::MultipliedMapping
Shortcut type for a concatenated Mapping using multiply operator.
Used to define the receiving power mapping.
Definition at line 40 of file Signal_.h.
Constructor & Destructor Documentation
Signal::Signal (simtime_t_cref start = -1.0, simtime_t_cref length = -1.0)
Initializes a signal with the specified start and length.
Definition at line 5 of file Signal.cc.
                                                                   :
         senderModuleID(-1), senderFromGateID(-1), receiverModuleID(-1), receiverToGateID(-1),
         sendingStart(sendingStart), duration(duration),
         propagationDelay(0),
         power(0), bitrate(0),
         txBitrate(0),
         rcvPower(0)
 {}
Signal::Signal (const Signal & o)
Overwrites the copy constructor to make sure that the mappings are cloned correct.
Definition at line 14 of file Signal.cc.
                               :
         senderModuleID(o.senderModuleID), senderFromGateID(o.senderFromGateID), receiverModuleID(o.receiverModuleID), receiverToGateID(o.receiverToGateID),
         sendingStart(o.sendingStart), duration(o.duration),
         propagationDelay(o.propagationDelay),
         power(0), bitrate(0),
         txBitrate(0),
         rcvPower(0)
 {
         if (o.power) {
                 power = o.power->constClone();
         }
         if (o.bitrate) {
                 bitrate = o.bitrate->clone();
         }
         if (o.txBitrate) {
                 txBitrate = o.txBitrate->clone();
         }
         for(ConstMappingList::const_iterator it = o.attenuations.begin();
                 it != o.attenuations.end(); it++){
                 attenuations.push_back((*it)->constClone());
         }
 }
Signal::~Signal ()
Delete the functions of this signal.
Definition at line 90 of file Signal.cc.
 {
         if(rcvPower){
                 if(propagationDelay != 0){
                         assert(rcvPower->getRefMapping() != power);
                         delete rcvPower->getRefMapping();
                 }
                 delete rcvPower;
         }
         if(power)
                 delete power;
         if(bitrate)
                 delete bitrate;
         if(txBitrate)
                 delete txBitrate;
         for(ConstMappingList::iterator it = attenuations.begin();
                 it != attenuations.end(); it++) {
                 delete *it;
         }
 }
Member Function Documentation
void Signal::addAttenuation (ConstMapping * att) inline
Adds a function representing an attenuation of the signal.
The ownership of the passed pointer goes to the signal.
Definition at line 177 of file Signal_.h.
Referenced by PERModel::filterSignal(), TwoRayInterferenceModel::filterSignal(), SimpleObstacleShadowing::filterSignal(), LogNormalShadowing::filterSignal(), BreakpointPathlossModel::filterSignal(), JakesFading::filterSignal(), SimplePathlossModel::filterSignal(), and RadioStateAnalogueModel::filterSignal().
{
                 //assert the attenuation wasn't already added to the list before
                 assert(std::find(attenuations.begin(), attenuations.end(), att) == attenuations.end());
                 attenuations.push_back(att);
                 if(rcvPower)
                         rcvPower->addMapping(att);
         }
const ConstMappingList& Signal::getAttenuation () const inline
Returns a list of functions representing the attenuations of the signal.
Definition at line 221 of file Signal_.h.
{
                 return attenuations;
         }
Mapping* Signal::getBitrate () inline
Returns the function representing the bitrate of the signal.
Definition at line 213 of file Signal_.h.
Referenced by Decider80211p::checkIfSignalOk().
{
                 return bitrate;
         }
simtime_t_cref Signal::getDuration () const
Returns the duration of the signal transmission.
Definition at line 133 of file Signal.cc.
Referenced by BasePhyLayer::handleAirFrameReceiving().
{
         return duration;
 }
simtime_t_cref Signal::getPropagationDelay () const
Returns the propagation delay of the signal.
Definition at line 137 of file Signal.cc.
{
         return propagationDelay;
 }
MultipliedMapping* Signal::getReceivingPower () inline
Calculates and returns the receiving power of this Signal.
Ownership of the returned mapping belongs to this class.
The receiving power is calculated by multiplying the transmission power with the attenuation of every receiving phys AnalogueModel.
Definition at line 232 of file Signal_.h.
Referenced by Decider80211p::calculateNoiseRSSIMapping(), BaseDecider::calculateRSSIMapping(), Decider80211p::calculateSinrAndSnrMapping(), BaseDecider::calculateSnrMapping(), Decider80211p::cca(), SNRThresholdDecider::processNewSignal(), and BaseDecider::processNewSignal().
{
                 if(!rcvPower)
                 {
                         ConstMapping* tmp = power;
                         if(propagationDelay != 0) {
                                 tmp = new ConstDelayedMapping(power, propagationDelay);
                         }
                         rcvPower = new MultipliedMapping(tmp,
                                                                                           attenuations.begin(),
                                                                                           attenuations.end(),
                                                                                           false, Argument::MappedZero);
                 }
                 return rcvPower;
         }
simtime_t Signal::getReceptionEnd () const
Returns the point in time when the receiving of the Signal ended at the receiver module.
Already includes the propagation delay.
Definition at line 129 of file Signal.cc.
Referenced by BaseDecider::calculateRSSIMapping(), Decider80211p::calculateSinrAndSnrMapping(), BaseDecider::calculateSnrMapping(), Decider80211p::checkIfSignalOk(), LogNormalShadowing::filterSignal(), JakesFading::filterSignal(), RadioStateAnalogueModel::filterSignal(), SNRThresholdDecider::processNewSignal(), BaseDecider::processNewSignal(), and SNRThresholdDecider::processSignalEnd().
{
         return sendingStart + propagationDelay + duration;
 }
cGate * Signal::getReceptionGate () const
Returns pointers to the gate from which the signal was sent and on which gate it arrived.
A NULL pointer is returned for new (unsent) signal.
Definition at line 182 of file Signal.cc.
 {
     if (receiverToGateID < 0) return NULL;
     cModule *const mod = getReceptionModule();
     return !mod ? NULL : mod->gate(receiverToGateID);
 }
cModule* Signal::getReceptionModule () const inline
Returns a pointer to the arrival module.
It returns NULL if the signal has not been sent/received yet, or if the module was deleted in the meantime.
Definition at line 253 of file Signal_.h.
Referenced by getReceptionGate().
 {return receiverModuleID < 0 ? NULL : simulation.getModule(receiverModuleID);}
simtime_t Signal::getReceptionStart () const
Returns the point in time when the receiving of the Signal started at the receiver module.
Already includes the propagation delay.
Definition at line 125 of file Signal.cc.
Referenced by BaseDecider::calculateRSSIMapping(), Decider80211p::calculateSinrAndSnrMapping(), BaseDecider::calculateSnrMapping(), Decider80211p::checkIfSignalOk(), LogNormalShadowing::filterSignal(), JakesFading::filterSignal(), RadioStateAnalogueModel::filterSignal(), BasePhyLayer::handleAirFrameReceiving(), BasePhyLayer::handleAirFrameStartReceive(), SNRThresholdDecider::processNewSignal(), BaseDecider::processNewSignal(), and SNRThresholdDecider::processSignalEnd().
{
         return sendingStart + propagationDelay;
 }
simtime_t Signal::getSendingEnd () const
Returns the point in time when the sending of the Signal ended at the sender module.
Definition at line 121 of file Signal.cc.
{
         return sendingStart + duration;
 }
cGate * Signal::getSendingGate () const
Returns pointers to the gate from which the signal was sent and on which gate it arrived.
A NULL pointer is returned for new (unsent) signal.
Definition at line 175 of file Signal.cc.
 {
     if (senderFromGateID < 0) return NULL;
     cModule *const mod = getSendingModule();
     return !mod ? NULL : mod->gate(senderFromGateID);
 }
cModule* Signal::getSendingModule () const inline
Returns a pointer to the sender module.
It returns NULL if the signal has not been sent/received yet, or if the sender module got deleted in the meantime.
Definition at line 267 of file Signal_.h.
Referenced by getSendingGate().
 {return senderModuleID < 0 ? NULL : simulation.getModule(senderModuleID);}
simtime_t_cref Signal::getSendingStart () const
Returns the point in time when the sending of the Signal started at the sender module.
Definition at line 117 of file Signal.cc.
Referenced by BasePhyLayer::handleAirFrameStartReceive().
{
         return sendingStart;
 }
ConstMapping* Signal::getTransmissionPower () inline
Returns the function representing the transmission power of the signal.
Be aware that the transmission power mapping is not yet affected by the propagation delay!
Definition at line 194 of file Signal_.h.
Referenced by TwoRayInterferenceModel::filterSignal(), SimpleObstacleShadowing::filterSignal(), and SimplePathlossModel::filterSignal().
{
                 return power;
         }
const ConstMapping* Signal::getTransmissionPower () const inline
Returns the function representing the transmission power of the signal.
Be aware that the transmission power mapping is not yet affected by the propagation delay!
Definition at line 205 of file Signal_.h.
{
                 return power;
         }
void Signal::markRcvPowerOutdated () inline protected
Deletes the rcvPower mapping member because it became out-dated.
This happens when transmission power or propagation delay changes.
Definition at line 82 of file Signal_.h.
Referenced by operator=(), setPropagationDelay(), and setTransmissionPower().
{
                 if(rcvPower){
                         if(propagationDelay != 0) {
                                 assert(rcvPower->getRefMapping() != power);
                                 delete rcvPower->getRefMapping();
                         }
                         delete rcvPower;
                         rcvPower = 0;
                 }
         }
const Signal & Signal::operator= (const Signal & o)
Overwrites the copy operator to make sure that the mappings are cloned correct.
Definition at line 40 of file Signal.cc.
{
         sendingStart     = o.sendingStart;
         duration         = o.duration;
         propagationDelay = o.propagationDelay;
         senderModuleID   = o.senderModuleID;
         senderFromGateID = o.senderFromGateID;
         receiverModuleID = o.receiverModuleID;
         receiverToGateID = o.receiverToGateID;
         markRcvPowerOutdated();
         if(power){
                 delete power;
                 power = 0;
         }
         if(bitrate){
                 delete bitrate;
                 bitrate = 0;
         }
         if(txBitrate){
                 delete txBitrate;
                 txBitrate = 0;
         }
         if(o.power)
                 power = o.power->constClone();
         if(o.bitrate)
                 bitrate = o.bitrate->clone();
         if(o.txBitrate)
                 txBitrate = o.txBitrate->clone();
         for(ConstMappingList::const_iterator it = attenuations.begin();
                 it != attenuations.end(); it++){
                 delete(*it);
         }
         attenuations.clear();
         for(ConstMappingList::const_iterator it = o.attenuations.begin();
                 it != o.attenuations.end(); it++){
                 attenuations.push_back((*it)->constClone());
         }
         return *this;
 }
void Signal::setBitrate (Mapping * bitrate)
Sets the function representing the bitrate of the signal.
The ownership of the passed pointer goes to the signal.
Definition at line 165 of file Signal.cc.
Referenced by Mac1609_4::createSignal(), and BaseMacLayer::createSignal().
 {
         assert(!txBitrate);
         if(this->bitrate)
                 delete this->bitrate;
         this->bitrate = bitrate;
 }
void Signal::setPropagationDelay (simtime_t_cref delay)
Sets the propagation delay of the signal.
This should be only set by the sending physical layer.
Definition at line 141 of file Signal.cc.
Referenced by BasePhyLayer::handleAirFrameStartReceive().
{
         assert(propagationDelay == 0);
         assert(!txBitrate);
         markRcvPowerOutdated();
         propagationDelay = delay;
         if(bitrate) {
                 txBitrate = bitrate;
                 bitrate = new DelayedMapping(txBitrate, propagationDelay);
         }
 }
void Signal::setReceptionSenderInfo (const cMessage *const pMsg)
Saves the arrival sender module information form message.
Definition at line 189 of file Signal.cc.
Referenced by BasePhyLayer::handleAirFrameStartReceive().
 {
         if (!pMsg)
                 return;
         assert(senderModuleID < 0);
         senderModuleID   = pMsg->getSenderModuleId();
         senderFromGateID = pMsg->getSenderGateId();
         receiverModuleID = pMsg->getArrivalModuleId();
         receiverToGateID = pMsg->getArrivalGateId();
 }
void Signal::setTransmissionPower (ConstMapping * power)
Sets the function representing the transmission power of the signal.
The ownership of the passed pointer goes to the signal.
Definition at line 155 of file Signal.cc.
Referenced by Mac1609_4::createSignal(), and BaseMacLayer::createSignal().
 {
         if(this->power){
                 markRcvPowerOutdated();
                 delete this->power;
         }
         this->power = power;
 }
Member Data Documentation
ConstMappingList Signal::attenuations protected
Stores the functions describing the attenuations of the signal.
Definition at line 70 of file Signal_.h.
Referenced by operator=(), Signal(), and ~Signal().
Mapping* Signal::bitrate protected
Stores the function which describes the bitrate of the signal.
Definition at line 64 of file Signal_.h.
Referenced by operator=(), setBitrate(), setPropagationDelay(), Signal(), and ~Signal().
simtime_t Signal::duration protected
The duration of the signal transmission.
Definition at line 56 of file Signal_.h.
Referenced by getDuration(), getReceptionEnd(), getSendingEnd(), and operator=().
ConstMapping* Signal::power protected
Stores the function which describes the power of the signal.
Definition at line 61 of file Signal_.h.
Referenced by operator=(), setTransmissionPower(), Signal(), and ~Signal().
simtime_t Signal::propagationDelay protected
The propagation delay of the transmission.
Definition at line 58 of file Signal_.h.
Referenced by getPropagationDelay(), getReceptionEnd(), getReceptionStart(), operator=(), setPropagationDelay(), and ~Signal().
MultipliedMapping* Signal::rcvPower protected
Stores the mapping defining the receiving power of the signal.
Definition at line 73 of file Signal_.h.
Referenced by ~Signal().
int Signal::receiverModuleID protected
Receiver module id, additional definition here because BasePhyLayer will do some selfMessages with AirFrame.
Definition at line 50 of file Signal_.h.
Referenced by operator=(), and setReceptionSenderInfo().
int Signal::receiverToGateID protected
Receiver gate id, additional definition here because BasePhyLayer will do some selfMessages with AirFrame.
Definition at line 52 of file Signal_.h.
Referenced by getReceptionGate(), operator=(), and setReceptionSenderInfo().
int Signal::senderFromGateID protected
Sender gate id, additional definition here because BasePhyLayer will do some selfMessages with AirFrame.
Definition at line 48 of file Signal_.h.
Referenced by getSendingGate(), operator=(), and setReceptionSenderInfo().
int Signal::senderModuleID protected
Sender module id, additional definition here because BasePhyLayer will do some selfMessages with AirFrame.
Definition at line 46 of file Signal_.h.
Referenced by operator=(), and setReceptionSenderInfo().
simtime_t Signal::sendingStart protected
The start of the signal transmission at the sender module.
Definition at line 54 of file Signal_.h.
Referenced by getReceptionEnd(), getReceptionStart(), getSendingEnd(), getSendingStart(), and operator=().
Mapping* Signal::txBitrate protected
If propagation delay is not zero this stores the undelayed bitrate.
Definition at line 67 of file Signal_.h.
Referenced by operator=(), setBitrate(), setPropagationDelay(), Signal(), and ~Signal().
The documentation for this class was generated from the following files:
Signal_.h
Signal.cc