Veins Framework: NetwToMacControlInfo Class Reference
NetwToMacControlInfo Class Reference
Control info to pass next hop L2 addr from netw to MAC layer.
#include <NetwToMacControlInfo.h>
Public Member Functions
NetwToMacControlInfo (const LAddress::L2Type &addr=LAddress::L2NULL)
Default constructor.
virtual ~NetwToMacControlInfo ()
Destructor.
virtual const LAddress::L2Type & getNextHopMac () const
Getter method.
virtual const LAddress::L2Type & getDest () const
virtual void setNextHopMac (const LAddress::L2Type &addr)
Setter method.
virtual void setDest (const LAddress::L2Type &addr)
Static Public Member Functions
static cObject *const setControlInfo (cMessage *const pMsg, const LAddress::L2Type &pDestAddr)
Attaches a "control info" structure (object) to the message pMsg.
static const LAddress::L2Type & getDestFromControlInfo (const cObject *const pCtrlInfo)
Extracts the MAC address from the "control info" structure (object).
Protected Attributes
LAddress::L2Type nextHopMac
MAC address of the sending or receiving node.
Detailed Description
Control info to pass next hop L2 addr from netw to MAC layer.
Control Info to pass interface information from the network to the MAC layer Currently the only information necessary is the MAC address of the next hop, which has to be determined by ARP or some similar mechanism
Author
Daniel Willkomm
Definition at line 42 of file NetwToMacControlInfo.h.
Constructor & Destructor Documentation
NetwToMacControlInfo::NetwToMacControlInfo (const LAddress::L2Type & addr = LAddress::L2NULL) inline
Default constructor.
Definition at line 50 of file NetwToMacControlInfo.h.
       : cObject()
       , nextHopMac(addr)
     {
     };
virtual NetwToMacControlInfo::~NetwToMacControlInfo () inline virtual
Destructor.
Definition at line 57 of file NetwToMacControlInfo.h.
 {};
Member Function Documentation
virtual const LAddress::L2Type& NetwToMacControlInfo::getDest () const inline virtual
Definition at line 63 of file NetwToMacControlInfo.h.
Referenced by getDestFromControlInfo().
{
         return nextHopMac;
     };
const LAddress::L2Type & NetwToMacControlInfo::getDestFromControlInfo (const cObject *const pCtrlInfo) static
Extracts the MAC address from the "control info" structure (object).
Extract the destination MAC address from the "control info" which was prev. set by NetwToMacControlInfo::setControlInfo().
Parameters
pCtrlInfo The "control info" structure (object) prev. set by NetwToMacControlInfo::setControlInfo().
Returns
The MAC address of message receiver.
Definition at line 37 of file NetwToMacControlInfo.cc.
Referenced by BaseMacLayer::getUpperDestinationFromControlInfo().
 {
         const tNetwToMacControlInfoBase *const cCtrlInfo = dynamic_cast<const tNetwToMacControlInfoBase *>(pCtrlInfo);
         assert(cCtrlInfo);
         return cCtrlInfo->getDest();
 }
virtual const LAddress::L2Type& NetwToMacControlInfo::getNextHopMac () const inline virtual
Getter method.
Definition at line 60 of file NetwToMacControlInfo.h.
{
         return nextHopMac;
     };
cObject *const NetwToMacControlInfo::setControlInfo (cMessage *const pMsg, const LAddress::L2Type & pDestAddr) static
Attaches a "control info" structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the destination MAC address.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters
pMsg The message where the "control info" shall be attached.
pDestAddr The MAC address of the message receiver.
Definition at line 27 of file NetwToMacControlInfo.cc.
 {
         tNetwToMacControlInfoBase *const cCtrlInfo = new tNetwToMacControlInfoBase();
         cCtrlInfo->setDest(pDestAddr);
         pMsg->setControlInfo(cCtrlInfo);
         return cCtrlInfo;
 }
virtual void NetwToMacControlInfo::setDest (const LAddress::L2Type & addr) inline virtual
Definition at line 71 of file NetwToMacControlInfo.h.
Referenced by setControlInfo().
{
         nextHopMac = addr;
     };
virtual void NetwToMacControlInfo::setNextHopMac (const LAddress::L2Type & addr) inline virtual
Setter method.
Definition at line 68 of file NetwToMacControlInfo.h.
{
         nextHopMac = addr;
     };
Member Data Documentation
LAddress::L2Type NetwToMacControlInfo::nextHopMac protected
MAC address of the sending or receiving node.
Definition at line 46 of file NetwToMacControlInfo.h.
The documentation for this class was generated from the following files:
NetwToMacControlInfo.h
NetwToMacControlInfo.cc