Veins Framework: Veins::AnnotationManager Class Reference
Veins::AnnotationManager Class Reference
#include <AnnotationManager.h>
Classes
class Annotation
class Group
class Line
class Point
class Polygon
Public Member Functions
~AnnotationManager ()
void initialize ()
void finish ()
void handleMessage (cMessage *msg)
void handleSelfMsg (cMessage *msg)
void handleParameterChange (const char *parname)
void addFromXml (cXMLElement *xml)
adds Annotations from an XML document; example below.
Group * createGroup (std::string title="untitled")
Point * drawPoint (Coord p, std::string color, std::string text, Group *group=0)
Line * drawLine (Coord p1, Coord p2, std::string color, Group *group=0)
Polygon * drawPolygon (std::list< Coord > coords, std::string color, Group *group=0)
Polygon * drawPolygon (std::vector< Coord > coords, std::string color, Group *group=0)
void drawBubble (Coord p1, std::string text)
void erase (const Annotation *annotation)
void eraseAll (Group *group=0)
void scheduleErase (simtime_t deltaT, Annotation *annotation)
cModule * createDummyModule (std::string displayString)
cModule * createDummyModuleLine (Coord p1, Coord p2, std::string color)
void show (const Annotation *annotation)
void hide (const Annotation *annotation)
void showAll (Group *group=0)
void hideAll (Group *group=0)
Protected Types
typedef std::list< Annotation * > Annotations
typedef std::list< Group * > Groups
Protected Attributes
bool debug
whether to emit debug messages
cXMLElement * annotationsXml
annotations to add at startup
std::list< cMessage * > scheduledEraseEvts
Annotations annotations
Groups groups
Detailed Description
Definition at line 34 of file AnnotationManager.h.
Member Typedef Documentation
typedef std::list<Annotation*> Veins::AnnotationManager::Annotations protected
Definition at line 130 of file AnnotationManager.h.
typedef std::list<Group*> Veins::AnnotationManager::Groups protected
Definition at line 131 of file AnnotationManager.h.
Constructor & Destructor Documentation
AnnotationManager::~AnnotationManager ()
Definition at line 53 of file AnnotationManager.cc.
{
         while (scheduledEraseEvts.begin() != scheduledEraseEvts.end()) {
                 cancelAndDelete(*scheduledEraseEvts.begin());
                 scheduledEraseEvts.erase(scheduledEraseEvts.begin());
         }
         scheduledEraseEvts.clear();
         while (annotations.begin() != annotations.end()) {
                 delete *annotations.begin();
                 annotations.erase(annotations.begin());
         }
         annotations.clear();
         while (groups.begin() != groups.end()) {
                 delete *groups.begin();
                 groups.erase(groups.begin());
         }
         groups.clear();
 }
Member Function Documentation
void AnnotationManager::addFromXml (cXMLElement * xml)
adds Annotations from an XML document; example below.
<annotations> <line color="#F00" shape="16,0 8,13.8564"> <poly color="#0F0" shape="16,64 8,77.8564 -8,77.8564 -16,64 -8,50.1436 8,50.1436"> </annotations>
Definition at line 116 of file AnnotationManager.cc.
Referenced by initialize().
{
         std::string rootTag = xml->getTagName();
         ASSERT (rootTag == "annotations");
         cXMLElementList list = xml->getChildren();
         for (cXMLElementList::const_iterator i = list.begin(); i != list.end(); ++i) {
                 cXMLElement* e = *i;
                 std::string tag = e->getTagName();
                 if (tag == "point") {
                         ASSERT(e->getAttribute("text"));
                         std::string text = e->getAttribute("text");
                         ASSERT(e->getAttribute("color"));
                         std::string color = e->getAttribute("color");
                         ASSERT(e->getAttribute("shape"));
                         std::string shape = e->getAttribute("shape");
                         std::vector<std::string> points = cStringTokenizer(shape.c_str(), " ").asVector();
                         ASSERT(points.size() == 2);
                         std::vector<double> p1a = cStringTokenizer(points[0].c_str(), ",").asDoubleVector();
                         ASSERT(p1a.size() == 2);
                         drawPoint(Coord(p1a[0], p1a[1]), color, text);
                 }
                 else if (tag == "line") {
                         ASSERT(e->getAttribute("color"));
                         std::string color = e->getAttribute("color");
                         ASSERT(e->getAttribute("shape"));
                         std::string shape = e->getAttribute("shape");
                         std::vector<std::string> points = cStringTokenizer(shape.c_str(), " ").asVector();
                         ASSERT(points.size() == 2);
                         std::vector<double> p1a = cStringTokenizer(points[0].c_str(), ",").asDoubleVector();
                         ASSERT(p1a.size() == 2);
                         std::vector<double> p2a = cStringTokenizer(points[1].c_str(), ",").asDoubleVector();
                         ASSERT(p2a.size() == 2);
                         drawLine(Coord(p1a[0], p1a[1]), Coord(p2a[0], p2a[1]), color);
                 }
                 else if (tag == "poly") {
                         ASSERT(e->getAttribute("color"));
                         std::string color = e->getAttribute("color");
                         ASSERT(e->getAttribute("shape"));
                         std::string shape = e->getAttribute("shape");
                         std::vector<std::string> points = cStringTokenizer(shape.c_str(), " ").asVector();
                         ASSERT(points.size() >= 2);
                         std::vector<Coord> coords;
                         for (std::vector<std::string>::const_iterator i = points.begin(); i != points.end(); ++i) {
                                 std::vector<double> pa = cStringTokenizer(i->c_str(), ",").asDoubleVector();
                                 ASSERT(pa.size() == 2);
                                 coords.push_back(Coord(pa[0], pa[1]));
                         }
                         drawPolygon(coords, color);
                 }
                 else {
                         error("while reading annotations xml: expected 'line' or 'poly', but got '%s'", tag.c_str());
                 }
         }
 }
cModule * AnnotationManager::createDummyModule (std::string displayString)
Definition at line 268 of file AnnotationManager.cc.
Referenced by createDummyModuleLine().
{
         static int32_t nodeVectorIndex = -1;
         cModule* parentmod = getParentModule();
         if (!parentmod) error("Parent Module not found");
         cModuleType* nodeType = cModuleType::get("org.car2x.veins.modules.world.annotations.AnnotationDummy");
         //TODO: this trashes the vectsize member of the cModule, although nobody seems to use it
         nodeVectorIndex++;
         cModule* mod = nodeType->create("annotation", parentmod, nodeVectorIndex, nodeVectorIndex);
         mod->finalizeParameters();
         mod->getDisplayString().parse(displayString.c_str());
         mod->buildInside();
         mod->scheduleStart(simTime());
         return mod;
 }
cModule * AnnotationManager::createDummyModuleLine (Coord p1, Coord p2, std::string color)
Definition at line 287 of file AnnotationManager.cc.
Referenced by show().
{
         double w = std::abs(p2.x - p1.x);
         double h = std::abs(p2.y - p1.y);
         double px = 0;
         if (p1.x <= p2.x) {
                 px = p1.x + 0.5 * w;
         } else {
                 px = p2.x + 0.5 * w;
                 w = -w;
         }
         double py = 0;
         if (p1.y <= p2.y) {
                 py = p1.y + 0.5 * h;
         } else {
                 py = p2.y + 0.5 * h;
                 h = -h;
         }
         std::stringstream ss;
         ss << "p=" << px << "," << py << ";b=" << w << ", " << h << ",polygon," << color << "," << color << ",1";
         std::string displayString = ss.str();
         return createDummyModule(displayString);
 }
AnnotationManager::Group * AnnotationManager::createGroup (std::string title = "untitled")
Definition at line 180 of file AnnotationManager.cc.
Referenced by Veins::ObstacleControl::initialize().
{
         Group* group = new Group(title);
         groups.push_back(group);
         return group;
 }
void AnnotationManager::drawBubble (Coord p1, std::string text)
Definition at line 224 of file AnnotationManager.cc.
Referenced by Veins::ObstacleControl::calculateAttenuation().
{
         std::string pxOld = getDisplayString().getTagArg("p", 0);
         std::string pyOld = getDisplayString().getTagArg("p", 1);
         std::string px; { std::stringstream ss; ss << p1.x; px = ss.str(); }
         std::string py; { std::stringstream ss; ss << p1.x; py = ss.str(); }
         getDisplayString().setTagArg("p", 0, px.c_str());
         getDisplayString().setTagArg("p", 1, py.c_str());
         bubble(text.c_str());
         getDisplayString().setTagArg("p", 0, pxOld.c_str());
         getDisplayString().setTagArg("p", 1, pyOld.c_str());
 }
AnnotationManager::Line * AnnotationManager::drawLine (Coord p1, Coord p2, std::string color, Group * group = 0)
Definition at line 198 of file AnnotationManager.cc.
Referenced by addFromXml(), minicurso_UFPI_TraCI_RSU::onData(), mfcv_rsu::onData(), default_veins_TraCI_RSU::onData(), default_veins_TraCI::onData(), mfcv::onData(), and minicurso_UFPI_TraCI::onData().
{
         Line* l = new Line(p1, p2, color);
         l->group = group;
         annotations.push_back(l);
         if (par("draw")) show(l);
         return l;
 }
AnnotationManager::Point * AnnotationManager::drawPoint (Coord p, std::string color, std::string text, Group * group = 0)
Definition at line 187 of file AnnotationManager.cc.
Referenced by addFromXml().
{
         Point* o = new Point(p, color, text);
         o->group = group;
         annotations.push_back(o);
         if (par("draw")) show(o);
         return o;
 }
AnnotationManager::Polygon * AnnotationManager::drawPolygon (std::list< Coord > coords, std::string color, Group * group = 0)
Definition at line 209 of file AnnotationManager.cc.
Referenced by Veins::ObstacleControl::add(), addFromXml(), and drawPolygon().
{
         Polygon* p = new Polygon(coords, color);
         p->group = group;
         annotations.push_back(p);
         if (par("draw")) show(p);
         return p;
 }
AnnotationManager::Polygon * AnnotationManager::drawPolygon (std::vector< Coord > coords, std::string color, Group * group = 0)
Definition at line 220 of file AnnotationManager.cc.
{
         return drawPolygon(std::list<Coord>(coords.begin(), coords.end()), color, group);
 }
void AnnotationManager::erase (const Annotation * annotation)
Definition at line 240 of file AnnotationManager.cc.
Referenced by Veins::ObstacleControl::erase(), eraseAll(), and handleSelfMsg().
{
         hide(annotation);
         annotations.remove(const_cast<Annotation*>(annotation));
         delete annotation;
 }
void AnnotationManager::eraseAll (Group * group = 0)
Definition at line 246 of file AnnotationManager.cc.
{
         for (Annotations::iterator i = annotations.begin(); i != annotations.end(); ) {
                 if ((!group) || ((*i)->group == group)) {
                         erase(*i++);
                 } else {
                         i++;
                 }
         }
 }
void AnnotationManager::finish ()
Definition at line 49 of file AnnotationManager.cc.
{
         hideAll();
 }
void AnnotationManager::handleMessage (cMessage * msg)
Definition at line 74 of file AnnotationManager.cc.
{
         if (msg->isSelfMessage()) {
                 handleSelfMsg(msg);
                 return;
         }
         error("AnnotationManager doesn't handle messages from other modules");
 }
void AnnotationManager::handleParameterChange (const char * parname)
Definition at line 98 of file AnnotationManager.cc.
{
         if (parname && (std::string(parname) == "draw")) {
                 if (par("draw")) {
                         showAll();
                 } else {
                         hideAll();
                 }
         }
 }
void AnnotationManager::handleSelfMsg (cMessage * msg)
Definition at line 82 of file AnnotationManager.cc.
Referenced by handleMessage().
{
         if (msg->getKind() == EVT_SCHEDULED_ERASE) {
                 Annotation* a = static_cast<Annotation*>(msg->getContextPointer());
                 ASSERT(a);
                 erase(a);
                 scheduledEraseEvts.remove(msg);
                 delete msg;
                 return;
         }
         error("unknown self message type");
 }
void AnnotationManager::hide (const Annotation * annotation)
Definition at line 375 of file AnnotationManager.cc.
Referenced by erase(), and hideAll().
{
         for (std::list<cModule*>::const_iterator i = annotation->dummyObjects.begin(); i != annotation->dummyObjects.end(); ++i) {
                 cModule* mod = *i;
                 mod->deleteModule();
         }
         annotation->dummyObjects.clear();
         TraCIScenarioManager* traci = TraCIScenarioManagerAccess().get();
         if (traci && traci->isConnected()) {
                 for (std::list<std::string>::const_iterator i = annotation->traciPolygonsIds.begin(); i != annotation->traciPolygonsIds.end(); ++i) {
                         std::string id = *i;
                         traci->getCommandInterface()->removePolygon(id, 3);
                 }
                 annotation->traciPolygonsIds.clear();
                 for (std::list<std::string>::const_iterator i = annotation->traciLineIds.begin(); i != annotation->traciLineIds.end(); ++i) {
                         std::string id = *i;
                         traci->getCommandInterface()->removePolygon(id, 4);
                 }
                 annotation->traciLineIds.clear();
                 for (std::list<std::string>::const_iterator i = annotation->traciPoiIds.begin(); i != annotation->traciPoiIds.end(); ++i) {
                         std::string id = *i;
                         traci->getCommandInterface()->removePoi(id, 5);
                 }
                 annotation->traciPoiIds.clear();
         }
 }
void AnnotationManager::hideAll (Group * group = 0)
Definition at line 408 of file AnnotationManager.cc.
Referenced by finish(), and handleParameterChange().
{
         for (Annotations::const_iterator i = annotations.begin(); i != annotations.end(); ++i) {
                 if ((!group) || ((*i)->group == group)) hide(*i);
         }
 }
void AnnotationManager::initialize ()
Definition at line 37 of file AnnotationManager.cc.
{
         debug = par("debug");
         scheduledEraseEvts.clear();
         annotations.clear();
         groups.clear();
         annotationsXml = par("annotations");
         addFromXml(annotationsXml);
 }
void AnnotationManager::scheduleErase (simtime_t deltaT, Annotation * annotation)
Definition at line 256 of file AnnotationManager.cc.
Referenced by default_veins_TraCI_RSU::onData(), mfcv_rsu::onData(), minicurso_UFPI_TraCI_RSU::onData(), default_veins_TraCI::onData(), mfcv::onData(), and minicurso_UFPI_TraCI::onData().
{
         Enter_Method_Silent();
         cMessage* evt = new cMessage("erase", EVT_SCHEDULED_ERASE);
         evt->setContextPointer(annotation);
         scheduleAt(simTime() + deltaT, evt);
         scheduledEraseEvts.push_back(evt);
 }
void AnnotationManager::show (const Annotation * annotation)
Definition at line 313 of file AnnotationManager.cc.
Referenced by drawLine(), drawPoint(), drawPolygon(), and showAll().
{
         if (annotation->dummyObjects.size() > 0) return;
         if (const Point* o = dynamic_cast<const Point*>(annotation)) {
                 if (ev.isGUI()) {
                         // no corresponding TkEnv representation
                 }
                 TraCIScenarioManager* traci = TraCIScenarioManagerAccess().get();
                 if (traci && traci->isConnected()) {
                         std::stringstream nameBuilder; nameBuilder << o->text << " " << ev.getUniqueNumber();
                         traci->getCommandInterface()->addPoi(nameBuilder.str(), "Annotation", TraCIColor::fromTkColor(o->color), 6, traci->omnet2traci(o->pos));
                         annotation->traciPoiIds.push_back(nameBuilder.str());
                 }
         }
         else if (const Line* l = dynamic_cast<const Line*>(annotation)) {
                 if (ev.isGUI()) {
                         cModule* mod = createDummyModuleLine(l->p1, l->p2, l->color);
                         annotation->dummyObjects.push_back(mod);
                 }
                 TraCIScenarioManager* traci = TraCIScenarioManagerAccess().get();
                 if (traci && traci->isConnected()) {
                         std::list<Coord> coords; coords.push_back(l->p1); coords.push_back(l->p2);
                         std::stringstream nameBuilder; nameBuilder << "Annotation" << ev.getUniqueNumber();
                         traci->getCommandInterface()->addPolygon(nameBuilder.str(), "Annotation", TraCIColor::fromTkColor(l->color), false, 5, traci->omnet2traci(coords));
                         annotation->traciLineIds.push_back(nameBuilder.str());
                 }
         }
         else if (const Polygon* p = dynamic_cast<const Polygon*>(annotation)) {
                 ASSERT(p->coords.size() >= 2);
                 if (ev.isGUI()) {
                         Coord lastCoords = *p->coords.rbegin();
                         for (std::list<Coord>::const_iterator i = p->coords.begin(); i != p->coords.end(); ++i) {
                                 Coord c1 = *i;
                                 Coord c2 = lastCoords;
                                 lastCoords = c1;
                                 cModule* mod = createDummyModuleLine(c1, c2, p->color);
                                 annotation->dummyObjects.push_back(mod);
                         }
                 }
                 TraCIScenarioManager* traci = TraCIScenarioManagerAccess().get();
                 if (traci && traci->isConnected()) {
                         std::stringstream nameBuilder; nameBuilder << "Annotation" << ev.getUniqueNumber();
                         traci->getCommandInterface()->addPolygon(nameBuilder.str(), "Annotation", TraCIColor::fromTkColor(p->color), false, 4, traci->omnet2traci(p->coords));
                         annotation->traciPolygonsIds.push_back(nameBuilder.str());
                 }
         }
         else {
                 error("unknown Annotation type");
         }
 }
void AnnotationManager::showAll (Group * group = 0)
Definition at line 402 of file AnnotationManager.cc.
Referenced by handleParameterChange().
{
         for (Annotations::const_iterator i = annotations.begin(); i != annotations.end(); ++i) {
                 if ((!group) || ((*i)->group == group)) show(*i);
         }
 }
Member Data Documentation
Annotations Veins::AnnotationManager::annotations protected
Definition at line 138 of file AnnotationManager.h.
Referenced by drawLine(), drawPoint(), drawPolygon(), erase(), eraseAll(), hideAll(), initialize(), showAll(), and ~AnnotationManager().
cXMLElement* Veins::AnnotationManager::annotationsXml protected
annotations to add at startup
Definition at line 134 of file AnnotationManager.h.
Referenced by initialize().
bool Veins::AnnotationManager::debug protected
whether to emit debug messages
Definition at line 133 of file AnnotationManager.h.
Referenced by initialize().
Groups Veins::AnnotationManager::groups protected
Definition at line 139 of file AnnotationManager.h.
Referenced by createGroup(), initialize(), and ~AnnotationManager().
std::list<cMessage*> Veins::AnnotationManager::scheduledEraseEvts protected
Definition at line 136 of file AnnotationManager.h.
Referenced by handleSelfMsg(), initialize(), scheduleErase(), and ~AnnotationManager().
The documentation for this class was generated from the following files:
AnnotationManager.h
AnnotationManager.cc