Veins Framework: ConstantSimpleConstMapping Class Reference
ConstantSimpleConstMapping Class Reference
Represents a constant mathematical mapping (f(x) = c)
#include <MappingUtils.h>
Public Member Functions
ConstantSimpleConstMapping (const DimensionSet &dims, argument_value_cref_t val)
ConstantSimpleConstMapping (const DimensionSet &dims, const Argument &key, argument_value_cref_t val)
virtual argument_value_t getValue (const Argument &pos) const
Returns the value of the mapping at the passed position.
const argument_value_t getValue () const
Returns the value of this constant mapping.
void setValue (argument_value_cref_t val)
Sets the value of this constant mapping.
ConstMapping * constClone () const
creates a clone of this mapping.
Public Member Functions inherited from SimpleConstMapping
virtual ConstMappingIterator * createConstIterator () const
Returns a pointer of a new Iterator which is able to iterate over the Mapping.
virtual ConstMappingIterator * createConstIterator (const Argument &pos) const
Returns a pointer of a new Iterator which is able to iterate over the Mapping.
SimpleConstMapping (const DimensionSet &dims)
Initializes a not yet iterateable SimpleConstmapping with the passed DimensionSet as domain.
SimpleConstMapping (const DimensionSet &dims, const Argument &key)
Fully initializes this mapping with the passed position as key entry.
SimpleConstMapping (const DimensionSet &dims, const Argument &key1, const Argument &key2)
Fully initializes this mapping with the passed two positions as key entries.
SimpleConstMapping (const DimensionSet &dims, const Argument &min, const Argument &max, const Argument &interval)
Fully initializes this mapping with the key entries defined by the passed min, max and interval values.
void initializeArguments (const Argument &key)
Initializes the key entry set with the passed position as entry.
void initializeArguments (const Argument &key1, const Argument &key2)
Initializes the key entry set with the passed two positions as entries.
void initializeArguments (const Argument &min, const Argument &max, const Argument &interval)
Initializes the key entry set with the passed min, max and interval-Arguments.
Public Member Functions inherited from ConstMapping
ConstMapping ()
Initializes the ConstMapping with a the time dimension as domain.
ConstMapping (const DimensionSet &dimSet)
Initializes the ConstMapping with the passed DimensionSet as Domain.
virtual ~ConstMapping ()
argument_value_t operator[] (const Argument &pos) const
Returns the value of this Mapping at the position specified by the passed Argument.
const DimensionSet & getDimensionSet () const
Returns this Mappings domain as DimensionSet.
template<class stream >
stream & print (stream &out, argument_value_cref_t lTimeScale=argument_value_t(1000), argument_value_cref_t lLeftColScale=Argument::MappedOne, const std::string &sTableHead=std::string("o\\ms"), const Dimension *const pOnlyDim=NULL) const
Prints the Mapping to an output stream.
Protected Attributes
argument_value_t value
Protected Attributes inherited from SimpleConstMapping
KeyEntrySet keyEntries
A set of Arguments defining the "points of interest" an iterator should iterate over.
Protected Attributes inherited from ConstMapping
DimensionSet dimensions
The dimensions of this mappings domain.
Additional Inherited Members
Public Types inherited from ConstMapping
typedef Argument::mapped_type argument_value_t
typedef Argument::mapped_type_cref argument_value_cref_t
Protected Types inherited from SimpleConstMapping
typedef std::set< Argument > KeyEntrySet
Type for a set of Arguments defining key entries.
Protected Member Functions inherited from SimpleConstMapping
void createKeyEntries (const Argument &from, const Argument &to, const Argument &step, Argument &pos)
Utility method to fill add range of key entries in the time dimension to the key entry set.
void createKeyEntries (const Argument &from, const Argument &to, const Argument &step, DimensionSet::const_iterator curDim, Argument &pos)
Utility method to fill add range of key entries in the passed dimension (and recursively its sub dimensions) to the key entry set.
Detailed Description
Represents a constant mathematical mapping (f(x) = c)
Returns the same value for every point in any dimension.
Author
Karl Wessel
Definition at line 764 of file MappingUtils.h.
Constructor & Destructor Documentation
ConstantSimpleConstMapping::ConstantSimpleConstMapping (const DimensionSet & dims, argument_value_cref_t val) inline
Definition at line 769 of file MappingUtils.h.
                                                                                        :
                 SimpleConstMapping(dims), value(val) {}
ConstantSimpleConstMapping::ConstantSimpleConstMapping (const DimensionSet & dims, const Argument & key, argument_value_cref_t val) inline
Definition at line 772 of file MappingUtils.h.
                                                                                      :
                 SimpleConstMapping(dims, key), value(val) {}
Member Function Documentation
ConstMapping* ConstantSimpleConstMapping::constClone () const inline virtual
creates a clone of this mapping.
This method has to be implemented by every subclass.
Implements SimpleConstMapping.
Definition at line 793 of file MappingUtils.h.
{
                 return new ConstantSimpleConstMapping(dimensions, value);
         }
virtual argument_value_t ConstantSimpleConstMapping::getValue (const Argument & pos) const inline virtual
Returns the value of the mapping at the passed position.
This method has to be implemented by every subclass and should only have constant complexity.
Implements SimpleConstMapping.
Definition at line 777 of file MappingUtils.h.
Referenced by MultiDimMapping< Linear >::createSubSignal(), MultiDimMapping< Linear >::MultiDimMapping(), and MultiDimMapping< Linear >::operator=().
{
                 return value;
         }
const argument_value_t ConstantSimpleConstMapping::getValue () const inline
Returns the value of this constant mapping.
Definition at line 784 of file MappingUtils.h.
{
                 return value;
         }
void ConstantSimpleConstMapping::setValue (argument_value_cref_t val) inline
Sets the value of this constant mapping.
Definition at line 791 of file MappingUtils.h.
 { value = val; }
Member Data Documentation
argument_value_t ConstantSimpleConstMapping::value protected
Definition at line 766 of file MappingUtils.h.
The documentation for this class was generated from the following file:
MappingUtils.h