Veins Framework: BaseMacLayer Class Reference
BaseMacLayer Class Reference
A very simple MAC module template which provides de- and encapsulation of messages using the standard addresses.
#include <BaseMacLayer.h>
Public Types
enum BaseMacMessageKinds { LAST_BASE_MAC_MESSAGE_KIND = 23000 }
Message kinds used by this layer.
enum BaseMacControlKinds { TX_OVER = 23500, PACKET_DROPPED, LAST_BASE_MAC_CONTROL_KIND }
Control message kinds used by this layer.
Public Member Functions
BaseMacLayer ()
BaseMacLayer (unsigned stacksize)
virtual void initialize (int)
Initialization of the module and some variables.
const LAddress::L2Type & getMACAddress ()
Returns the MAC address of this MAC module.
Public Member Functions inherited from BaseLayer
BaseLayer ()
BaseLayer (unsigned stacksize)
virtual ~BaseLayer ()
virtual void handleMessage (cMessage *)
Called every time a message arrives.
virtual void finish ()
Called when the simulation has finished.
Public Member Functions inherited from Veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from BaseModule
BaseModule ()
Function to get the logging name of id.
BaseModule (unsigned stacksize)
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed.
Protected Member Functions
virtual void registerInterface ()
Registers this bridge's NIC with INET's InterfaceTable.
virtual void handleUpperMsg (cMessage *msg)
Handle messages comming from the network layer.
virtual void handleLowerMsg (cMessage *msg)
If message arrives from lower layer, check whether it is for us.
virtual void handleSelfMsg (cMessage *msg)
Handle self messages such as timer...
virtual void handleLowerControl (cMessage *msg)
Handle control messages from lower layer.
virtual void handleUpperControl (cMessage *msg)
Handle control messages from upper layer.
virtual cPacket * decapsMsg (MacPkt *)
decapsulate the network message from the MacPkt
virtual MacPkt * encapsMsg (cPacket *)
Encapsulate the NetwPkt into an MacPkt.
virtual Signal * createSignal (simtime_t_cref start, simtime_t_cref length, double power, double bitrate)
Creates a simple Signal defined over time with the passed parameters.
Mapping * createConstantMapping (simtime_t_cref start, simtime_t_cref end, Argument::mapped_type_cref value)
Creates a simple Mapping with a constant curve progression at the passed value.
Mapping * createRectangleMapping (simtime_t_cref start, simtime_t_cref end, Argument::mapped_type_cref value)
Creates a simple Mapping with a constant curve progression at the passed value and discontinuities at the boundaries.
ConstMapping * createSingleFrequencyMapping (simtime_t_cref start, simtime_t_cref end, Argument::mapped_type_cref centerFreq, Argument::mapped_type_cref bandWith, Argument::mapped_type_cref value)
Creates a Mapping defined over time and frequency with constant power in a certain frequency band.
BaseConnectionManager * getConnectionManager ()
Returns a pointer to this MACs NICs ConnectionManager module.
virtual const LAddress::L2Type & getUpperDestinationFromControlInfo (const cObject *const pCtrlInfo)
Extracts the MAC address from the "control info" structure (object).
virtual cObject *const setUpControlInfo (cMessage *const pMsg, const LAddress::L2Type &pSrcAddr)
Attaches a "control info" (MacToNetw) structure (object) to the message pMsg.
virtual cObject *const setDownControlInfo (cMessage *const pMsg, Signal *const pSignal)
Attaches a "control info" (MacToPhy) structure (object) to the message pMsg.
Protected Member Functions inherited from BaseLayer
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from Veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
Protected Attributes
MacToPhyInterface * phy
Handler to the physical layer.
int headerLength
Pointer to the arp module.
LAddress::L2Type myMacAddr
MAC address.
bool coreDebug
debug this core module?
int phyHeaderLength
The length of the phy header (in bits).
Protected Attributes inherited from BaseLayer
PassedMessage * passedMsg
The last message passed through this layer.
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
Protected Attributes inherited from Veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from BaseModule
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Static Public Attributes inherited from BaseLayer
static const simsignalwrap_t catPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_PACKET_NAME)
SignalID for packets.
static const simsignalwrap_t catPassedMsgSignal = simsignalwrap_t(MIXIM_SIGNAL_PASSEDMSG_NAME)
Signal for passed messages.
static const simsignalwrap_t catDroppedPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_DROPPEDPACKET_NAME)
Signal for dropped packets.
Static Protected Attributes inherited from BaseModule
static const simsignalwrap_t catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME)
Stores the category of the HostState.
Detailed Description
A very simple MAC module template which provides de- and encapsulation of messages using the standard addresses.
It also provides basic handling of lower layer messages.
Author
Daniel Willkomm, Karl Wessel
Definition at line 45 of file BaseMacLayer.h.
Member Enumeration Documentation
enum BaseMacLayer::BaseMacControlKinds
Control message kinds used by this layer.
Enumerator
TX_OVER
Indicates the end of a transmission.
PACKET_DROPPED
Tells the netw layer that a packet to be sent has been dropped.
LAST_BASE_MAC_CONTROL_KIND
Stores the id on which classes extending BaseMac should continue their own control kinds.
Definition at line 55 of file BaseMacLayer.h.
{
         TX_OVER = 23500,
         PACKET_DROPPED,
         LAST_BASE_MAC_CONTROL_KIND,
     };
enum BaseMacLayer::BaseMacMessageKinds
Message kinds used by this layer.
Enumerator
LAST_BASE_MAC_MESSAGE_KIND
Stores the id on which classes extending BaseMac should continue their own message kinds.
Definition at line 49 of file BaseMacLayer.h.
{
         LAST_BASE_MAC_MESSAGE_KIND = 23000,
     };
Constructor & Destructor Documentation
BaseMacLayer::BaseMacLayer () inline
Definition at line 97 of file BaseMacLayer.h.
       : BaseLayer()
       , phy(NULL)
       , myMacAddr(LAddress::L2NULL)
     {}
BaseMacLayer::BaseMacLayer (unsigned stacksize) inline
Definition at line 102 of file BaseMacLayer.h.
       : BaseLayer(stacksize)
       , phy(NULL)
       , myMacAddr(LAddress::L2NULL)
     {}
Member Function Documentation
Mapping * BaseMacLayer::createConstantMapping (simtime_t_cref start, simtime_t_cref end, Argument::mapped_type_cref value) protected
Creates a simple Mapping with a constant curve progression at the passed value.
Used by "createSignal" to create the bitrate mapping.
Definition at line 244 of file BaseMacLayer.cc.
Referenced by createSignal().
 {
         //create mapping over time
         Mapping* m = MappingUtils::createMapping(Argument::MappedZero, DimensionSet::timeDomain, Mapping::LINEAR);
         //set position Argument
         Argument startPos(start);
         //set mapping at position
         m->setValue(startPos, value);
         //set position Argument
         Argument endPos(end);
         //set mapping at position
         m->setValue(endPos, value);
         return m;
 }
Mapping * BaseMacLayer::createRectangleMapping (simtime_t_cref start, simtime_t_cref end, Argument::mapped_type_cref value) protected
Creates a simple Mapping with a constant curve progression at the passed value and discontinuities at the boundaries.
Used by "createSignal" to create the power mapping.
Definition at line 264 of file BaseMacLayer.cc.
Referenced by createSignal().
 {
         //create mapping over time
         Mapping* m = MappingUtils::createMapping(DimensionSet::timeDomain, Mapping::LINEAR);
         //set position Argument
         Argument startPos(start);
         //set discontinuity at position
         MappingUtils::addDiscontinuity(m, startPos, Argument::MappedZero, MappingUtils::post(start), value);
         //set position Argument
         Argument endPos(end);
         //set discontinuity at position
         MappingUtils::addDiscontinuity(m, endPos, Argument::MappedZero, MappingUtils::pre(end), value);
         return m;
 }
Signal * BaseMacLayer::createSignal (simtime_t_cref start, simtime_t_cref length, double power, double bitrate) protected virtual
Creates a simple Signal defined over time with the passed parameters.
Convenience method to be able to create the appropriate Signal for the MacToPhyControlInfo without needing to care about creating Mappings.
NOTE: The created signal's transmission-power is a rectangular function. This method uses MappingUtils::addDiscontinuity to represent the discontinuities at the beginning and end of this rectangular function. Because of this the created mapping which represents the signal's transmission-power is still zero at the exact start and end. Please see the method MappingUtils::addDiscontinuity for the reason.
Definition at line 227 of file BaseMacLayer.cc.
 {
         simtime_t end = start + length;
         //create signal with start at current simtime and passed length
         Signal* s = new Signal(start, length);
         //create and set tx power mapping
         Mapping* txPowerMapping = createRectangleMapping(start, end, power);
         s->setTransmissionPower(txPowerMapping);
         //create and set bitrate mapping
         Mapping* bitrateMapping = createConstantMapping(start, end, bitrate);
         s->setBitrate(bitrateMapping);
         return s;
 }
ConstMapping * BaseMacLayer::createSingleFrequencyMapping (simtime_t_cref start, simtime_t_cref end, Argument::mapped_type_cref centerFreq, Argument::mapped_type_cref bandWith, Argument::mapped_type_cref value) protected
Creates a Mapping defined over time and frequency with constant power in a certain frequency band.
Definition at line 282 of file BaseMacLayer.cc.
Referenced by Mac1609_4::createSignal().
 {
         Mapping* res = MappingUtils::createMapping(Argument::MappedZero, DimensionSet::timeFreqDomain, Mapping::LINEAR);
         Argument pos(DimensionSet::timeFreqDomain);
         pos.setArgValue(Dimension::frequency, centerFreq - halfBandwidth);
         pos.setTime(start);
         res->setValue(pos, value);
         pos.setTime(end);
         res->setValue(pos, value);
         pos.setArgValue(Dimension::frequency, centerFreq + halfBandwidth);
         res->setValue(pos, value);
         pos.setTime(start);
         res->setValue(pos, value);
         return res;
 }
cPacket * BaseMacLayer::decapsMsg (MacPkt * msg) protected virtual
decapsulate the network message from the MacPkt
Decapsulates the network packet from the received MacPkt.
Definition at line 131 of file BaseMacLayer.cc.
Referenced by handleLowerMsg().
 {
     cPacket *m = msg->decapsulate();
     setUpControlInfo(m, msg->getSrcAddr());
     // delete the macPkt
     delete msg;
     coreEV << " message decapsulated " << endl;
     return m;
 }
MacPkt * BaseMacLayer::encapsMsg (cPacket * netwPkt) protected virtual
Encapsulate the NetwPkt into an MacPkt.
Encapsulates the received NetwPkt into a MacPkt and set all needed header fields.
Definition at line 145 of file BaseMacLayer.cc.
Referenced by handleUpperMsg().
 {
     MacPkt *pkt = new MacPkt(netwPkt->getName(), netwPkt->getKind());
     pkt->setBitLength(headerLength);
     // copy dest address from the Control Info attached to the network
     // message by the network layer
     cObject* cInfo = netwPkt->removeControlInfo();
     coreEV <<"CInfo removed, mac addr="<< getUpperDestinationFromControlInfo(cInfo) << endl;
     pkt->setDestAddr(getUpperDestinationFromControlInfo(cInfo));
     //delete the control info
     delete cInfo;
     //set the src address to own mac address (nic module getId())
     pkt->setSrcAddr(myMacAddr);
     //encapsulate the network packet
     pkt->encapsulate(netwPkt);
     coreEV <<"pkt encapsulated\n";
     return pkt;
 }
BaseConnectionManager * BaseMacLayer::getConnectionManager () protected
Returns a pointer to this MACs NICs ConnectionManager module.
Returns
pointer to the connection manager module
Definition at line 308 of file BaseMacLayer.cc.
{
         cModule* nic = getParentModule();
         return ChannelAccess::getConnectionManager(nic);
 }
const LAddress::L2Type& BaseMacLayer::getMACAddress () inline
Returns the MAC address of this MAC module.
Definition at line 114 of file BaseMacLayer.h.
 { return myMacAddr; }
const LAddress::L2Type & BaseMacLayer::getUpperDestinationFromControlInfo (const cObject *const pCtrlInfo) protected virtual
Extracts the MAC address from the "control info" structure (object).
Extract the destination MAC address from the "control info" which was prev. set by NetwToMacControlInfo::setControlInfo().
Parameters
pCtrlInfo The "control info" structure (object) prev. set by NetwToMacControlInfo::setControlInfo().
Returns
The MAC address of message receiver.
Definition at line 313 of file BaseMacLayer.cc.
Referenced by encapsMsg().
{
         return NetwToMacControlInfo::getDestFromControlInfo(pCtrlInfo);
 }
void BaseMacLayer::handleLowerControl (cMessage * msg) protected virtual
Handle control messages from lower layer.
Implements BaseLayer.
Reimplemented in Mac1609_4.
Definition at line 212 of file BaseMacLayer.cc.
 {
         switch (msg->getKind())
         {
                 case MacToPhyInterface::TX_OVER:
                         msg->setKind(TX_OVER);
                         sendControlUp(msg);
                         break;
                 default:
                         EV << "BaseMacLayer does not handle control messages of this type (name was "<<msg->getName()<<")\n";
                         delete msg;
                         break;
         }
 }
void BaseMacLayer::handleLowerMsg (cMessage * msg) protected virtual
If message arrives from lower layer, check whether it is for us.
This basic implementation just forwards all message that are broadcast (destAddr = L2BROADCAST) or destined for this node (destAddr = nic module getId()) to the network layer.
Send it up if yes.
See Also
sendUp
Implements BaseLayer.
Reimplemented in Mac1609_4.
Definition at line 191 of file BaseMacLayer.cc.
 {
     MacPkt*          mac  = static_cast<MacPkt *>(msg);
     LAddress::L2Type dest = mac->getDestAddr();
     LAddress::L2Type src  = mac->getSrcAddr();
     //only foward to upper layer if message is for me or broadcast
     if((dest == myMacAddr) || LAddress::isL2Broadcast(dest)) {
                 coreEV << "message with mac addr " << src
                            << " for me (dest=" << dest
                            << ") -> forward packet to upper layer\n";
                 sendUp(decapsMsg(mac));
     }
     else{
                 coreEV << "message with mac addr " << src
                            << " not for me (dest=" << dest
                            << ") -> delete (my MAC="<<myMacAddr<<")\n";
                 delete mac;
     }
 }
virtual void BaseMacLayer::handleSelfMsg (cMessage * msg) inline protected virtual
Handle self messages such as timer...
Implements BaseLayer.
Reimplemented in Mac1609_4.
Definition at line 141 of file BaseMacLayer.h.
{
         error("BaseMacLayer does not handle self messages");
     };
virtual void BaseMacLayer::handleUpperControl (cMessage * msg) inline protected virtual
Handle control messages from upper layer.
Implements BaseLayer.
Reimplemented in Mac1609_4.
Definition at line 146 of file BaseMacLayer.h.
{
         error("BaseMacLayer does not handle control messages from upper layers");
     };
void BaseMacLayer::handleUpperMsg (cMessage * mac) protected virtual
Handle messages comming from the network layer.
Redefine this function if you want to process messages from upper layers before they are send to lower layers.
Here is the place to implement a real medium access functionality.
If message arrives from upper layer, make a MAC packet from it (encapsMsg) and send it down (sendDown).
See Also
encapsMsg, sendDown
To forward the message to lower layers after processing it please use sendDown. It will take care of anything needed
Implements BaseLayer.
Reimplemented in Mac1609_4.
Definition at line 177 of file BaseMacLayer.cc.
 {
         assert(dynamic_cast<cPacket*>(mac));
     sendDown(encapsMsg(static_cast<cPacket*>(mac)));
 }
void BaseMacLayer::initialize (int stage) virtual
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseLayer.
Reimplemented from BaseLayer.
Reimplemented in Mac1609_4.
Definition at line 52 of file BaseMacLayer.cc.
Referenced by Mac1609_4::initialize().
 {
     BaseLayer::initialize(stage);
     if(stage==0)
     {
         // get handle to phy layer
         if ((phy = FindModule<MacToPhyInterface*>::findSubModule(getParentModule())) == NULL) {
                 error("Could not find a PHY module.");
         }
         headerLength    = par("headerLength");
         phyHeaderLength = phy->getPhyHeaderLength();
         hasPar("coreDebug") ? coreDebug = par("coreDebug").boolValue() : coreDebug = false;
     }
     if (myMacAddr == LAddress::L2NULL) {
         // see if there is an addressing module available
         // otherwise use NIC modules id as MAC address
         AddressingInterface* addrScheme = FindModule<AddressingInterface*>::findSubModule(findHost());
         if(addrScheme) {
             myMacAddr = addrScheme->myMacAddr(this);
         } else {
             const std::string addressString = par("address").stringValue();
             if (addressString.empty() || addressString == "auto")
                 myMacAddr = LAddress::L2Type(getParentModule()->getId());
             else
                 myMacAddr = LAddress::L2Type(addressString.c_str());
             // use streaming operator for string conversion, this makes it more
             // independent from the myMacAddr type
             std::ostringstream oSS; oSS << myMacAddr;
             par("address").setStringValue(oSS.str());
         }
         registerInterface();
     }
 }
void BaseMacLayer::registerInterface () protected virtual
Registers this bridge's NIC with INET's InterfaceTable.
Definition at line 88 of file BaseMacLayer.cc.
Referenced by initialize().
 {
 #ifdef MIXIM_INET
     IInterfaceTable *ift = InterfaceTableAccess().getIfExists();
     if (ift) {
         cModule* nic = getParentModule();
         InterfaceEntry *e = new InterfaceEntry();
         // interface name: NIC module's name without special
         // characters ([])
         char *interfaceName = new char[strlen(nic->getFullName()) + 1];
         char *d = interfaceName;
         for (const char *s = nic->getFullName(); *s; s++)
             if (isalnum(*s))
                 *d++ = *s;
         *d = '\0';
         e->setName(interfaceName);
         delete [] interfaceName;
         // this MAC address must be the same as the one in BaseMacLayer
         e->setMACAddress(myMacAddr);
         // generate interface identifier for IPv6
         e->setInterfaceToken(myMacAddr.formInterfaceIdentifier());
         // MTU on 802.11 = ?
         e->setMtu(1500);            // FIXME
         // capabilities
         e->setBroadcast(true);
         e->setMulticast(true);
         e->setPointToPoint(false);
         // add
         ift->addInterface(e, this);
     }
 #endif
 }
cObject *const BaseMacLayer::setDownControlInfo (cMessage *const pMsg, Signal *const pSignal) protected virtual
Attaches a "control info" (MacToPhy) structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the signal.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters
pMsg The message where the "control info" shall be attached.
pSignal The signal which should be send.
Definition at line 328 of file BaseMacLayer.cc.
 {
         return MacToPhyControlInfo::setControlInfo(pMsg, pSignal);
 }
cObject *const BaseMacLayer::setUpControlInfo (cMessage *const pMsg, const LAddress::L2Type & pSrcAddr) protected virtual
Attaches a "control info" (MacToNetw) structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the destination MAC address.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters
pMsg The message where the "control info" shall be attached.
pSrcAddr The MAC address of the message receiver.
Definition at line 320 of file BaseMacLayer.cc.
Referenced by decapsMsg().
 {
         return MacToNetwControlInfo::setControlInfo(pMsg, pSrcAddr);
 }
Member Data Documentation
bool BaseMacLayer::coreDebug protected
debug this core module?
Definition at line 84 of file BaseMacLayer.h.
Referenced by initialize().
int BaseMacLayer::headerLength protected
Pointer to the arp module.
Length of the MacPkt header
Definition at line 76 of file BaseMacLayer.h.
Referenced by encapsMsg(), and initialize().
LAddress::L2Type BaseMacLayer::myMacAddr protected
MAC address.
Definition at line 81 of file BaseMacLayer.h.
Referenced by encapsMsg(), handleLowerMsg(), initialize(), and registerInterface().
MacToPhyInterface* BaseMacLayer::phy protected
Handler to the physical layer.
Definition at line 68 of file BaseMacLayer.h.
Referenced by Mac1609_4::handleLowerControl(), Mac1609_4::handleSelfMsg(), and initialize().
int BaseMacLayer::phyHeaderLength protected
The length of the phy header (in bits).
Since the MAC layer has to create the signal for a transmission it has to know the total length of the packet and therefore needs the length of the phy header.
Definition at line 93 of file BaseMacLayer.h.
Referenced by Mac1609_4::createSignal(), and initialize().
The documentation for this class was generated from the following files:
BaseMacLayer.h
BaseMacLayer.cc