Veins Framework: Veins::TraCIMobility Class Reference
Veins::TraCIMobility Class Reference
#include <TraCIMobility.h>
Classes
class Statistics
Public Member Functions
TraCIMobility ()
virtual void initialize (int)
Initializes mobility model parameters.
virtual void finish ()
Delete dynamically allocated objects.
virtual void handleSelfMsg (cMessage *msg)
Called upon arrival of a self messages.
virtual void preInitialize (std::string external_id, const Coord &position, std::string road_id="", double speed=-1, double angle=-1)
virtual void nextPosition (const Coord &position, std::string road_id="", double speed=-1, double angle=-1, TraCIScenarioManager::VehicleSignal signals=TraCIScenarioManager::VEH_SIGNAL_UNDEF)
virtual void changePosition ()
virtual void changeParkingState (bool)
virtual void updateDisplayString ()
virtual void setExternalId (std::string external_id)
virtual std::string getExternalId () const
virtual double getAntennaPositionOffset () const
virtual Coord getPositionAt (const simtime_t &t) const
virtual bool getParkingState () const
virtual std::string getRoadId () const
virtual double getSpeed () const
virtual
TraCIScenarioManager::VehicleSignal getSignals () const
virtual double getAngleRad () const
returns angle in rads, 0 being east, with -M_PI <= angle < M_PI.
virtual TraCIScenarioManager * getManager () const
virtual TraCICommandInterface * getCommandInterface () const
void commandSetSpeedMode (int32_t bitset)
void commandSetSpeed (double speed)
void commandSetColor (const TraCIColor &color)
void commandSlowDown (double speed, int duration)
void commandChangeRoute (std::string roadId, double travelTime)
void commandNewRoute (std::string roadId)
void commandParkVehicle ()
double commandDistanceRequest (Coord position1, Coord position2, bool returnDrivingDistance)
void commandStopNode (std::string roadId, double pos, uint8_t laneid, double radius, double waittime)
std::list< std::string > commandGetPolygonIds ()
std::string commandGetPolygonTypeId (std::string polyId)
std::list< Coord > commandGetPolygonShape (std::string polyId)
void commandSetPolygonShape (std::string polyId, std::list< Coord > points)
bool commandAddVehicle (std::string vehicleId, std::string vehicleTypeId, std::string routeId, simtime_t emitTime_st=-TraCICommandInterface::DEPART_NOW, double emitPosition=-TraCICommandInterface::DEPART_POS_BASE, double emitSpeed=-TraCICommandInterface::DEPART_SPEED_MAX, int8_t emitLane=-TraCICommandInterface::DEPART_LANE_BEST_FREE)
int commandGetLaneIndex ()
std::string commandGetLaneId ()
bool commandChangeVehicleRoute (std::list< std::string > edges)
double commandGetLaneLength (std::string laneId)
Public Member Functions inherited from BaseMobility
BaseMobility ()
BaseMobility (unsigned stacksize)
virtual void handleMessage (cMessage *msg)
This modules should only receive self-messages.
virtual Coord getCurrentPosition () const
Returns the current position at the current simulation time.
virtual Coord getCurrentSpeed () const
Returns the current speed at the current simulation time.
Public Member Functions inherited from Veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from BaseModule
BaseModule ()
Function to get the logging name of id.
BaseModule (unsigned stacksize)
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed.
Protected Member Functions
virtual void fixIfHostGetsOutside ()
called after each read to check for (and handle) invalid positions
double calculateCO2emission (double v, double a) const
Returns the amount of CO2 emissions in grams/second, calculated for an average Car.
Coord calculateAntennaPosition (const Coord &vehiclePos) const
Calculates where the antenna of this car is, given its front bumper position.
Protected Member Functions inherited from BaseMobility
virtual int iconSizeTagToSize (const char *tag)
Maps the passed icon size tag (is) to an actual size in pixels.
virtual const char * iconSizeToTag (double size)
Maps the passed size in pixels to an appropriate icon size tag (is).
virtual void handleBorderMsg (cMessage *)
Called upon arrival of a border messages.
virtual void makeMove ()
Moves the host.
virtual void updatePosition ()
Update the position information for this node.
double playgroundSizeX () const
Returns the width of the playground.
double playgroundSizeY () const
Returns the height of the playground.
double playgroundSizeZ () const
Returns the height of the playground.
Coord getRandomPosition ()
Random position somewhere in the playground.
bool handleIfOutside (BorderPolicy, Coord &, Coord &, Coord &, double &)
Main border handling function.
BorderHandling checkIfOutside (Coord, Coord &)
Checks whether the host is outside the playground and returns where.
void goToBorder (BorderPolicy, BorderHandling, Coord &, Coord &)
calculate the step to reach the border
void reflectCoordinate (BorderHandling border, Coord &c)
helperfunction for reflectIfOutside() to reflect a Coordinate at a given border
void reflectIfOutside (BorderHandling, Coord &, Coord &, Coord &, double &)
Utility function to reflect the node if it goes outside the playground.
void wrapIfOutside (BorderHandling, Coord &, Coord &)
Utility function to wrap the node to the opposite edge (torus) if it goes outside the playground.
void placeRandomlyIfOutside (Coord &)
Utility function to place the node randomly if it goes outside the playground.
Protected Member Functions inherited from Veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
Protected Attributes
bool debug
whether to emit debug messages
int accidentCount
number of accidents
cOutVector currentPosXVec
vector plotting posx
cOutVector currentPosYVec
vector plotting posy
cOutVector currentSpeedVec
vector plotting speed
cOutVector currentAccelerationVec
vector plotting acceleration
cOutVector currentCO2EmissionVec
vector plotting current CO2 emission
Statistics statistics
everything statistics-related
bool isPreInitialized
true if preInitialize() has been called immediately before initialize()
std::string external_id
updated by setExternalId()
double antennaPositionOffset
front offset for the antenna on this car
simtime_t lastUpdate
updated by nextPosition()
Coord roadPosition
position of front bumper, updated by nextPosition()
std::string road_id
updated by nextPosition()
double speed
updated by nextPosition()
double angle
updated by nextPosition()
TraCIScenarioManager::VehicleSignal signals
updated by nextPosition()
cMessage * startAccidentMsg
cMessage * stopAccidentMsg
TraCIScenarioManager * manager
double last_speed
bool isParking
Protected Attributes inherited from BaseMobility
BaseWorldUtility * world
Pointer to BaseWorldUtility – these two must know each other.
Move move
Stores the current position and move pattern of the host.
simtime_t updateInterval
Time interval (in seconds) to update the hosts position.
cMessage * moveMsg
Self message to trigger movement.
bool coreDebug
debug this core module?
bool scaleNodeByDepth
Enable depth dependent scaling of nodes when 3d and tkenv is used.
double playgroundScaleX
Scaling of the playground in X direction.
double playgroundScaleY
Scaling of the playground in Y direction.
double origDisplayWidth
The original width the node is displayed width.
double origDisplayHeight
The original height the node is displayed width.
double origIconSize
The original size of the icon of the node.
Protected Attributes inherited from Veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from BaseModule
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Static Protected Attributes
static const simsignalwrap_t parkingStateChangedSignal = simsignalwrap_t(TRACI_SIGNAL_PARKING_CHANGE_NAME)
Static Protected Attributes inherited from BaseMobility
static const simsignalwrap_t mobilityStateChangedSignal = simsignalwrap_t(MIXIM_SIGNAL_MOBILITY_CHANGE_NAME)
Store the category of HostMove.
Static Protected Attributes inherited from BaseModule
static const simsignalwrap_t catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME)
Stores the category of the HostState.
Additional Inherited Members
Public Types inherited from BaseMobility
enum BorderPolicy { REFLECT, WRAP, PLACERANDOMLY, RAISEERROR }
Selects how a node should behave if it reaches the edge of the playground.
enum BaseMobilityMsgKinds { MOVE_HOST = 21311, MOVE_TO_BORDER, LAST_BASE_MOBILITY_KIND }
The kind field of messages.
enum BorderHandling {
NOWHERE, X_SMALLER, X_BIGGER, Y_SMALLER,
Y_BIGGER, Z_SMALLER, Z_BIGGER
}
Specifies which border actually has been reached.
Detailed Description
Definition at line 53 of file TraCIMobility.h.
Constructor & Destructor Documentation
Veins::TraCIMobility::TraCIMobility () inline
Definition at line 72 of file TraCIMobility.h.
 : BaseMobility(), isPreInitialized(false) {}
Member Function Documentation
Coord TraCIMobility::calculateAntennaPosition (const Coord & vehiclePos) const protected
Calculates where the antenna of this car is, given its front bumper position.
Definition at line 352 of file TraCIMobility.cc.
Referenced by changePosition(), initialize(), and preInitialize().
{
         Coord corPos;
         if (antennaPositionOffset >= 0.001) {
                 //calculate antenna position of vehicle according to antenna offset
                 corPos = Coord(vehiclePos.x - antennaPositionOffset*cos(angle), vehiclePos.y + antennaPositionOffset*sin(angle), vehiclePos.z);
         } else {
                 corPos = Coord(vehiclePos.x, vehiclePos.y, vehiclePos.z);
         }
         return corPos;
 }
double TraCIMobility::calculateCO2emission (double v, double a) const protected
Returns the amount of CO2 emissions in grams/second, calculated for an average Car.
Parameters
v speed in m/s
a acceleration in m/s^2
Returns
emission in g/s
Definition at line 319 of file TraCIMobility.cc.
Referenced by changePosition().
{
         // Calculate CO2 emission parameters according to:
         // Cappiello, A. and Chabini, I. and Nam, E.K. and Lue, A. and Abou Zeid, M., "A statistical model of vehicle emissions and fuel consumption," IEEE 5th International Conference on Intelligent Transportation Systems (IEEE ITSC), pp. 801-809, 2002
         double A = 1000 * 0.1326; // W/m/s
         double B = 1000 * 2.7384e-03; // W/(m/s)^2
         double C = 1000 * 1.0843e-03; // W/(m/s)^3
         double M = 1325.0; // kg
         // power in W
         double P_tract = A*v + B*v*v + C*v*v*v + M*a*v; // for sloped roads: +M*g*sin_theta*v
         /*
         // "Category 7 vehicle" (e.g. a '92 Suzuki Swift)
         double alpha = 1.01;
         double beta = 0.0162;
         double delta = 1.90e-06;
         double zeta = 0.252;
         double alpha1 = 0.985;
         */
         // "Category 9 vehicle" (e.g. a '94 Dodge Spirit)
         double alpha = 1.11;
         double beta = 0.0134;
         double delta = 1.98e-06;
         double zeta = 0.241;
         double alpha1 = 0.973;
         if (P_tract <= 0) return alpha1;
         return alpha + beta*v*3.6 + delta*v*v*v*(3.6*3.6*3.6) + zeta*a*v;
 }
void TraCIMobility::changeParkingState (bool newState) virtual
Definition at line 241 of file TraCIMobility.cc.
Referenced by Veins::TraCIScenarioManager::processSimSubscription().
 {
     isParking = newState;
     emit(parkingStateChangedSignal, this);
 }
void TraCIMobility::changePosition () virtual
Definition at line 196 of file TraCIMobility.cc.
Referenced by Veins::TraCIScenarioManager::addModule(), and nextPosition().
 {
         // ensure we're not called twice in one time step
         ASSERT(lastUpdate != simTime());
         // keep statistics (for current step)
         currentPosXVec.record(move.getStartPos().x);
         currentPosYVec.record(move.getStartPos().y);
         Coord nextPos = calculateAntennaPosition(roadPosition);
         nextPos.z = move.getCurrentPosition().z;
         // keep statistics (relative to last step)
         if (statistics.startTime != simTime()) {
                 simtime_t updateInterval = simTime() - this->lastUpdate;
                 double distance = move.getStartPos().distance(nextPos);
                 statistics.totalDistance += distance;
                 statistics.totalTime += updateInterval;
                 if (speed != -1) {
                         statistics.minSpeed = std::min(statistics.minSpeed, speed);
                         statistics.maxSpeed = std::max(statistics.maxSpeed, speed);
                         currentSpeedVec.record(speed);
                         if (last_speed != -1) {
                                 double acceleration = (speed - last_speed) / updateInterval;
                                 double co2emission = calculateCO2emission(speed, acceleration);
                                 currentAccelerationVec.record(acceleration);
                                 currentCO2EmissionVec.record(co2emission);
                                 statistics.totalCO2Emission+=co2emission * updateInterval.dbl();
                         }
                         last_speed = speed;
                 } else {
                         last_speed = -1;
                         speed = -1;
                 }
         }
         this->lastUpdate = simTime();
         move.setStart(Coord(nextPos.x, nextPos.y, move.getCurrentPosition().z)); // keep z position
         move.setDirectionByVector(Coord(cos(angle), -sin(angle)));
         move.setSpeed(speed);
         if (ev.isGUI()) updateDisplayString();
         fixIfHostGetsOutside();
         updatePosition();
 }
bool Veins::TraCIMobility::commandAddVehicle (std::string vehicleId, std::string vehicleTypeId, std::string routeId, simtime_t emitTime_st = -TraCICommandInterface::DEPART_NOW, double emitPosition = -TraCICommandInterface::DEPART_POS_BASE, double emitSpeed = -TraCICommandInterface::DEPART_SPEED_MAX, int8_t emitLane = -TraCICommandInterface::DEPART_LANE_BEST_FREE) inline
Definition at line 163 of file TraCIMobility.h.
{
                         return getCommandInterface()->addVehicle(vehicleId, vehicleTypeId, routeId, emitTime_st, emitPosition, emitSpeed, emitLane);
                 }
void Veins::TraCIMobility::commandChangeRoute (std::string roadId, double travelTime) inline
Definition at line 136 of file TraCIMobility.h.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), default_veins_TraCI::onData(), mfcv::onData(), minicurso_UFPI_TraCI::onData(), and minicurso_UFPI_TraCI::verifyAndSendCongestionMessage().
{
                         getCommandInterface()->changeRoute(getExternalId(), roadId, travelTime);
                 }
bool Veins::TraCIMobility::commandChangeVehicleRoute (std::list< std::string > edges) inline
Definition at line 172 of file TraCIMobility.h.
{
                         return getCommandInterface()->changeVehicleRoute(getExternalId(), edges);
                 }
double Veins::TraCIMobility::commandDistanceRequest (Coord position1, Coord position2, bool returnDrivingDistance) inline
Definition at line 145 of file TraCIMobility.h.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), and Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate().
{
                         return getCommandInterface()->distanceRequest(getManager()->omnet2traci(position1), getManager()->omnet2traci(position2), returnDrivingDistance);
                 }
std::string Veins::TraCIMobility::commandGetLaneId () inline
Definition at line 169 of file TraCIMobility.h.
Referenced by minicurso_UFPI_TraCI::onData(), and minicurso_UFPI_TraCI::verifyAndSendCongestionMessage().
{
                         return getCommandInterface()->getLaneId(getExternalId());
                 }
int Veins::TraCIMobility::commandGetLaneIndex () inline
Definition at line 166 of file TraCIMobility.h.
{
                         return getCommandInterface()->getLaneIndex(getExternalId());
                 }
double Veins::TraCIMobility::commandGetLaneLength (std::string laneId) inline
Definition at line 177 of file TraCIMobility.h.
Referenced by minicurso_UFPI_TraCI::onData(), and minicurso_UFPI_TraCI::verifyAndSendCongestionMessage().
{
                     return getCommandInterface()->getLaneLength(laneId);
                 }
std::list<std::string> Veins::TraCIMobility::commandGetPolygonIds () inline
Definition at line 151 of file TraCIMobility.h.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), and Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate().
{
                         return getCommandInterface()->getPolygonIds();
                 }
std::list<Coord> Veins::TraCIMobility::commandGetPolygonShape (std::string polyId) inline
Definition at line 157 of file TraCIMobility.h.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), and Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate().
{
                         return getManager()->traci2omnet(getCommandInterface()->getPolygonShape(polyId));
                 }
std::string Veins::TraCIMobility::commandGetPolygonTypeId (std::string polyId) inline
Definition at line 154 of file TraCIMobility.h.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), and Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate().
{
                         return getCommandInterface()->getPolygonTypeId(polyId);
                 }
void Veins::TraCIMobility::commandNewRoute (std::string roadId) inline
Definition at line 139 of file TraCIMobility.h.
{
                         getCommandInterface()->newRoute(getExternalId(), roadId);
                 }
void Veins::TraCIMobility::commandParkVehicle () inline
Definition at line 142 of file TraCIMobility.h.
{
                         getCommandInterface()->setVehicleParking(getExternalId());
                 }
void Veins::TraCIMobility::commandSetColor (const TraCIColor & color) inline
Definition at line 130 of file TraCIMobility.h.
{
                         getCommandInterface()->setColor(getExternalId(), color);
                 }
void Veins::TraCIMobility::commandSetPolygonShape (std::string polyId, std::list< Coord > points) inline
Definition at line 160 of file TraCIMobility.h.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), and Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate().
{
                         getCommandInterface()->setPolygonShape(polyId, getManager()->omnet2traci(points));
                 }
void Veins::TraCIMobility::commandSetSpeed (double speed) inline
Definition at line 127 of file TraCIMobility.h.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), and handleSelfMsg().
{
                         getCommandInterface()->setSpeed(getExternalId(), speed);
                 }
void Veins::TraCIMobility::commandSetSpeedMode (int32_t bitset) inline
Definition at line 124 of file TraCIMobility.h.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), and Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate().
{
                         getCommandInterface()->setSpeedMode(getExternalId(), bitset);
                 }
void Veins::TraCIMobility::commandSlowDown (double speed, int duration) inline
Definition at line 133 of file TraCIMobility.h.
{
                         getCommandInterface()->slowDown(getExternalId(),speed,duration);
                 }
void Veins::TraCIMobility::commandStopNode (std::string roadId, double pos, uint8_t laneid, double radius, double waittime) inline
Definition at line 148 of file TraCIMobility.h.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), and Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate().
{
                         getCommandInterface()->stopNode(getExternalId(), roadId, pos, laneid, radius, waittime);
                 }
void TraCIMobility::finish () virtual
Delete dynamically allocated objects.
Reimplemented from BaseMobility.
Definition at line 134 of file TraCIMobility.cc.
 {
         statistics.stopTime = simTime();
         statistics.recordScalars(*this);
         cancelAndDelete(startAccidentMsg);
         cancelAndDelete(stopAccidentMsg);
         isPreInitialized = false;
 }
void TraCIMobility::fixIfHostGetsOutside () protected virtual
called after each read to check for (and handle) invalid positions
Reimplemented from BaseMobility.
Definition at line 303 of file TraCIMobility.cc.
Referenced by changePosition().
 {
         Coord pos = move.getStartPos();
         Coord dummy = Coord::ZERO;
         double dum;
         bool outsideX = (pos.x < 0) || (pos.x >= playgroundSizeX());
         bool outsideY = (pos.y < 0) || (pos.y >= playgroundSizeY());
         bool outsideZ = (!world->use2D()) && ((pos.z < 0) || (pos.z >= playgroundSizeZ()));
         if (outsideX || outsideY || outsideZ) {
                 error("Tried moving host to (%f, %f) which is outside the playground", pos.x, pos.y);
         }
         handleIfOutside( RAISEERROR, pos, dummy, dummy, dum);
 }
virtual double Veins::TraCIMobility::getAngleRad () const inline virtual
returns angle in rads, 0 being east, with -M_PI <= angle < M_PI.
Definition at line 113 of file TraCIMobility.h.
{
                         if (angle == M_PI) throw cRuntimeError("TraCIMobility::getAngleRad called with no angle set yet");
                         return angle;
                 }
virtual double Veins::TraCIMobility::getAntennaPositionOffset () const inline virtual
Definition at line 89 of file TraCIMobility.h.
{
                         return antennaPositionOffset;
                 }
virtual TraCICommandInterface* Veins::TraCIMobility::getCommandInterface () const inline virtual
Definition at line 121 of file TraCIMobility.h.
Referenced by commandAddVehicle(), commandChangeRoute(), commandChangeVehicleRoute(), commandDistanceRequest(), commandGetLaneId(), commandGetLaneIndex(), commandGetLaneLength(), commandGetPolygonIds(), commandGetPolygonShape(), commandGetPolygonTypeId(), commandNewRoute(), commandParkVehicle(), commandSetColor(), commandSetPolygonShape(), commandSetSpeed(), commandSetSpeedMode(), commandSlowDown(), commandStopNode(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), and Veins::default_veins_TraCI_TestApp::handlePositionUpdate().
{
                         return getManager()->getCommandInterface();
                 }
virtual std::string Veins::TraCIMobility::getExternalId () const inline virtual
Definition at line 85 of file TraCIMobility.h.
Referenced by commandChangeRoute(), commandChangeVehicleRoute(), commandGetLaneId(), commandGetLaneIndex(), commandNewRoute(), commandParkVehicle(), commandSetColor(), commandSetSpeed(), commandSetSpeedMode(), commandSlowDown(), and commandStopNode().
{
                         if (external_id == "") throw cRuntimeError("TraCIMobility::getExternalId called with no external_id set yet");
                         return external_id;
                 }
virtual TraCIScenarioManager* Veins::TraCIMobility::getManager () const inline virtual
Definition at line 117 of file TraCIMobility.h.
Referenced by commandDistanceRequest(), commandGetPolygonShape(), commandSetPolygonShape(), getCommandInterface(), Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), and Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate().
{
                         if (!manager) manager = TraCIScenarioManagerAccess().get();
                         return manager;
                 }
virtual bool Veins::TraCIMobility::getParkingState () const inline virtual
Definition at line 95 of file TraCIMobility.h.
Referenced by default_veins_TraCI::handleParkingUpdate(), mfcv::handleParkingUpdate(), and minicurso_UFPI_TraCI::handleParkingUpdate().
{
                         return isParking;
                 }
virtual Coord Veins::TraCIMobility::getPositionAt (const simtime_t & t) const inline virtual
Definition at line 92 of file TraCIMobility.h.
Referenced by default_veins_TraCI::onData(), mfcv::onData(), and minicurso_UFPI_TraCI::onData().
{
                         return move.getPositionAt(t) ;
                 }
virtual std::string Veins::TraCIMobility::getRoadId () const inline virtual
Definition at line 98 of file TraCIMobility.h.
Referenced by service_discovery::deterministQuery(), test1::deterministQuery(), default_veins_TraCI::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), minicurso_UFPI_TraCI::handleSelfMsg(), mfcv::imprime_wsm(), minicurso_UFPI_TraCI::onBeacon(), default_veins_TraCI::onData(), mfcv::onData(), minicurso_UFPI_TraCI::onData(), mfcv::prepareWSM_node(), and minicurso_UFPI_TraCI::verifyAndSendCongestionMessage().
{
                         if (road_id == "") throw cRuntimeError("TraCIMobility::getRoadId called with no road_id set yet");
                         return road_id;
                 }
virtual TraCIScenarioManager::VehicleSignal Veins::TraCIMobility::getSignals () const inline virtual
Definition at line 106 of file TraCIMobility.h.
{
                         if (signals == -1) throw cRuntimeError("TraCIMobility::getSignals called with no signals set yet");
                         return signals;
                 }
virtual double Veins::TraCIMobility::getSpeed () const inline virtual
Definition at line 102 of file TraCIMobility.h.
Referenced by service_discovery::answerQuery(), test1::answerQuery(), default_veins_TraCI::handlePositionUpdate(), mfcv::handlePositionUpdate(), Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), minicurso_UFPI_TraCI::handleSelfMsg(), test1::insertService(), service_discovery::insertService(), and mfcv::prepareWSM_node().
{
                         if (speed == -1) throw cRuntimeError("TraCIMobility::getSpeed called with no speed set yet");
                         return speed;
                 }
void TraCIMobility::handleSelfMsg (cMessage * msg) virtual
Called upon arrival of a self messages.
The only self message possible is to indicate a new movement. If the host is stationary this function is never called.
every time a self message arrives makeMove is called to handle the movement. Afterward updatePosition updates the position with the display.
Reimplemented from BaseMobility.
Definition at line 146 of file TraCIMobility.cc.
 {
         if (msg == startAccidentMsg) {
                 commandSetSpeed(0);
                 simtime_t accidentDuration = par("accidentDuration");
                 scheduleAt(simTime() + accidentDuration, stopAccidentMsg);
                 accidentCount--;
         }
         else if (msg == stopAccidentMsg) {
                 commandSetSpeed(-1);
                 if (accidentCount > 0) {
                         simtime_t accidentInterval = par("accidentInterval");
                         scheduleAt(simTime() + accidentInterval, startAccidentMsg);
                 }
         }
 }
void TraCIMobility::initialize (int stage) virtual
Initializes mobility model parameters.
Assigns a pointer to ConnectionManager and gets a pointer to its host.
Creates a random position for a host if the position is not given as a parameter in "omnetpp.ini".
Additionally the registration with ConnectionManager is done and it is assured that the position display string tag (p) exists and contains the exact (x) tag.
If the speed of the host is bigger than 0 a first MOVE_HOST self message is scheduled in stage 1
Reimplemented from BaseMobility.
Definition at line 76 of file TraCIMobility.cc.
 {
         if (stage == 0)
         {
                 BaseMobility::initialize(stage);
                 debug = par("debug");
                 antennaPositionOffset = par("antennaPositionOffset");
                 accidentCount = par("accidentCount");
                 currentPosXVec.setName("posx");
                 currentPosYVec.setName("posy");
                 currentSpeedVec.setName("speed");
                 currentAccelerationVec.setName("acceleration");
                 currentCO2EmissionVec.setName("co2emission");
                 statistics.initialize();
                 statistics.watch(*this);
                 ASSERT(isPreInitialized);
                 isPreInitialized = false;
                 Coord nextPos = calculateAntennaPosition(roadPosition);
                 nextPos.z = move.getCurrentPosition().z;
                 move.setStart(nextPos);
                 move.setDirectionByVector(Coord(cos(angle), -sin(angle)));
                 move.setSpeed(speed);
                 WATCH(road_id);
                 WATCH(speed);
                 WATCH(angle);
                 isParking = false;
                 startAccidentMsg = 0;
                 stopAccidentMsg = 0;
                 manager = 0;
                 last_speed = -1;
                 if (accidentCount > 0) {
                         simtime_t accidentStart = par("accidentStart");
                         startAccidentMsg = new cMessage("scheduledAccident");
                         stopAccidentMsg = new cMessage("scheduledAccidentResolved");
                         scheduleAt(simTime() + accidentStart, startAccidentMsg);
                 }
         }
         else if (stage == 1)
         {
                 // don't call BaseMobility::initialize(stage) -- our parent will take care to call changePosition later
         }
         else
         {
                 BaseMobility::initialize(stage);
         }
 }
void TraCIMobility::nextPosition (const Coord & position, std::string road_id = "", double speed = -1, double angle = -1, TraCIScenarioManager::VehicleSignal signals = TraCIScenarioManager::VEH_SIGNAL_UNDEF) virtual
Definition at line 183 of file TraCIMobility.cc.
Referenced by Veins::TraCIScenarioManager::processVehicleSubscription().
 {
         if (debug) EV << "nextPosition " << position.x << " " << position.y << " " << road_id << " " << speed << " " << angle << std::endl;
         isPreInitialized = false;
         this->roadPosition = position;
         this->road_id = road_id;
         this->speed = speed;
         this->angle = angle;
         this->signals = signals;
         changePosition();
 }
void TraCIMobility::preInitialize (std::string external_id, const Coord & position, std::string road_id = "", double speed = -1, double angle = -1) virtual
Definition at line 163 of file TraCIMobility.cc.
Referenced by Veins::TraCIScenarioManager::addModule().
 {
         this->external_id = external_id;
         this->lastUpdate = 0;
         this->roadPosition = position;
         this->road_id = road_id;
         this->speed = speed;
         this->angle = angle;
         this->antennaPositionOffset = par("antennaPositionOffset");
         Coord nextPos = calculateAntennaPosition(roadPosition);
         nextPos.z = move.getCurrentPosition().z;
         move.setStart(nextPos);
         move.setDirectionByVector(Coord(cos(angle), -sin(angle)));
         move.setSpeed(speed);
         isPreInitialized = true;
 }
virtual void Veins::TraCIMobility::setExternalId (std::string external_id) inline virtual
Definition at line 82 of file TraCIMobility.h.
{
                         this->external_id = external_id;
                 }
void TraCIMobility::updateDisplayString () virtual
Definition at line 247 of file TraCIMobility.cc.
Referenced by changePosition().
{
         ASSERT(-M_PI <= angle);
         ASSERT(angle < M_PI);
         getParentModule()->getDisplayString().setTagArg("b", 2, "rect");
         getParentModule()->getDisplayString().setTagArg("b", 3, "red");
         getParentModule()->getDisplayString().setTagArg("b", 4, "red");
         getParentModule()->getDisplayString().setTagArg("b", 5, "0");
         if (angle < -M_PI + 0.5 * M_PI_4 * 1) {
                 getParentModule()->getDisplayString().setTagArg("t", 0, "\u2190");
                 getParentModule()->getDisplayString().setTagArg("b", 0, "4");
                 getParentModule()->getDisplayString().setTagArg("b", 1, "2");
         }
         else if (angle < -M_PI + 0.5 * M_PI_4 * 3) {
                 getParentModule()->getDisplayString().setTagArg("t", 0, "\u2199");
                 getParentModule()->getDisplayString().setTagArg("b", 0, "3");
                 getParentModule()->getDisplayString().setTagArg("b", 1, "3");
         }
         else if (angle < -M_PI + 0.5 * M_PI_4 * 5) {
                 getParentModule()->getDisplayString().setTagArg("t", 0, "\u2193");
                 getParentModule()->getDisplayString().setTagArg("b", 0, "2");
                 getParentModule()->getDisplayString().setTagArg("b", 1, "4");
         }
         else if (angle < -M_PI + 0.5 * M_PI_4 * 7) {
                 getParentModule()->getDisplayString().setTagArg("t", 0, "\u2198");
                 getParentModule()->getDisplayString().setTagArg("b", 0, "3");
                 getParentModule()->getDisplayString().setTagArg("b", 1, "3");
         }
         else if (angle < -M_PI + 0.5 * M_PI_4 * 9) {
                 getParentModule()->getDisplayString().setTagArg("t", 0, "\u2192");
                 getParentModule()->getDisplayString().setTagArg("b", 0, "4");
                 getParentModule()->getDisplayString().setTagArg("b", 1, "2");
         }
         else if (angle < -M_PI + 0.5 * M_PI_4 * 11) {
                 getParentModule()->getDisplayString().setTagArg("t", 0, "\u2197");
                 getParentModule()->getDisplayString().setTagArg("b", 0, "3");
                 getParentModule()->getDisplayString().setTagArg("b", 1, "3");
         }
         else if (angle < -M_PI + 0.5 * M_PI_4 * 13) {
                 getParentModule()->getDisplayString().setTagArg("t", 0, "\u2191");
                 getParentModule()->getDisplayString().setTagArg("b", 0, "2");
                 getParentModule()->getDisplayString().setTagArg("b", 1, "4");
         }
         else if (angle < -M_PI + 0.5 * M_PI_4 * 15) {
                 getParentModule()->getDisplayString().setTagArg("t", 0, "\u2196");
                 getParentModule()->getDisplayString().setTagArg("b", 0, "3");
                 getParentModule()->getDisplayString().setTagArg("b", 1, "3");
         }
         else {
                 getParentModule()->getDisplayString().setTagArg("t", 0, "\u2190");
                 getParentModule()->getDisplayString().setTagArg("b", 0, "4");
                 getParentModule()->getDisplayString().setTagArg("b", 1, "2");
         }
 }
Member Data Documentation
int Veins::TraCIMobility::accidentCount protected
number of accidents
Definition at line 183 of file TraCIMobility.h.
Referenced by handleSelfMsg(), and initialize().
double Veins::TraCIMobility::angle protected
updated by nextPosition()
Definition at line 202 of file TraCIMobility.h.
Referenced by calculateAntennaPosition(), changePosition(), getAngleRad(), initialize(), nextPosition(), preInitialize(), and updateDisplayString().
double Veins::TraCIMobility::antennaPositionOffset protected
front offset for the antenna on this car
Definition at line 196 of file TraCIMobility.h.
Referenced by calculateAntennaPosition(), getAntennaPositionOffset(), initialize(), and preInitialize().
cOutVector Veins::TraCIMobility::currentAccelerationVec protected
vector plotting acceleration
Definition at line 188 of file TraCIMobility.h.
Referenced by changePosition(), and initialize().
cOutVector Veins::TraCIMobility::currentCO2EmissionVec protected
vector plotting current CO2 emission
Definition at line 189 of file TraCIMobility.h.
Referenced by changePosition(), and initialize().
cOutVector Veins::TraCIMobility::currentPosXVec protected
vector plotting posx
Definition at line 185 of file TraCIMobility.h.
Referenced by changePosition(), and initialize().
cOutVector Veins::TraCIMobility::currentPosYVec protected
vector plotting posy
Definition at line 186 of file TraCIMobility.h.
Referenced by changePosition(), and initialize().
cOutVector Veins::TraCIMobility::currentSpeedVec protected
vector plotting speed
Definition at line 187 of file TraCIMobility.h.
Referenced by changePosition(), and initialize().
bool Veins::TraCIMobility::debug protected
whether to emit debug messages
Definition at line 182 of file TraCIMobility.h.
Referenced by initialize(), and nextPosition().
std::string Veins::TraCIMobility::external_id protected
updated by setExternalId()
Definition at line 195 of file TraCIMobility.h.
Referenced by getExternalId(), preInitialize(), and setExternalId().
bool Veins::TraCIMobility::isParking protected
Definition at line 212 of file TraCIMobility.h.
Referenced by changeParkingState(), getParkingState(), and initialize().
bool Veins::TraCIMobility::isPreInitialized protected
true if preInitialize() has been called immediately before initialize()
Definition at line 193 of file TraCIMobility.h.
Referenced by finish(), initialize(), nextPosition(), and preInitialize().
double Veins::TraCIMobility::last_speed protected
Definition at line 208 of file TraCIMobility.h.
Referenced by changePosition(), and initialize().
simtime_t Veins::TraCIMobility::lastUpdate protected
updated by nextPosition()
Definition at line 198 of file TraCIMobility.h.
Referenced by changePosition(), and preInitialize().
TraCIScenarioManager* Veins::TraCIMobility::manager mutable protected
Definition at line 207 of file TraCIMobility.h.
Referenced by getManager(), and initialize().
const simsignalwrap_t TraCIMobility::parkingStateChangedSignal = simsignalwrap_t(TRACI_SIGNAL_PARKING_CHANGE_NAME) static protected
Definition at line 210 of file TraCIMobility.h.
Referenced by changeParkingState().
std::string Veins::TraCIMobility::road_id protected
updated by nextPosition()
Definition at line 200 of file TraCIMobility.h.
Referenced by getRoadId(), nextPosition(), and preInitialize().
Coord Veins::TraCIMobility::roadPosition protected
position of front bumper, updated by nextPosition()
Definition at line 199 of file TraCIMobility.h.
Referenced by changePosition(), initialize(), nextPosition(), and preInitialize().
TraCIScenarioManager::VehicleSignal Veins::TraCIMobility::signals protected
updated by nextPosition()
Definition at line 203 of file TraCIMobility.h.
Referenced by getSignals(), and nextPosition().
double Veins::TraCIMobility::speed protected
updated by nextPosition()
Definition at line 201 of file TraCIMobility.h.
Referenced by changePosition(), getSpeed(), initialize(), nextPosition(), and preInitialize().
cMessage* Veins::TraCIMobility::startAccidentMsg protected
Definition at line 205 of file TraCIMobility.h.
Referenced by finish(), handleSelfMsg(), and initialize().
Statistics Veins::TraCIMobility::statistics protected
everything statistics-related
Definition at line 191 of file TraCIMobility.h.
Referenced by changePosition(), finish(), and initialize().
cMessage* Veins::TraCIMobility::stopAccidentMsg protected
Definition at line 206 of file TraCIMobility.h.
Referenced by finish(), handleSelfMsg(), and initialize().
The documentation for this class was generated from the following files:
TraCIMobility.h
TraCIMobility.cc