Veins Framework: FWMath Class Reference
FWMath Class Reference
Support functions for mathematical operations.
#include <FWMath.h>
Static Public Member Functions
static double mod (double dividend, double divisor)
Returns the rest of a whole-numbered division.
static double div (double dividend, double divisor)
Returns the result of a whole-numbered division.
static double modulo (double a, double n)
Returns the remainder r on division of dividend a by divisor n, using floored division.
static bool close (double one, double two)
Tests whether two doubles are close enough to be declared equal.
static int stepfunction (double i)
Returns 0 if i is close to 0, 1 if i is positive and greater than epsilon, or -1 if it is negative and less than epsilon.
static int sign (double i)
Returns 1 if the parameter is greater or equal to zero, -1 otherwise.
static int round (double d)
Returns an integer that corresponds to rounded double parameter.
static double floorToZero (double d)
Discards the fractional part of the parameter, e.g.
static double max (double a, double b)
Returns the greater of the given parameters.
static double dBm2mW (double dBm)
Converts a dBm value into milliwatts.
static double mW2dBm (double mW)
Convert a mW value to dBm.
Detailed Description
Support functions for mathematical operations.
This class contains all kind of mathematical support functions
Author
Christian Frank
Definition at line 100 of file FWMath.h.
Member Function Documentation
static bool FWMath::close (double one, double two) inline static
Tests whether two doubles are close enough to be declared equal.
Returns true if parameters are at most epsilon apart, false otherwise
Definition at line 132 of file FWMath.h.
Referenced by Move::getPositionAt(), Move::setDirectionByTarget(), and Move::setDirectionByVector().
 { return fabs(one-two)<EPSILON; }
static double FWMath::dBm2mW (double dBm) inline static
Converts a dBm value into milliwatts.
Definition at line 163 of file FWMath.h.
Referenced by BasePhyLayer::initialize(), and LogNormalShadowing::randomLogNormalGain().
 { return pow(10.0, dBm/10.0); }
static double FWMath::div (double dividend, double divisor) inline static
Returns the result of a whole-numbered division.
Definition at line 115 of file FWMath.h.
{
       double i;
       modf(dividend/divisor, &i);
       return i;
   }
static double FWMath::floorToZero (double d) inline static
Discards the fractional part of the parameter, e.g.
-3.8 becomes -3
Definition at line 153 of file FWMath.h.
 { return (d >= 0.0)? floor(d) : ceil(d); }
static double FWMath::max (double a, double b) inline static
Returns the greater of the given parameters.
Definition at line 158 of file FWMath.h.
 { return (a<b)? b : a; }
static double FWMath::mod (double dividend, double divisor) inline static
Returns the rest of a whole-numbered division.
Definition at line 107 of file FWMath.h.
{
       double i;
       return modf(dividend/divisor, &i)*divisor;
   }
static double FWMath::modulo (double a, double n) inline static
Returns the remainder r on division of dividend a by divisor n, using floored division.
The remainder r has the same sign as the divisor n.
Definition at line 125 of file FWMath.h.
Referenced by BaseMobility::wrapIfOutside().
 { return (a - n * floor(a/n)); }
static double FWMath::mW2dBm (double mW) inline static
Convert a mW value to dBm.
Definition at line 168 of file FWMath.h.
Referenced by TwoRayInterferenceModel::Mapping::getValue().
 { return (10 * log10(mW)); }
static int FWMath::round (double d) inline static
Returns an integer that corresponds to rounded double parameter.
Definition at line 148 of file FWMath.h.
 { return (int)(ceil(d-0.5)); }
static int FWMath::sign (double i) inline static
Returns 1 if the parameter is greater or equal to zero, -1 otherwise.
Definition at line 143 of file FWMath.h.
 { return (i>=0)? 1 : -1; };
static int FWMath::stepfunction (double i) inline static
Returns 0 if i is close to 0, 1 if i is positive and greater than epsilon, or -1 if it is negative and less than epsilon.
Definition at line 138 of file FWMath.h.
 { return (i>EPSILON) ? 1 : close(i, 0) ? 0 :-1; };
The documentation for this class was generated from the following file:
FWMath.h