Veins Framework: MacPkt Class Reference
MacPkt Class Reference
Class generated from base/messages/MacPkt.msg:35 by nedtool.
#include <MacPkt_m.h>
Public Member Functions
MacPkt (const char *name=NULL, int kind=0)
MacPkt (const MacPkt &other)
virtual ~MacPkt ()
MacPkt & operator= (const MacPkt &other)
virtual MacPkt * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual LAddress::L2Type & getDestAddr ()
virtual const LAddress::L2Type & getDestAddr () const
virtual void setDestAddr (const LAddress::L2Type &destAddr)
virtual LAddress::L2Type & getSrcAddr ()
virtual const LAddress::L2Type & getSrcAddr () const
virtual void setSrcAddr (const LAddress::L2Type &srcAddr)
virtual long getSequenceId () const
virtual void setSequenceId (long sequenceId)
Protected Member Functions
bool operator== (const MacPkt &)
Protected Attributes
LAddress::L2Type destAddr_var
LAddress::L2Type srcAddr_var
long sequenceId_var
Private Member Functions
void copy (const MacPkt &other)
Detailed Description
Class generated from base/messages/MacPkt.msg:35 by nedtool.
// A basic MAC (Media Access Control) packet format definition
//
// subclass if you want to create your own MAC layer packet class
//
// The basic MAC packet only provides source and destination address
//
//
Author
 Daniel Willkomm
packet MacPkt
{
    LAddress::L2Type destAddr; // destination mac address
    LAddress::L2Type srcAddr; // source mac address
    long sequenceId; // Sequence Number to detect duplicate messages
}
Definition at line 40 of file MacPkt_m.h.
Constructor & Destructor Documentation
MacPkt::MacPkt (const char * name = NULL, int kind = 0)
Referenced by dup().
MacPkt::MacPkt (const MacPkt & other)
virtual MacPkt::~MacPkt () virtual
Member Function Documentation
void MacPkt::copy (const MacPkt & other) private
virtual MacPkt* MacPkt::dup () const inline virtual
Reimplemented in Mac80211Pkt.
Definition at line 59 of file MacPkt_m.h.
 {return new MacPkt(*this);}
virtual LAddress::L2Type& MacPkt::getDestAddr () virtual
Referenced by Mac1609_4::handleLowerMsg(), and BaseMacLayer::handleLowerMsg().
virtual const LAddress::L2Type& MacPkt::getDestAddr () const inline virtual
Definition at line 65 of file MacPkt_m.h.
Referenced by getDestAddr().
 {return const_cast<MacPkt*>(this)->getDestAddr();}
virtual long MacPkt::getSequenceId () const virtual
virtual LAddress::L2Type& MacPkt::getSrcAddr () virtual
Referenced by BaseMacLayer::decapsMsg(), Mac1609_4::handleLowerMsg(), and BaseMacLayer::handleLowerMsg().
virtual const LAddress::L2Type& MacPkt::getSrcAddr () const inline virtual
Definition at line 68 of file MacPkt_m.h.
Referenced by getSrcAddr().
 {return const_cast<MacPkt*>(this)->getSrcAddr();}
MacPkt& MacPkt::operator= (const MacPkt & other)
bool MacPkt::operator== (const MacPkt &) protected
virtual void MacPkt::parsimPack (cCommBuffer * b) virtual
Reimplemented in Mac80211Pkt.
Referenced by doPacking().
virtual void MacPkt::parsimUnpack (cCommBuffer * b) virtual
Reimplemented in Mac80211Pkt.
Referenced by doUnpacking().
virtual void MacPkt::setDestAddr (const LAddress::L2Type & destAddr) virtual
Referenced by BaseMacLayer::encapsMsg(), and Mac1609_4::handleSelfMsg().
virtual void MacPkt::setSequenceId (long sequenceId) virtual
virtual void MacPkt::setSrcAddr (const LAddress::L2Type & srcAddr) virtual
Referenced by BaseMacLayer::encapsMsg(), and Mac1609_4::handleSelfMsg().
Member Data Documentation
LAddress::L2Type MacPkt::destAddr_var protected
Definition at line 43 of file MacPkt_m.h.
long MacPkt::sequenceId_var protected
Definition at line 45 of file MacPkt_m.h.
LAddress::L2Type MacPkt::srcAddr_var protected
Definition at line 44 of file MacPkt_m.h.
The documentation for this class was generated from the following file:
MacPkt_m.h