Veins Framework: Veins::TraCIConnection Class Reference
Veins::TraCIConnection Class Reference
#include <TraCIConnection.h>
Public Member Functions
~TraCIConnection ()
TraCIBuffer query (uint8_t commandId, const TraCIBuffer &buf=TraCIBuffer())
sends a single command via TraCI, checks status response, returns additional responses
TraCIBuffer queryOptional (uint8_t commandId, const TraCIBuffer &buf, bool &success, std::string *errorMsg=0)
sends a single command via TraCI, expects no reply, returns true if successful
void sendMessage (std::string buf)
sends a message via TraCI (after adding the header)
std::string receiveMessage ()
receives a message via TraCI (and strips the header)
Static Public Member Functions
static TraCIConnection * connect (const char *host, int port)
Private Member Functions
TraCIConnection (void *)
Private Attributes
void * socketPtr
Detailed Description
Definition at line 9 of file TraCIConnection.h.
Constructor & Destructor Documentation
Veins::TraCIConnection::~TraCIConnection ()
Definition at line 31 of file TraCIConnection.cc.
{
         if (socketPtr) {
                 closesocket(socket(socketPtr));
                 delete static_cast<SOCKET*>(socketPtr);
         }
 }
Veins::TraCIConnection::TraCIConnection (void * ptr) private
Definition at line 27 of file TraCIConnection.cc.
Referenced by connect().
                                           : socketPtr(ptr) {
         ASSERT(socketPtr);
 }
Member Function Documentation
TraCIConnection * Veins::TraCIConnection::connect (const char * host, int port) static
Definition at line 38 of file TraCIConnection.cc.
Referenced by Veins::TraCIScenarioManager::handleSelfMsg().
{
         MYDEBUG << "TraCIScenarioManager connecting to TraCI server" << endl;
         if (initsocketlibonce() != 0) opp_error("Could not init socketlib");
         in_addr addr;
         struct hostent* host_ent;
         struct in_addr saddr;
         saddr.s_addr = inet_addr(host);
         if (saddr.s_addr != static_cast<unsigned int>(-1)) {
                 addr = saddr;
         } else if ((host_ent = gethostbyname(host))) {
                 addr = *((struct in_addr*) host_ent->h_addr_list[0]);
         } else {
                 opp_error("Invalid TraCI server address: %s", host);
                 return 0;
         }
         sockaddr_in address;
         memset((char*) &address, 0, sizeof(address));
         address.sin_family = AF_INET;
         address.sin_port = htons(port);
         address.sin_addr.s_addr = addr.s_addr;
         SOCKET* socketPtr = new SOCKET();
         *socketPtr = ::socket(AF_INET, SOCK_STREAM, 0);
         if (*socketPtr < 0) opp_error("Could not create socket to connect to TraCI server");
         if (::connect(*socketPtr, (sockaddr const*) &address, sizeof(address)) < 0) {
                 opp_error("Could not connect to TraCI server. Make sure it is running and not behind a firewall. Error message: %d: %s", sock_errno(), strerror(sock_errno()));
         }
         {
                 int x = 1;
                 ::setsockopt(*socketPtr, IPPROTO_TCP, TCP_NODELAY, (const char*) &x, sizeof(x));
         }
         return new TraCIConnection(socketPtr);
 }
TraCIBuffer Veins::TraCIConnection::query (uint8_t commandId, const TraCIBuffer & buf = TraCIBuffer())
sends a single command via TraCI, checks status response, returns additional responses
Definition at line 79 of file TraCIConnection.cc.
Referenced by Veins::TraCICommandInterface::addPoi(), Veins::TraCICommandInterface::addPolygon(), Veins::TraCICommandInterface::changeRoute(), Veins::TraCICommandInterface::changeVehicleRoute(), Veins::TraCICommandInterface::distanceRequest(), Veins::TraCIScenarioManager::executeOneTimestep(), Veins::TraCIScenarioManager::finish(), Veins::TraCICommandInterface::genericGetCoord(), Veins::TraCICommandInterface::genericGetCoordList(), Veins::TraCICommandInterface::genericGetDouble(), Veins::TraCICommandInterface::genericGetInt(), Veins::TraCICommandInterface::genericGetString(), Veins::TraCICommandInterface::genericGetStringList(), Veins::TraCIScenarioManager::init_traci(), Veins::TraCICommandInterface::newRoute(), Veins::TraCICommandInterface::positionConversionLonLat(), Veins::TraCICommandInterface::removePoi(), Veins::TraCICommandInterface::removePolygon(), Veins::TraCICommandInterface::setColor(), Veins::TraCICommandInterface::setPolygonShape(), Veins::TraCICommandInterface::setSpeed(), Veins::TraCICommandInterface::setSpeedMode(), Veins::TraCICommandInterface::setTrafficLightPhaseIndex(), Veins::TraCICommandInterface::setTrafficLightProgram(), Veins::TraCICommandInterface::setVehicleParking(), Veins::TraCICommandInterface::slowDown(), Veins::TraCICommandInterface::stopNode(), Veins::TraCIScenarioManager::subscribeToVehicleVariables(), and Veins::TraCIScenarioManager::unsubscribeFromVehicleVariables().
{
         sendMessage(makeTraCICommand(commandId, buf));
         TraCIBuffer obuf(receiveMessage());
         uint8_t cmdLength; obuf >> cmdLength;
         uint8_t commandResp; obuf >> commandResp;
         ASSERT(commandResp == commandId);
         uint8_t result; obuf >> result;
         std::string description; obuf >> description;
         if (result == RTYPE_NOTIMPLEMENTED) opp_error("TraCI server reported command 0x%2x not implemented (\"%s\"). Might need newer version.", commandId, description.c_str());
         if (result == RTYPE_ERR) opp_error("TraCI server reported error executing command 0x%2x (\"%s\").", commandId, description.c_str());
         ASSERT(result == RTYPE_OK);
         return obuf;
 }
TraCIBuffer Veins::TraCIConnection::queryOptional (uint8_t commandId, const TraCIBuffer & buf, bool & success, std::string * errorMsg = 0)
sends a single command via TraCI, expects no reply, returns true if successful
Definition at line 94 of file TraCIConnection.cc.
Referenced by Veins::TraCICommandInterface::addVehicle(), and Veins::TraCICommandInterface::getVersion().
{
         sendMessage(makeTraCICommand(commandId, buf));
         TraCIBuffer obuf(receiveMessage());
         uint8_t cmdLength; obuf >> cmdLength;
         uint8_t commandResp; obuf >> commandResp;
         ASSERT(commandResp == commandId);
         uint8_t result; obuf >> result;
         std::string description; obuf >> description;
         success = (result == RTYPE_OK);
         if (errorMsg) *errorMsg = description;
         return obuf;
 }
std::string Veins::TraCIConnection::receiveMessage ()
receives a message via TraCI (and strips the header)
Definition at line 108 of file TraCIConnection.cc.
Referenced by Veins::TraCIScenarioManagerLaunchd::init_traci(), query(), and queryOptional().
{
         if (!socketPtr) opp_error("Not connected to TraCI server");
         uint32_t msgLength;
         {
                 char buf2[sizeof(uint32_t)];
                 uint32_t bytesRead = 0;
                 while (bytesRead < sizeof(uint32_t)) {
                         int receivedBytes = ::recv(socket(socketPtr), reinterpret_cast<char*>(&buf2) + bytesRead, sizeof(uint32_t) - bytesRead, 0);
                         if (receivedBytes > 0) {
                                 bytesRead += receivedBytes;
                         } else if (receivedBytes == 0) {
                                 opp_error("Connection to TraCI server closed unexpectedly. Check your server's log");
                         } else {
                                 if (sock_errno() == EINTR) continue;
                                 if (sock_errno() == EAGAIN) continue;
                                 opp_error("Connection to TraCI server lost. Check your server's log. Error message: %d: %s", sock_errno(), strerror(sock_errno()));
                         }
                 }
                 TraCIBuffer(std::string(buf2, sizeof(uint32_t))) >> msgLength;
         }
         uint32_t bufLength = msgLength - sizeof(msgLength);
         char buf[bufLength];
         {
                 MYDEBUG << "Reading TraCI message of " << bufLength << " bytes" << endl;
                 uint32_t bytesRead = 0;
                 while (bytesRead < bufLength) {
                         int receivedBytes = ::recv(socket(socketPtr), reinterpret_cast<char*>(&buf) + bytesRead, bufLength - bytesRead, 0);
                         if (receivedBytes > 0) {
                                 bytesRead += receivedBytes;
                         } else if (receivedBytes == 0) {
                                 opp_error("Connection to TraCI server closed unexpectedly. Check your server's log");
                         } else {
                                 if (sock_errno() == EINTR) continue;
                                 if (sock_errno() == EAGAIN) continue;
                                 opp_error("Connection to TraCI server lost. Check your server's log. Error message: %d: %s", sock_errno(), strerror(sock_errno()));
                         }
                 }
         }
         return std::string(buf, bufLength);
 }
void Veins::TraCIConnection::sendMessage (std::string buf)
sends a message via TraCI (after adding the header)
Definition at line 151 of file TraCIConnection.cc.
Referenced by Veins::TraCIScenarioManagerLaunchd::init_traci(), query(), and queryOptional().
{
         if (!socketPtr) opp_error("Not connected to TraCI server");
         {
                 uint32_t msgLength = sizeof(uint32_t) + buf.length();
                 TraCIBuffer buf2 = TraCIBuffer();
                 buf2 << msgLength;
                 uint32_t bytesWritten = 0;
                 while (bytesWritten < sizeof(uint32_t)) {
                         size_t sentBytes = ::send(socket(socketPtr), buf2.str().c_str() + bytesWritten, sizeof(uint32_t) - bytesWritten, 0);
                         if (sentBytes > 0) {
                                 bytesWritten += sentBytes;
                         } else {
                                 if (sock_errno() == EINTR) continue;
                                 if (sock_errno() == EAGAIN) continue;
                                 opp_error("Connection to TraCI server lost. Check your server's log. Error message: %d: %s", sock_errno(), strerror(sock_errno()));
                         }
                 }
         }
         {
                 MYDEBUG << "Writing TraCI message of " << buf.length() << " bytes" << endl;
                 uint32_t bytesWritten = 0;
                 while (bytesWritten < buf.length()) {
                         size_t sentBytes = ::send(socket(socketPtr), buf.c_str() + bytesWritten, buf.length() - bytesWritten, 0);
                         if (sentBytes > 0) {
                                 bytesWritten += sentBytes;
                         } else {
                                 if (sock_errno() == EINTR) continue;
                                 if (sock_errno() == EAGAIN) continue;
                                 opp_error("Connection to TraCI server lost. Check your server's log. Error message: %d: %s", sock_errno(), strerror(sock_errno()));
                         }
                 }
         }
 }
Member Data Documentation
void* Veins::TraCIConnection::socketPtr private
Definition at line 38 of file TraCIConnection.h.
Referenced by connect(), receiveMessage(), sendMessage(), TraCIConnection(), and ~TraCIConnection().
The documentation for this class was generated from the following files:
TraCIConnection.h
TraCIConnection.cc