Veins Framework: epidemic_rsu Class Reference
epidemic_rsu Class Reference
Small RSU Demo using 11p.
#include <epidemic_rsu.h>
Public Member Functions
virtual void initialize (int stage)
Initialization of the module and some variables.
Public Member Functions inherited from BaseWaveApplLayer
~BaseWaveApplLayer ()
virtual void initialize_default_veins_TraCI (int stage)
virtual void initialize_mfcv (int stage)
virtual void initialize_minicurso_UFPI_TraCI (int stage)
virtual void initialize_osdp (int stage)
virtual void initialize_service_discovery (int stage)
virtual void initialize_test1 (int stage)
virtual void initialize_epidemic (int stage)
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed.
Public Member Functions inherited from BaseApplLayer
BaseApplLayer ()
BaseApplLayer (unsigned stacksize)
Public Member Functions inherited from BaseLayer
BaseLayer ()
BaseLayer (unsigned stacksize)
virtual ~BaseLayer ()
virtual void handleMessage (cMessage *)
Called every time a message arrives.
Public Member Functions inherited from Veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from BaseModule
BaseModule ()
Function to get the logging name of id.
BaseModule (unsigned stacksize)
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
Protected Types
typedef unordered_map< string,
WaveShortMessage > MyMapEpidemicMessageBuffer
typedef pair< string,
WaveShortMessage > MyPairEpidemicMessageBuffer
Protected Member Functions
virtual void onBeacon (WaveShortMessage *wsm)
virtual void onData (WaveShortMessage *wsm)
void sendLocalSummaryVector (unsigned int newRecipientAddress)
void sendEpidemicRequestMessageVector (unsigned int newRecipientAddress)
void sendMessagesRequested (string s, unsigned int recipientAddress)
void sendBeacon ()
void sendBeacon (unsigned int target)
virtual void sendWSM (WaveShortMessage *wsm)
string getLocalSummaryVectorData ()
string getEpidemicRequestMessageVectorData ()
WaveShortMessage getEpidemicLocalMessageBuffer (string s)
void printNodesIRecentlySentSummaryVector ()
void printEpidemicLocalMessageBuffer ()
void printEpidemicRequestMessageVector ()
void printWaveShortMessage (WaveShortMessage wsm)
void printWaveShortMessage (WaveShortMessage *wsm)
void printEpidemicLocalSummaryVectorData ()
void printEpidemicRemoteSummaryVectorData ()
void createEpidemicRequestMessageVector ()
void printQueueFIFO (queue< string > qFIFO)
void createEpidemicRemoteSummaryVector (string s)
virtual void finish ()
Called when the simulation has finished.
Protected Member Functions inherited from BaseWaveApplLayer
virtual void handleLowerMsg (cMessage *msg)
handle messages from below
virtual void handleSelfMsg (cMessage *msg)
handle self messages
virtual WaveShortMessage * prepareWSM (std::string name, int dataLengthBits, t_channel channel, int priority, unsigned int rcvId, int serial=0)
virtual WaveShortMessage * prepareWSM_epidemic (string name, int dataLengthBits, t_channel channel, int priority, unsigned int rcvId, int serial=0)
virtual unsigned int MACToInteger ()
virtual void handlePositionUpdate (cObject *obj)
Protected Member Functions inherited from BaseApplLayer
void sendDelayedDown (cMessage *, simtime_t_cref)
Sends a message delayed to the lower layer.
virtual const LAddress::L3Type myApplAddr () const
Return my application layer address.
virtual void handleLowerControl (cMessage *msg)
Handle control messages from lower layer.
virtual void handleUpperMsg (cMessage *msg)
Handle messages from upper layer.
virtual void handleUpperControl (cMessage *msg)
Handle control messages from upper layer.
Protected Member Functions inherited from BaseLayer
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from Veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
Protected Attributes
AnnotationManager * annotations
BaseMobility * mobi
bool sentMessage
MyMapEpidemicMessageBuffer epidemicLocalMessageBuffer
unordered_map< string, bool > epidemicLocalSummaryVector
unordered_map< string, bool > epidemicRemoteSummaryVector
unordered_map< string, bool > epidemicRequestMessageVector
unordered_map< unsigned int,
simtime_t > nodesRecentlyFoundList
unordered_map< unsigned int,
simtime_t > nodesIRecentlySentSummaryVector
queue< string > queueFIFO
double maiortempo = 0
Protected Attributes inherited from BaseWaveApplLayer
int beaconLengthBits
int beaconPriority
bool sendData
bool sendBeacons
simtime_t individualOffset
int dataLengthBits
bool dataOnSch
int dataPriority
Coord curPosition
int mySCH
int myId
cMessage * sendBeaconEvt
WaveAppToMac1609_4Interface * myMac
int sendSummaryVectorInterval
unsigned int maximumEpidemicBufferSize
unsigned int hopCount
string source
string target
Protected Attributes inherited from BaseApplLayer
int headerLength
Length of the ApplPkt header.
Protected Attributes inherited from BaseLayer
PassedMessage * passedMsg
The last message passed through this layer.
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
Protected Attributes inherited from Veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from BaseModule
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Public Types inherited from BaseWaveApplLayer
enum WaveApplMessageKinds {
SERVICE_PROVIDER = LAST_BASE_APPL_MESSAGE_KIND, SEND_BEACON_EVT, SEND_BEACON_EVT_minicurso, SERVICE_EXPIRED_EVT,
SERVICE_QUERY_EVT, SERVICE_EVT, MOBILITY_EVT, SEND_BEACON_EVT_epidemic
}
Public Types inherited from BaseApplLayer
enum BaseApplMessageKinds { LAST_BASE_APPL_MESSAGE_KIND = 25000 }
The message kinds this layer uses.
enum BaseApplControlKinds { LAST_BASE_APPL_CONTROL_KIND = 25500 }
The control message kinds this layer uses.
Static Public Attributes inherited from BaseLayer
static const simsignalwrap_t catPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_PACKET_NAME)
SignalID for packets.
static const simsignalwrap_t catPassedMsgSignal = simsignalwrap_t(MIXIM_SIGNAL_PASSEDMSG_NAME)
Signal for passed messages.
static const simsignalwrap_t catDroppedPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_DROPPEDPACKET_NAME)
Signal for dropped packets.
Static Protected Attributes inherited from BaseWaveApplLayer
static const simsignalwrap_t mobilityStateChangedSignal = simsignalwrap_t(MIXIM_SIGNAL_MOBILITY_CHANGE_NAME)
Static Protected Attributes inherited from BaseModule
static const simsignalwrap_t catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME)
Stores the category of the HostState.
Detailed Description
Small RSU Demo using 11p.
Definition at line 35 of file epidemic_rsu.h.
Member Typedef Documentation
typedef unordered_map<string, WaveShortMessage> epidemic_rsu::MyMapEpidemicMessageBuffer protected
Definition at line 43 of file epidemic_rsu.h.
typedef pair<string, WaveShortMessage> epidemic_rsu::MyPairEpidemicMessageBuffer protected
Definition at line 44 of file epidemic_rsu.h.
Member Function Documentation
void epidemic_rsu::createEpidemicRemoteSummaryVector (string s) protected
Definition at line 412 of file epidemic_rsu.cc.
Referenced by onData().
{
     //cout << "Creating the epidemicRemoteSummaryVector in " << findHost()->getFullName() << endl;
     string delimiter = "|";
     size_t pos = 0;
     string token;
     unsigned i = 0;
     epidemicRemoteSummaryVector.clear();
     while ((pos = s.find(delimiter)) != std::string::npos) {
       //token = s.substr(0, pos);
       //std::cout << token << std::endl;
       //Catch jus the key of the local summary vector
       if(i%2 == 0)
         epidemicRemoteSummaryVector.insert(make_pair<string, bool>(s.substr(0, pos),true));
       s.erase(0, pos + delimiter.length());
       i++;
     }
     //std::cout << s << std::endl;
 }
void epidemic_rsu::createEpidemicRequestMessageVector () protected
Definition at line 431 of file epidemic_rsu.cc.
Referenced by onData().
{
     epidemicRequestMessageVector.clear();
     for(auto& x: epidemicRemoteSummaryVector){
         unordered_map<string,bool>::const_iterator got = epidemicLocalSummaryVector.find(x.first);
         //cout << "I'm in createEpidemicRequestMessageVector().  x.first: " << x.first << " x.second: " << x.second << endl;
         if(got == epidemicLocalSummaryVector.end()){ //true value means that there is no entry in the epidemicLocalSummaryVector for a epidemicRemoteSummaryVector key
             //Putting the message in the EpidemicRequestMessageVector
             string s = x.first;
             epidemicRequestMessageVector.insert(make_pair<string, bool>(s.c_str(),true));
         }
         //An entry in the unordered_map was found
         else{
             //cout << "I'm in createEpidemicRequestMessageVector().  got->first: " << got->first << " got->second: " << got->second << endl;
             //cout << "The message " << got->first << " in the epidemicRemoteSummaryVector was found in my epidemicLocalSummaryVector." << endl;
         }
     }
 }
void epidemic_rsu::finish () protected virtual
Called when the simulation has finished.
Reimplemented from BaseWaveApplLayer.
Definition at line 594 of file epidemic_rsu.cc.
{
 //    // This function is called by OMNeT++ at the end of the simulation.
 //    cout << "Number of Messages Received: " << numMessageReceived << endl;
 //    cout << "Hop count, min:    " << hopCountStats.getMin() << endl;
 //    cout << "Hop count, max:    " << hopCountStats.getMax() << endl;
 //    cout << "Hop count, mean:   " << hopCountStats.getMean() << endl;
 //    cout << "Hop count, stddev: " << hopCountStats.getStddev() << endl;
 //
 //    // This function is called by OMNeT++ at the end of the simulation.
 //    cout << "Maior Delay: " << maiortempo << endl;
 //    cout << "messageArrivalTimeStats, min:    " << messageArrivalTimeStats.getMin() << endl;
 //    cout << "messageArrivalTimeStats, max:    " << messageArrivalTimeStats.getMax() << endl;
 //    cout << "messageArrivalTimeStats, mean:   " << messageArrivalTimeStats.getMean() << endl;
 //    cout << "messageArrivalTimeStats, stddev: " << messageArrivalTimeStats.getStddev() << endl;
 //
 //
 //    // This function is called by OMNeT++ at the end of the simulation.
 //    EV << "Number of Messages Received: " << numMessageReceived << endl;
 //    EV << "Hop count, min:    " << hopCountStats.getMin() << endl;
 //    EV << "Hop count, max:    " << hopCountStats.getMax() << endl;
 //    EV << "Hop count, mean:   " << hopCountStats.getMean() << endl;
 //    EV << "Hop count, stddev: " << hopCountStats.getStddev() << endl;
 //
 //    // This function is called by OMNeT++ at the end of the simulation.
 //    EV << "Maior Delay: " << maiortempo << endl;
 //    EV << "messageArrivalTimeStats, min:    " << messageArrivalTimeStats.getMin() << endl;
 //    EV << "messageArrivalTimeStats, max:    " << messageArrivalTimeStats.getMax() << endl;
 //    EV << "messageArrivalTimeStats, mean:   " << messageArrivalTimeStats.getMean() << endl;
 //    EV << "messageArrivalTimeStats, stddev: " << messageArrivalTimeStats.getStddev() << endl;
 //
 //    recordScalar("#numMessageReceived", numMessageReceived);
 //
 //    hopCountStats.recordAs("hop CCount");
 //    messageArrivalTimeStats.recordAs("Latency to Delivery Message");
 }
WaveShortMessage epidemic_rsu::getEpidemicLocalMessageBuffer (string s) protected
string epidemic_rsu::getEpidemicRequestMessageVectorData () protected
Definition at line 449 of file epidemic_rsu.cc.
Referenced by sendEpidemicRequestMessageVector().
{
     ostringstream ss;
     //adding the requester name in order to identify if the requester is also the target of the messages with hopcount == 1.
     //In this case, hopcount == 1, the messages can be sent to the target. Otherwise, the message will not be spread
     ss << findHost()->getFullName() << "|";
     for(auto& x: epidemicRequestMessageVector)
         ss << x.first << "|" << x.second << "|";
     string s = ss.str();
     s = s.substr(0, s.length() - 1);
     cout << "String format of EpidemicRequestMessageVector from " << findHost()->getFullName() << ": " <<  s  << endl;
     return s.c_str();
 }
string epidemic_rsu::getLocalSummaryVectorData () protected
Definition at line 469 of file epidemic_rsu.cc.
Referenced by sendLocalSummaryVector().
{
     ostringstream ss;
     for(auto& x: epidemicLocalSummaryVector)
         ss << x.first << "|" << x.second << "|";
     string s = ss.str();
     s = s.substr(0, s.length() - 1);
     //cout << "EpidemicLocalSummaryVector from " << findHost()->getFullName() << "(" << MACToInteger() << "): " <<  s  << endl;
     return s.c_str();
 }
void epidemic_rsu::initialize (int stage) virtual
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseLayer.
Then we have to intialize the gates and - if necessary - some own variables.
Reimplemented from BaseApplLayer.
Definition at line 27 of file epidemic_rsu.cc.
{
     BaseWaveApplLayer::initialize_epidemic(stage);
     if (stage == 0) {
         mobi = dynamic_cast<BaseMobility*> (getParentModule()->getSubmodule("mobility"));
         ASSERT(mobi);
         annotations = AnnotationManagerAccess().getIfExists();
         ASSERT(annotations);
         //To record some statistics about the simulation
         //hopCountStats.setName("hopCountStats"); //Histogram
         //hopCountStats.setRangeAutoUpper(0, 10, 1.5); //Histogram
         //hopCountVector.setName("HopCount");
         //messageArrivalTimeStats.setName("messageArrivalStats"); //Histogram
         //messageArrivalTimeStats.setRangeAutoUpper(0, 10, 1.5); //Histogram
         //messageArrivalTimeVector.setName("messageArrivalVector");
         //numMessageReceived = 0;
         std::cout << "I'm " << findHost()->getFullName() <<  " myMac: " << myMac << " MACToInteger: " << MACToInteger() << endl;
     }
 }
void epidemic_rsu::onBeacon (WaveShortMessage * wsm) protected virtual
Implements BaseWaveApplLayer.
Definition at line 48 of file epidemic_rsu.cc.
{
     //cout << "I'm " << findHost()->getFullName() << "(" << MACToInteger() << ") and I received a Beacon from " << wsm->getSenderAddress() << " with destination " << wsm->getRecipientAddress() << endl;
     //Verifying if I have the smaller address in order to start the anti-entropy session sending out my summary vector
     if(wsm->getSenderAddress() > MACToInteger()){ //true means that I have the smaller address
         //cout << "I'm " << findHost()->getFullName() << " and my ID is smaller than the Beacon sender." << endl;
         //Verifying if (current contact simutime - last contact simutime) is bigger than previous slide window defined
         //A new summary vector needs to be re-sent to the same contact node only "sendSummaryVectorInterval" seconds after the last one
         unordered_map<unsigned int,simtime_t>::const_iterator got = nodesIRecentlySentSummaryVector.find(wsm->getSenderAddress());
         if(got == nodesIRecentlySentSummaryVector.end()){ //true value means that there is no entry in the nodesIRecentlySentSummaryVector for the current contact node
             //cout << "I'm " << findHost()->getFullName() << ". Contact not found in nodesIRecentlySentSummaryVector. Sending my summary vector to " << wsm->getSenderAddress() << endl;
             //Sending my summary vector to another mobile node
             sendLocalSummaryVector(wsm->getSenderAddress());
             nodesIRecentlySentSummaryVector.insert(make_pair<unsigned int, simtime_t>(wsm->getSenderAddress(),simTime()));
             printNodesIRecentlySentSummaryVector();
         }
         //An entry in the unordered_map was found
         else{
            //cout << "I'm " << findHost()->getFullName() << ". Contact found in nodesIRecentlySentSummaryVector. Node: " << got->first << " added at " << (simTime() - got->second) << " seconds ago." << endl;
            if((simTime() - got->second) > sendSummaryVectorInterval){ //checking if I should update the nodesIRecentlySentSummaryVector entry
                //cout << "I'm " << findHost()->getFullName() << " and I'm updating the entry in the nodesIRecentlySentSummaryVector." << endl;
                sendLocalSummaryVector(wsm->getSenderAddress());
                nodesIRecentlySentSummaryVector.erase(wsm->getSenderAddress());
                nodesIRecentlySentSummaryVector.insert(make_pair<unsigned int, simtime_t>(wsm->getSenderAddress(),simTime()));
                printNodesIRecentlySentSummaryVector();
            }
         }
     }
     //My address is bigger than the Beacon sender
     else{
         //do nothing
         //std::cout << "My ID is bigger than the Beacon sender." << std::endl;
     }
 }
void epidemic_rsu::onData (WaveShortMessage * wsm) protected virtual
Implements BaseWaveApplLayer.
Definition at line 84 of file epidemic_rsu.cc.
{
     //Verifying the kind of a received message: if a summary vector (true) or a epidemic buffer data message (false).
     if(wsm->getSummaryVector()){
        //checking if the summary vector was sent to me
        if(wsm->getRecipientAddress() == MACToInteger()){
           cout << "I'm " << findHost()->getFullName() << "(" << MACToInteger() << ") and I just recieved the summary vector |> " << wsm->getWsmData() << " <| from " << wsm->getSenderAddress() << endl;
           //Creating the remote summary vector with the data received in wsm->message field
           createEpidemicRemoteSummaryVector(wsm->getWsmData());
           printEpidemicRemoteSummaryVectorData();
           printEpidemicLocalSummaryVectorData();
           //Creating a key vector in order to request messages that I still do not have in my buffer
           createEpidemicRequestMessageVector();
           printEpidemicRequestMessageVector();
           //Verifying if this is the end of second round of the anti-entropy session when the EpidemicRemoteSummaryVector and EpidemicLocalSummaryVector are equals
           if((epidemicRequestMessageVector.empty() ||(strcmp(wsm->getWsmData(),"") == 0)) && (wsm->getSenderAddress() > MACToInteger())){
              //cout << "EpidemicRequestMessageVector from " << findHost()->getFullName() << " is empty now " << endl;
              //cout << "Or strcmp(wsm->getWsmData(),\"\") == 0) " << endl;
              //cout << "And  wsm->getSenderAddress() > MACToInteger() " << endl;
           }else if(epidemicRequestMessageVector.empty()){
               //cout << "EpidemicRequestMessageVector from " << findHost()->getFullName() << " is empty now " << endl;
               //changing the turn of the anti-entropy session. In this case, I have not found any differences between EpidemicRemoteSummaryVector and EpidemicLocalSummaryVector but I need to change the round of anti-entropy session
               sendLocalSummaryVector(wsm->getSenderAddress());
           }else{
               //Sending a request vector in order to get messages that I don't have
               sendEpidemicRequestMessageVector(wsm->getSenderAddress());
           }
        }
     }
     //is a data message requisition or a data message content
     else{
         //cout << "I'm " << findHost()->getFullName() << ". This is not a summary vector" << endl;
         //Verifying if this is a request message
         if(wsm->getRequestMessages()){
             //checking if the request vector was sent to me
             if(wsm->getRecipientAddress() == MACToInteger()){
                 //Searching for elements in the epidemicLocalMessageBuffer and sending them to requester
                 cout << "I'm " << findHost()->getFullName() << ". I received the epidemicRequestMessageVector |> " << wsm->getWsmData() << " <| from " << wsm->getSenderAddress() << endl;
                 sendMessagesRequested(wsm->getWsmData(), wsm->getSenderAddress());
             }
         }
         //is data content
         else{
              if(wsm->getRecipientAddress() == MACToInteger()){
                  //WSMData generated by car[3]|car[3]|rsu[0]|1.2
                  cout << "I'm " << findHost()->getFullName() << "(" << MACToInteger() << "). I received all the message requested |> " << wsm->getWsmData() << " <| from " << wsm->getSenderAddress() << endl;
                  cout << "Before message processing " << endl;
                  printEpidemicLocalMessageBuffer();
                  cout << "Before message processing " << endl;
                  printEpidemicLocalSummaryVectorData();
                  cout << "Before message processing " << endl;
                  printQueueFIFO(queueFIFO);
                  string delimiter = "|";
                  size_t pos = 0;
                  string tokenkey, tokenData, tokenSource, tokenTarget, tokenTimestamp, tokenhopcount;
                  string messageReceived = wsm->getWsmData();
                  simtime_t st;
                  //cout << "pos = messageReceived.find(delimiter): " << messageReceived.find(delimiter) << endl;
                  //cout << "std::string::npos: " << std::string::npos << endl;
                  while((pos = messageReceived.find(delimiter)) != std::string::npos) {
                         tokenkey = messageReceived.substr(0, pos);
                         messageReceived.erase(0, pos + delimiter.length());
                         pos = messageReceived.find(delimiter);
                         tokenData = messageReceived.substr(0, pos);
                         messageReceived.erase(0, pos + delimiter.length());
                         pos = messageReceived.find(delimiter);
                         tokenSource = messageReceived.substr(0, pos);
                         messageReceived.erase(0, pos + delimiter.length());
                         pos = messageReceived.find(delimiter);
                         tokenTarget = messageReceived.substr(0, pos);
                         messageReceived.erase(0, pos + delimiter.length());
                         pos = messageReceived.find(delimiter);
                         tokenTimestamp = messageReceived.substr(0, pos);
                         messageReceived.erase(0, pos + delimiter.length());
                         pos = messageReceived.find(delimiter);
                         tokenhopcount = messageReceived.substr(0, pos);
                         messageReceived.erase(0, pos + delimiter.length());
                         //cout << "I'm " << findHost()->getFullName() << " and the message received is tokenData: " << tokenData << "tokenSource: " << tokenSource << "tokenTarget: " << tokenTarget << "tokenTimestamp: " << tokenTimestamp << endl;
                         WaveShortMessage w = *wsm;
                         w.setWsmData(tokenData.c_str());
                         w.setSource(tokenSource.c_str());
                         w.setTarget(tokenTarget.c_str());
                         w.setTimestamp(st.parse(tokenTimestamp.c_str()));
                         w.setHopCount(stoi(tokenhopcount));
                         //checking if the maximum buffer size was reached
                         if(queueFIFO.size() < maximumEpidemicBufferSize){
                             //Verifying if there is no entry for current message received in my epidemicLocalMessageBuffer
                             unordered_map<string,WaveShortMessage>::const_iterator got = epidemicLocalMessageBuffer.find(tokenkey);
                             if(got == epidemicLocalMessageBuffer.end()){ //true value means that there is no entry in the epidemicLocalMessageBuffer for the current message identification
                                 //Putting the message in the epidemicLocalMessageBuffer
                                 epidemicLocalMessageBuffer.insert(MyPairEpidemicMessageBuffer(tokenkey,w));
                                 //Putting the message in the EpidemicLocalSummaryVector
                                 epidemicLocalSummaryVector.insert(make_pair<string, bool>(tokenkey.c_str(),true));
                                 //FIFO strategy to set the maximum size that a node is willing to allocate epidemic messages in its buffer
                                 queueFIFO.push(tokenkey.c_str());
                                 //printQueueFIFO(queueFIFO);
                                 bubble("message added in my buffer"); //making animation message more informative
                                 //recording some statistics
 //                                cout << "findHost()->getFullName() == w.getTarget(): " << " findHost()->getFullName(): " << findHost()->getFullName() << " w.getTarget():" << w.getTarget() << endl;
                                 if(strcmp(findHost()->getFullName(), w.getTarget()) == 0){
                                     //hopCountVector.record(hopCount - w.getHopCount());
                                     //hopCountStats.collect(hopCount - w.getHopCount());
                                     //messageArrivalTimeVector.record((simTime() - w.getTimestamp()));
                                     //messageArrivalTimeStats.collect((simTime() - w.getTimestamp()));
                                     //numMessageReceived++;
                                    // emit(delayToDeliverSignal, (simTime() - w.getTimestamp()));
                                    // emit(hopsToDeliverSignal, (hopCount - w.getHopCount()));
                                    // emit(messageArrivalSignal, 1);
                                     if(maiortempo < (simTime() - w.getTimestamp()).dbl())
                                         maiortempo = (simTime() - w.getTimestamp()).dbl();
 //                                    cout << "numMessageReceived: " << numMessageReceived << endl;
                                 }
                             }
                             //An entry in the unordered_map was found
                             else{
                                 //do nothing because the message is already in my epidemicLocalBuffer
                             }
                         }
                         //The maximum buffer size was reached, so I have to remove the first item from the queueFIFO
                         else{
                             //Verifying if there is no entry for current message received in my epidemicLocalMessageBuffer
                             unordered_map<string,WaveShortMessage>::const_iterator got = epidemicLocalMessageBuffer.find(tokenkey.c_str());
                             if(got == epidemicLocalMessageBuffer.end()){ //true value means that there is no entry in the epidemicLocalMessageBuffer for the current message identification
                                 epidemicLocalMessageBuffer.erase(queueFIFO.front());
                                 epidemicLocalSummaryVector.erase(queueFIFO.front());
                                 queueFIFO.pop();
                                 //Putting the message in the epidemicLocalMessageBuffer
                                 epidemicLocalMessageBuffer.insert(MyPairEpidemicMessageBuffer(tokenkey,w));
                                 //Putting the message in the EpidemicLocalSummaryVector
                                 epidemicLocalSummaryVector.insert(make_pair<string, bool>(tokenkey.c_str(),true));
                                 //FIFO strategy to set the maximum size that a node is willing to allocate epidemic messages in its buffer
                                 queueFIFO.push(tokenkey.c_str());
                                 //printQueueFIFO(queueFIFO);
                                 //recording some statistics
 //                                cout << "findHost()->getFullName() == w.getTarget(): " << " findHost()->getFullName(): " << findHost()->getFullName() << " w.getTarget():" << w.getTarget() << endl;
                                 if(strcmp(findHost()->getFullName(), w.getTarget()) == 0){
                                     //hopCountVector.record(hopCount - w.getHopCount());
                                     //hopCountStats.collect(hopCount - w.getHopCount());
                                     //messageArrivalTimeVector.record((simTime() - w.getTimestamp()));
                                     //messageArrivalTimeStats.collect((simTime() - w.getTimestamp()));
                                     cout << "Removing an item in my buffer because the size of it was reached" << endl;
                                     //cout << "numMessageReceived++: " << numMessageReceived++ << endl;
                                     //numMessageReceived++;
                                     //emit(arrivalSignal, (hopCount - w.getHopCount()));
                                     //emit(arrivalSignal, (simTime() - w.getTimestamp()));
                                     if(maiortempo < (simTime() - w.getTimestamp()).dbl())
                                         maiortempo = (simTime() - w.getTimestamp()).dbl();
 //                                    cout << "numMessageReceived: " << numMessageReceived << endl;
                                 }
                             }
                             //An entry in the unordered_map was found
                             else{
                                 //do nothing because the message is already in my epidemicLocalBuffer
                             }
                         }
                  } // end of while
                  cout << "After message processing " << endl;
                  printEpidemicLocalMessageBuffer();
                  cout << "After message processing " << endl;
                  printEpidemicLocalSummaryVectorData();
                  cout << "After message processing " << endl;
                  printQueueFIFO(queueFIFO);
                  //changing the turn of the anti-entropy session. If this is the first round, call sendLocalSummaryVector(wsm->getSenderAddress())
                  if(wsm->getSenderAddress() < MACToInteger())
                    sendLocalSummaryVector(wsm->getSenderAddress());
              } //end of if
         }// end of else
         //Verifying if I'm the target of a message
         if(strcmp(wsm->getTarget(),findHost()->getFullName()) == 0){
           std::cout << "I'm " << findHost()->getFullName() << ", the recipient of the message." << " at " << simTime() << std::endl;
           //sendWSM(prepareWSM_epidemic("beacon", beaconLengthBits, type_CCH, beaconPriority, wsm->getSenderAddress(), -1));
         }
         //this node is a relaying node because it is not the target of the message
         else{
              //std::cout << findHost()->getFullName() << " will cache the message for forwarding it later." << " at " << simTime() << std::endl;
         }
     }
 }
void epidemic_rsu::printEpidemicLocalMessageBuffer () protected
Definition at line 487 of file epidemic_rsu.cc.
Referenced by onData(), and sendMessagesRequested().
{
     if(epidemicLocalMessageBuffer.empty()){
            cout << "EpidemicLocalMessageBuffer from " << findHost()->getFullName() << " is empty now " << endl;
     }else{
         int i = 0;
         cout << "Printing the epidemicLocalMessageBuffer from " << findHost()->getFullName() << "(" << MACToInteger() <<"):" << endl;
         for(auto& x: epidemicLocalMessageBuffer){
             WaveShortMessage wsmBuffered = x.second;
             cout << " Key " << ++i << ": " << x.first << " - Message Content: " << wsmBuffered.getWsmData() << " source: " << wsmBuffered.getSource() << " target: " << wsmBuffered.getTarget() << " Timestamp: " << wsmBuffered.getTimestamp() << " HopCount: " << wsmBuffered.getHopCount() << endl;
         }
     }
 }
void epidemic_rsu::printEpidemicLocalSummaryVectorData () protected
Definition at line 500 of file epidemic_rsu.cc.
Referenced by onData().
{
     if(epidemicLocalSummaryVector.empty()){
            cout << "EpidemicLocalSummaryVector from " << findHost()->getFullName() << " is empty now " << endl;
     }else{
         ostringstream ss;
         for(auto& x: epidemicLocalSummaryVector)
            ss << x.first << "|" << x.second << "|";
         string s = ss.str();
         s = s.substr(0, s.length() - 1);
         cout << "EpidemicLocalSummaryVector from " << findHost()->getFullName() << "(" << MACToInteger() << "): " <<  s  << endl;
     }
 }
void epidemic_rsu::printEpidemicRemoteSummaryVectorData () protected
Definition at line 513 of file epidemic_rsu.cc.
Referenced by onData().
{
     if(epidemicRemoteSummaryVector.empty()){
            cout << "EpidemicRemoteSummaryVector from " << findHost()->getFullName() << " is empty now " << endl;
     }else{
         ostringstream ss;
         for(auto& x: epidemicRemoteSummaryVector)
             ss << x.first << "|" << x.second << "|";
         string s = ss.str();
         s = s.substr(0, s.length() - 1);
         cout << "EpidemicRemoteSummaryVector from " << findHost()->getFullName() << ": " <<  s  << endl;
     }
 }
void epidemic_rsu::printEpidemicRequestMessageVector () protected
Definition at line 526 of file epidemic_rsu.cc.
Referenced by onData().
{
     if(epidemicRequestMessageVector.empty()){
         cout << "EpidemicRequestMessageVector from " << findHost()->getFullName() << " is empty now " << endl;
     }
     else{
         ostringstream ss;
         for(auto& x: epidemicRequestMessageVector)
             ss << x.first << "|" << x.second << "|";
         string s = ss.str();
         s = s.substr(0, s.length() - 1);
         cout << "EpidemicRequestMessageVector from " << findHost()->getFullName() << ": " <<  s  << endl;
     }
 }
void epidemic_rsu::printNodesIRecentlySentSummaryVector () protected
Definition at line 541 of file epidemic_rsu.cc.
Referenced by onBeacon().
{
     if(nodesIRecentlySentSummaryVector.empty()){
            cout << "NodesIRecentlySentSummaryVector from " << findHost()->getFullName() << " is empty now " << endl;
     }
     else{
         int i = 0;
         cout << "NodesIRecentlySentSummaryVector from " << findHost()->getFullName() << " (" << MACToInteger() << "):" << endl;
         for(auto& x: nodesIRecentlySentSummaryVector)
             cout << ++i << " Node: " << x.first << " added at " << x.second << endl;
     }
 }
void epidemic_rsu::printQueueFIFO (queue< string > qFIFO) protected
Definition at line 479 of file epidemic_rsu.cc.
Referenced by onData().
{
     int i = 0;
     while(!qFIFO.empty()){
         cout << "I'm " << findHost()->getFullName() << " - queueFIFO Element " << ++i << ": " << qFIFO.front() << endl;
         qFIFO.pop();
     }
 }
void epidemic_rsu::printWaveShortMessage (WaveShortMessage wsm) protected
Definition at line 553 of file epidemic_rsu.cc.
{
     cout << "wsm.getName():" << wsm.getName() << endl;
     cout << "wsm.getBitLength():" << wsm.getBitLength() << endl;
     cout << "wsm.getChannelNumber():" << wsm.getChannelNumber() << endl;
     cout << "wsm.getPsid():" << wsm.getPsid() << endl;
     cout << "wsm.getPriority():" << wsm.getPriority() << endl;
     cout << "wsm.getWsmVersion():" << wsm.getWsmVersion() << endl;
     cout << "wsm.getTimestamp():" << wsm.getTimestamp() << endl;
     cout << "wsm.getSenderAddress():" << wsm.getSenderAddress() << endl;
     cout << "wsm.getRecipientAddress():" << wsm.getRecipientAddress() << endl;
     cout << "wsm.getSource():" << wsm.getSource() << endl;
     cout << "wsm.getTarget():" << wsm.getTarget() << endl;
     cout << "wsm.getSenderPos():" << wsm.getSenderPos() << endl;
     cout << "wsm.getSerial():" << wsm.getSerial() << endl;
     cout << "wsm.getSummaryVector():" << wsm.getSummaryVector() << endl;
     cout << "wsm.getRequestMessages():" << wsm.getRequestMessages() << endl;
     cout << "wsm.getWsmData():" << wsm.getWsmData() << endl;
     cout << "wsm.getLocalMessageIdentificaton(): " << wsm.getLocalMessageIdentificaton() << endl;
     cout << "wsm.getGlobalMessageIdentificaton(): " << wsm.getGlobalMessageIdentificaton() << endl;
     cout << "wsm.getHopCount(): " << wsm.getHopCount() << endl;
 }
void epidemic_rsu::printWaveShortMessage (WaveShortMessage * wsm) protected
Definition at line 575 of file epidemic_rsu.cc.
{
     cout << "wsm->getName()" << wsm->getName() << endl;
     cout << "wsm->getBitLength()" << wsm->getBitLength() << endl;
     cout << "wsm->getChannelNumber()" << wsm->getChannelNumber() << endl;
     cout << "wsm->getPsid()" << wsm->getPsid() << endl;
     cout << "wsm->getPriority()" << wsm->getPriority() << endl;
     cout << "wsm->getWsmVersion()" << wsm->getWsmVersion() << endl;
     cout << "wsm->getTimestamp()" << wsm->getTimestamp() << endl;
     cout << "wsm->getSenderAddress()" << wsm->getSenderAddress() << endl;
     cout << "wsm->getRecipientAddress()" << wsm->getRecipientAddress() << endl;
     cout << "wsm->getSource()" << wsm->getSource() << endl;
     cout << "wsm->getTarget()" << wsm->getTarget() << endl;
     cout << "wsm->getSenderPos()" << wsm->getSenderPos() << endl;
     cout << "wsm->getSerial()" << wsm->getSerial() << endl;
     cout << "wsm->getSummaryVector()" << wsm->getSummaryVector() << endl;
     cout << "wsm->getRequestMessages()" << wsm->getRequestMessages() << endl;
     cout << "wsm->getWsmData()" << wsm->getWsmData() << endl;
 }
void epidemic_rsu::sendBeacon () protected
Definition at line 265 of file epidemic_rsu.cc.
{
     t_channel channel = dataOnSch ? type_SCH : type_CCH;
     std::cout << "Channel: " << channel << std::endl;
     WaveShortMessage* wsm = prepareWSM_epidemic("beacon", dataLengthBits, channel, dataPriority, BROADCAST,2);
     sendWSM(wsm);
 }
void epidemic_rsu::sendBeacon (unsigned int target) protected
void epidemic_rsu::sendEpidemicRequestMessageVector (unsigned int newRecipientAddress) protected
Definition at line 399 of file epidemic_rsu.cc.
Referenced by onData().
{
     t_channel channel = dataOnSch ? type_SCH : type_CCH;
     WaveShortMessage* wsm = prepareWSM_epidemic("data", dataLengthBits, channel, dataPriority, newRecipientAddress,2);
     wsm->setSummaryVector(false);
     wsm->setRequestMessages(true);
     //Put the summary vector here
     wsm->setWsmData(getEpidemicRequestMessageVectorData().c_str());
     //Sending the summary vector
     sendWSM(wsm);
     //cout << "Sending a vector of request messages from " << findHost()->getFullName() <<"(" << MACToInteger() << ") to " << newRecipientAddress << endl;
     //epidemicRequestMessageVector.clear();
 }
void epidemic_rsu::sendLocalSummaryVector (unsigned int newRecipientAddress) protected
Definition at line 277 of file epidemic_rsu.cc.
Referenced by onBeacon(), and onData().
{
     t_channel channel = dataOnSch ? type_SCH : type_CCH;
     WaveShortMessage* wsm = prepareWSM_epidemic("data", dataLengthBits, channel, dataPriority, newRecipientAddress,2);
     wsm->setSummaryVector(true);
     wsm->setRequestMessages(false);
     //Put the summary vector here, on data wsm field
     wsm->setWsmData(getLocalSummaryVectorData().c_str());
     //Sending the summary vector
     sendWSM(wsm);
 }
void epidemic_rsu::sendMessagesRequested (string s, unsigned int recipientAddress) protected
Definition at line 288 of file epidemic_rsu.cc.
Referenced by onData().
{
     cout << "I'm " << findHost()->getFullName() << "(" << MACToInteger() << "). Sending the following messages resquested: " << s << " to " << recipientAddress << endl;
     t_channel channel = dataOnSch ? type_SCH : type_CCH;
     WaveShortMessage* wsm = prepareWSM_epidemic("data", dataLengthBits, channel, dataPriority, recipientAddress,2);
     string delimiter = "|";
     size_t pos = 0;
     string token;
     unsigned i = 0;
     string message="";
     printEpidemicLocalMessageBuffer();
     //Extracting who request message
     pos = s.find(delimiter);
     string tokenRequester = s.substr(0, pos);
     s.erase(0, pos + delimiter.length());
     while ((pos = s.find(delimiter)) != std::string::npos) {
       //Catch jus the key of the local summary vector
       if(i%2 == 0){
           ostringstream ss;
           //cout << "i = " << i << " - looking for the message key(s.substr(0, pos)): " << s.substr(0, pos) << endl;
           WaveShortMessage w;
           unordered_map<string,WaveShortMessage>::const_iterator got = epidemicLocalMessageBuffer.find(s.substr(0, pos));
           if(got == epidemicLocalMessageBuffer.end()){ //true value means that there is no entry in the epidemicLocalSummaryVector for a epidemicRemoteSummaryVector key
           }else{
                w = got->second;
                //WaveShortMessage w = getEpidemicLocalMessageBuffer(s.substr(0, pos));
                //Verifying if I'm still able to spread the message or not. If w.getHopCount == 1 I'm able to send the message only to its target
                if(w.getHopCount() > 1){
                  ss << s.substr(0, pos) << "|" << w.getWsmData() << "|" << w.getSource() << "|" << w.getTarget() << "|" << w.getTimestamp() << "|" << w.getHopCount() - 1 << "|";
                }else if(w.getHopCount() == 1){
                  if((strcmp(tokenRequester.c_str(),w.getTarget()) == 0)){
                    ss << s.substr(0, pos) << "|" << w.getWsmData() << "|" << w.getSource() << "|" << w.getTarget() << "|" << w.getTimestamp() << "|" << w.getHopCount() - 1 << "|";
                  }
                }
                //cout << "ss.str() inside the sendMessageRequested method: " << ss.str() << endl;
                message += ss.str();
                //cout << "message inside the sendMessageRequested method. message += ss.str(): " << message << endl;
           }
       }
       //cout << "i = " << i << " - s inside the sendMessageRequested method: " << s << endl;
       s.erase(0, pos + delimiter.length());
       //cout << "i = " << i << " - s inside the sendMessageRequested method, after s.erase(0, pos + delimiter.length()): " << s << endl;
       i++;
     }
     message = message.substr(0, message.length() - 1);
     cout << "Message that is sending as a result of a requisition vector request. wsm->setWsmData: " <<  message << endl;
     wsm->setWsmData(message.c_str());
     wsm->setSummaryVector(false);
     wsm->setRequestMessages(false);
     sendWSM(wsm);
 }
void epidemic_rsu::sendWSM (WaveShortMessage * wsm) protected virtual
Reimplemented from BaseWaveApplLayer.
Definition at line 272 of file epidemic_rsu.cc.
Referenced by sendBeacon(), sendEpidemicRequestMessageVector(), sendLocalSummaryVector(), and sendMessagesRequested().
{
     sendDelayedDown(wsm,individualOffset);
 }
Member Data Documentation
AnnotationManager* epidemic_rsu::annotations protected
Definition at line 39 of file epidemic_rsu.h.
Referenced by initialize().
MyMapEpidemicMessageBuffer epidemic_rsu::epidemicLocalMessageBuffer protected
Definition at line 46 of file epidemic_rsu.h.
Referenced by onData(), printEpidemicLocalMessageBuffer(), and sendMessagesRequested().
unordered_map<string, bool> epidemic_rsu::epidemicLocalSummaryVector protected
Definition at line 48 of file epidemic_rsu.h.
Referenced by createEpidemicRequestMessageVector(), getLocalSummaryVectorData(), onData(), and printEpidemicLocalSummaryVectorData().
unordered_map<string, bool> epidemic_rsu::epidemicRemoteSummaryVector protected
Definition at line 50 of file epidemic_rsu.h.
Referenced by createEpidemicRemoteSummaryVector(), createEpidemicRequestMessageVector(), and printEpidemicRemoteSummaryVectorData().
unordered_map<string, bool> epidemic_rsu::epidemicRequestMessageVector protected
Definition at line 52 of file epidemic_rsu.h.
Referenced by createEpidemicRequestMessageVector(), getEpidemicRequestMessageVectorData(), onData(), and printEpidemicRequestMessageVector().
double epidemic_rsu::maiortempo = 0 protected
Definition at line 60 of file epidemic_rsu.h.
Referenced by onData().
BaseMobility* epidemic_rsu::mobi protected
Definition at line 40 of file epidemic_rsu.h.
Referenced by initialize().
unordered_map<unsigned int, simtime_t> epidemic_rsu::nodesIRecentlySentSummaryVector protected
Definition at line 57 of file epidemic_rsu.h.
Referenced by onBeacon(), and printNodesIRecentlySentSummaryVector().
unordered_map<unsigned int, simtime_t> epidemic_rsu::nodesRecentlyFoundList protected
Definition at line 55 of file epidemic_rsu.h.
queue<string> epidemic_rsu::queueFIFO protected
Definition at line 59 of file epidemic_rsu.h.
Referenced by onData().
bool epidemic_rsu::sentMessage protected
Definition at line 41 of file epidemic_rsu.h.
The documentation for this class was generated from the following files:
epidemic_rsu.h
epidemic_rsu.cc