Veins Framework: Argument Class Reference
Argument Class Reference
Defines an argument for a mapping.
#include <MappingBase.h>
Classes
class key_iterator
Public Types
typedef DimensionSet::value_type key_type
typedef double mapped_type
typedef const mapped_type mapped_type_cref
typedef container_type::iterator iterator
Iterator type for this set.
typedef
container_type::const_iterator const_iterator
Const-iterator type for this set.
Public Member Functions
Argument (simtime_t_cref timeVal=0)
Initialize this argument with the passed value for the time dimension.
Argument (const DimensionSet &dims, simtime_t_cref timeVal=SIMTIME_ZERO)
Initializes the Argument with the dimensions of the passed DimensionSet set to zero, and the passed value for the time (or zero, if omitted).
simtime_t_cref getTime () const
Returns the time value of this argument.
void setTime (simtime_t_cref time)
Changes the time value of this argument.
bool hasArgVal (const Argument::key_type &dim) const
Returns true if this Argument has a value for the passed Dimension.
mapped_type_cref getArgValue (const Argument::key_type &dim) const
Returns the value for the specified dimension.
void setArgValue (const Argument::key_type &dim, Argument::mapped_type_cref value)
Changes the value for the specified dimension.
void setArgValues (const Argument &o, bool ignoreUnknown=false)
Update the values of this Argument with the values of the passed Argument.
bool isSamePosition (const Argument &other) const
Returns true if the passed Argument points to the same position.
bool operator== (const Argument &o) const
Two Arguments are compared equal if they have the same dimensions and the same values.
bool isClose (const Argument &o, Argument::mapped_type_cref epsilon=Argument::mapped_type(0.000001)) const
Two Arguments are compared close if they have the same dimensions and their values don't differ more then a specific epsilon.
bool operator< (const Argument &o) const
Returns true if this Argument is smaller then the passed Argument.
int compare (const Argument &o, const DimensionSet *const dims=NULL) const
Compares this Argument with the passed Argument in the dimensions of the passed DimensionsSet.
DimensionSet getDimensions () const
Returns the dimensions this argument is defined over.
void operator= (const Argument &o)
Fast implementation of the copy-operator then the default implementation.
iterator begin ()
Returns an iterator to the first argument value in this Argument.
const_iterator begin () const
Returns an iterator to the first argument value in this Argument.
iterator end ()
Returns an iterator to the value behind the last argument value.
const_iterator end () const
Returns an iterator to the value behind the last argument value.
iterator find (const Argument::key_type &dim)
Returns an iterator to the Argument value for the passed Dimension.
const_iterator find (const Argument::key_type &dim) const
Returns an iterator to the Argument value for the passed Dimension.
iterator lower_bound (const Argument::key_type &dim)
Returns an iterator to the first Argument value which dimension compares greater or equal to the passed Dimension.
const_iterator lower_bound (const Argument::key_type &dim) const
Returns an iterator to the first Argument value which dimension compares greater or equal to the passed Dimension.
Static Public Attributes
static const mapped_type MappedZero = Argument::mapped_type(0)
Zero value of a Argument value.
static const mapped_type MappedOne = Argument::mapped_type(1)
One value of a Argument value.
Protected Types
typedef std::map< key_type,
mapped_type > container_type
typedef container_type::value_type value_type
Protected Member Functions
iterator insertValue (iterator pos, const Argument::value_type &valPair, iterator &itEnd, bool ignoreUnknown=false)
Inserts the passed value for the passed Dimension into this Argument.
Protected Attributes
simtime_t time
Stores the time dimension in Omnet's time type.
container_type values
Maps the dimensions of this Argument to their values.
Friends
std::ostream & operator<< (std::ostream &out, const Argument &d)
Output operator for Arguments.
Detailed Description
Defines an argument for a mapping.
Defines values for a specified set of dimensions, but at least for the time dimension.
Note: Currently an Argument can be maximal defined over ten Dimensions plus the time dimension!
Author
Karl Wessel
Definition at line 284 of file MappingBase.h.
Member Typedef Documentation
typedef container_type::const_iterator Argument::const_iterator
Const-iterator type for this set.
Definition at line 307 of file MappingBase.h.
typedef std::map<key_type, mapped_type> Argument::container_type protected
Definition at line 295 of file MappingBase.h.
typedef container_type::iterator Argument::iterator
Iterator type for this set.
Definition at line 305 of file MappingBase.h.
typedef DimensionSet::value_type Argument::key_type
Definition at line 286 of file MappingBase.h.
typedef double Argument::mapped_type
Definition at line 287 of file MappingBase.h.
typedef const mapped_type Argument::mapped_type_cref
Definition at line 288 of file MappingBase.h.
typedef container_type::value_type Argument::value_type protected
Definition at line 296 of file MappingBase.h.
Constructor & Destructor Documentation
Argument::Argument (simtime_t_cref timeVal = 0)
Initialize this argument with the passed value for the time dimension.
Definition at line 73 of file MappingBase.cc.
                                         :
         time(timeVal), values()
 {}
Argument::Argument (const DimensionSet & dims, simtime_t_cref timeVal = SIMTIME_ZERO)
Initializes the Argument with the dimensions of the passed DimensionSet set to zero, and the passed value for the time (or zero, if omitted).
Definition at line 77 of file MappingBase.cc.
                                                                    :
         time(timeVal), values()
 {
         DimensionSet::const_iterator       it    = dims.begin();
         const DimensionSet::const_iterator itEnd = dims.end();
         assert((*it) == Dimension::time);
         for ( ++it; it != itEnd; ++it) {
                 values.insert( Argument::value_type(*it, Argument::MappedZero) );
         }
 }
Member Function Documentation
iterator Argument::begin () inline
Returns an iterator to the first argument value in this Argument.
Definition at line 502 of file MappingBase.h.
Referenced by MappingUtils::findMax(), MappingUtils::findMin(), isClose(), isSamePosition(), ConstMapping::print(), and setArgValues().
 { return values.begin(); }
const_iterator Argument::begin () const inline
Returns an iterator to the first argument value in this Argument.
Definition at line 506 of file MappingBase.h.
 { return values.begin(); }
int Argument::compare (const Argument & o, const DimensionSet *const dims = NULL) const
Compares this Argument with the passed Argument in the dimensions of the passed DimensionsSet.
(Every other Dimension is asserted equal).
Returns
< 0 - passed Argument is bigger = 0 - Arguments are equal > 0 - passed Argument is smaller
See "operator<" for definition of smaller, equal and bigger.
Definition at line 261 of file MappingBase.cc.
Referenced by MappingUtils::findMin(), operator<(), and operator==().
 {
         DimensionSet::const_iterator                 DimItLast; if (dims != NULL) DimItLast = dims->end();
         const DimensionSet::const_iterator           DimItEnd  = DimItLast;
         const container_type::const_reverse_iterator rItEnd = values.rend();
         const container_type::const_iterator         itEndO = o.values.end();
         container_type::const_reverse_iterator       rIt;
         container_type::const_iterator               itO;
         bool                                         bDidCompare = false;
         //iterate through passed dimensions and compare arguments in these dimensions
         for (container_type::const_reverse_iterator rIt = values.rbegin(); rIt != rItEnd; ++rIt) {
                 bool bMissedDimsEntry = false;
                 if (dims != NULL) {
                         DimensionSet::const_iterator DimItCurr = dims->find(rIt->first);
                         if (DimItCurr == DimItEnd) {
                                 continue;
                         }
                         if (DimItLast != DimItEnd && (--DimItLast) != DimItEnd) {
                                 bMissedDimsEntry = (DimItLast != DimItCurr); // missed something
                         }
                         DimItLast = DimItCurr;
                 }
                 bDidCompare = true;
                 //catch special cases time, missing dimension values (after which we can abort)
                 if( bMissedDimsEntry || (itO = o.values.find(rIt->first)) == itEndO ) {
                         if (time == o.time)
                                 return 0;
                         return (time < o.time) ? -1 : 1;
                 }
                 //if both Arguments are defined in the current dimensions
                 //compare them (otherwise we assume them equal and continue)
                 if (rIt->second != itO->second)
                         return (rIt->second < itO->second) ? -1 : 1;
         }
         if (dims == NULL || (dims->find(Dimension::time) != DimItEnd || (!bDidCompare && !dims->empty()))) {
                 if (time == o.time)
                         return 0;
                 return (time < o.time) ? -1 : 1;
         }
         return 0;
 }
iterator Argument::end () inline
Returns an iterator to the value behind the last argument value.
Definition at line 512 of file MappingBase.h.
Referenced by MappingUtils::findMax(), MappingUtils::findMin(), isClose(), isSamePosition(), ConstMapping::print(), and setArgValues().
 { return values.end(); }
const_iterator Argument::end () const inline
Returns an iterator to the value behind the last argument value.
Definition at line 516 of file MappingBase.h.
 { return values.end(); }
Argument::iterator Argument::find (const Argument::key_type & dim)
Returns an iterator to the Argument value for the passed Dimension.
Returns end() if there is no Argument for that dimension.
Definition at line 100 of file MappingBase.cc.
Referenced by getArgValue(), and ConstMapping::print().
{
         assert(!(dim == Dimension::time));
         return values.find(dim);
 }
Argument::const_iterator Argument::find (const Argument::key_type & dim) const
Returns an iterator to the Argument value for the passed Dimension.
Returns end() if there is no Argument for that dimension.
Definition at line 106 of file MappingBase.cc.
{
         assert(!(dim == Dimension::time));
         return values.find(dim);
 }
Argument::mapped_type_cref Argument::getArgValue (const Argument::key_type & dim) const
Returns the value for the specified dimension.
Note: Don't use this function to get the time value! Use "getTime()" instead.
Returns zero if no value with the specified dimension is set for this argument.
Definition at line 128 of file MappingBase.cc.
Referenced by FilledUpMapping::appendValue(), MappingUtils::createCompatibleMapping(), SimpleConstMapping::createKeyEntries(), MappingUtils::findMax(), MappingUtils::findMin(), SimplePathlossConstMapping::getValue(), TwoRayInterferenceModel::Mapping::getValue(), MultiDimMapping< Linear >::getValue(), MultiDimMappingIterator< Linear >::iterateTo(), MultiDimMappingIterator< Linear >::jumpTo(), ConstMapping::print(), and MultiDimMapping< Linear >::setValue().
 {
         const_iterator it = find(dim);
         if(it == values.end())
                 return MappedZero;
         return it->second;
 }
DimensionSet Argument::getDimensions () const inline
Returns the dimensions this argument is defined over.
Note: this method has linear complexity over the number of dimensions, since the DimensionSet has to be created from the values and their dimensions inside this Argument.
Definition at line 467 of file MappingBase.h.
Referenced by MappingUtils::findMax(), MappingUtils::findMin(), operator<(), and SimpleConstMappingIterator::SimpleConstMappingIterator().
{
                 typedef key_iterator<const_iterator> key_const_iterator;
                 DimensionSet res(Dimension::time);
                 res.insert(key_const_iterator(values.begin()), key_const_iterator(values.end()));
                 return res;
         }
simtime_t_cref Argument::getTime () const
Returns the time value of this argument.
Definition at line 90 of file MappingBase.cc.
Referenced by MappingUtils::addDiscontinuity(), SNRThresholdDecider::checkIfAboveThreshold(), TimeMapping< Interpolator >::createIterator(), SimpleConstMapping::createKeyEntries(), BaseDelayedIterator< Base, Iterator >::delayPosition(), BaseDelayedMapping< Mapping >::delayPosition(), MappingUtils::findMax(), MappingUtils::findMin(), JakesFadingMapping::getValue(), TimeMapping< Interpolator >::getValue(), RSAMMapping::getValue(), TimeMappingIterator< Interpolator >::iterateTo(), RSAMConstMappingIterator::iterateTo(), TimeMappingIterator< Interpolator >::jumpTo(), RSAMConstMappingIterator::jumpTo(), TimeMappingIterator< Interpolator >::next(), ConstMapping::print(), TimeMapping< Interpolator >::setValue(), and BaseDelayedIterator< Base, Iterator >::undelayPosition().
 {
         return time;
 }
bool Argument::hasArgVal (const Argument::key_type & dim) const
Returns true if this Argument has a value for the passed Dimension.
Definition at line 124 of file MappingBase.cc.
Referenced by SimplePathlossConstMapping::getValue(), TwoRayInterferenceModel::Mapping::getValue(), MultiDimMapping< Linear >::getValue(), MultiDimMappingIterator< Linear >::iterateTo(), and MultiDimMappingIterator< Linear >::jumpTo().
{
         return values.find(dim) != values.end();
 }
Argument::iterator Argument::insertValue (iterator pos, const Argument::value_type & valPair, iterator & itEnd, bool ignoreUnknown = false) inline protected
Inserts the passed value for the passed Dimension into this Argument.
The parameter "pos" defines the position inside the Dimension<->Value-pair array to start searching for the dimension to set.
If the "ignoreUnknown"-parameter is set to true the new value is only set if the Dimension was defined in this Argument before (means, no new DImensions are added to the Argument).
The method returns the position inside the array the value was inserted.
Definition at line 152 of file MappingBase.cc.
Referenced by setArgValues().
{
         pos = values.lower_bound(valPair.first);
         if(pos != itEnd && !(values.key_comp()(valPair.first, pos->first))) {
             // key already exists
             // update pos->second if you care to
                 pos->second = valPair.second;
                 return pos;
         }
         if (ignoreUnknown)
                 return pos;
         pos   = values.insert(pos, valPair);
         itEnd = values.end();
         return pos;
 }
bool Argument::isClose (const Argument & o, Argument::mapped_type_cref epsilon = Argument::mapped_type(0.000001)) const
Two Arguments are compared close if they have the same dimensions and their values don't differ more then a specific epsilon.
Definition at line 218 of file MappingBase.cc.
{
         if(values.size() != o.values.size())
                 return false;
         if(fabs(SIMTIME_DBL(time - o.time)) > epsilon)
                 return false;
         const_iterator       itO    = o.begin();
         const const_iterator itEnd  = end();
         const const_iterator itEndO = o.end();
         for(const_iterator it = begin();
                 it != itEnd && itO != itEndO; ++it) {
                 if(!(it->first == itO->first) || (fabs( it->second - itO->second ) > epsilon)){
                         return false;
                 }
                 ++itO;
         }
         return true;
 }
bool Argument::isSamePosition (const Argument & other) const
Returns true if the passed Argument points to the same position.
The functions returns true if every Dimension in the passed Argument exists in this Argument and their values are the same. The difference to the == operator is that the dimensions of the passed Argument can be a subset of the dimensions of this Argument.
Definition at line 182 of file MappingBase.cc.
Referenced by MappingUtils::applyElementWiseOperator().
 {
         if(time != o.time){
                 return false;
         }
         if(values.size() < o.values.size()){
                 return false;
         }
         if(o.values.empty())
                 return true;
         const_iterator       itO    = o.begin();
         const_iterator       it     = begin();
         const const_iterator itEnd  = end();
         const const_iterator itEndO = o.end();
         while (it != itEnd) {
                 if (itO->first < it->first) {
                         break;
                 } else if (it->first < itO->first)
                         ++it;
                 else {
                         if(it->second != itO->second){
                                 break;
                         }
                         ++it;
                         ++itO;
                 }
                 if (itO == itEndO) return true;
         }
         return false;
 }
Argument::iterator Argument::lower_bound (const Argument::key_type & dim)
Returns an iterator to the first Argument value which dimension compares greater or equal to the passed Dimension.
Definition at line 112 of file MappingBase.cc.
{
         assert(!(dim == Dimension::time));
         return values.lower_bound(dim);
 }
Argument::const_iterator Argument::lower_bound (const Argument::key_type & dim) const
Returns an iterator to the first Argument value which dimension compares greater or equal to the passed Dimension.
Definition at line 118 of file MappingBase.cc.
{
         assert(!(dim == Dimension::time));
         return values.lower_bound(dim);
 }
bool Argument::operator< (const Argument & o) const
Returns true if this Argument is smaller then the passed Argument.
The dimensions of the Arguments have to be the same.
An Argument is compared smaller than another Argument if the value of the Dimension with the highest id is compared smaller. If the value of the highest Dimension is compared bigger the Argument isn't compared smaller (method returns false). If the values of the Dimension with the highest Dimension are equal, the next smaller Dimension is compared.
Definition at line 254 of file MappingBase.cc.
 {
         assert(getDimensions() == o.getDimensions());
         return compare(o) < 0;
 }
void Argument::operator= (const Argument & o)
Fast implementation of the copy-operator then the default implementation.
Definition at line 249 of file MappingBase.cc.
{
         values = o.values;
         time   = o.time;
 }
bool Argument::operator== (const Argument & o) const
Two Arguments are compared equal if they have the same dimensions and the same values.
Definition at line 241 of file MappingBase.cc.
 {
         if(time != o.time || values.size() != o.values.size())
                 return false;
         return compare(o) == 0;
 }
void Argument::setArgValue (const Argument::key_type & dim, Argument::mapped_type_cref value)
Changes the value for the specified dimension.
Note: Don't use this function to change the time value! Use "setTime()" instead.
If the argument doesn't already contain a value for the specified dimension the new dimension is added.
Definition at line 138 of file MappingBase.cc.
Referenced by Decider80211p::calcChannelSenseRSSI(), Decider80211p::cca(), Decider80211p::checkIfSignalOk(), SimpleConstMapping::createKeyEntries(), BaseMacLayer::createSingleFrequencyMapping(), MultiDimMappingIterator< Linear >::jumpToBegin(), MultiDimMappingIterator< Linear >::MultiDimMappingIterator(), MultiDimMappingIterator< Linear >::next(), ConstMapping::print(), Decider80211p::processNewSignal(), and MultiDimMappingIterator< Linear >::updateNextPosition().
 {
         assert(!(dim == Dimension::time));
         iterator pos = values.lower_bound(dim);
         if(pos != values.end() && !(values.key_comp()(dim, pos->first))) {
             // key already exists
             // update pos->second if you care to
                 pos->second = value;
                 return;
         }
         values.insert(pos, Argument::value_type(dim, value));
 }
void Argument::setArgValues (const Argument & o, bool ignoreUnknown = false)
Update the values of this Argument with the values of the passed Argument.
Only the dimensions from the passed Argument are updated or added.
If the ignoreUnknown parameter is set to true, only the Dimensions already inside the Argument are updated.
Definition at line 168 of file MappingBase.cc.
Referenced by MultiDimMappingIterator< Linear >::iterateTo(), MultiDimMappingIterator< Linear >::jumpTo(), MultiDimMappingIterator< Linear >::jumpToBegin(), MultiDimMappingIterator< Linear >::next(), and MultiDimMappingIterator< Linear >::updateNextPosition().
{
         time = o.time;
         iterator             pos      = begin();
         const const_iterator oEndIter = o.end();
         iterator             EndIter  = values.end();
         for(const_iterator it = o.begin(); it != oEndIter; ++it) {
                 pos = insertValue(pos, *it, EndIter, ignoreUnknown);
                 if (ignoreUnknown && pos == EndIter)
                         break; //current dimension was not found and next will be also not in our dimension set
         }
 }
void Argument::setTime (simtime_t_cref time)
Changes the time value of this argument.
Definition at line 95 of file MappingBase.cc.
Referenced by MappingUtils::addDiscontinuity(), Decider80211p::calcChannelSenseRSSI(), Decider80211p::cca(), Decider80211p::checkIfSignalOk(), SimpleConstMapping::createKeyEntries(), Mac1609_4::createSignal(), BaseMacLayer::createSingleFrequencyMapping(), BaseDelayedIterator< Base, Iterator >::delayPosition(), BaseDelayedMapping< Mapping >::delayPosition(), LogNormalShadowing::filterSignal(), TimeMappingIterator< Interpolator >::iterateTo(), TimeMappingIterator< Interpolator >::jumpTo(), TimeMappingIterator< Interpolator >::jumpToBegin(), TimeMappingIterator< Interpolator >::next(), ConstMapping::print(), Decider80211p::processNewSignal(), TimeMappingIterator< Interpolator >::TimeMappingIterator(), BaseDelayedIterator< Base, Iterator >::undelayPosition(), and TimeMappingIterator< Interpolator >::updateNextPos().
 {
         this->time = time;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Argument & d) friend
Output operator for Arguments.
Produces output of form "(x1, x2, x3, <...>)".
Definition at line 482 of file MappingBase.h.
{
                 using std::operator<<;
                 out << "(" << d.time;
                 for (const_iterator it = d.begin(); it != d.end(); ++it) {
                         out << ", " << it->second << "@" << it->first;
                 }
         return (out << ")");
     }
Member Data Documentation
const Argument::mapped_type Argument::MappedOne = Argument::mapped_type(1) static
One value of a Argument value.
Definition at line 293 of file MappingBase.h.
Referenced by LinearIntplMapping::getValue().
const Argument::mapped_type Argument::MappedZero = Argument::mapped_type(0) static
Zero value of a Argument value.
Definition at line 291 of file MappingBase.h.
Referenced by Argument(), BaseDecider::calcChannelSenseRSSI(), Decider80211p::calculateNoiseRSSIMapping(), BaseDecider::calculateRSSIMapping(), Decider80211p::calculateSinrAndSnrMapping(), BaseDecider::calculateSnrMapping(), Decider80211p::cca(), BaseMacLayer::createConstantMapping(), BaseMacLayer::createRectangleMapping(), BaseMacLayer::createSingleFrequencyMapping(), getArgValue(), Signal::getReceivingPower(), MultiDimMappingIterator< Linear >::getValue(), and MultiDimMapping< Linear >::getValue().
simtime_t Argument::time protected
Stores the time dimension in Omnet's time type.
Definition at line 298 of file MappingBase.h.
Referenced by compare(), getTime(), isClose(), isSamePosition(), operator=(), operator==(), setArgValues(), and setTime().
container_type Argument::values protected
Maps the dimensions of this Argument to their values.
Definition at line 301 of file MappingBase.h.
Referenced by Argument(), compare(), find(), getArgValue(), hasArgVal(), insertValue(), isClose(), isSamePosition(), lower_bound(), operator=(), operator==(), setArgValue(), and setArgValues().
The documentation for this class was generated from the following files:
MappingBase.h
MappingBase.cc