Veins Framework: Veins::Radio Class Reference
Veins::Radio Class Reference
#include <PhyUtils.h>
Public Types
enum RadioState {
RX = 0, TX, SLEEP, SWITCHING,
NUM_RADIO_STATES
}
The state of the radio of the nic.
Public Member Functions
virtual ~Radio ()
Destructor for the Radio class.
virtual simtime_t switchTo (int newState, simtime_t_cref now)
A function called by the Physical Layer to start the switching process to a new RadioState.
virtual void setSwitchTime (int from, int to, simtime_t_cref time)
function called by PhyLayer in order to make an entry in the switch times matrix, i.e.
virtual int getCurrentState () const
Returns the state the Radio is currently in.
virtual void endSwitch (simtime_t_cref now)
called by PhyLayer when duration-time for the current switching process is up
virtual RadioStateAnalogueModel * getAnalogueModel ()
Returns a pointer to the RadioStateAnalogueModel.
virtual void cleanAnalogueModelUntil (simtime_t_cref t)
discards information in the RadioStateAnalogueModel before given time-point
void setTrackingModeTo (bool b)
sets tracking mode
void setCurrentChannel (int newChannel)
Changes the current channel of the radio.
int getCurrentChannel ()
Returns the channel the radio is currently set to.
Static Public Member Functions
static Radio * createNewRadio (bool recordStats=false, int initialState=RX, Argument::mapped_type_cref minAtt=Argument::MappedOne, Argument::mapped_type_cref maxAtt=Argument::MappedZero, int currentChannel=0, int nbChannels=1)
Creates a new instance of this class.
Protected Member Functions
Radio (int numRadioStates, bool recordStats, int initialState=RX, Argument::mapped_type_cref minAtt=Argument::MappedOne, Argument::mapped_type_cref maxAtt=Argument::MappedZero, int currentChannel=0, int nbChannels=1)
Intern constructor to initialize the radio.
virtual void makeRSAMEntry (simtime_t_cref time, int state)
responsible for making entries to the RSAM
virtual Argument::mapped_type_cref mapStateToAtt (int state)
maps RadioState to attenuation, the Radios receiving characteristic
Protected Attributes
cOutVector radioStates
Output vector for radio states.
cOutVector radioChannels
Output vector for radio channels.
int state
The current state the radio is in.
int nextState
The state the radio is currently switching to.
const int numRadioStates
The number of radio states this Radio can be in.
simtime_t ** swTimes
Array for storing switch-times between states.
const Argument::mapped_type minAtt
Constant to store the minimum attenuation for a Radio instance.
const Argument::mapped_type maxAtt
Constant to store the maximum attenuation for a Radio instance.
RadioStateAnalogueModel rsam
The corresponding RadioStateAnalogueModel.
int currentChannel
Currently selected channel (varies between 0 and nbChannels-1).
int nbChannels
Number of available channels.
Detailed Description
Definition at line 199 of file PhyUtils.h.
Member Enumeration Documentation
enum Veins::Radio::RadioState
The state of the radio of the nic.
Enumerator
RX
receiving state
TX
transmitting state
SLEEP
sleeping
SWITCHING
switching between two states
NUM_RADIO_STATES
No real radio state just a counter constant for the amount of states.
Sub-classing Radios which want to add more states can add their own states in their own enum beginning at the value of NUM_RADIO_STATES. They should also remember to update the "numRadioStates" member accordingly.
See Also
RadioUWBIR for an example.
Definition at line 205 of file PhyUtils.h.
{
                 RX = 0,
                 TX,
                 SLEEP,
                 SWITCHING,
                 NUM_RADIO_STATES
         };
Constructor & Destructor Documentation
Radio::~Radio () virtual
Destructor for the Radio class.
Definition at line 130 of file PhyUtils.cc.
 {
         // delete all allocated memory for the switching times matrix
         for (int i = 0; i < numRadioStates; i++)
         {
                 delete[] swTimes[i];
         }
         delete[] swTimes;
         swTimes = 0;
 }
Radio::Radio (int numRadioStates, bool recordStats, int initialState = RX, Argument::mapped_type_cref minAtt = Argument::MappedOne, Argument::mapped_type_cref maxAtt = Argument::MappedZero, int currentChannel = 0, int nbChannels = 1) protected
Intern constructor to initialize the radio.
By defining no default constructor we assure that sub classing radios have to explicitly call this constructor which assures they pass the correct number of radio states.
The protected constructor + factory method solution assures that while sub-classing Radios HAVE to explicitly pass their correct amount of radio states to this constructor, the user (creator) of the Radio doesn't has to pass it or even know about it (which wouldn't be possible with a public constructor). Therefore sub classing Radios which could be sub-classed further should also do it this way.
Definition at line 88 of file PhyUtils.cc.
                                                             :
         state(initialState), nextState(initialState),
         numRadioStates(numRadioStates),
         minAtt(minAtt), maxAtt(maxAtt),
         rsam(mapStateToAtt(initialState)),
         currentChannel(currentChannel), nbChannels(nbChannels)
 {
         assert(nbChannels > 0);
         assert(currentChannel > -1);
         assert(currentChannel < nbChannels);
         radioStates.setName("RadioState");
         radioStates.setEnabled(recordStats);
         radioStates.record(initialState);
         radioChannels.setName("RadioChannel");
         radioChannels.setEnabled(recordStats);
         radioChannels.record(currentChannel);
         // allocate memory for one dimension
         swTimes = new simtime_t* [numRadioStates];
         // go through the first dimension and
         for (int i = 0; i < numRadioStates; i++)
         {
                 // allocate memory for the second dimension
                 swTimes[i] = new simtime_t[numRadioStates];
         }
         // initialize all matrix entries to 0.0
         for (int i = 0; i < numRadioStates; i++)
         {
                 for (int j = 0; j < numRadioStates; j++)
                 {
                         swTimes[i][j] = 0;
                 }
         }
 }
Member Function Documentation
virtual void Veins::Radio::cleanAnalogueModelUntil (simtime_t_cref t) inline virtual
discards information in the RadioStateAnalogueModel before given time-point
Definition at line 345 of file PhyUtils.h.
Referenced by BasePhyLayer::handleAirFrameEndReceive().
{
                 rsam.cleanUpUntil(t);
         }
static Radio* Veins::Radio::createNewRadio (bool recordStats = false, int initialState = RX, Argument::mapped_type_cref minAtt = Argument::MappedOne, Argument::mapped_type_cref maxAtt = Argument::MappedZero, int currentChannel = 0, int nbChannels = 1) inline static
Creates a new instance of this class.
Since Radio hasn't a public constructor this is the only way to create an instance of this class.
This method assures that the radio is initialized with the correct number of radio states. Sub classing Radios should also define a factory method like this instead of an public constructor.
Definition at line 275 of file PhyUtils.h.
         {
                 return new Radio(NUM_RADIO_STATES,
                                                  recordStats,
                                                  initialState,
                                                  minAtt, maxAtt,
                                                  currentChannel, nbChannels);
         }
void Radio::endSwitch (simtime_t_cref now) virtual
called by PhyLayer when duration-time for the current switching process is up
Radio checks whether it is in switching state (pre-condition) and switches to the target state
The actual simtime must be passed, to create properly RSAMEntry
Definition at line 189 of file PhyUtils.cc.
Referenced by BasePhyLayer::finishRadioSwitching().
 {
         // make sure we are currently switching
         assert(state == SWITCHING);
         // set the current state finally to the next state
         state = nextState;
         radioStates.record(state);
         // make entry to RSAM
         makeRSAMEntry(now, state);
         return;
 }
virtual RadioStateAnalogueModel* Veins::Radio::getAnalogueModel () inline virtual
Returns a pointer to the RadioStateAnalogueModel.
This method is intended to be used by the PhyLayer to obtain a pointer to the corresponding RSAM to this Radio
Definition at line 337 of file PhyUtils.h.
Referenced by BasePhyLayer::getAnalogueModelFromName(), and BasePhyLayer::~BasePhyLayer().
{
                 return (&rsam);
         }
int Veins::Radio::getCurrentChannel () inline
Returns the channel the radio is currently set to.
Returns
The current channel of the radio, between 0 and nbChannels-1.
Definition at line 373 of file PhyUtils.h.
Referenced by PhyLayer80211p::encapsMsg(), BasePhyLayer::encapsMsg(), and BasePhyLayer::getCurrentRadioChannel().
{
                 return currentChannel;
         }
virtual int Veins::Radio::getCurrentState () const inline virtual
Returns the state the Radio is currently in.
Definition at line 314 of file PhyUtils.h.
Referenced by BasePhyLayer::getRadioState(), and BasePhyLayer::handleUpperMessage().
{
                 return state;
         }
virtual void Veins::Radio::makeRSAMEntry (simtime_t_cref time, int state) inline protected virtual
responsible for making entries to the RSAM
Definition at line 403 of file PhyUtils.h.
Referenced by endSwitch(), and switchTo().
         {
                 rsam.writeRecvEntry(time, mapStateToAtt(state));
         }
virtual Argument::mapped_type_cref Veins::Radio::mapStateToAtt (int state) inline protected virtual
maps RadioState to attenuation, the Radios receiving characteristic
Definition at line 412 of file PhyUtils.h.
         {
                 if (state == RX) {
                         return minAtt;
                 }
                 else{
                         return maxAtt;
                 }
         }
void Veins::Radio::setCurrentChannel (int newChannel) inline
Changes the current channel of the radio.
Parameters
newChannel The new channel to switch to, between 0 and nbChannels-1
Definition at line 362 of file PhyUtils.h.
Referenced by BasePhyLayer::setCurrentRadioChannel().
{
                 assert(newChannel > -1);
                 assert(newChannel < nbChannels);
                 currentChannel = newChannel;
                 radioChannels.record(currentChannel);
         }
void Radio::setSwitchTime (int from, int to, simtime_t_cref time) virtual
function called by PhyLayer in order to make an entry in the switch times matrix, i.e.
set the time for switching from one state to another
Definition at line 174 of file PhyUtils.cc.
Referenced by BasePhyLayer::initializeRadio().
 {
         // assert parameters are in valid range
         assert(time >= 0.0);
         assert(0 <= from && from < numRadioStates);
         assert(0 <= to && to < numRadioStates);
         // it shall not be possible to set times to/from SWITCHING
         assert(from != SWITCHING && to != SWITCHING);
         swTimes[from][to] = time;
         return;
 }
void Veins::Radio::setTrackingModeTo (bool b) inline
sets tracking mode
Definition at line 352 of file PhyUtils.h.
Referenced by BasePhyLayer::handleAirFrameEndReceive(), and BasePhyLayer::handleAirFrameStartReceive().
{
                 rsam.setTrackingModeTo(b);
         }
simtime_t Radio::switchTo (int newState, simtime_t_cref now) virtual
A function called by the Physical Layer to start the switching process to a new RadioState.
Returns
-1: Error code if the Radio is currently switching else: switching time from the current RadioState to the new RadioState
The actual simtime must be passed, to create properly RSAMEntry
Definition at line 142 of file PhyUtils.cc.
Referenced by BasePhyLayer::setRadioState().
 {
         // state to switch to must be in a valid range, i.e. 0 <= newState < numRadioStates
         assert(0 <= newState && newState < numRadioStates);
         // state to switch to must not be SWITCHING
         assert(newState != SWITCHING);
         // return error value if newState is the same as the current state
         // if (newState == state) return -1;
         // return error value if Radio is currently switching
         if (state == SWITCHING) return -1;
         /* REGULAR CASE */
         // set the nextState to the newState and the current state to SWITCHING
         nextState = newState;
         int lastState = state;
         state = SWITCHING;
         radioStates.record(state);
         // make entry to RSAM
         makeRSAMEntry(now, state);
         // return matching entry from the switch times matrix
         return swTimes[lastState][nextState];
 }
Member Data Documentation
int Veins::Radio::currentChannel protected
Currently selected channel (varies between 0 and nbChannels-1).
Definition at line 258 of file PhyUtils.h.
const Argument::mapped_type Veins::Radio::maxAtt protected
Constant to store the maximum attenuation for a Radio instance.
Definition at line 248 of file PhyUtils.h.
const Argument::mapped_type Veins::Radio::minAtt protected
Constant to store the minimum attenuation for a Radio instance.
Definition at line 246 of file PhyUtils.h.
int Veins::Radio::nbChannels protected
Number of available channels.
Definition at line 261 of file PhyUtils.h.
int Veins::Radio::nextState protected
The state the radio is currently switching to.
Definition at line 237 of file PhyUtils.h.
Referenced by endSwitch(), and switchTo().
const int Veins::Radio::numRadioStates protected
The number of radio states this Radio can be in.
Definition at line 241 of file PhyUtils.h.
Referenced by Radio(), setSwitchTime(), switchTo(), and ~Radio().
cOutVector Veins::Radio::radioChannels protected
Output vector for radio channels.
Definition at line 232 of file PhyUtils.h.
Referenced by Radio().
cOutVector Veins::Radio::radioStates protected
Output vector for radio states.
Definition at line 230 of file PhyUtils.h.
Referenced by endSwitch(), Radio(), and switchTo().
RadioStateAnalogueModel Veins::Radio::rsam protected
The corresponding RadioStateAnalogueModel.
Depends on the characteristics of the radio
Definition at line 255 of file PhyUtils.h.
int Veins::Radio::state protected
The current state the radio is in.
Definition at line 235 of file PhyUtils.h.
Referenced by endSwitch(), and switchTo().
simtime_t** Veins::Radio::swTimes protected
Array for storing switch-times between states.
Definition at line 243 of file PhyUtils.h.
Referenced by Radio(), setSwitchTime(), switchTo(), and ~Radio().
The documentation for this class was generated from the following files:
PhyUtils.h
PhyUtils.cc