Veins Framework: PhyLayer80211p Class Reference
PhyLayer80211p Class Reference
Adaptation of the PhyLayer class for 802.11p.
#include <PhyLayer80211p.h>
Public Member Functions
void initialize (int stage)
This is needed to circumvent a bug in MiXiM that allows different header length interpretations for receiving and sending airframes.
Public Member Functions inherited from BasePhyLayer
BasePhyLayer ()
virtual ~BasePhyLayer ()
Free the pointer to the decider and the AnalogueModels and the Radio.
virtual void finish ()
Only calls the deciders finish method.
virtual cObject *const setUpControlInfo (cMessage *const pMsg, DeciderResult *const pDeciderResult)
Attaches a "control info" (PhyToMac) structure (object) to the message pMsg.
virtual simtime_t setRadioState (int rs)
Tells the BasePhyLayer to switch to the specified radio state.
virtual ChannelState getChannelState ()
Returns the current state of the channel.
virtual int getPhyHeaderLength ()
Returns the length of the phy header in bits.
virtual void setCurrentRadioChannel (int newRadioChannel)
Sets the channel currently used by the radio.
virtual int getCurrentRadioChannel ()
Returns the channel currently used by the radio.
virtual int getNbRadioChannels ()
Returns the number of channels available on this radio.
virtual void getChannelInfo (simtime_t_cref from, simtime_t_cref to, AirFrameVector &out)
Fills the passed AirFrameVector with all AirFrames that intersect with the time interval [from, to].
virtual ConstMapping * getThermalNoise (simtime_t_cref from, simtime_t_cref to)
Returns a Mapping which defines the thermal noise in the passed time frame (in mW).
virtual void sendControlMsgToMac (cMessage *msg)
Called by the Decider to send a control message to the MACLayer.
virtual void sendUp (AirFrame *packet, DeciderResult *result)
Called to send an AirFrame with DeciderResult to the MACLayer.
virtual simtime_t getSimTime ()
Returns the current simulation time.
virtual void cancelScheduledMessage (cMessage *msg)
Tells the PhyLayer to cancel a scheduled message (AirFrame or ControlMessage).
virtual void rescheduleMessage (cMessage *msg, simtime_t_cref t)
Tells the PhyLayer to reschedule a message (AirFrame or ControlMessage).
virtual void drawCurrent (double amount, int activity)
Does nothing.
virtual BaseWorldUtility * getWorldUtility ()
Returns a pointer to the simulations world-utility-module.
void recordScalar (const char *name, double value, const char *unit=NULL)
Records a double into the scalar result file.
Public Member Functions inherited from Veins::ChannelAccess
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Called by the signalling mechanism to inform of changes.
virtual ChannelMobilityPtrType getMobilityModule ()
Returns the host's mobility module.
Public Member Functions inherited from Veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from BaseModule
BaseModule ()
Function to get the logging name of id.
BaseModule (unsigned stacksize)
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
Public Member Functions inherited from DeciderToPhyInterface
virtual ~DeciderToPhyInterface ()
Public Member Functions inherited from MacToPhyInterface
virtual ~MacToPhyInterface ()
Public Member Functions inherited from Mac80211pToPhy11pInterface
virtual ~Mac80211pToPhy11pInterface ()
Public Member Functions inherited from Decider80211pToPhy80211pInterface
virtual ~Decider80211pToPhy80211pInterface ()
Protected Types
enum ProtocolIds { IEEE_80211 = 12123 }
Protected Types inherited from BasePhyLayer
enum ProtocolIds { GENERIC = 0 }
enum AirFrameStates { START_RECEIVE = 1, RECEIVING, END_RECEIVE }
The states of the receiving process for AirFrames.
typedef std::vector
< AnalogueModel * > AnalogueModelList
Used to store the AnalogueModels to be used as filters.
typedef std::map< std::string,
cMsgPar > ParameterMap
Used at initialisation to pass the parameters to the AnalogueModel and Decider.
Protected Types inherited from AccessModuleWrap< T >
typedef T wrapType
Protected Member Functions
virtual AnalogueModel * getAnalogueModelFromName (std::string name, ParameterMap &params)
Creates and returns an instance of the AnalogueModel with the specified name.
AnalogueModel * initializeSimplePathlossModel (ParameterMap &params)
Creates and initializes a SimplePathlossModel with the passed parameter values.
AnalogueModel * initializeLogNormalShadowing (ParameterMap &params)
Creates and initializes a LogNormalShadowing with the passed parameter values.
AnalogueModel * initializeJakesFading (ParameterMap &params)
Creates and initializes a JakesFading with the passed parameter values.
virtual AnalogueModel * initializeBreakpointPathlossModel (ParameterMap &params)
Creates and initializes a BreakpointPathlossModel with the passed parameter values.
AnalogueModel * initializeSimpleObstacleShadowing (ParameterMap &params)
Creates and initializes a SimpleObstacleShadowing with the passed parameter values.
virtual AnalogueModel * initializePERModel (ParameterMap &params)
Creates a simple Packet Error Rate model that attenuates a percentage of the packets to zero, and does not attenuate the other packets.
AnalogueModel * initializeTwoRayInterferenceModel (ParameterMap &params)
Creates and initializes a TwoRayInterferenceModel with the passed parameter values.
virtual Decider * getDeciderFromName (std::string name, ParameterMap &params)
Creates and returns an instance of the Decider with the specified name.
virtual Decider * initializeDecider80211p (ParameterMap &params)
Initializes a new Decider80211 from the passed parameter map.
virtual AirFrame * encapsMsg (cPacket *msg)
This function encapsulates messages from the upper layer into an AirFrame and sets all necessary attributes.
virtual void changeListeningFrequency (double freq)
virtual void handleSelfMessage (cMessage *msg)
Handles self scheduled messages.
virtual int getRadioState ()
Returns the current state the radio is in.
Protected Member Functions inherited from BasePhyLayer
template<class T >
T readPar (const char *parName, const T defaultValue)
Reads and returns the parameter with the passed name.
virtual void handleMessage (cMessage *msg)
OMNeT++ handle message function.
virtual Radio * initializeRadio ()
Initializes and returns the radio class to use.
virtual void filterSignal (AirFrame *frame)
Filters the passed AirFrame's Signal by every registered AnalogueModel.
virtual void finishRadioSwitching ()
Called the moment the simulated switching process of the Radio is finished.
virtual int myProtocolId ()
Returns the identifier of the protocol this phy uses to send messages.
virtual bool isKnownProtocolId (int id)
Returns true if the protocol with the passed identifier is decodeable by the decider.
virtual void handleAirFrame (AirFrame *frame)
Handles messages received from the channel (probably AirFrames).
virtual void handleUpperMessage (cMessage *msg)
Handles messages received from the upper layer through the data gate.
virtual void handleUpperControlMessage (cMessage *msg)
Handles messages received from the upper layer through the control gate.
virtual void handleChannelSenseRequest (cMessage *msg)
Handles reception of a ChannelSenseRequest by forwarding it to the decider and scheduling it to the point in time returned by the decider.
void handleAirFrameFirstReceive (AirFrame *msg)
Handles incoming AirFrames with the state FIRST_RECEIVE.
virtual void handleAirFrameStartReceive (AirFrame *msg)
Handles incoming AirFrames with the state START_RECEIVE.
virtual void handleAirFrameReceiving (AirFrame *msg)
Handles incoming AirFrames with the state RECEIVING.
virtual void handleAirFrameEndReceive (AirFrame *msg)
Handles incoming AirFrames with the state END_RECEIVE.
void sendControlMessageUp (cMessage *msg)
Sends the passed control message to the upper layer.
void sendMacPktUp (cMessage *pkt)
Sends the passed MacPkt to the upper layer.
void sendMessageDown (AirFrame *pkt)
Sends the passed AirFrame to the channel.
void sendSelfMessage (cMessage *msg, simtime_t_cref time)
Schedule self message to passed point in time.
Protected Member Functions inherited from Veins::ChannelAccess
simtime_t calculatePropagationDelay (const NicEntry *nic)
Calculates the propagation delay to the passed receiving nic.
void sendToChannel (cPacket *msg)
Sends a message to all nics connected to this one.
Protected Member Functions inherited from Veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
Protected Member Functions inherited from AccessModuleWrap< T >
AccessModuleWrap ()
T *const get (cModule *const from=NULL)
Additional Inherited Members
Public Types inherited from DeciderToPhyInterface
typedef std::list< AirFrame * > AirFrameVector
Type for container of AirFrames.
Public Types inherited from MacToPhyInterface
enum BasePhyMessageKinds {
TX_OVER = 22000, RADIO_SWITCHING_OVER, CHANNEL_SENSE_REQUEST, AIR_FRAME,
LAST_BASE_PHY_KIND
}
Message kinds used by every phy layer.
Public Types inherited from Mac80211pToPhy11pInterface
enum BasePhyMessageKinds { CHANNEL_IDLE, CHANNEL_BUSY }
Static Public Member Functions inherited from Veins::ChannelAccess
static BaseConnectionManager * getConnectionManager (cModule *nic)
Returns a pointer to the ConnectionManager responsible for the passed NIC module.
Protected Attributes inherited from BasePhyLayer
int protocolId
ConstantSimpleConstMapping * thermalNoise
Defines the strength of the thermal noise.
double maxTXPower
The maximum transmission power a message can be send with.
double sensitivity
The sensitivity describes the minimum strength a signal must have to be received.
bool recordStats
Stores if tracking of statistics (esp.
ChannelInfo channelInfo
Channel info keeps track of received AirFrames and provides information about currently active AirFrames at the channel.
Radio * radio
The state machine storing the current radio state (TX, RX, SLEEP).
Decider * decider
Pointer to the decider module.
AnalogueModelList analogueModels
List of the analogue models to use.
int upperLayerIn
The id of the in-data gate from the Mac layer.
int upperLayerOut
The id of the out-data gate to the Mac layer.
int upperControlOut
The id of the out-control gate to the Mac layer.
int upperControlIn
The id of the in-control gate from the Mac layer.
cMessage * radioSwitchingOverTimer
Self message scheduled to the point in time when the switching process of the radio is over.
cMessage * txOverTimer
Self message scheduled to the point in time when the transmission of an AirFrame is over.
int headerLength
Stores the length of the phy header in bits.
BaseWorldUtility * world
Pointer to the World Utility, to obtain some global information.
Protected Attributes inherited from Veins::ChannelAccess
bool useSendDirect
use sendDirect or not?
BaseConnectionManager * cc
Pointer to the PropagationModel module.
bool coreDebug
debug this core module?
bool usePropagationDelay
Defines if the physical layer should simulate propagation delay.
bool isRegistered
Is this module already registered with ConnectionManager?
BaseWorldUtility * world
Pointer to the World Utility, to obtain some global information.
Protected Attributes inherited from Veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from BaseModule
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Static Protected Attributes inherited from BasePhyLayer
static short airFramePriority = 10
Defines the scheduling priority of AirFrames.
Static Protected Attributes inherited from Veins::ChannelAccess
static const simsignalwrap_t mobilityStateChangedSignal = simsignalwrap_t(MIXIM_SIGNAL_MOBILITY_CHANGE_NAME)
A signal used to subscribe to mobility state changes.
Static Protected Attributes inherited from BaseModule
static const simsignalwrap_t catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME)
Stores the category of the HostState.
Detailed Description
Adaptation of the PhyLayer class for 802.11p.
See Also
BaseWaveApplLayer
Mac1609_4
PhyLayer80211p
Decider80211p
Definition at line 53 of file PhyLayer80211p.h.
Member Enumeration Documentation
enum PhyLayer80211p::ProtocolIds protected
Enumerator
IEEE_80211
Definition at line 62 of file PhyLayer80211p.h.
{
                         IEEE_80211 = 12123
                 };
Member Function Documentation
void PhyLayer80211p::changeListeningFrequency (double freq) protected virtual
Implements Mac80211pToPhy11pInterface.
Definition at line 365 of file PhyLayer80211p.cc.
{
         Decider80211p* dec = dynamic_cast<Decider80211p*>(decider);
         assert(dec);
         dec->changeFrequency(freq);
 }
AirFrame * PhyLayer80211p::encapsMsg (cPacket * msg) protected virtual
This function encapsulates messages from the upper layer into an AirFrame and sets all necessary attributes.
Reimplemented from BasePhyLayer.
Definition at line 411 of file PhyLayer80211p.cc.
 {
         // the cMessage passed must be a MacPacket... but no cast needed here
         // MacPkt* pkt = static_cast<MacPkt*>(msg);
         // ...and must always have a ControlInfo attached (contains Signal)
         cObject* ctrlInfo = macPkt->removeControlInfo();
         assert(ctrlInfo);
         // create the new AirFrame
         AirFrame* frame = new AirFrame11p(macPkt->getName(), AIR_FRAME);
         // Retrieve the pointer to the Signal-instance from the ControlInfo-instance.
         // We are now the new owner of this instance.
         Signal* s = MacToPhyControlInfo::getSignalFromControlInfo(ctrlInfo);
         // make sure we really obtained a pointer to an instance
         assert(s);
         // set the members
         assert(s->getDuration() > 0);
         frame->setDuration(s->getDuration());
         // copy the signal into the AirFrame
         frame->setSignal(*s);
         //set priority of AirFrames above the normal priority to ensure
         //channel consistency (before any thing else happens at a time
         //point t make sure that the channel has removed every AirFrame
         //ended at t and added every AirFrame started at t)
         frame->setSchedulingPriority(airFramePriority);
         frame->setProtocolId(myProtocolId());
         frame->setBitLength(headerLength);
         frame->setId(world->getUniqueAirFrameId());
         frame->setChannel(radio->getCurrentChannel());
         // pointer and Signal not needed anymore
         delete s;
         s = 0;
         // delete the Control info
         delete ctrlInfo;
         ctrlInfo = 0;
         frame->encapsulate(macPkt);
         // --- from here on, the AirFrame is the owner of the MacPacket ---
         macPkt = 0;
         coreEV <<"AirFrame encapsulated, length: " << frame->getBitLength() << "\n";
         return frame;
 }
AnalogueModel * PhyLayer80211p::getAnalogueModelFromName (std::string name, ParameterMap & params) protected virtual
Creates and returns an instance of the AnalogueModel with the specified name.
Is able to initialize the following AnalogueModels:
Reimplemented from BasePhyLayer.
Definition at line 57 of file PhyLayer80211p.cc.
{
         if (name == "SimplePathlossModel") {
                 return initializeSimplePathlossModel(params);
         }
         else if (name == "LogNormalShadowing")
         {
                 return initializeLogNormalShadowing(params);
         }
         else if (name == "JakesFading")
         {
                 return initializeJakesFading(params);
         }
         else if(name == "BreakpointPathlossModel")
         {
                 return initializeBreakpointPathlossModel(params);
         } else if(name == "PERModel")
         {
                 return initializePERModel(params);
         }
         else if (name == "SimpleObstacleShadowing")
         {
                 return initializeSimpleObstacleShadowing(params);
         }
         else if (name == "TwoRayInterferenceModel")
         {
                 if (world->use2D()) error("The TwoRayInterferenceModel uses nodes' z-position as the antenna height over ground. Refusing to work in a 2D world");
                 return initializeTwoRayInterferenceModel(params);
         }
         return BasePhyLayer::getAnalogueModelFromName(name, params);
 }
Decider * PhyLayer80211p::getDeciderFromName (std::string name, ParameterMap & params) protected virtual
Creates and returns an instance of the Decider with the specified name.
Is able to initialize the following Deciders:
Decider80211p
SNRThresholdDecider
Reimplemented from BasePhyLayer.
Definition at line 296 of file PhyLayer80211p.cc.
{
         if(name == "Decider80211p") {
                 protocolId = IEEE_80211;
                 return initializeDecider80211p(params);
         }
         return BasePhyLayer::getDeciderFromName(name, params);
 }
int PhyLayer80211p::getRadioState () protected virtual
Returns the current state the radio is in.
See RadioState for possible values.
This method is mainly used by the mac layer.
Reimplemented from BasePhyLayer.
Definition at line 461 of file PhyLayer80211p.cc.
{
         return BasePhyLayer::getRadioState();
 };
void PhyLayer80211p::handleSelfMessage (cMessage * msg) protected virtual
Handles self scheduled messages.
Reimplemented from BasePhyLayer.
Definition at line 370 of file PhyLayer80211p.cc.
{
         switch(msg->getKind()) {
         //transmission overBasePhyLayer::
         case TX_OVER: {
                 assert(msg == txOverTimer);
                 sendControlMsgToMac(new cMessage("Transmission over", TX_OVER));
                 //check if there is another packet on the chan, and change the chan-state to idle
                 Decider80211p* dec = dynamic_cast<Decider80211p*>(decider);
                 assert(dec);
                 if (dec->cca(simTime(),NULL)) {
                         //chan is idle
                         DBG << "Channel idle after transmit!\n";
                         dec->setChannelIdleStatus(true);
                 }
                 else {
                         DBG << "Channel not yet idle after transmit!\n";
                 }
                 break;
         }
         //radio switch over
         case RADIO_SWITCHING_OVER:
                 assert(msg == radioSwitchingOverTimer);
                 BasePhyLayer::finishRadioSwitching();
                 break;
         //AirFrame
         case AIR_FRAME:
                 BasePhyLayer::handleAirFrame(static_cast<AirFrame*>(msg));
                 break;
         //ChannelSenseRequest
         case CHANNEL_SENSE_REQUEST:
                 BasePhyLayer::handleChannelSenseRequest(msg);
                 break;
         default:
                 break;
         }
 }
void PhyLayer80211p::initialize (int stage) virtual
This is needed to circumvent a bug in MiXiM that allows different header length interpretations for receiving and sending airframes.
Reimplemented from BasePhyLayer.
Definition at line 46 of file PhyLayer80211p.cc.
{
         BasePhyLayer::initialize(stage);
         if (stage == 0) {
                 if (par("headerLength").longValue() != PHY_HDR_TOTAL_LENGTH) {
                 opp_error("The header length of the 802.11p standard is 46bit, please change your omnetpp.ini accordingly by either setting it to 46bit or removing the entry");
                 }
                 //erase the RadioStateAnalogueModel
                 analogueModels.erase(analogueModels.begin());
         }
 }
AnalogueModel * PhyLayer80211p::initializeBreakpointPathlossModel (ParameterMap & params) protected virtual
Creates and initializes a BreakpointPathlossModel with the passed parameter values.
Definition at line 116 of file PhyLayer80211p.cc.
Referenced by getAnalogueModelFromName().
{
         double alpha1 =-1, alpha2=-1, breakpointDistance=-1;
         double L01=-1, L02=-1;
         double carrierFrequency = 5.890e+9;
         bool useTorus = world->useTorus();
         const Coord& playgroundSize = *(world->getPgs());
         ParameterMap::iterator it;
         it = params.find("alpha1");
         if ( it != params.end() ) // parameter alpha1 has been specified in config.xml
         {
                 // set alpha1
                 alpha1 = it->second.doubleValue();
                 coreEV << "createPathLossModel(): alpha1 set from config.xml to " << alpha1 << endl;
                 // check whether alpha is not smaller than specified in ConnectionManager
                 if(cc->hasPar("alpha") && alpha1 < cc->par("alpha").doubleValue())
                 {
                 // throw error
                         opp_error("TestPhyLayer::createPathLossModel(): alpha can't be smaller than specified in \
                        ConnectionManager. Please adjust your config.xml file accordingly");
                 }
         }
         it = params.find("L01");
         if(it != params.end()) {
                 L01 = it->second.doubleValue();
         }
         it = params.find("L02");
         if(it != params.end()) {
                 L02 = it->second.doubleValue();
         }
         it = params.find("alpha2");
         if ( it != params.end() ) // parameter alpha1 has been specified in config.xml
         {
                 // set alpha2
                 alpha2 = it->second.doubleValue();
                 coreEV << "createPathLossModel(): alpha2 set from config.xml to " << alpha2 << endl;
                 // check whether alpha is not smaller than specified in ConnectionManager
                 if(cc->hasPar("alpha") && alpha2 < cc->par("alpha").doubleValue())
                 {
                 // throw error
                         opp_error("TestPhyLayer::createPathLossModel(): alpha can't be smaller than specified in \
                        ConnectionManager. Please adjust your config.xml file accordingly");
                 }
         }
         it = params.find("breakpointDistance");
         if ( it != params.end() ) // parameter alpha1 has been specified in config.xml
         {
                 breakpointDistance = it->second.doubleValue();
                 coreEV << "createPathLossModel(): breakpointDistance set from config.xml to " << alpha2 << endl;
                 // check whether alpha is not smaller than specified in ConnectionManager
         }
         // get carrierFrequency from config
         it = params.find("carrierFrequency");
         if ( it != params.end() ) // parameter carrierFrequency has been specified in config.xml
         {
                 // set carrierFrequency
                 carrierFrequency = it->second.doubleValue();
                 coreEV << "createPathLossModel(): carrierFrequency set from config.xml to " << carrierFrequency << endl;
                 // check whether carrierFrequency is not smaller than specified in ConnectionManager
                 if(cc->hasPar("carrierFrequency") && carrierFrequency < cc->par("carrierFrequency").doubleValue())
                 {
                         // throw error
                         opp_error("TestPhyLayer::createPathLossModel(): carrierFrequency can't be smaller than specified in \
                        ConnectionManager. Please adjust your config.xml file accordingly");
                 }
         }
         else // carrierFrequency has not been specified in config.xml
         {
                 if (cc->hasPar("carrierFrequency")) // parameter carrierFrequency has been specified in ConnectionManager
                 {
                         // set carrierFrequency according to ConnectionManager
                         carrierFrequency = cc->par("carrierFrequency").doubleValue();
                         coreEV << "createPathLossModel(): carrierFrequency set from ConnectionManager to " << carrierFrequency << endl;
                 }
                 else // carrierFrequency has not been specified in ConnectionManager
                 {
                         // keep carrierFrequency at default value
                         coreEV << "createPathLossModel(): carrierFrequency set from default value to " << carrierFrequency << endl;
                 }
         }
         if(alpha1 ==-1 || alpha2==-1 || breakpointDistance==-1 || L01==-1 || L02==-1) {
                 opp_error("Undefined parameters for breakpointPathlossModel. Please check your configuration.");
         }
         return new BreakpointPathlossModel(L01, L02, alpha1, alpha2, breakpointDistance, carrierFrequency, useTorus, playgroundSize, coreDebug);
 }
Decider * PhyLayer80211p::initializeDecider80211p (ParameterMap & params) protected virtual
Initializes a new Decider80211 from the passed parameter map.
Definition at line 349 of file PhyLayer80211p.cc.
Referenced by getDeciderFromName().
{
         double centerFreq = params["centerFrequency"];
         bool collectCollisionStatistics = false;
         {
                 ParameterMap::iterator it = params.find("collectCollisionStatistics");
                 if (it != params.end()) {
                         collectCollisionStatistics = it->second.doubleValue();
                 }
         }
         Decider80211p* dec = new Decider80211p(this, sensitivity, centerFreq, findHost()->getIndex(), collectCollisionStatistics, coreDebug);
         dec->setPath(getParentModule()->getFullPath());
         return dec;
 }
AnalogueModel * PhyLayer80211p::initializeJakesFading (ParameterMap & params) protected
Creates and initializes a JakesFading with the passed parameter values.
Definition at line 98 of file PhyLayer80211p.cc.
Referenced by getAnalogueModelFromName().
{
         int fadingPaths = params["fadingPaths"].longValue();
         simtime_t delayRMS = params["delayRMS"].doubleValue();
         simtime_t interval = params["interval"].doubleValue();
         double carrierFrequency = 5.890e+9;
         if (params.count("carrierFrequency") > 0) {
                 carrierFrequency = params["carrierFrequency"];
         }
         else {
                 if (cc->hasPar("carrierFrequency")) {
                         carrierFrequency = cc->par("carrierFrequency").doubleValue();
                 }
         }
         return new JakesFading(fadingPaths, delayRMS, carrierFrequency, interval);
 }
AnalogueModel * PhyLayer80211p::initializeLogNormalShadowing (ParameterMap & params) protected
Creates and initializes a LogNormalShadowing with the passed parameter values.
Definition at line 90 of file PhyLayer80211p.cc.
Referenced by getAnalogueModelFromName().
{
         double mean = params["mean"].doubleValue();
         double stdDev = params["stdDev"].doubleValue();
         simtime_t interval = params["interval"].doubleValue();
         return new LogNormalShadowing(mean, stdDev, interval);
 }
AnalogueModel * PhyLayer80211p::initializePERModel (ParameterMap & params) protected virtual
Creates a simple Packet Error Rate model that attenuates a percentage of the packets to zero, and does not attenuate the other packets.
Definition at line 291 of file PhyLayer80211p.cc.
Referenced by getAnalogueModelFromName().
{
         double per = params["packetErrorRate"].doubleValue();
         return new PERModel(per);
 }
AnalogueModel * PhyLayer80211p::initializeSimpleObstacleShadowing (ParameterMap & params) protected
Creates and initializes a SimpleObstacleShadowing with the passed parameter values.
Definition at line 304 of file PhyLayer80211p.cc.
Referenced by getAnalogueModelFromName().
{
         // init with default value
         double carrierFrequency = 5.890e+9;
         bool useTorus = world->useTorus();
         const Coord& playgroundSize = *(world->getPgs());
         ParameterMap::iterator it;
         // get carrierFrequency from config
         it = params.find("carrierFrequency");
         if ( it != params.end() ) // parameter carrierFrequency has been specified in config.xml
         {
                 // set carrierFrequency
                 carrierFrequency = it->second.doubleValue();
                 coreEV << "initializeSimpleObstacleShadowing(): carrierFrequency set from config.xml to " << carrierFrequency << endl;
                 // check whether carrierFrequency is not smaller than specified in ConnectionManager
                 if(cc->hasPar("carrierFrequency") && carrierFrequency < cc->par("carrierFrequency").doubleValue())
                 {
                         // throw error
                         opp_error("initializeSimpleObstacleShadowing(): carrierFrequency can't be smaller than specified in ConnectionManager. Please adjust your config.xml file accordingly");
                 }
         }
         else // carrierFrequency has not been specified in config.xml
         {
                 if (cc->hasPar("carrierFrequency")) // parameter carrierFrequency has been specified in ConnectionManager
                 {
                         // set carrierFrequency according to ConnectionManager
                         carrierFrequency = cc->par("carrierFrequency").doubleValue();
                         coreEV << "createPathLossModel(): carrierFrequency set from ConnectionManager to " << carrierFrequency << endl;
                 }
                 else // carrierFrequency has not been specified in ConnectionManager
                 {
                         // keep carrierFrequency at default value
                         coreEV << "createPathLossModel(): carrierFrequency set from default value to " << carrierFrequency << endl;
                 }
         }
         ObstacleControl* obstacleControlP = ObstacleControlAccess().getIfExists();
         if (!obstacleControlP) opp_error("initializeSimpleObstacleShadowing(): cannot find ObstacleControl module");
         return new SimpleObstacleShadowing(*obstacleControlP, carrierFrequency, useTorus, playgroundSize, coreDebug);
 }
AnalogueModel * PhyLayer80211p::initializeSimplePathlossModel (ParameterMap & params) protected
Creates and initializes a SimplePathlossModel with the passed parameter values.
Definition at line 215 of file PhyLayer80211p.cc.
Referenced by getAnalogueModelFromName().
{
         // init with default value
         double alpha = 2.0;
         double carrierFrequency = 5.890e+9;
         bool useTorus = world->useTorus();
         const Coord& playgroundSize = *(world->getPgs());
         // get alpha-coefficient from config
         ParameterMap::iterator it = params.find("alpha");
         if ( it != params.end() ) // parameter alpha has been specified in config.xml
         {
                 // set alpha
                 alpha = it->second.doubleValue();
                 coreEV << "createPathLossModel(): alpha set from config.xml to " << alpha << endl;
                 // check whether alpha is not smaller than specified in ConnectionManager
                 if(cc->hasPar("alpha") && alpha < cc->par("alpha").doubleValue())
                 {
                 // throw error
                         opp_error("TestPhyLayer::createPathLossModel(): alpha can't be smaller than specified in \
                        ConnectionManager. Please adjust your config.xml file accordingly");
                 }
         }
         else // alpha has not been specified in config.xml
         {
                 if (cc->hasPar("alpha")) // parameter alpha has been specified in ConnectionManager
                 {
                         // set alpha according to ConnectionManager
                         alpha = cc->par("alpha").doubleValue();
                         coreEV << "createPathLossModel(): alpha set from ConnectionManager to " << alpha << endl;
                 }
                 else // alpha has not been specified in ConnectionManager
                 {
                         // keep alpha at default value
                         coreEV << "createPathLossModel(): alpha set from default value to " << alpha << endl;
                 }
         }
         // get carrierFrequency from config
         it = params.find("carrierFrequency");
         if ( it != params.end() ) // parameter carrierFrequency has been specified in config.xml
         {
                 // set carrierFrequency
                 carrierFrequency = it->second.doubleValue();
                 coreEV << "createPathLossModel(): carrierFrequency set from config.xml to " << carrierFrequency << endl;
                 // check whether carrierFrequency is not smaller than specified in ConnectionManager
                 if(cc->hasPar("carrierFrequency") && carrierFrequency < cc->par("carrierFrequency").doubleValue())
                 {
                         // throw error
                         opp_error("TestPhyLayer::createPathLossModel(): carrierFrequency can't be smaller than specified in \
                        ConnectionManager. Please adjust your config.xml file accordingly");
                 }
         }
         else // carrierFrequency has not been specified in config.xml
         {
                 if (cc->hasPar("carrierFrequency")) // parameter carrierFrequency has been specified in ConnectionManager
                 {
                         // set carrierFrequency according to ConnectionManager
                         carrierFrequency = cc->par("carrierFrequency").doubleValue();
                         coreEV << "createPathLossModel(): carrierFrequency set from ConnectionManager to " << carrierFrequency << endl;
                 }
                 else // carrierFrequency has not been specified in ConnectionManager
                 {
                         // keep carrierFrequency at default value
                         coreEV << "createPathLossModel(): carrierFrequency set from default value to " << carrierFrequency << endl;
                 }
         }
         return new SimplePathlossModel(alpha, carrierFrequency, useTorus, playgroundSize, coreDebug);
 }
AnalogueModel * PhyLayer80211p::initializeTwoRayInterferenceModel (ParameterMap & params) protected
Creates and initializes a TwoRayInterferenceModel with the passed parameter values.
Definition at line 209 of file PhyLayer80211p.cc.
Referenced by getAnalogueModelFromName().
{
         double dielectricConstant= params["DielectricConstant"].doubleValue();
         return new TwoRayInterferenceModel(dielectricConstant, coreDebug);
 }
The documentation for this class was generated from the following files:
PhyLayer80211p.h
PhyLayer80211p.cc