Veins Framework: mfcv Class Reference
mfcv Class Reference
Small IVC Demo using 11p.
#include <mfcv.h>
Public Member Functions
virtual void initialize (int stage)
Initialization of the module and some variables.
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed.
Public Member Functions inherited from BaseWaveApplLayer
~BaseWaveApplLayer ()
virtual void initialize_default_veins_TraCI (int stage)
virtual void initialize_mfcv (int stage)
virtual void initialize_minicurso_UFPI_TraCI (int stage)
virtual void initialize_osdp (int stage)
virtual void initialize_service_discovery (int stage)
virtual void initialize_test1 (int stage)
virtual void finish ()
Called when the simulation has finished.
Public Member Functions inherited from BaseApplLayer
BaseApplLayer ()
BaseApplLayer (unsigned stacksize)
Public Member Functions inherited from BaseLayer
BaseLayer ()
BaseLayer (unsigned stacksize)
virtual ~BaseLayer ()
virtual void handleMessage (cMessage *)
Called every time a message arrives.
Public Member Functions inherited from Veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from BaseModule
BaseModule ()
Function to get the logging name of id.
BaseModule (unsigned stacksize)
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
Protected Member Functions
virtual void onBeacon (WaveShortMessage *wsm)
virtual void onData (WaveShortMessage *wsm)
void sendMessage (std::string blockedRoadId)
virtual void handlePositionUpdate (cObject *obj)
virtual void handleParkingUpdate (cObject *obj)
virtual void sendWSM (WaveShortMessage *wsm)
virtual void handleSelfMsg (cMessage *msg)
handle self messages
virtual void handleLowerMsg (cMessage *msg)
handle messages from below
virtual WaveShortMessage * prepareWSM_node (std::string name, int dataLengthBits, t_channel channel, int priority, int rcvId, int serial=0)
virtual void imprime_wsm (WaveShortMessage *wsm)
Protected Member Functions inherited from BaseWaveApplLayer
virtual WaveShortMessage * prepareWSM (std::string name, int dataLengthBits, t_channel channel, int priority, int rcvId, int serial=0)
Protected Member Functions inherited from BaseApplLayer
void sendDelayedDown (cMessage *, simtime_t_cref)
Sends a message delayed to the lower layer.
virtual const LAddress::L3Type myApplAddr () const
Return my application layer address.
virtual void handleLowerControl (cMessage *msg)
Handle control messages from lower layer.
virtual void handleUpperMsg (cMessage *msg)
Handle messages from upper layer.
virtual void handleUpperControl (cMessage *msg)
Handle control messages from upper layer.
Protected Member Functions inherited from BaseLayer
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from Veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
Protected Attributes
TraCIMobility * traci
AnnotationManager * annotations
simtime_t lastDroveAt
bool sentMessage
bool isParking
bool sendWhileParking
vector< pair< simtime_t, double > > speedsList
Protected Attributes inherited from BaseWaveApplLayer
int beaconLengthBits
int beaconPriority
bool sendData
bool sendBeacons
simtime_t individualOffset
int dataLengthBits
bool dataOnSch
int dataPriority
Coord curPosition
int mySCH
int myId
cMessage * sendBeaconEvt
WaveAppToMac1609_4Interface * myMac
Protected Attributes inherited from BaseApplLayer
int headerLength
Length of the ApplPkt header.
Protected Attributes inherited from BaseLayer
PassedMessage * passedMsg
The last message passed through this layer.
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
Protected Attributes inherited from Veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from BaseModule
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Static Protected Attributes
static const simsignalwrap_t parkingStateChangedSignal = simsignalwrap_t(TRACI_SIGNAL_PARKING_CHANGE_NAME)
Static Protected Attributes inherited from BaseWaveApplLayer
static const simsignalwrap_t mobilityStateChangedSignal = simsignalwrap_t(MIXIM_SIGNAL_MOBILITY_CHANGE_NAME)
Static Protected Attributes inherited from BaseModule
static const simsignalwrap_t catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME)
Stores the category of the HostState.
Additional Inherited Members
Public Types inherited from BaseWaveApplLayer
enum WaveApplMessageKinds {
SERVICE_PROVIDER = LAST_BASE_APPL_MESSAGE_KIND, SEND_BEACON_EVT, SEND_BEACON_EVT_minicurso, SERVICE_EXPIRED_EVT,
SERVICE_QUERY_EVT, SERVICE_EVT, MOBILITY_EVT
}
Public Types inherited from BaseApplLayer
enum BaseApplMessageKinds { LAST_BASE_APPL_MESSAGE_KIND = 25000 }
The message kinds this layer uses.
enum BaseApplControlKinds { LAST_BASE_APPL_CONTROL_KIND = 25500 }
The control message kinds this layer uses.
Static Public Attributes inherited from BaseLayer
static const simsignalwrap_t catPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_PACKET_NAME)
SignalID for packets.
static const simsignalwrap_t catPassedMsgSignal = simsignalwrap_t(MIXIM_SIGNAL_PASSEDMSG_NAME)
Signal for passed messages.
static const simsignalwrap_t catDroppedPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_DROPPEDPACKET_NAME)
Signal for dropped packets.
Detailed Description
Small IVC Demo using 11p.
Definition at line 36 of file mfcv.h.
Member Function Documentation
void mfcv::handleLowerMsg (cMessage * msg) protected virtual
handle messages from below
Reimplemented from BaseWaveApplLayer.
Definition at line 126 of file mfcv.cc.
{
     WaveShortMessage* wsm = dynamic_cast<WaveShortMessage*>(msg);
     ASSERT(wsm);
     if (std::string(wsm->getName()) == "beacon_node") {
         DBG << "Beacon (node) recebido!";
         onBeacon(wsm);
     }
     else if (std::string(wsm->getName()) == "beacon_rsu") {
         DBG << "Beacon (rsu) recebido!";
         onBeacon(wsm);
     }
     else if (std::string(wsm->getName()) == "data") {
         onData(wsm);
     }
     else {
         DBG << "unknown message (" << wsm->getName() << ")  received\n";
     }
     delete(msg);
 }
void mfcv::handleParkingUpdate (cObject * obj) protected virtual
Definition at line 77 of file mfcv.cc.
Referenced by receiveSignal().
{
         isParking = traci->getParkingState();
         if (sendWhileParking == false) {
                 if (isParking == true) {
                         (FindModule<BaseConnectionManager*>::findGlobalModule())->unregisterNic(this->getParentModule()->getSubmodule("nic"));
                 }
                 else {
                         Coord pos = traci->getCurrentPosition();
                         (FindModule<BaseConnectionManager*>::findGlobalModule())->registerNic(this->getParentModule()->getSubmodule("nic"), (ChannelAccess*) this->getParentModule()->getSubmodule("nic")->getSubmodule("phy80211p"), &pos);
                 }
         }
 }
void mfcv::handlePositionUpdate (cObject * obj) protected virtual
Reimplemented from BaseWaveApplLayer.
Definition at line 89 of file mfcv.cc.
Referenced by receiveSignal().
{
         BaseWaveApplLayer::handlePositionUpdate(obj);
         // stopped for for at least 10s?
         if (traci->getSpeed() < 1) {
                 if (simTime() - lastDroveAt >= 10) {
                         findHost()->getDisplayString().updateWith("r=16,red");
                         // if (!sentMessage) sendMessage(traci->getRoadId());
                 }
         }
         else {
                 lastDroveAt = simTime();
         }
 }
void mfcv::handleSelfMsg (cMessage * msg) protected virtual
handle self messages
Reimplemented from BaseWaveApplLayer.
Definition at line 111 of file mfcv.cc.
{
     switch (msg->getKind()) {
         case SEND_BEACON_EVT: {
             sendWSM(prepareWSM_node("beacon_node", beaconLengthBits, type_CCH, beaconPriority, 0, -1));
             scheduleAt(simTime() + par("beaconInterval").doubleValue(), sendBeaconEvt);
             break;
         }
         default: {
             if (msg)
                 DBG << "APP: Error: Got Self Message of unknown kind! Name: " << msg->getName() << endl;
             break;
         }
     }
 }
void mfcv::imprime_wsm (WaveShortMessage * wsm) protected virtual
Definition at line 201 of file mfcv.cc.
Referenced by onBeacon().
{
     std::cout << "\n\n wsm:" << wsm;
     std::cout << "\n traci->getId():" << traci->getId();
     std::cout << "\n wsm->getVehicleId():" << wsm->getVehicleId();
     std::cout << "\n wsm->getId():" << wsm->getId();
     std::cout << "\n wsm->getArrivalTime():" << wsm->getArrivalTime();
     std::cout << "\n traci->getRoadId():" << traci->getRoadId();
     std::cout << "\n wsm->getRoadId():" << wsm->getRoadId();
     std::cout << "\n wsm->getWsmVersion():" << wsm->getWsmVersion();
     std::cout << "\n wsm->getSecurityType():" << wsm->getSecurityType();
     std::cout << "\n wsm->getChannelNumber():" << wsm->getChannelNumber();
     std::cout << "\n wsm->getDataRate():" << wsm->getDataRate();
     std::cout << "\n wsm->getPriority():" << wsm->getPriority();
     std::cout << "\n wsm->getPsid():" << wsm->getPsid();
     std::cout << "\n wsm->getPsc():" << wsm->getPsc();
     std::cout << "\n wsm->getTimestamp():" << wsm->getTimestamp();
     std::cout << "\n wsm->getSenderPos():" << wsm->getSenderPos();
     std::cout << "\n wsm->:getSenderSpeed():" << wsm->getSenderSpeed();
     std::cout << "\n wsm->:getWsmLength():" << wsm->getWsmLength();
     std::cout << "\n wsm->:getWsmData():" << wsm->getWsmData();
     std::cout << "\n wsm->:getSenderAddress():" << wsm->getSenderAddress();
     std::cout << "\n wsm->:getRecipientAddress():" << wsm->getRecipientAddress();
     std::cout << "\n wsm->getSerial():" << wsm->getSerial();
     std::cout << "\n wsm->getDisplayString():" << wsm->getDisplayString();
     std::cout << "\n wsm->getBitLength():" << wsm->getBitLength();
 }
void mfcv::initialize (int stage) virtual
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseLayer.
Then we have to intialize the gates and - if necessary - some own variables.
Reimplemented from BaseApplLayer.
Definition at line 30 of file mfcv.cc.
{
         BaseWaveApplLayer::initialize_mfcv(stage);
         if (stage == 0) {
                 traci = TraCIMobilityAccess().get(getParentModule());
                 annotations = AnnotationManagerAccess().getIfExists();
                 ASSERT(annotations);
                 sentMessage = false;
                 lastDroveAt = simTime();
                 findHost()->subscribe(parkingStateChangedSignal, this);
                 isParking = false;
                 sendWhileParking = par("sendWhileParking").boolValue();
         }
 }
void mfcv::onBeacon (WaveShortMessage * wsm) protected virtual
Implements BaseWaveApplLayer.
Definition at line 45 of file mfcv.cc.
Referenced by handleLowerMsg().
{
     imprime_wsm(wsm);
 }
void mfcv::onData (WaveShortMessage * wsm) protected virtual
Implements BaseWaveApplLayer.
Definition at line 51 of file mfcv.cc.
Referenced by handleLowerMsg().
{
         findHost()->getDisplayString().updateWith("r=16,green");
         annotations->scheduleErase(1, annotations->drawLine(wsm->getSenderPos(), traci->getPositionAt(simTime()), "blue"));
         if (traci->getRoadId()[0] != ':') traci->commandChangeRoute(wsm->getWsmData(), 9999);
         if (!sentMessage) sendMessage(wsm->getWsmData());
 }
WaveShortMessage * mfcv::prepareWSM_node (std::string name, int dataLengthBits, t_channel channel, int priority, int rcvId, int serial = 0) protected virtual
Definition at line 148 of file mfcv.cc.
Referenced by handleSelfMsg().
{
     WaveShortMessage* wsm = new WaveShortMessage(name.c_str());
     wsm->addBitLength(headerLength);
     wsm->addBitLength(lengthBits);
     switch (channel) {
         case type_SCH: wsm->setChannelNumber(Channels::SCH1); break; //will be rewritten at Mac1609_4 to actual Service Channel. This is just so no controlInfo is needed
         case type_CCH: wsm->setChannelNumber(Channels::CCH); break;
     }
     wsm->setPsid(0);
     wsm->setPriority(priority);
     wsm->setWsmVersion(1);
     //
     wsm->setRoadId(traci->getRoadId().c_str());
     wsm->setSenderSpeed(traci->getSpeed());
     wsm->setVehicleId(traci->getId());
     // ver como definir o id, traci->getId()
     int veh_id = traci->getId();
     if (veh_id = 10) {
          wsm->setCategory(1);
      }
     else if (veh_id = 16) {
         wsm->setCategory(2);
     }
     else {
        wsm->setCategory(10);
     }
     wsm->setTimestamp(simTime());
     wsm->setSenderAddress(myId);
     wsm->setRecipientAddress(rcvId);
     wsm->setSenderPos(curPosition);
     wsm->setSerial(serial);
     //
     if (name == "beacon_node") {
         DBG << "Creating Beacon_node with Priority " << priority << " at Applayer at " << wsm->getTimestamp() << std::endl;
     }
     else if (name == "data_node") {
         DBG << "Creating Data_node with Priority " << priority << " at Applayer at " << wsm->getTimestamp() << std::endl;
     }
     else if (name == "beacon") {
         DBG << "Creating Beacon with Priority " << priority << " at Applayer at " << wsm->getTimestamp() << std::endl;
     }
     else if (name == "data") {
         DBG << "Creating Data with Priority " << priority << " at Applayer at " << wsm->getTimestamp() << std::endl;
     }
     return wsm;
 }
void mfcv::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj) virtual
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed.
In this base class just handle the host state switching and some debug notifications
Reimplemented from BaseWaveApplLayer.
Definition at line 68 of file mfcv.cc.
{
         Enter_Method_Silent();
         if (signalID == mobilityStateChangedSignal) {
                 handlePositionUpdate(obj);
         }
         else if (signalID == parkingStateChangedSignal) {
                 handleParkingUpdate(obj);
         }
 }
void mfcv::sendMessage (std::string blockedRoadId) protected
Definition at line 59 of file mfcv.cc.
Referenced by onData().
{
     sentMessage = true;
         t_channel channel = dataOnSch ? type_SCH : type_CCH;
         WaveShortMessage* wsm = prepareWSM("data", dataLengthBits, channel, dataPriority, -1,2);
         wsm->setWsmData(blockedRoadId.c_str());
         sendWSM(wsm);
 }
void mfcv::sendWSM (WaveShortMessage * wsm) protected virtual
Reimplemented from BaseWaveApplLayer.
Definition at line 103 of file mfcv.cc.
Referenced by handleSelfMsg(), and sendMessage().
{
         if (isParking && !sendWhileParking) return;
         sendDelayedDown(wsm,individualOffset);
 }
Member Data Documentation
AnnotationManager* mfcv::annotations protected
Definition at line 42 of file mfcv.h.
Referenced by initialize(), and onData().
bool mfcv::isParking protected
Definition at line 45 of file mfcv.h.
Referenced by handleParkingUpdate(), initialize(), and sendWSM().
simtime_t mfcv::lastDroveAt protected
Definition at line 43 of file mfcv.h.
Referenced by handlePositionUpdate(), and initialize().
const simsignalwrap_t mfcv::parkingStateChangedSignal = simsignalwrap_t(TRACI_SIGNAL_PARKING_CHANGE_NAME) static protected
Definition at line 47 of file mfcv.h.
Referenced by initialize(), and receiveSignal().
bool mfcv::sendWhileParking protected
Definition at line 46 of file mfcv.h.
Referenced by handleParkingUpdate(), initialize(), and sendWSM().
bool mfcv::sentMessage protected
Definition at line 44 of file mfcv.h.
Referenced by initialize(), onData(), and sendMessage().
vector<pair<simtime_t, double> > mfcv::speedsList protected
Definition at line 51 of file mfcv.h.
TraCIMobility* mfcv::traci protected
Definition at line 41 of file mfcv.h.
Referenced by handleParkingUpdate(), handlePositionUpdate(), imprime_wsm(), initialize(), onData(), and prepareWSM_node().
The documentation for this class was generated from the following files:
mfcv.h
mfcv.cc