Veins Framework: DeciderToPhyInterface Class Reference
DeciderToPhyInterface Class Reference abstract
This class is the interface for a Decider to the BasePhyLayer.
#include <DeciderToPhyInterface.h>
Public Types
typedef std::list< AirFrame * > AirFrameVector
Type for container of AirFrames.
Public Member Functions
virtual ~DeciderToPhyInterface ()
virtual void getChannelInfo (simtime_t_cref from, simtime_t_cref to, AirFrameVector &out)=0
Fills the passed AirFrameVector with all AirFrames that intersect with the time interval [from, to].
virtual ConstMapping * getThermalNoise (simtime_t_cref from, simtime_t_cref to)=0
Returns a Mapping which defines the thermal noise in the passed time frame (in mW).
virtual void sendControlMsgToMac (cMessage *msg)=0
Called by the Decider to send a control message to the MACLayer.
virtual void sendUp (AirFrame *packet, DeciderResult *result)=0
Called to send an AirFrame with DeciderResult to the MACLayer.
virtual simtime_t getSimTime ()=0
Returns the current simulation time.
virtual void cancelScheduledMessage (cMessage *msg)=0
Tells the PhyLayer to cancel a scheduled message (AirFrame or ControlMessage).
virtual void rescheduleMessage (cMessage *msg, simtime_t_cref t)=0
Tells the PhyLayer to reschedule a message (AirFrame or ControlMessage).
virtual void drawCurrent (double amount, int activity)=0
Enables the Decider to draw Power from the phy layers power accounts.
virtual BaseWorldUtility * getWorldUtility ()=0
Returns a pointer to the simulations world-utility-module.
virtual void recordScalar (const char *name, double value, const char *unit=NULL)=0
Utility method to enable a Decider, which isn't an OMNeT-module, to use the OMNeT-method 'recordScalar' with the help of and through its interface to BasePhyLayer.
virtual int getCurrentRadioChannel ()=0
Returns the channel currently used by the radio.
Detailed Description
This class is the interface for a Decider to the BasePhyLayer.
The Decider can do the following things using it:
    - get the current simulation time
            - get the list of AirFrames that intersect with a specific time interval (to
                    calculate SNR)
            - tell the BasePhyLayer to hand an AirFrame up to the MACLayer
            - tell the BasePhyLayer to send a control message to the MACLayer (to answer
                    a ChannelSenseRequest)
Definition at line 43 of file DeciderToPhyInterface.h.
Member Typedef Documentation
typedef std::list<AirFrame*> DeciderToPhyInterface::AirFrameVector
Type for container of AirFrames.
Used as out-value in "getChannelInfo" method.
Definition at line 51 of file DeciderToPhyInterface.h.
Constructor & Destructor Documentation
virtual DeciderToPhyInterface::~DeciderToPhyInterface () inline virtual
Definition at line 53 of file DeciderToPhyInterface.h.
 {}
Member Function Documentation
virtual void DeciderToPhyInterface::cancelScheduledMessage (cMessage * msg) pure virtual
Tells the PhyLayer to cancel a scheduled message (AirFrame or ControlMessage).
Used by the Decider if it doesn't need to handle an AirFrame or ControlMessage again anymore.
Implemented in BasePhyLayer.
Referenced by BaseDecider::channelStateChanged().
virtual void DeciderToPhyInterface::drawCurrent (double amount, int activity) pure virtual
Enables the Decider to draw Power from the phy layers power accounts.
Does nothing if no Battery module in simulation is present.
Implemented in BasePhyLayer.
virtual void DeciderToPhyInterface::getChannelInfo (simtime_t_cref from, simtime_t_cref to, AirFrameVector & out) pure virtual
Fills the passed AirFrameVector with all AirFrames that intersect with the time interval [from, to].
Implemented in BasePhyLayer.
Referenced by BaseDecider::getChannelInfo().
virtual int DeciderToPhyInterface::getCurrentRadioChannel () pure virtual
Returns the channel currently used by the radio.
Implemented in BasePhyLayer.
virtual simtime_t DeciderToPhyInterface::getSimTime () pure virtual
Returns the current simulation time.
Implemented in BasePhyLayer.
Referenced by BaseDecider::answerCSR(), SNRThresholdDecider::canAnswerCSR(), BaseDecider::canAnswerCSR(), BaseDecider::channelStateChanged(), SNRThresholdDecider::getChannelState(), BaseDecider::getChannelState(), BaseDecider::handleNewSenseRequest(), and BaseDecider::handleSenseRequestEnd().
virtual ConstMapping* DeciderToPhyInterface::getThermalNoise (simtime_t_cref from, simtime_t_cref to) pure virtual
Returns a Mapping which defines the thermal noise in the passed time frame (in mW).
The implementing class of this method keeps ownership of the Mapping.
Implemented in BasePhyLayer.
Referenced by Decider80211p::calculateNoiseRSSIMapping(), BaseDecider::calculateRSSIMapping(), and Decider80211p::cca().
virtual BaseWorldUtility* DeciderToPhyInterface::getWorldUtility () pure virtual
Returns a pointer to the simulations world-utility-module.
Implemented in BasePhyLayer.
virtual void DeciderToPhyInterface::recordScalar (const char * name, double value, const char * unit = NULL) pure virtual
Utility method to enable a Decider, which isn't an OMNeT-module, to use the OMNeT-method 'recordScalar' with the help of and through its interface to BasePhyLayer.
The method-signature is taken from OMNeTs 'ccomponent.h' but made pure virtual here. See the original method-description below:
Records a double into the scalar result file.
Implemented in BasePhyLayer.
Referenced by Decider80211p::finish().
virtual void DeciderToPhyInterface::rescheduleMessage (cMessage * msg, simtime_t_cref t) pure virtual
Tells the PhyLayer to reschedule a message (AirFrame or ControlMessage).
Used by the Decider if it has to handle an AirFrame or an control message earlier than it has returned to the PhyLayer the last time the Decider handled that message.
Implemented in BasePhyLayer.
Referenced by BaseDecider::channelStateChanged().
virtual void DeciderToPhyInterface::sendControlMsgToMac (cMessage * msg) pure virtual
Called by the Decider to send a control message to the MACLayer.
This function can be used to answer a ChannelSenseRequest to the MACLayer
Implemented in BasePhyLayer.
Referenced by SNRThresholdDecider::answerCSR(), BaseDecider::answerCSR(), Decider80211p::processSignalEnd(), and Decider80211p::setChannelIdleStatus().
virtual void DeciderToPhyInterface::sendUp (AirFrame * packet, DeciderResult * result) pure virtual
Called to send an AirFrame with DeciderResult to the MACLayer.
When a packet is completely received and not noise, the Decider call this function to send the packet together with the corresponding DeciderResult up to MACLayer
Implemented in BasePhyLayer.
Referenced by SNRThresholdDecider::processSignalEnd(), Decider80211p::processSignalEnd(), and BaseDecider::processSignalEnd().
The documentation for this class was generated from the following file:
DeciderToPhyInterface.h