Veins Framework: ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItList > Class Template Reference
ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItList > Class Template Reference
Iterator for every intersection of a specific interval in a AirFrameMatrix.
#include <ChannelInfo.h>
Public Member Functions
BaseIntersectionIterator (C *airFrames, simtime_t_cref from, simtime_t_cref to)
Creates an iterator for the specified interval at the specified AirFrameMatrix.
AirFrame * next ()
Increases the iterator to the next intersecting AirFrame and returns a pointer to this AirFrame.
Public Attributes
C * intervals
Pointer to the matrix holding the intervals.
simtime_t from
Point in time to start iterating over intersections.
simtime_t to
Point in time to end iterating over intersections.
ItMatrix endIt
Iterator over AirFrame end times.
ItList startIt
Iterator over AirFrame start times.
bool alreadyNext
True if the we are already pointing to the next entry.
Detailed Description
template<class C, class ItMatrix, class ItList>
class ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItList >
Iterator for every intersection of a specific interval in a AirFrameMatrix.
A time interval A_start to A_end intersects with another interval B_start to B_end iff the following two conditions are fulfilled:
            1. A_end >= B_start.
            2. A_start <= B_end and
Or the defined by the opposite: The two intervals do not intersect iff A_end < B_start or A_start > B_end.
To iterate over a two dimensional (end-time x start-time) container of AirFrames this class iterates over all AirFrame-lists whose end-time is bigger or equal than the interval start (intersect condition 1) and in each of these lists iterates over all entries but only stops at and returns entries which start-time is smaller or equal than the interval end (intersection condition 2).
In template form to work as const- and non-const iterator.
Definition at line 84 of file ChannelInfo.h.
Constructor & Destructor Documentation
template<class C, class ItMatrix, class ItList> ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItList >::BaseIntersectionIterator (C * airFrames, simtime_t_cref from, simtime_t_cref to) inline
Creates an iterator for the specified interval at the specified AirFrameMatrix.
Definition at line 111 of file ChannelInfo.h.
                                                                                                :
                         intervals(airFrames), from(from), to(to)
                 {
                         // begin at the smallest end-time-entry fulfilling the intersection
                         // condition 1
                         endIt = intervals->lower_bound(from);
                         if(endIt != intervals->end()) {
                                 startIt = endIt->second.begin();
                         }
                         //we are already pointing at the first unchecked interval
                         alreadyNext = true;
                 }
Member Function Documentation
template<class C, class ItMatrix, class ItList> AirFrame* ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItList >::next () inline
Increases the iterator to the next intersecting AirFrame and returns a pointer to this AirFrame.
Definition at line 129 of file ChannelInfo.h.
Referenced by ChannelInfo::checkAndCleanInterval(), ChannelInfo::getIntersections(), and ChannelInfo::isIntersecting().
                 {
                         if(endIt == intervals->end())
                                 return 0;
                         // "alreadyNext" indicates that some previous iterator function has
                         // already increased the intern iterators to a yet unchecked values.
                         // This happens after initialization of the iterator and when an
                         // element is erased.
                         if(alreadyNext)
                                 alreadyNext = false;
                         else
                                 startIt++;
                         while(endIt != intervals->end())
{
                                 // while there are entries left at the current end-time
                                 while(startIt != endIt->second.end())
{
                                         // check if this entry fulfilles the intersection condition
                                         // 2 (condition 1 is already fulfilled in the constructor by
                                         // the start-value of the end-time-iterator)
                                         if(startIt->first <= to) {
                                                 return startIt->second;
                                         }
                                         startIt++;
                                 }
                                 endIt++;
                                 if(endIt == intervals->end())
                                         return 0;
                                 startIt = endIt->second.begin();
                         }
                         return 0;
                 }
Member Data Documentation
template<class C, class ItMatrix, class ItList> bool ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItList >::alreadyNext
True if the we are already pointing to the next entry.
Definition at line 103 of file ChannelInfo.h.
template<class C, class ItMatrix, class ItList> ItMatrix ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItList >::endIt
Iterator over AirFrame end times.
Definition at line 97 of file ChannelInfo.h.
template<class C, class ItMatrix, class ItList> simtime_t ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItList >::from
Point in time to start iterating over intersections.
Definition at line 91 of file ChannelInfo.h.
template<class C, class ItMatrix, class ItList> C* ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItList >::intervals
Pointer to the matrix holding the intervals.
Definition at line 88 of file ChannelInfo.h.
template<class C, class ItMatrix, class ItList> ItList ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItList >::startIt
Iterator over AirFrame start times.
Definition at line 100 of file ChannelInfo.h.
template<class C, class ItMatrix, class ItList> simtime_t ChannelInfo::BaseIntersectionIterator< C, ItMatrix, ItList >::to
Point in time to end iterating over intersections.
Definition at line 94 of file ChannelInfo.h.
The documentation for this class was generated from the following file:
ChannelInfo.h