Veins Framework: BaseConnectionManager Class Reference
BaseConnectionManager Class Reference abstract
Module to control the channel and handle all connection related stuff.
#include <BaseConnectionManager.h>
Classes
class CoordSet
Represents an minimalistic (hash)set of GridCoords.
class GridCoord
Represents a position inside a grid.
Public Member Functions
virtual ~BaseConnectionManager ()
virtual int numInitStages () const
Needs two initialization stages.
virtual void initialize (int stage)
Reads init parameters and calculates a maximal interference distance.
bool registerNic (cModule *nic, ChannelAccess *chAccess, const Coord *nicPos)
Registers a nic to have its connections managed by ConnectionManager.
bool unregisterNic (cModule *nic)
Unregisters a NIC such that its connections aren't managed by the CM anymore.
void updateNicPos (int nicID, const Coord *newPos)
Updates the position information of a registered nic.
const NicEntry::GateList & getGateList (int nicID) const
Returns the ingates of all nics in range.
const cGate * getOutGateTo (const NicEntry *nic, const NicEntry *targetNic) const
Returns the ingate of the with id==targetID, or 0 if not in range.
Protected Types
typedef std::map< int, NicEntry * > NicEntries
Type for map from nic-module id to nic-module pointer.
typedef std::vector< NicEntries > RowVector
Type for 1-dimensional array of NicEntries.
typedef std::vector< RowVector > NicMatrix
Type for 2-dimensional array of NicEntries.
typedef std::vector< NicMatrix > NicCube
Type for 3-dimensional array of NicEntries.
Protected Member Functions
virtual double calcInterfDist ()=0
Calculate interference distance.
virtual void registerNicExt (int nicID)
Called by "registerNic()" after the nic has been registered.
virtual void updateConnections (int nicID, const Coord *oldPos, const Coord *newPos)
Updates the connections of the nic with "nicID".
virtual bool isInRange (NicEntries::mapped_type pFromNic, NicEntries::mapped_type pToNic)
Check if the two nic's are in range.
Protected Attributes
NicEntries nics
Map from nic-module ids to nic-module pointers.
bool coreDebug
Set debugging for the basic module.
bool sendDirect
Does the ConnectionManager use sendDirect or not?
const Coord * playgroundSize
Stores the size of the playground.
double maxInterferenceDistance
the biggest interference distance in the network.
double maxDistSquared
Square of maxInterferenceDistance cache a value that is often used.
bool useTorus
Stores the useTorus flag of the WorldUtility.
bool drawMIR
Stores if maximum interference distance should be displayed in TkEnv.
NicCube nicGrid
Register of all nics.
Coord findDistance
Distance that helps to find a node under a certain position.
GridCoord gridDim
The size of the grid.
Private Member Functions
void updateNicConnections (NicEntries &nmap, NicEntries::mapped_type nic)
Manages the connections of a registered nic.
void checkGrid (GridCoord &oldCell, GridCoord &newCell, int id)
Check connections of a nic in the grid.
GridCoord getCellForCoordinate (const Coord &c)
Calculates the corresponding cell of a coordinate.
NicEntries & getCellEntries (GridCoord &cell)
Returns the NicEntries of the cell with specified coordinate.
int wrapIfTorus (int value, int max)
If the value is outside of its bounds (zero and max) this function returns -1 if useTorus is false and the wrapped value if useTorus is true.
void fillUnionWithNeighbors (CoordSet &gridUnion, GridCoord cell)
Adds every direct Neighbor of a GridCoord to a union of coords.
Detailed Description
Module to control the channel and handle all connection related stuff.
The central module that coordinates the connections between all nodes, and handles dynamic gate creation. BaseConnectionManager therefore periodically communicates with the ChannelAccess modules
You may not instantiate BaseConnectionManager! Use ConnectionManager instead.
Author
Steffen Sroka, Daniel Willkomm, Karl Wessel
Christoph Sommer ("unregisterNic()"-method)
See Also
ChannelAccess
Definition at line 27 of file BaseConnectionManager.h.
Member Typedef Documentation
typedef std::vector<NicMatrix> BaseConnectionManager::NicCube protected
Type for 3-dimensional array of NicEntries.
Definition at line 234 of file BaseConnectionManager.h.
typedef std::map<int, NicEntry*> BaseConnectionManager::NicEntries protected
Type for map from nic-module id to nic-module pointer.
Definition at line 201 of file BaseConnectionManager.h.
typedef std::vector<RowVector> BaseConnectionManager::NicMatrix protected
Type for 2-dimensional array of NicEntries.
Definition at line 232 of file BaseConnectionManager.h.
typedef std::vector<NicEntries> BaseConnectionManager::RowVector protected
Type for 1-dimensional array of NicEntries.
Definition at line 230 of file BaseConnectionManager.h.
Constructor & Destructor Documentation
BaseConnectionManager::~BaseConnectionManager () virtual
Definition at line 434 of file BaseConnectionManager.cc.
 {
         for (NicEntries::iterator ne = nics.begin(); ne != nics.end(); ne++) {
                 delete ne->second;
         }
 }
Member Function Documentation
virtual double BaseConnectionManager::calcInterfDist () protected pure virtual
Calculate interference distance.
Called by BaseConnectionManager already during initialization stage 0. Implementations therefore have to make sure that everything necessary for calculation is either already initialized or has to be initialized in this method!
This method has to be overridden by any derived class.
Implemented in ConnectionManager.
Referenced by initialize().
void BaseConnectionManager::checkGrid (BaseConnectionManager::GridCoord & oldCell, BaseConnectionManager::GridCoord & newCell, int id) private
Check connections of a nic in the grid.
Definition at line 189 of file BaseConnectionManager.cc.
Referenced by updateConnections().
 {
     // structure to find union of grid squares
     CoordSet gridUnion(74);
     // find nic at old position
     NicEntries&             oldCellEntries = getCellEntries(oldCell);
     NicEntries::iterator    it  = oldCellEntries.find(id);
     NicEntries::mapped_type nic = it->second;
     // move nic to a new position in matrix
     if(oldCell != newCell) {
         oldCellEntries.erase(it);
         getCellEntries(newCell)[id] = nic;
     }
         if((gridDim.x == 1) && (gridDim.y == 1) && (gridDim.z == 1)) {
                 gridUnion.add(oldCell);
     } else {
                 //add grid around oldPos
                 fillUnionWithNeighbors(gridUnion, oldCell);
         if(oldCell != newCell) {
             //add grid around newPos
             fillUnionWithNeighbors(gridUnion, newCell);
         }
     }
     GridCoord* c = gridUnion.next();
     while(c != 0) {
                 ccEV << "Update cons in [" << c->info() << "]" << endl;
                 updateNicConnections(getCellEntries(*c), nic);
                 c = gridUnion.next();
     }
 }
void BaseConnectionManager::fillUnionWithNeighbors (CoordSet & gridUnion, GridCoord cell) private
Adds every direct Neighbor of a GridCoord to a union of coords.
Definition at line 249 of file BaseConnectionManager.cc.
Referenced by checkGrid(), and unregisterNic().
 {
         for(int iz = (int)cell.z - 1; iz <= (int)cell.z + 1; iz++) {
                 int cz = wrapIfTorus(iz, gridDim.z);
                 if(cz == -1) {
                         continue;
                 }
                 for(int ix = (int)cell.x - 1; ix <= (int)cell.x + 1; ix++) {
                         int cx = wrapIfTorus(ix, gridDim.x);
                         if(cx == -1) {
                                 continue;
                         }
                         for(int iy = (int)cell.y - 1; iy <= (int)cell.y + 1; iy++) {
                                 int cy = wrapIfTorus(iy, gridDim.y);
                                 if(cy != -1) {
                                         gridUnion.add(GridCoord(cx, cy, cz));
                                 }
                         }
                 }
         }
 }
BaseConnectionManager::NicEntries & BaseConnectionManager::getCellEntries (BaseConnectionManager::GridCoord & cell) private
Returns the NicEntries of the cell with specified coordinate.
Definition at line 171 of file BaseConnectionManager.cc.
Referenced by checkGrid(), registerNicExt(), and unregisterNic().
 {
     return nicGrid[cell.x][cell.y][cell.z];
 }
BaseConnectionManager::GridCoord BaseConnectionManager::getCellForCoordinate (const Coord & c) private
Calculates the corresponding cell of a coordinate.
Definition at line 155 of file BaseConnectionManager.cc.
Referenced by registerNicExt(), unregisterNic(), and updateConnections().
 {
     return GridCoord(c, findDistance);
 }
const NicEntry::GateList & BaseConnectionManager::getGateList (int nicID) const
Returns the ingates of all nics in range.
Definition at line 415 of file BaseConnectionManager.cc.
Referenced by Veins::ChannelAccess::sendToChannel().
 {
         NicEntries::const_iterator ItNic = nics.find(nicID);
         if (ItNic == nics.end())
                 error("No nic with this ID (%d) is registered with this ConnectionManager.", nicID);
     return ItNic->second->getGateList();
 }
const cGate * BaseConnectionManager::getOutGateTo (const NicEntry * nic, const NicEntry * targetNic) const
Returns the ingate of the with id==targetID, or 0 if not in range.
Definition at line 424 of file BaseConnectionManager.cc.
 {
         NicEntries::const_iterator ItNic = nics.find(nic->nicId);
         if (ItNic == nics.end())
                 error("No nic with this ID (%d) is registered with this ConnectionManager.", nic->nicId);
     return ItNic->second->getOutGateTo(targetNic);
 }
void BaseConnectionManager::initialize (int stage) virtual
Reads init parameters and calculates a maximal interference distance.
Definition at line 42 of file BaseConnectionManager.cc.
 {
         //BaseModule::initialize(stage);
         if (stage == 0)
         {
                 if(hasPar("coreDebug"))
                         coreDebug = par("coreDebug").boolValue();
                 else
                         coreDebug = false;
                 drawMIR = hasPar("drawMaxIntfDist")
                                                 ? par("drawMaxIntfDist").boolValue() : false;
                 ccEV <<"initializing BaseConnectionManager\n";
                 BaseWorldUtility* world = FindModule<BaseWorldUtility*>
                                         ::findGlobalModule();
                 assert(world != 0);
                 playgroundSize = world->getPgs();
                 useTorus = world->useTorus();
                 if(hasPar("sendDirect"))
                         sendDirect = par("sendDirect").boolValue();
                 else
                         sendDirect = false;
                 maxInterferenceDistance = calcInterfDist();
                 maxDistSquared = maxInterferenceDistance * maxInterferenceDistance;
                 //----initialize node grid-----
                 //step 1 - calculate dimension of grid
                 //one cell should have at least the size of maxInterferenceDistance
                 //but also should divide the playground in equal parts
                 Coord dim((*playgroundSize) / maxInterferenceDistance);
                 gridDim = GridCoord(dim);
                 //A grid smaller or equal to 3x3 would mean that every cell has every
                 //other cell as direct neighbor (if our playground is a torus, even if
                 //not the most of the cells are direct neighbors of each other. So we
                 //reduce the grid size to 1x1.
                 if((gridDim.x <= 3) && (gridDim.y <= 3) && (gridDim.z <= 3))
                 {
                         gridDim.x = 1;
                         gridDim.y = 1;
                         gridDim.z = 1;
                 } else {
                         gridDim.x = std::max(1, gridDim.x);
                         gridDim.y = std::max(1, gridDim.y);
                         gridDim.z = std::max(1, gridDim.z);
                 }
                 //step 2 - initialize the matrix which represents our grid
                 NicEntries entries;
                 RowVector row;
                 NicMatrix matrix;
                 for (int i = 0; i < gridDim.z; ++i) {
                         row.push_back(entries);                 //copy empty NicEntries to RowVector
                 }
                 for (int i = 0; i < gridDim.y; ++i) {//fill the ColVector with copies of
                         matrix.push_back(row);                   //the RowVector.
                 }
                 for (int i = 0; i < gridDim.x; ++i) {   //fill the grid with copies of
                         nicGrid.push_back(matrix);                      //the matrix.
                 }
                 ccEV << " using " << gridDim.x << "x" <<
                                                          gridDim.y << "x" <<
                                                          gridDim.z << " grid" << endl;
                 //step 3 -      calculate the factor which maps the coordinate of a node
                 //                      to the grid cell
                 //if we use a 1x1 grid every coordinate is mapped to (0,0, 0)
                 findDistance = Coord(std::max(playgroundSize->x, maxInterferenceDistance),
                                                          std::max(playgroundSize->y, maxInterferenceDistance),
                                                          std::max(playgroundSize->z, maxInterferenceDistance));
                 //otherwise we divide the playground into cells of size of the maximum
                 //interference distance
                 if (gridDim.x != 1)
                         findDistance.x = playgroundSize->x / gridDim.x;
                 if (gridDim.y != 1)
                         findDistance.y = playgroundSize->y / gridDim.y;
                 if (gridDim.z != 1)
                         findDistance.z = playgroundSize->z / gridDim.z;
                 //since the upper playground borders (at pg-size) are part of the
                 //playground we have to assure that they are mapped to a valid
                 //(the last) grid cell we do this by increasing the find distance
                 //by a small value.
                 //This also assures that findDistance is never zero.
                 findDistance += Coord(EPSILON, EPSILON, EPSILON);
                 //findDistance (equals cell size) has to be greater or equal
                 //maxInt-distance
                 assert(findDistance.x >= maxInterferenceDistance);
                 assert(findDistance.y >= maxInterferenceDistance);
                 assert(findDistance.z >= maxInterferenceDistance);
                 //playGroundSize has to be part of the playGround
                 assert(GridCoord(*playgroundSize, findDistance).x == gridDim.x - 1);
                 assert(GridCoord(*playgroundSize, findDistance).y == gridDim.y - 1);
                 assert(GridCoord(*playgroundSize, findDistance).z == gridDim.z - 1);
                 ccEV << "findDistance is " << findDistance.info() << endl;
         }
         else if (stage == 1)
         {
         }
 }
bool BaseConnectionManager::isInRange (NicEntries::mapped_type pFromNic, NicEntries::mapped_type pToNic) protected virtual
Check if the two nic's are in range.
This function will be used to decide if two nic's shall be connected or not. It is simple to overload this function to enhance the decision for connection or not.
Parameters
pFromNic Nic source point which should be checked.
pToNic Nic target point which should be checked.
Returns
true if the nic's are in range and can be connected, false if not.
Definition at line 272 of file BaseConnectionManager.cc.
Referenced by updateNicConnections().
 {
         double dDistance = 0.0;
     if(useTorus) {
         dDistance = sqrTorusDist(pFromNic->pos, pToNic->pos, *playgroundSize);
     } else {
         dDistance = pFromNic->pos.sqrdist(pToNic->pos);
     }
     return (dDistance <= maxDistSquared);
 }
virtual int BaseConnectionManager::numInitStages () const inline virtual
Needs two initialization stages.
Definition at line 348 of file BaseConnectionManager.h.
{
                 return 2;
         }
bool BaseConnectionManager::registerNic (cModule * nic, ChannelAccess * chAccess, const Coord * nicPos)
Registers a nic to have its connections managed by ConnectionManager.
If you want to do your own stuff at the registration of a nic see "registerNicExt()".
Definition at line 316 of file BaseConnectionManager.cc.
Referenced by Veins::ChannelAccess::receiveSignal().
 {
         assert(nic != 0);
         int nicID = nic->getId();
         ccEV << " registering nic #" << nicID << endl;
         // create new NicEntry
         NicEntries::mapped_type nicEntry;
         if(sendDirect)
                 nicEntry = new NicEntryDirect(coreDebug);
         else
                 nicEntry = new NicEntryDebug(coreDebug);
         // fill nicEntry
         nicEntry->nicPtr = nic;
         nicEntry->nicId = nicID;
         nicEntry->hostId = nic->getParentModule()->getId();
         nicEntry->pos = *nicPos;
         nicEntry->chAccess = chAccess;
         // add to map
         nics[nicID] = nicEntry;
         registerNicExt(nicID);
         updateConnections(nicID, nicPos, nicPos);
         if(drawMIR) {
                 nic->getParentModule()->getDisplayString().setTagArg("r", 0, maxInterferenceDistance);
         }
         return sendDirect;
 }
void BaseConnectionManager::registerNicExt (int nicID) protected virtual
Called by "registerNic()" after the nic has been registered.
That means that the NicEntry for the nic has already been created and added to nics map.
You better know what you are doing if you want to override this method. Most time you won't need to.
See ConnectionManager::registerNicExt() for an example.
Parameters
nicID - the id of the NicEntry
Definition at line 176 of file BaseConnectionManager.cc.
Referenced by registerNic().
 {
         NicEntries::mapped_type nicEntry = nics[nicID];
         GridCoord cell = getCellForCoordinate(nicEntry->pos);
         ccEV <<" registering (ext) nic at loc " << cell.info() << std::endl;
         // add to matrix
         NicEntries& cellEntries = getCellEntries(cell);
     cellEntries[nicID] = nicEntry;
 }
bool BaseConnectionManager::unregisterNic (cModule * nic)
Unregisters a NIC such that its connections aren't managed by the CM anymore.
NOTE: This method asserts that the passed NIC module was previously registered with this ConnectionManager!
This method should be used for dynamic networks were hosts can actually disappear.
Parameters
nic the NIC module to be unregistered
Returns
returns true if the NIC was unregistered successfully
Definition at line 354 of file BaseConnectionManager.cc.
Referenced by Veins::TraCIScenarioManager::deleteModule().
 {
         assert(nicModule != 0);
         // find nicEntry
         int nicID = nicModule->getId();
         ccEV << " unregistering nic #" << nicID << endl;
         //we assume that the module was previously registered with this CM
         //TODO: maybe change this to an omnet-error instead of an assertion
         assert(nics.find(nicID) != nics.end());
         NicEntries::mapped_type nicEntry = nics[nicID];
         // get all affected grid squares
         CoordSet gridUnion(74);
         GridCoord cell = getCellForCoordinate(nicEntry->pos);
         if((gridDim.x == 1) && (gridDim.y == 1) && (gridDim.z == 1)) {
                 gridUnion.add(cell);
         } else {
                 fillUnionWithNeighbors(gridUnion, cell);
         }
         // disconnect from all NICs in these grid squares
         GridCoord* c = gridUnion.next();
         while(c != 0) {
                 ccEV << "Update cons in [" << c->info() << "]" << endl;
                 NicEntries& nmap = getCellEntries(*c);
                 for(NicEntries::iterator i = nmap.begin(); i != nmap.end(); ++i) {
                         NicEntries::mapped_type other = i->second;
                         if (other == nicEntry) continue;
                         if (!other->isConnected(nicEntry)) continue;
                         other->disconnectFrom(nicEntry);
                         nicEntry->disconnectFrom(other);
                 }
                 c = gridUnion.next();
         }
         // erase from grid
         NicEntries& cellEntries = getCellEntries(cell);
         cellEntries.erase(nicID);
         // erase from list of known nics
         nics.erase(nicID);
         delete nicEntry;
         return true;
 }
void BaseConnectionManager::updateConnections (int nicID, const Coord * oldPos, const Coord * newPos) protected virtual
Updates the connections of the nic with "nicID".
This method is called by "updateNicPos()" after the new Position is stored in the corresponding nic.
Most time you won't need to override this method.
Parameters
nicID the id of the NicEntry
oldPos the old position of the nic
newPos the new position of the nic
Definition at line 160 of file BaseConnectionManager.cc.
Referenced by registerNic(), and updateNicPos().
 {
         GridCoord oldCell = getCellForCoordinate(*oldPos);
     GridCoord newCell = getCellForCoordinate(*newPos);
         checkGrid(oldCell, newCell, nicID );
 }
void BaseConnectionManager::updateNicConnections (NicEntries & nmap, NicEntries::mapped_type nic) private
Manages the connections of a registered nic.
Definition at line 284 of file BaseConnectionManager.cc.
Referenced by checkGrid().
 {
     int id = nic->nicId;
     for(NicEntries::iterator i = nmap.begin(); i != nmap.end(); ++i) {
         NicEntries::mapped_type nic_i = i->second;
         // no recursive connections
         if ( nic_i->nicId == id ) continue;
         bool inRange   = isInRange(nic, nic_i);
         bool connected = nic->isConnected(nic_i);
         if ( inRange && !connected ) {
             // nodes within communication range: connect
             // nodes within communication range && not yet connected
             ccEV << "nic #" << id << " and #" << nic_i->nicId
                  << " are in range" << endl;
             nic->connectTo( nic_i );
             nic_i->connectTo( nic );
         }
         else if ( !inRange && connected ) {
             // out of range: disconnect
             // out of range, and still connected
             ccEV << "nic #" << id << " and #" << nic_i->nicId
                  << " are NOT in range" << endl;
             nic->disconnectFrom( nic_i );
             nic_i->disconnectFrom( nic );
         }
     }
 }
void BaseConnectionManager::updateNicPos (int nicID, const Coord * newPos)
Updates the position information of a registered nic.
Definition at line 403 of file BaseConnectionManager.cc.
Referenced by Veins::ChannelAccess::receiveSignal().
 {
         NicEntries::iterator ItNic = nics.find(nicID);
         if (ItNic == nics.end())
                 error("No nic with this ID (%d) is registered with this ConnectionManager.", nicID);
     Coord oldPos = ItNic->second->pos;
     ItNic->second->pos = *newPos;
         updateConnections(nicID, &oldPos, newPos);
 }
int BaseConnectionManager::wrapIfTorus (int value, int max) private
If the value is outside of its bounds (zero and max) this function returns -1 if useTorus is false and the wrapped value if useTorus is true.
Otherwise its just returns the value unchanged.
Definition at line 231 of file BaseConnectionManager.cc.
Referenced by fillUnionWithNeighbors().
{
         if(value < 0) {
                 if(useTorus) {
                         return max + value;
                 } else {
                         return -1;
                 }
         } else if(value >= max) {
                 if(useTorus) {
                         return value - max;
                 } else {
                         return -1;
                 }
         } else {
                 return value;
         }
 }
Member Data Documentation
bool BaseConnectionManager::coreDebug protected
Set debugging for the basic module.
Definition at line 207 of file BaseConnectionManager.h.
Referenced by initialize(), and registerNic().
bool BaseConnectionManager::drawMIR protected
Stores if maximum interference distance should be displayed in TkEnv.
Definition at line 227 of file BaseConnectionManager.h.
Referenced by initialize(), and registerNic().
Coord BaseConnectionManager::findDistance protected
Distance that helps to find a node under a certain position.
Can be larger then
See Also
maxInterferenceDistance to allow nodes to be placed into the same square if the playground is too small for the grid speedup to work.
Definition at line 252 of file BaseConnectionManager.h.
Referenced by initialize().
GridCoord BaseConnectionManager::gridDim protected
The size of the grid.
Definition at line 255 of file BaseConnectionManager.h.
Referenced by checkGrid(), fillUnionWithNeighbors(), initialize(), and unregisterNic().
double BaseConnectionManager::maxDistSquared protected
Square of maxInterferenceDistance cache a value that is often used.
Definition at line 220 of file BaseConnectionManager.h.
Referenced by initialize(), and isInRange().
double BaseConnectionManager::maxInterferenceDistance protected
the biggest interference distance in the network.
Definition at line 216 of file BaseConnectionManager.h.
Referenced by initialize(), and registerNic().
NicCube BaseConnectionManager::nicGrid protected
Register of all nics.
This matrix keeps all nics according to their position. It allows to restrict the position update to a subset of all nics.
Definition at line 242 of file BaseConnectionManager.h.
Referenced by initialize().
NicEntries BaseConnectionManager::nics protected
Map from nic-module ids to nic-module pointers.
Definition at line 204 of file BaseConnectionManager.h.
Referenced by getGateList(), getOutGateTo(), registerNic(), registerNicExt(), unregisterNic(), updateNicPos(), and ~BaseConnectionManager().
const Coord* BaseConnectionManager::playgroundSize protected
Stores the size of the playground.
Definition at line 213 of file BaseConnectionManager.h.
Referenced by initialize(), and isInRange().
bool BaseConnectionManager::sendDirect protected
Does the ConnectionManager use sendDirect or not?
Definition at line 210 of file BaseConnectionManager.h.
Referenced by initialize(), and registerNic().
bool BaseConnectionManager::useTorus protected
Stores the useTorus flag of the WorldUtility.
Definition at line 223 of file BaseConnectionManager.h.
Referenced by initialize(), isInRange(), and wrapIfTorus().
The documentation for this class was generated from the following files:
BaseConnectionManager.h
BaseConnectionManager.cc