Veins Framework: Veins::TraCIMobilityAccess Class Reference
Veins::TraCIMobilityAccess Class Reference
#include <TraCIMobility.h>
Public Member Functions
TraCIMobility * get (cModule *host)
Detailed Description
Definition at line 233 of file TraCIMobility.h.
Member Function Documentation
TraCIMobility* Veins::TraCIMobilityAccess::get (cModule * host) inline
Definition at line 236 of file TraCIMobility.h.
Referenced by osdp::initialize(), service_discovery::initialize(), test1::initialize(), AdvancedFlooding::initialize(), vehDist::initialize(), default_veins_TraCI::initialize(), minicurso_UFPI_TraCI::initialize(), mfcv::initialize(), epidemic::initialize(), mfcv_epidemic::initialize(), Veins::default_veins_TraCI_TestApp::initialize(), Veins::minicurso_UFPI_TraCI_TestApp::initialize(), Veins::epidemic_app::initialize(), and Veins::mfcv_epidemic_app::initialize().
{
                         TraCIMobility* traci = FindModule<TraCIMobility*>::findSubModule(host);
                         ASSERT(traci);
                         return traci;
                 };
The documentation for this class was generated from the following file:
TraCIMobility.h