Veins Framework: BaseModule Class Reference
BaseModule Class Reference
Base class for all simple modules of a host.
#include <BaseModule.h>
Public Member Functions
BaseModule ()
Function to get the logging name of id.
BaseModule (unsigned stacksize)
virtual void initialize (int)
Basic initialization for all modules.
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed.
Protected Member Functions
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
Protected Attributes
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Static Protected Attributes
static const simsignalwrap_t catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME)
Stores the category of the HostState.
Detailed Description
Base class for all simple modules of a host.
This method raises an error if the host state changes to something else than ACTIVE. Therefore that a sub-classing module can be used in a simulation where the host state can change it has to override that method which forces the author to make sure the module reacts well to host state changes. Alternatively one can also set a "notAffectedByHostState" parameter of the module to true.
The base module additionally provides a function findHost which returns a pointer to the host module and a function hostIndex to return the index of the host module. The latter one correspondes to the index shown in tkenv and comes in very handy for testing and debugging using tkenv. It is used e.g. in all the 'print' macros used for debugging.
There will never be a stand-alone BaseModule module.
Note: most modules wont derive from BaseModule directly but from its sub class "BatteryAccess" which extends BaseModule by several methods for accessing the battery module.
See Also
BatteryAccess
Author
Steffen Sroka
Andreas Koepke
Definition at line 73 of file BaseModule.h.
Constructor & Destructor Documentation
BaseModule::BaseModule ()
Function to get the logging name of id.
Definition at line 30 of file BaseModule.cc.
                       :
         cSimpleModule()
 {}
BaseModule::BaseModule (unsigned stacksize)
Definition at line 34 of file BaseModule.cc.
                                         :
         cSimpleModule(stacksize)
 {}
Member Function Documentation
cModule *const BaseModule::findHost (void) protected
Function to get a pointer to the host module.
Definition at line 86 of file BaseModule.cc.
Referenced by vehDist::deleteMessage(), vehDist_rsu::fieldsToSave(), vehDist::fieldsToSave(), Flooding::finish(), AdvancedFlooding::finish(), BaseWaveApplLayer::finish(), vehDist::generateMessage(), epidemic_rsu::getEpidemicRequestMessageVectorData(), mfcv_epidemic_rsu::getMfcv_EpidemicRequestMessageVectorData(), default_veins_TraCI::handlePositionUpdate(), mfcv::handlePositionUpdate(), vehDist::handlePositionUpdate(), Flooding::initialize(), AdvancedFlooding::initialize(), vehDist::initialize(), default_veins_TraCI::initialize(), mfcv_epidemic_rsu::initialize(), epidemic_rsu::initialize(), mfcv::initialize(), minicurso_UFPI_TraCI::initialize(), Veins::default_veins_TraCI_TestApp::initialize(), Veins::mfcv_epidemic_app::initialize(), Veins::epidemic_app::initialize(), Veins::minicurso_UFPI_TraCI_TestApp::initialize(), BaseMacLayer::initialize(), initialize(), Veins::ChannelAccess::initialize(), BaseMobility::initialize(), BaseWaveApplLayer::initialize_default_veins_TraCI(), BaseWaveApplLayer::initialize_epidemic(), BaseWaveApplLayer::initialize_mfcv_epidemic(), BaseWaveApplLayer::initialize_minicurso_UFPI_TraCI(), PhyLayer80211p::initializeDecider80211p(), logName(), default_veins_TraCI_RSU::onData(), mfcv_rsu::onData(), minicurso_UFPI_TraCI_RSU::onData(), default_veins_TraCI::onData(), vehDist_rsu::onData(), mfcv::onData(), vehDist::onData(), mfcv_epidemic_rsu::onData(), epidemic_rsu::onData(), minicurso_UFPI_TraCI::onData(), vehDist_rsu::prepareBeaconWSM(), vehDist::prepareBeaconWSM(), vehDist::printBeaconNeighbors(), vehDist_rsu::printCountMessagesReceived(), epidemic_rsu::printEpidemicLocalMessageBuffer(), epidemic_rsu::printEpidemicLocalSummaryVectorData(), epidemic_rsu::printEpidemicRemoteSummaryVectorData(), epidemic_rsu::printEpidemicRequestMessageVector(), vehDist::printMessagesBuffer(), mfcv_epidemic_rsu::printMfcv_EpidemicLocalMessageBuffer(), mfcv_epidemic_rsu::printMfcv_EpidemicLocalSummaryVectorData(), mfcv_epidemic_rsu::printMfcv_EpidemicRemoteSummaryVectorData(), mfcv_epidemic_rsu::printMfcv_EpidemicRequestMessageVector(), epidemic_rsu::printNodesIRecentlySentSummaryVector(), mfcv_epidemic_rsu::printNodesIRecentlySentSummaryVector(), vehDist::printOrdemBeacons(), vehDist::printOrdemMessages(), mfcv_epidemic_rsu::printQueueFIFO(), epidemic_rsu::printQueueFIFO(), Veins::BatteryAccess::registerWithBattery(), vehDist::removeBeaconOutSizeBuffer(), vehDist::removeMessageOutSizeBuffer(), vehDist_rsu::restartFilesResult(), vehDist::saveVehStartPosition(), vehDist::sendDataMessage(), mfcv_epidemic_rsu::sendMessagesRequested(), epidemic_rsu::sendMessagesRequested(), vehDist::updateMessageWSM(), BaseMobility::updatePosition(), and vehDist::vehSendData().
 {
         return FindModule<>::findHost(this);
 }
const cModule *const BaseModule::findHost (void) const protected
Definition at line 91 of file BaseModule.cc.
 {
         return FindModule<>::findHost(this);
 }
const cModule* const BaseModule::getNode () const inline
Get a reference to the local node module.
Definition at line 148 of file BaseModule.h.
{
         return findHost();
     };
void BaseModule::handleHostState (const HostState & state) protected virtual
Called whenever the hosts state changes.
Default implementation of this method throws an error whenever the host state changes and the "notAffectedbyHostState" variable is not explicitly set. This is because every module of a host has to make sure to react well to changes in the host state. Or it has to explicitly set its parameter "notAffectedbyHostState" to true.
Definition at line 66 of file BaseModule.cc.
Referenced by receiveSignal().
 {
         if(notAffectedByHostState)
                 return;
         if(state.get() != HostState::ACTIVE) {
                 error("Hosts state changed to something else than active which"
                           " is not handled by this module. Either handle this state"
                           " correctly or if this module really isn't affected by the"
                           " hosts state set the parameter \"notAffectedByHostState\""
                           " of this module to true.");
         }
 }
void BaseModule::initialize (int stage) virtual
Basic initialization for all modules.
Subscription should be in stage==0, and firing notifications in stage==1 or later.
NOTE: You have to call this in the initialize() function of the inherited class!
Reimplemented in BasePhyLayer, BaseMobility, Mac1609_4, Veins::ChannelAccess, BaseMacLayer, BaseLayer, BaseApplLayer, Veins::TraCIMobility, PhyLayer80211p, Veins::default_veins_TraCI_TestApp, Veins::epidemic_app, Veins::mfcv_epidemic_app, Veins::minicurso_UFPI_TraCI_TestApp, epidemic, mfcv_epidemic, mfcv, minicurso_UFPI_TraCI, epidemic_rsu, mfcv_epidemic_rsu, default_veins_TraCI, default_veins_TraCI_RSU, mfcv_rsu, minicurso_UFPI_TraCI_RSU, vehDist, vehDist_rsu, AdvancedFlooding, service_discovery, test1, Flooding, osdp, osdp_RSU, service_discovery_RSU, and test1_rsu.
Definition at line 45 of file BaseModule.cc.
Referenced by Veins::ChannelAccess::initialize(), and BaseMobility::initialize().
{
     if (stage == 0) {
         notAffectedByHostState = hasPar("notAffectedByHostState") && par("notAffectedByHostState").boolValue();
         hasPar("debug") ? debug = par("debug").boolValue() : debug = true;
         findHost()->subscribe(catHostStateSignal, this);
     }
 }
std::string BaseModule::logName (void) const
Function to get the logging name of the host.
This function returns the logging name of the module with the specified id.
The logging name is the ned module name of the host (unless the host ned variable loggingName is specified). It can be used for logging messages to simplify debugging in TKEnv.
It can be used for logging messages to simplify debugging in TKEnv.
Only supports ids from simple module derived from the BaseModule or the nic compound module id.
Parameters
id Id of the module for the desired logging name
Returns
logging name of module id or NULL if not found
See Also
logName
Definition at line 124 of file BaseModule.cc.
 {
         std::ostringstream ost;
         if (hasPar("logName")) // let modules override
         {
                 ost << par("logName").stringValue();
         }
         else
         {
                 const cModule *const parent = findHost();
                 parent->hasPar("logName") ?
                         ost << parent->par("logName").stringValue() : ost << parent->getName();
                 ost << "[" << parent->getIndex() << "]";
         }
         return ost.str();
 }
virtual int BaseModule::numInitStages () const inline virtual
Divide initialization into two stages.
In the first stage (stage==0), modules subscribe to notification. The first notifications (e.g. about the initial values of some variables such as RadioState) should take place earliest in the second stage (stage==1), when everyone interested in them has already subscribed. Further one should try to keep calls to other modules out of stage 0 to assure that the other module had at least once the chance to initialize itself in stage 0.
Reimplemented in Veins::default_veins_TraCI_TestApp, Veins::epidemic_app, Veins::mfcv_epidemic_app, and Veins::minicurso_UFPI_TraCI_TestApp.
Definition at line 132 of file BaseModule.h.
Referenced by Veins::default_veins_TraCI_TestApp::numInitStages(), Veins::minicurso_UFPI_TraCI_TestApp::numInitStages(), Veins::mfcv_epidemic_app::numInitStages(), and Veins::epidemic_app::numInitStages().
{
         return 2;
     }
void BaseModule::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj) virtual
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed.
In this base class just handle the host state switching and some debug notifications
Reimplemented in Veins::ChannelAccess, BaseWaveApplLayer, Veins::default_veins_TraCI_TestApp, Veins::epidemic_app, Veins::mfcv_epidemic_app, Veins::minicurso_UFPI_TraCI_TestApp, epidemic, mfcv_epidemic, mfcv, minicurso_UFPI_TraCI, default_veins_TraCI, vehDist, AdvancedFlooding, and Flooding.
Definition at line 53 of file BaseModule.cc.
{
         Enter_Method_Silent();
         if (signalID == catHostStateSignal) {
                 const HostState *const pHostState = dynamic_cast<const HostState *const>(obj);
                 if (pHostState) {
                         handleHostState(*pHostState);
                 }
                 else {
                         opp_warning("Got catHostStateSignal but obj was not a HostState pointer?");
                 }
         }
 }
void BaseModule::switchHostState (HostState::States state) protected
Switches the host to the passed state.
If the hosts state is switched to anything else than "ACTIVE" every module of the host has to handle this explicitly (see method "handleHostState()")!
Definition at line 80 of file BaseModule.cc.
 {
         HostState hostState(state);
         emit(catHostStateSignal, &hostState);
 }
Member Data Documentation
const simsignalwrap_t BaseModule::catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME) static protected
Stores the category of the HostState.
Definition at line 84 of file BaseModule.h.
Referenced by initialize(), receiveSignal(), and switchHostState().
bool BaseModule::debug protected
Debug switch for all other modules.
Definition at line 76 of file BaseModule.h.
Referenced by initialize().
bool BaseModule::notAffectedByHostState protected
Stores if this module is affected by changes in the hosts state.
If not explicitly set this module has to capture changes in the host state.
Definition at line 81 of file BaseModule.h.
Referenced by handleHostState(), and initialize().
The documentation for this class was generated from the following files:
BaseModule.h
BaseModule.cc