Veins Framework: Mapping Class Reference
Mapping Class Reference abstract
Represents a changeable mapping (mathematical function) from at least time to Argument::mapped_type.
#include <MappingBase.h>
Public Types
enum InterpolationMethod { STEPS, NEAREST, LINEAR }
Types of interpolation methods for mappings.
Public Types inherited from ConstMapping
typedef Argument::mapped_type argument_value_t
typedef Argument::mapped_type_cref argument_value_cref_t
Public Member Functions
Mapping (const DimensionSet &dims)
Initializes the Mapping with the passed DimensionSet as domain.
Mapping ()
Initializes the Mapping with the time dimension as domain.
virtual ~Mapping ()
virtual void setValue (const Argument &pos, argument_value_cref_t value)=0
Changes the value of the Mapping at the specified position.
virtual void appendValue (const Argument &pos, argument_value_cref_t value)
Appends the passed value at the passed position to the mapping.
virtual MappingIterator * createIterator ()=0
Returns a pointer of a new Iterator which is able to iterate over the Mapping and can change it.
virtual MappingIterator * createIterator (const Argument &pos)=0
Returns a pointer of a new Iterator which is able to iterate over the function and can change it.
virtual ConstMappingIterator * createConstIterator () const
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
virtual ConstMappingIterator * createConstIterator (const Argument &pos) const
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
virtual Mapping * clone () const =0
Returns a deep copy of this Mapping.
virtual ConstMapping * constClone () const
Returns a deep const copy of this mapping by using the according "clone()"-implementation.
Public Member Functions inherited from ConstMapping
ConstMapping ()
Initializes the ConstMapping with a the time dimension as domain.
ConstMapping (const DimensionSet &dimSet)
Initializes the ConstMapping with the passed DimensionSet as Domain.
virtual ~ConstMapping ()
virtual argument_value_t getValue (const Argument &pos) const =0
Returns the value of this Mapping at the position specified by the passed Argument.
argument_value_t operator[] (const Argument &pos) const
Returns the value of this Mapping at the position specified by the passed Argument.
const DimensionSet & getDimensionSet () const
Returns this Mappings domain as DimensionSet.
template<class stream >
stream & print (stream &out, argument_value_cref_t lTimeScale=argument_value_t(1000), argument_value_cref_t lLeftColScale=Argument::MappedOne, const std::string &sTableHead=std::string("o\\ms"), const Dimension *const pOnlyDim=NULL) const
Prints the Mapping to an output stream.
Additional Inherited Members
Protected Attributes inherited from ConstMapping
DimensionSet dimensions
The dimensions of this mappings domain.
Detailed Description
Represents a changeable mapping (mathematical function) from at least time to Argument::mapped_type.
This class extends the ConstMapping interface with write access.
See ConstMapping for details.
Author
Karl Wessel
Definition at line 1021 of file MappingBase.h.
Member Enumeration Documentation
enum Mapping::InterpolationMethod
Types of interpolation methods for mappings.
Enumerator
STEPS
interpolates with next lower entry
NEAREST
interpolates with nearest entry
LINEAR
interpolates linear with next lower and next upper entry constant before the first and after the last entry
Definition at line 1024 of file MappingBase.h.
{
                 STEPS,
                 NEAREST,
                 LINEAR
         };
Constructor & Destructor Documentation
Mapping::Mapping (const DimensionSet & dims) inline
Initializes the Mapping with the passed DimensionSet as domain.
The passed DimensionSet has to contain the time dimension!
Definition at line 1043 of file MappingBase.h.
                                          :
                 ConstMapping(dims) {}
Mapping::Mapping () inline
Initializes the Mapping with the time dimension as domain.
Definition at line 1049 of file MappingBase.h.
                  :
                         ConstMapping() {}
virtual Mapping::~Mapping () inline virtual
Definition at line 1052 of file MappingBase.h.
 {}
Member Function Documentation
virtual void Mapping::appendValue (const Argument & pos, argument_value_cref_t value) inline virtual
Appends the passed value at the passed position to the mapping.
This method assumes that the passed position is after the last key entry of the mapping.
Depending on the implementation of the underlying method this method could be faster or at least as fast as the "setValue()"-method.
Implementations of the Mapping interface can override this method if appending values to the end of the mapping could be implemented faster than the "setValue()" method. Otherwise this method just calls the "setValue()"-method implementation.
Reimplemented in FilledUpMapping.
Definition at line 1075 of file MappingBase.h.
Referenced by FilledUpMapping::FilledUpMapping(), and LogNormalShadowing::filterSignal().
{
                 setValue(pos, value);
         }
virtual Mapping* Mapping::clone () const pure virtual
Returns a deep copy of this Mapping.
Implemented in DelayedMapping, MultiDimMapping< Interpolator >, MultiDimMapping< Linear >, ConstMappingWrapper, LinearIntplMapping, and TimeMapping< Interpolator >.
Referenced by Signal::operator=(), and Signal::Signal().
virtual ConstMapping* Mapping::constClone () const inline virtual
Returns a deep const copy of this mapping by using the according "clone()"-implementation.
Implements ConstMapping.
Reimplemented in ConstMappingWrapper.
Definition at line 1124 of file MappingBase.h.
 { return clone(); }
virtual ConstMappingIterator* Mapping::createConstIterator () const inline virtual
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
Override this method if your ConstIterator differs from the normal iterator.
Implements ConstMapping.
Reimplemented in BaseDelayedMapping< Mapping >, and ConstMappingWrapper.
Definition at line 1099 of file MappingBase.h.
Referenced by SNRThresholdDecider::checkIfAboveThreshold(), and Decider80211p::checkIfSignalOk().
{
                 return dynamic_cast<ConstMappingIterator*>( const_cast<Mapping*>(this)->createIterator() );
         }
virtual ConstMappingIterator* Mapping::createConstIterator (const Argument & pos) const inline virtual
Returns an ConstMappingIterator by use of the respective implementation of the "createIterator()"-method.
Override this method if your ConstIterator differs from the normal iterator.
Implements ConstMapping.
Reimplemented in BaseDelayedMapping< Mapping >, and ConstMappingWrapper.
Definition at line 1109 of file MappingBase.h.
{
                 return dynamic_cast<ConstMappingIterator*>( const_cast<Mapping*>(this)->createIterator(pos) );
         }
virtual MappingIterator* Mapping::createIterator () pure virtual
Returns a pointer of a new Iterator which is able to iterate over the Mapping and can change it.
Implemented in DelayedMapping, FilledUpMapping, MultiDimMapping< Interpolator >, MultiDimMapping< Linear >, ConstMappingWrapper, LinearIntplMapping, and TimeMapping< Interpolator >.
Referenced by MappingUtils::applyElementWiseOperator().
virtual MappingIterator* Mapping::createIterator (const Argument & pos) pure virtual
Returns a pointer of a new Iterator which is able to iterate over the function and can change it.
The iterator starts at the passed position.
Implemented in DelayedMapping, FilledUpMapping, MultiDimMapping< Interpolator >, MultiDimMapping< Linear >, ConstMappingWrapper, LinearIntplMapping, and TimeMapping< Interpolator >.
virtual void Mapping::setValue (const Argument & pos, argument_value_cref_t value) pure virtual
Changes the value of the Mapping at the specified position.
The complexity of this method depends on the implementation.
Implemented in DelayedMapping, MultiDimMapping< Interpolator >, MultiDimMapping< Linear >, ConstMappingWrapper, LinearIntplMapping, and TimeMapping< Interpolator >.
Referenced by MappingUtils::addDiscontinuity(), BaseMacLayer::createConstantMapping(), Mac1609_4::createSignal(), and BaseMacLayer::createSingleFrequencyMapping().
The documentation for this class was generated from the following file:
MappingBase.h