Veins Framework: Mac80211Pkt Class Reference
Mac80211Pkt Class Reference
Class generated from modules/messages/Mac80211Pkt.msg:24 by nedtool.
#include <Mac80211Pkt_m.h>
Public Member Functions
Mac80211Pkt (const char *name=NULL, int kind=0)
Mac80211Pkt (const Mac80211Pkt &other)
virtual ~Mac80211Pkt ()
Mac80211Pkt & operator= (const Mac80211Pkt &other)
virtual Mac80211Pkt * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getAddress3 () const
virtual void setAddress3 (int address3)
virtual int getAddress4 () const
virtual void setAddress4 (int address4)
virtual int getFragmentation () const
virtual void setFragmentation (int fragmentation)
virtual int getInformationDS () const
virtual void setInformationDS (int informationDS)
virtual int getSequenceControl () const
virtual void setSequenceControl (int sequenceControl)
virtual bool getRetry () const
virtual void setRetry (bool retry)
virtual simtime_t getDuration () const
virtual void setDuration (simtime_t duration)
Public Member Functions inherited from MacPkt
MacPkt (const char *name=NULL, int kind=0)
MacPkt (const MacPkt &other)
virtual ~MacPkt ()
MacPkt & operator= (const MacPkt &other)
virtual LAddress::L2Type & getDestAddr ()
virtual const LAddress::L2Type & getDestAddr () const
virtual void setDestAddr (const LAddress::L2Type &destAddr)
virtual LAddress::L2Type & getSrcAddr ()
virtual const LAddress::L2Type & getSrcAddr () const
virtual void setSrcAddr (const LAddress::L2Type &srcAddr)
virtual long getSequenceId () const
virtual void setSequenceId (long sequenceId)
Protected Member Functions
bool operator== (const Mac80211Pkt &)
Protected Member Functions inherited from MacPkt
bool operator== (const MacPkt &)
Protected Attributes
int address3_var
int address4_var
int fragmentation_var
int informationDS_var
int sequenceControl_var
bool retry_var
simtime_t duration_var
Protected Attributes inherited from MacPkt
LAddress::L2Type destAddr_var
LAddress::L2Type srcAddr_var
long sequenceId_var
Private Member Functions
void copy (const Mac80211Pkt &other)
Detailed Description
Class generated from modules/messages/Mac80211Pkt.msg:24 by nedtool.
//
// Defines all fields of an 802.11 MAC frame
//
packet Mac80211Pkt extends MacPkt
{
    int address3;
    int address4;
    int fragmentation; //part of the Frame Control field
    int informationDS; //part of the Frame Control field
    int sequenceControl;
    bool retry;
    simtime_t duration;         //the expected remaining duration the current transaction
}
Definition at line 40 of file Mac80211Pkt_m.h.
Constructor & Destructor Documentation
Mac80211Pkt::Mac80211Pkt (const char * name = NULL, int kind = 0)
Referenced by dup().
Mac80211Pkt::Mac80211Pkt (const Mac80211Pkt & other)
virtual Mac80211Pkt::~Mac80211Pkt () virtual
Member Function Documentation
void Mac80211Pkt::copy (const Mac80211Pkt & other) private
virtual Mac80211Pkt* Mac80211Pkt::dup () const inline virtual
Reimplemented from MacPkt.
Definition at line 63 of file Mac80211Pkt_m.h.
 {return new Mac80211Pkt(*this);}
virtual int Mac80211Pkt::getAddress3 () const virtual
virtual int Mac80211Pkt::getAddress4 () const virtual
virtual simtime_t Mac80211Pkt::getDuration () const virtual
virtual int Mac80211Pkt::getFragmentation () const virtual
virtual int Mac80211Pkt::getInformationDS () const virtual
virtual bool Mac80211Pkt::getRetry () const virtual
virtual int Mac80211Pkt::getSequenceControl () const virtual
Mac80211Pkt& Mac80211Pkt::operator= (const Mac80211Pkt & other)
bool Mac80211Pkt::operator== (const Mac80211Pkt &) protected
virtual void Mac80211Pkt::parsimPack (cCommBuffer * b) virtual
Reimplemented from MacPkt.
Referenced by doPacking().
virtual void Mac80211Pkt::parsimUnpack (cCommBuffer * b) virtual
Reimplemented from MacPkt.
Referenced by doUnpacking().
virtual void Mac80211Pkt::setAddress3 (int address3) virtual
virtual void Mac80211Pkt::setAddress4 (int address4) virtual
virtual void Mac80211Pkt::setDuration (simtime_t duration) virtual
virtual void Mac80211Pkt::setFragmentation (int fragmentation) virtual
virtual void Mac80211Pkt::setInformationDS (int informationDS) virtual
virtual void Mac80211Pkt::setRetry (bool retry) virtual
virtual void Mac80211Pkt::setSequenceControl (int sequenceControl) virtual
Member Data Documentation
int Mac80211Pkt::address3_var protected
Definition at line 43 of file Mac80211Pkt_m.h.
int Mac80211Pkt::address4_var protected
Definition at line 44 of file Mac80211Pkt_m.h.
simtime_t Mac80211Pkt::duration_var protected
Definition at line 49 of file Mac80211Pkt_m.h.
int Mac80211Pkt::fragmentation_var protected
Definition at line 45 of file Mac80211Pkt_m.h.
int Mac80211Pkt::informationDS_var protected
Definition at line 46 of file Mac80211Pkt_m.h.
bool Mac80211Pkt::retry_var protected
Definition at line 48 of file Mac80211Pkt_m.h.
int Mac80211Pkt::sequenceControl_var protected
Definition at line 47 of file Mac80211Pkt_m.h.
The documentation for this class was generated from the following file:
Mac80211Pkt_m.h