Veins Framework: Veins::Obstacle Class Reference
Veins::Obstacle Class Reference
#include <Obstacle.h>
Public Types
typedef std::vector< Coord > Coords
Public Member Functions
Obstacle (std::string id, double attenuationPerWall, double attenuationPerMeter)
void setShape (Coords shape)
const Coords & getShape () const
const Coord getBboxP1 () const
const Coord getBboxP2 () const
double calculateAttenuation (const Coord &senderPos, const Coord &receiverPos) const
Public Attributes
AnnotationManager::Annotation * visualRepresentation
Protected Attributes
std::string id
double attenuationPerWall
in dB.
double attenuationPerMeter
in dB / m.
Coords coords
Coord bboxP1
Coord bboxP2
Detailed Description
Definition at line 32 of file Obstacle.h.
Member Typedef Documentation
typedef std::vector<Coord> Veins::Obstacle::Coords
Definition at line 34 of file Obstacle.h.
Constructor & Destructor Documentation
Obstacle::Obstacle (std::string id, double attenuationPerWall, double attenuationPerMeter)
Definition at line 25 of file Obstacle.cc.
                                                                                       :
         visualRepresentation(0),
         id(id),
         attenuationPerWall(attenuationPerWall),
         attenuationPerMeter(attenuationPerMeter) {
 }
Member Function Documentation
double Obstacle::calculateAttenuation (const Coord & senderPos, const Coord & receiverPos) const
Definition at line 93 of file Obstacle.cc.
Referenced by Veins::ObstacleControl::calculateAttenuation().
{
         // if obstacles has neither walls nor matter: bail.
         if (getShape().size() < 2) return 1;
         // get a list of points (in [0, 1]) along the line between sender and receiver where the beam intersects with this obstacle
         std::multiset<double> intersectAt;
         bool doesIntersect = false;
         const Obstacle::Coords& shape = getShape();
         Obstacle::Coords::const_iterator i = shape.begin();
         Obstacle::Coords::const_iterator j = (shape.rbegin()+1).base();
         for (; i != shape.end(); j = i++) {
                 Coord c1 = *i;
                 Coord c2 = *j;
                 double i = segmentsIntersectAt(senderPos, receiverPos, c1, c2);
                 if (i != -1) {
                         doesIntersect = true;
                         intersectAt.insert(i);
                 }
         }
         // if beam interacts with neither walls nor matter: bail.
         bool senderInside = isPointInObstacle(senderPos, *this);
         bool receiverInside = isPointInObstacle(receiverPos, *this);
         if (!doesIntersect && !senderInside && !receiverInside) return 1;
         // remember number of walls before messing with intersection points
         double numWalls = intersectAt.size();
         // for distance calculation, make sure every other pair of points marks transition through matter and void, respectively.
         if (senderInside) intersectAt.insert(0);
         if (receiverInside) intersectAt.insert(1);
         ASSERT((intersectAt.size() % 2) == 0);
         // sum up distances in matter.
         double fractionInObstacle = 0;
         for (std::multiset<double>::const_iterator i = intersectAt.begin(); i != intersectAt.end(); ) {
                 double p1 = *(i++);
                 double p2 = *(i++);
                 fractionInObstacle += (p2 - p1);
         }
         // calculate attenuation
         double totalDistance = senderPos.distance(receiverPos);
         double attenuation = (attenuationPerWall * numWalls) + (attenuationPerMeter * fractionInObstacle * totalDistance);
         return pow(10.0, -attenuation/10.0);
 }
const Coord Obstacle::getBboxP1 () const
Definition at line 48 of file Obstacle.cc.
Referenced by Veins::ObstacleControl::add(), and Veins::ObstacleControl::calculateAttenuation().
{
         return bboxP1;
 }
const Coord Obstacle::getBboxP2 () const
Definition at line 52 of file Obstacle.cc.
Referenced by Veins::ObstacleControl::add(), and Veins::ObstacleControl::calculateAttenuation().
{
         return bboxP2;
 }
const Obstacle::Coords & Obstacle::getShape () const
Definition at line 44 of file Obstacle.cc.
Referenced by Veins::ObstacleControl::add(), and calculateAttenuation().
{
         return coords;
 }
void Obstacle::setShape (Coords shape)
Definition at line 32 of file Obstacle.cc.
Referenced by Veins::TraCIScenarioManager::init_traci().
{
         coords = shape;
         bboxP1 = Coord(1e7, 1e7);
         bboxP2 = Coord(-1e7, -1e7);
         for (Coords::const_iterator i = coords.begin(); i != coords.end(); ++i) {
                 bboxP1.x = std::min(i->x, bboxP1.x);
                 bboxP1.y = std::min(i->y, bboxP1.y);
                 bboxP2.x = std::max(i->x, bboxP2.x);
                 bboxP2.y = std::max(i->y, bboxP2.y);
         }
 }
Member Data Documentation
double Veins::Obstacle::attenuationPerMeter protected
in dB / m.
Consumer Wi-Fi vs. an interior hollow wall will give approx. 5 dB
Definition at line 50 of file Obstacle.h.
Referenced by calculateAttenuation().
double Veins::Obstacle::attenuationPerWall protected
in dB.
Consumer Wi-Fi vs. an exterior wall will give approx. 50 dB
Definition at line 49 of file Obstacle.h.
Referenced by calculateAttenuation().
Coord Veins::Obstacle::bboxP1 protected
Definition at line 52 of file Obstacle.h.
Referenced by getBboxP1(), and setShape().
Coord Veins::Obstacle::bboxP2 protected
Definition at line 53 of file Obstacle.h.
Referenced by getBboxP2(), and setShape().
Coords Veins::Obstacle::coords protected
Definition at line 51 of file Obstacle.h.
Referenced by getShape(), and setShape().
std::string Veins::Obstacle::id protected
Definition at line 48 of file Obstacle.h.
AnnotationManager::Annotation* Veins::Obstacle::visualRepresentation
Definition at line 45 of file Obstacle.h.
Referenced by Veins::ObstacleControl::add(), and Veins::ObstacleControl::erase().
The documentation for this class was generated from the following files:
Obstacle.h
Obstacle.cc