Veins Framework: BaseLayer Class Reference
BaseLayer Class Reference abstract
A very simple layer template.
#include <BaseLayer.h>
Public Member Functions
BaseLayer ()
BaseLayer (unsigned stacksize)
virtual ~BaseLayer ()
virtual void initialize (int)
Initialization of the module and some variables.
virtual void handleMessage (cMessage *)
Called every time a message arrives.
virtual void finish ()
Called when the simulation has finished.
Public Member Functions inherited from Veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from BaseModule
BaseModule ()
Function to get the logging name of id.
BaseModule (unsigned stacksize)
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed.
Static Public Attributes
static const simsignalwrap_t catPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_PACKET_NAME)
SignalID for packets.
static const simsignalwrap_t catPassedMsgSignal = simsignalwrap_t(MIXIM_SIGNAL_PASSEDMSG_NAME)
Signal for passed messages.
static const simsignalwrap_t catDroppedPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_DROPPEDPACKET_NAME)
Signal for dropped packets.
Protected Member Functions
Handle Messages
Functions to be redefined by the programmer
These are the functions provided to add own functionality to your modules. These functions are called whenever a self message or a data message from the upper or lower layer arrives respectively.
virtual void handleSelfMsg (cMessage *msg)=0
Handle self messages such as timer...
virtual void handleUpperMsg (cMessage *msg)=0
Handle messages from upper layer.
virtual void handleLowerMsg (cMessage *msg)=0
Handle messages from lower layer.
virtual void handleLowerControl (cMessage *msg)=0
Handle control messages from lower layer.
virtual void handleUpperControl (cMessage *msg)=0
Handle control messages from upper layer.
Convenience Functions
Functions for convenience - NOT to be modified
These are functions taking care of message encapsulation and message sending. Normally you should not need to alter these.
All these functions assume that YOU do all the necessary handling of control information etc. before you use them.
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from Veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
Protected Attributes
PassedMessage * passedMsg
The last message passed through this layer.
gate ids
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
Protected Attributes inherited from Veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from BaseModule
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Static Protected Attributes inherited from BaseModule
static const simsignalwrap_t catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME)
Stores the category of the HostState.
Detailed Description
A very simple layer template.
This module provides basic abstractions that ease development of a network or MAC layer.
Author
Andreas Koepke
Definition at line 41 of file BaseLayer.h.
Constructor & Destructor Documentation
BaseLayer::BaseLayer () inline
Definition at line 69 of file BaseLayer.h.
         : BatteryAccess()
         , passedMsg(NULL)
     {}
BaseLayer::BaseLayer (unsigned stacksize) inline
Definition at line 73 of file BaseLayer.h.
         : BatteryAccess(stacksize)
         , passedMsg(NULL)
     {}
BaseLayer::~BaseLayer () virtual
Definition at line 156 of file BaseLayer.cc.
 {
     if (passedMsg != NULL) {
         delete passedMsg;
     }
 }
Member Function Documentation
void BaseLayer::finish () virtual
Called when the simulation has finished.
Reimplemented in Mac1609_4, BaseWaveApplLayer, Veins::default_veins_TraCI_TestApp, and Veins::minicurso_UFPI_TraCI_TestApp.
Definition at line 152 of file BaseLayer.cc.
{
 }
virtual void BaseLayer::handleLowerControl (cMessage * msg) protected pure virtual
Handle control messages from lower layer.
Implemented in Mac1609_4, BaseMacLayer, and BaseApplLayer.
Referenced by handleMessage().
virtual void BaseLayer::handleLowerMsg (cMessage * msg) protected pure virtual
Handle messages from lower layer.
Implemented in BaseMacLayer, Mac1609_4, BaseApplLayer, BaseWaveApplLayer, mfcv, Veins::default_veins_TraCI_TestApp, Veins::minicurso_UFPI_TraCI_TestApp, and mfcv_rsu.
Referenced by handleMessage().
void BaseLayer::handleMessage (cMessage * msg) virtual
Called every time a message arrives.
The basic handle message function.
Depending on the gate a message arrives handleMessage just calls different handle*Msg functions to further process the message.
You should not make any changes in this function but implement all your functionality into the handle*Msg functions called from here.
See Also
handleUpperMsg, handleLowerMsg, handleSelfMsg
Definition at line 75 of file BaseLayer.cc.
 {
     if (msg->isSelfMessage()){
         handleSelfMsg(msg);
     } else if(msg->getArrivalGateId()==upperLayerIn) {
         recordPacket(PassedMessage::INCOMING,PassedMessage::UPPER_DATA,msg);
         handleUpperMsg(msg);
     } else if(msg->getArrivalGateId()==upperControlIn) {
         recordPacket(PassedMessage::INCOMING,PassedMessage::UPPER_CONTROL,msg);
         handleUpperControl(msg);
     } else if(msg->getArrivalGateId()==lowerControlIn){
         recordPacket(PassedMessage::INCOMING,PassedMessage::LOWER_CONTROL,msg);
         handleLowerControl(msg);
     } else if(msg->getArrivalGateId()==lowerLayerIn) {
         recordPacket(PassedMessage::INCOMING,PassedMessage::LOWER_DATA,msg);
         handleLowerMsg(msg);
     }
     else if(msg->getArrivalGateId()==-1) {
         /* Classes extending this class may not use all the gates, f.e.
          * BaseApplLayer has no upper gates. In this case all upper gate-
          * handles are initialized to -1. When getArrivalGateId() equals -1,
          * it would be wrong to forward the message to one of these gates,
          * as they actually don't exist, so raise an error instead.
          */
         opp_error("No self message and no gateID?? Check configuration.");
     } else {
         /* msg->getArrivalGateId() should be valid, but it isn't recognized
          * here. This could signal the case that this class is extended
          * with extra gates, but handleMessage() isn't overridden to
          * check for the new gate(s).
          */
         opp_error("Unknown gateID?? Check configuration or override handleMessage().");
     }
 }
virtual void BaseLayer::handleSelfMsg (cMessage * msg) protected pure virtual
Handle self messages such as timer...
Implemented in Mac1609_4, BaseMacLayer, BaseApplLayer, BaseWaveApplLayer, minicurso_UFPI_TraCI, mfcv, Veins::default_veins_TraCI_TestApp, Veins::minicurso_UFPI_TraCI_TestApp, service_discovery, test1, mfcv_rsu, minicurso_UFPI_TraCI_RSU, osdp, service_discovery_RSU, test1_rsu, and osdp_RSU.
Referenced by handleMessage().
virtual void BaseLayer::handleUpperControl (cMessage * msg) protected pure virtual
Handle control messages from upper layer.
Implemented in BaseMacLayer, Mac1609_4, and BaseApplLayer.
Referenced by handleMessage().
virtual void BaseLayer::handleUpperMsg (cMessage * msg) protected pure virtual
Handle messages from upper layer.
This function is pure virtual here, because there is no reasonable guess what to do with it by default.
Implemented in Mac1609_4, BaseMacLayer, and BaseApplLayer.
Referenced by handleMessage().
void BaseLayer::initialize (int stage) virtual
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseModule.
This module takes care of the gate initialization.
Reimplemented from BaseModule.
Reimplemented in Mac1609_4, BaseMacLayer, BaseApplLayer, Veins::default_veins_TraCI_TestApp, Veins::minicurso_UFPI_TraCI_TestApp, mfcv, minicurso_UFPI_TraCI, default_veins_TraCI, default_veins_TraCI_RSU, mfcv_rsu, minicurso_UFPI_TraCI_RSU, service_discovery, test1, osdp, osdp_RSU, service_discovery_RSU, and test1_rsu.
Definition at line 41 of file BaseLayer.cc.
Referenced by BaseApplLayer::initialize(), and BaseMacLayer::initialize().
 {
     BatteryAccess::initialize(stage);
     if(stage==0){
         passedMsg = NULL;
         if (hasPar("stats") && par("stats").boolValue()) {
             passedMsg = new PassedMessage();
             if (passedMsg != NULL) {
                 passedMsg->fromModule = getId();
             }
         }
         upperLayerIn  = findGate("upperLayerIn");
         upperLayerOut = findGate("upperLayerOut");
         lowerLayerIn  = findGate("lowerLayerIn");
         lowerLayerOut = findGate("lowerLayerOut");
         upperControlIn  = findGate("upperControlIn");
         upperControlOut = findGate("upperControlOut");
         lowerControlIn  = findGate("lowerControlIn");
         lowerControlOut = findGate("lowerControlOut");
     }
 }
void BaseLayer::recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage * m) protected
Definition at line 140 of file BaseLayer.cc.
Referenced by handleMessage(), sendControlDown(), sendControlUp(), BaseApplLayer::sendDelayedDown(), sendDown(), and sendUp().
{
     if (passedMsg == NULL)
         return;
     passedMsg->direction = dir;
     passedMsg->gateType  = gate;
     passedMsg->kind      = msg->getKind();
     passedMsg->name      = msg->getName();
     emit(catPassedMsgSignal, passedMsg);
 }
void BaseLayer::sendControlDown (cMessage * msg) protected
Sends a control message to a lower layer.
Definition at line 130 of file BaseLayer.cc.
{
     recordPacket(PassedMessage::OUTGOING,PassedMessage::LOWER_CONTROL,msg);
     if (gate(lowerControlOut)->isPathOK())
         send(msg, lowerControlOut);
     else {
         EV << "BaseLayer: lowerControlOut is not connected; dropping message" << std::endl;
         delete msg;
     }
 }
void BaseLayer::sendControlUp (cMessage * msg) protected
Sends a control message to an upper layer.
Definition at line 120 of file BaseLayer.cc.
Referenced by BaseMacLayer::handleLowerControl().
{
     recordPacket(PassedMessage::OUTGOING,PassedMessage::UPPER_CONTROL,msg);
     if (gate(upperControlOut)->isPathOK())
         send(msg, upperControlOut);
     else {
         EV << "BaseLayer: upperControlOut is not connected; dropping message" << std::endl;
         delete msg;
     }
 }
void BaseLayer::sendDown (cMessage * msg) protected
Sends a message to the lower layer.
Short hand for send(msg, lowerLayerOut);
You have to take care of encapsulation We recommend that you use a pair of functions called encapsMsg/decapsMsg.
Definition at line 110 of file BaseLayer.cc.
Referenced by BaseMacLayer::handleUpperMsg().
{
     recordPacket(PassedMessage::OUTGOING,PassedMessage::LOWER_DATA,msg);
     send(msg, lowerLayerOut);
 }
void BaseLayer::sendUp (cMessage * msg) protected
Sends a message to the upper layer.
Short hand for send(msg, upperLayerOut); You have to take care of decapsulation and deletion of superflous frames. We recommend that you use a pair of functions decapsMsg/encapsMsg.
Definition at line 115 of file BaseLayer.cc.
Referenced by Mac1609_4::handleLowerMsg(), and BaseMacLayer::handleLowerMsg().
{
     recordPacket(PassedMessage::OUTGOING,PassedMessage::UPPER_DATA,msg);
     send(msg, upperLayerOut);
 }
Member Data Documentation
const simsignalwrap_t BaseLayer::catDroppedPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_DROPPEDPACKET_NAME) static
Signal for dropped packets.
Definition at line 49 of file BaseLayer.h.
const simsignalwrap_t BaseLayer::catPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_PACKET_NAME) static
SignalID for packets.
Definition at line 45 of file BaseLayer.h.
const simsignalwrap_t BaseLayer::catPassedMsgSignal = simsignalwrap_t(MIXIM_SIGNAL_PASSEDMSG_NAME) static
Signal for passed messages.
Definition at line 47 of file BaseLayer.h.
Referenced by recordPacket().
int BaseLayer::lowerControlIn protected
Definition at line 60 of file BaseLayer.h.
Referenced by handleMessage(), and initialize().
int BaseLayer::lowerControlOut protected
Definition at line 61 of file BaseLayer.h.
Referenced by initialize(), and sendControlDown().
int BaseLayer::lowerLayerIn protected
Definition at line 56 of file BaseLayer.h.
Referenced by handleMessage(), and initialize().
int BaseLayer::lowerLayerOut protected
Definition at line 57 of file BaseLayer.h.
Referenced by Mac1609_4::handleSelfMsg(), initialize(), BaseApplLayer::sendDelayedDown(), and sendDown().
PassedMessage* BaseLayer::passedMsg protected
The last message passed through this layer.
This variable will be only not NULL if we are in statistic recording mode.
Definition at line 66 of file BaseLayer.h.
Referenced by initialize(), recordPacket(), and ~BaseLayer().
int BaseLayer::upperControlIn protected
Definition at line 58 of file BaseLayer.h.
Referenced by handleMessage(), and initialize().
int BaseLayer::upperControlOut protected
Definition at line 59 of file BaseLayer.h.
Referenced by initialize(), and sendControlUp().
int BaseLayer::upperLayerIn protected
Definition at line 54 of file BaseLayer.h.
Referenced by handleMessage(), and initialize().
int BaseLayer::upperLayerOut protected
Definition at line 55 of file BaseLayer.h.
Referenced by initialize(), and sendUp().
The documentation for this class was generated from the following files:
BaseLayer.h
BaseLayer.cc