Veins Framework: Flooding Class Reference
Flooding Class Reference
#include <Flooding.h>
Public Types
enum WaveApplMessageKinds { SERVICE_PROVIDER = LAST_BASE_APPL_MESSAGE_KIND, SEND_BEACON_EVT, GENERATE_MESSAGE }
Public Types inherited from BaseApplLayer
enum BaseApplMessageKinds { LAST_BASE_APPL_MESSAGE_KIND = 25000 }
The message kinds this layer uses.
enum BaseApplControlKinds { LAST_BASE_APPL_CONTROL_KIND = 25500 }
The control message kinds this layer uses.
Public Member Functions
~Flooding ()
virtual void initialize (int stage)
Initialization of the module and some variables.
virtual void finish ()
Called when the simulation has finished.
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed.
Public Member Functions inherited from BaseApplLayer
BaseApplLayer ()
BaseApplLayer (unsigned stacksize)
Public Member Functions inherited from BaseLayer
BaseLayer ()
BaseLayer (unsigned stacksize)
virtual ~BaseLayer ()
virtual void handleMessage (cMessage *)
Called every time a message arrives.
Public Member Functions inherited from Veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from BaseModule
BaseModule ()
Function to get the logging name of id.
BaseModule (unsigned stacksize)
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
Protected Member Functions
virtual void handleLowerMsg (cMessage *msg)
handle messages from below
virtual void handleSelfMsg (cMessage *msg)
handle self messages
virtual FloodingMessage * prepareWSM (std::string name, int dataLengthBits, t_channel channel, int priority, int rcvId, int serial=0)
virtual void sendWSM (WaveShortMessage *wsm)
virtual void handlePositionUpdate (cObject *obj)
virtual FloodingMessage * generateMessage ()
Protected Member Functions inherited from BaseApplLayer
void sendDelayedDown (cMessage *, simtime_t_cref)
Sends a message delayed to the lower layer.
virtual const LAddress::L3Type myApplAddr () const
Return my application layer address.
virtual void handleLowerControl (cMessage *msg)
Handle control messages from lower layer.
virtual void handleUpperMsg (cMessage *msg)
Handle messages from upper layer.
virtual void handleUpperControl (cMessage *msg)
Handle control messages from upper layer.
Protected Member Functions inherited from BaseLayer
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from Veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
Protected Attributes
int beaconLengthBits
int beaconPriority
bool sendData
bool sendBeacons
simtime_t individualOffset
int dataLengthBits
bool dataOnSch
int dataPriority
Coord curPosition
int mySCH
int myId
cMessage * sendBeaconEvt
cMessage * generateMessageEvt
WaveAppToMac1609_4Interface * myMac
Protected Attributes inherited from BaseApplLayer
int headerLength
Length of the ApplPkt header.
Protected Attributes inherited from BaseLayer
PassedMessage * passedMsg
The last message passed through this layer.
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
Protected Attributes inherited from Veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from BaseModule
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Static Protected Attributes
static const simsignalwrap_t mobilityStateChangedSignal = simsignalwrap_t(MIXIM_SIGNAL_MOBILITY_CHANGE_NAME)
Static Protected Attributes inherited from BaseModule
static const simsignalwrap_t catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME)
Stores the category of the HostState.
Additional Inherited Members
Static Public Attributes inherited from BaseLayer
static const simsignalwrap_t catPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_PACKET_NAME)
SignalID for packets.
static const simsignalwrap_t catPassedMsgSignal = simsignalwrap_t(MIXIM_SIGNAL_PASSEDMSG_NAME)
Signal for passed messages.
static const simsignalwrap_t catDroppedPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_DROPPEDPACKET_NAME)
Signal for dropped packets.
Detailed Description
Definition at line 16 of file Flooding.h.
Member Enumeration Documentation
enum Flooding::WaveApplMessageKinds
Enumerator
SERVICE_PROVIDER
SEND_BEACON_EVT
GENERATE_MESSAGE
Definition at line 25 of file Flooding.h.
{
                         SERVICE_PROVIDER = LAST_BASE_APPL_MESSAGE_KIND,
                         SEND_BEACON_EVT, GENERATE_MESSAGE
                 };
Constructor & Destructor Documentation
Flooding::~Flooding ()
Definition at line 131 of file Flooding.cc.
                     {
 }
Member Function Documentation
void Flooding::finish () virtual
Called when the simulation has finished.
Reimplemented from BaseLayer.
Definition at line 115 of file Flooding.cc.
                       {
         // TODO Store scalars here
         findHost()->unsubscribe(mobilityStateChangedSignal, this);
 }
FloodingMessage * Flooding::generateMessage () protected virtual
Definition at line 123 of file Flooding.cc.
Referenced by handleSelfMsg().
{
     FloodingMessage* flm = prepareWSM("flm", dataLengthBits, type_CCH, beaconPriority, 0, -1);
     flm->setMsgId(intuniform(0, 1000));
     return flm;
 }
void Flooding::handleLowerMsg (cMessage * msg) protected virtual
handle messages from below
Reimplemented from BaseApplLayer.
Definition at line 88 of file Flooding.cc.
{
         FloodingMessage* flm = dynamic_cast<FloodingMessage*>(msg);
         ASSERT(flm);
         // TODO: here the magic happens ;-) ideally you need exactly 13 characters to implement flooding, maybe a lot more for the statistics and to avoid continuous rebroadcasts
 }
void Flooding::handlePositionUpdate (cObject * obj) protected virtual
Definition at line 83 of file Flooding.cc.
Referenced by receiveSignal().
{
         ChannelMobilityPtrType const mobility = check_and_cast<ChannelMobilityPtrType>(obj);
         curPosition = mobility->getCurrentPosition();
 }
void Flooding::handleSelfMsg (cMessage * msg) protected virtual
handle self messages
Reimplemented from BaseApplLayer.
Definition at line 97 of file Flooding.cc.
{
         switch (msg->getKind()) {
                 case GENERATE_MESSAGE: {
                         sendWSM(generateMessage());
                         break;
                 }
                 default: {
                         if (msg)
                                 DBG << "APP: Error: Got Self Message of unknown kind! Name: " << msg->getName() << endl;
                         break;
                 }
         }
 }
void Flooding::initialize (int stage) virtual
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseLayer.
Then we have to intialize the gates and - if necessary - some own variables.
Reimplemented from BaseApplLayer.
Definition at line 7 of file Flooding.cc.
{
         BaseApplLayer::initialize(stage);
         if (stage==0) {
                 myMac = FindModule<WaveAppToMac1609_4Interface*>::findSubModule(
                             getParentModule());
                 assert(myMac);
                 myId = getParentModule()->getIndex();
                 headerLength = par("headerLength").longValue();
                 double maxOffset = par("maxOffset").doubleValue();
                 beaconLengthBits = par("beaconLengthBits").longValue();
                 beaconPriority = par("beaconPriority").longValue();
                 sendData = par("sendData").boolValue();
                 dataLengthBits = par("dataLengthBits").longValue();
                 //simulate asynchronous channel access
                 double offSet = dblrand() * (par("beaconInterval").doubleValue()/2);
                 offSet = offSet + floor(offSet/0.050)*0.050;
                 individualOffset = dblrand() * maxOffset;
                 findHost()->subscribe(mobilityStateChangedSignal, this);
                 generateMessageEvt = new cMessage("generate Message", GENERATE_MESSAGE);
                 // TODO: Select a random node (myId == ?) with some random delay to generate and broadcast (using generateMessageEvt) a message once during the simulation.
                 // test Jonh
                 //std::cout << findHost()->getFullName() << findHost()->getFullName() << endl;
                 std::string source = findHost()->getFullName();
                 if (source.compare("node[0]")){
                     std::cout << findHost()->getFullName() << findHost()->getFullName() << endl;
                     scheduleAt(simTime() + offSet, generateMessageEvt);
                 }
         }
 }
FloodingMessage * Flooding::prepareWSM (std::string name, int dataLengthBits, t_channel channel, int priority, int rcvId, int serial = 0) protected virtual
Definition at line 48 of file Flooding.cc.
Referenced by generateMessage().
{
     FloodingMessage* flm = new FloodingMessage(name.c_str());
     flm->addBitLength(headerLength);
     flm->addBitLength(lengthBits);
         switch (channel) {
                 case type_SCH: flm->setChannelNumber(Channels::SCH1); break; //will be rewritten at Mac1609_4 to actual Service Channel. This is just so no controlInfo is needed
                 case type_CCH: flm->setChannelNumber(Channels::CCH); break;
         }
         flm->setPsid(0);
         flm->setPriority(priority);
         flm->setWsmVersion(1);
         flm->setTimestamp(simTime());
         flm->setSenderAddress(myId);
         flm->setRecipientAddress(rcvId);
         flm->setSenderPos(curPosition);
         flm->setSerial(serial);
         if (name == "beacon") {
                 DBG << "Creating Beacon with Priority " << priority << " at Applayer at " << flm->getTimestamp() << std::endl;
         }
         if (name == "data") {
                 DBG << "Creating Data with Priority " << priority << " at Applayer at " << flm->getTimestamp() << std::endl;
         }
         return flm;
 }
void Flooding::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj) virtual
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed.
In this base class just handle the host state switching and some debug notifications
Reimplemented from BaseModule.
Definition at line 76 of file Flooding.cc.
{
         Enter_Method_Silent();
         if (signalID == mobilityStateChangedSignal) {
                 handlePositionUpdate(obj);
         }
 }
void Flooding::sendWSM (WaveShortMessage * wsm) protected virtual
Definition at line 111 of file Flooding.cc.
Referenced by handleSelfMsg().
{
         sendDelayedDown(wsm,individualOffset);
 }
Member Data Documentation
int Flooding::beaconLengthBits protected
Definition at line 47 of file Flooding.h.
Referenced by initialize().
int Flooding::beaconPriority protected
Definition at line 48 of file Flooding.h.
Referenced by generateMessage(), and initialize().
Coord Flooding::curPosition protected
Definition at line 55 of file Flooding.h.
Referenced by handlePositionUpdate(), and prepareWSM().
int Flooding::dataLengthBits protected
Definition at line 52 of file Flooding.h.
Referenced by generateMessage(), and initialize().
bool Flooding::dataOnSch protected
Definition at line 53 of file Flooding.h.
int Flooding::dataPriority protected
Definition at line 54 of file Flooding.h.
cMessage* Flooding::generateMessageEvt protected
Definition at line 60 of file Flooding.h.
Referenced by initialize().
simtime_t Flooding::individualOffset protected
Definition at line 51 of file Flooding.h.
Referenced by initialize(), and sendWSM().
const simsignalwrap_t Flooding::mobilityStateChangedSignal = simsignalwrap_t(MIXIM_SIGNAL_MOBILITY_CHANGE_NAME) static protected
Definition at line 32 of file Flooding.h.
Referenced by finish(), initialize(), and receiveSignal().
int Flooding::myId protected
Definition at line 57 of file Flooding.h.
Referenced by initialize(), and prepareWSM().
WaveAppToMac1609_4Interface* Flooding::myMac protected
Definition at line 62 of file Flooding.h.
Referenced by initialize().
int Flooding::mySCH protected
Definition at line 56 of file Flooding.h.
cMessage* Flooding::sendBeaconEvt protected
Definition at line 59 of file Flooding.h.
bool Flooding::sendBeacons protected
Definition at line 50 of file Flooding.h.
bool Flooding::sendData protected
Definition at line 49 of file Flooding.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
Flooding.h
Flooding.cc