Veins Framework: MacToPhyControlInfo Class Reference
MacToPhyControlInfo Class Reference
Stores information which is needed by the physical layer when sending a MacPkt.
#include <MacToPhyControlInfo.h>
Public Member Functions
MacToPhyControlInfo (Signal *signal=NULL)
Initialize the MacToPhyControlInfo with the passed signal or null if signal is ommited.
virtual ~MacToPhyControlInfo ()
Delete the signal if it is still in our ownership.
void setSignal (Signal *s)
Sets the signal of this MacToPhyControlInfo.
Signal * retrieveSignal ()
Returns a pointer to the Signal of this ControlInfo.
Static Public Member Functions
static cObject *const setControlInfo (cMessage *const pMsg, Signal *const pSignal)
Attaches a "control info" structure (object) to the message pMsg.
static Signal *const getSignal (cMessage *const pMsg)
extracts the signal from message "control info".
static Signal *const getSignalFromControlInfo (cObject *const pCtrlInfo)
extracts the signal from "control info".
Protected Attributes
Signal * signal
A pointer to the signal representing the transmission.
Detailed Description
Stores information which is needed by the physical layer when sending a MacPkt.
Definition at line 14 of file MacToPhyControlInfo.h.
Constructor & Destructor Documentation
MacToPhyControlInfo::MacToPhyControlInfo (Signal * signal = NULL) inline
Initialize the MacToPhyControlInfo with the passed signal or null if signal is ommited.
NOTE: Once a signal is passed to the MacToPhyControlInfo, MacToPhyControlInfo takes the ownership of the Signal.
Definition at line 27 of file MacToPhyControlInfo.h.
                                                   :
                 signal(signal) {}
virtual MacToPhyControlInfo::~MacToPhyControlInfo () inline virtual
Delete the signal if it is still in our ownership.
Definition at line 33 of file MacToPhyControlInfo.h.
{
                 if(signal)
                         delete signal;
         }
Member Function Documentation
static Signal* const MacToPhyControlInfo::getSignal (cMessage *const pMsg) inline static
extracts the signal from message "control info".
Definition at line 89 of file MacToPhyControlInfo.h.
{
         return getSignalFromControlInfo(pMsg->getControlInfo());
     }
static Signal* const MacToPhyControlInfo::getSignalFromControlInfo (cObject *const pCtrlInfo) inline static
extracts the signal from "control info".
Definition at line 95 of file MacToPhyControlInfo.h.
Referenced by PhyLayer80211p::encapsMsg(), and BasePhyLayer::encapsMsg().
{
         MacToPhyControlInfo *const cCtrlInfo = dynamic_cast<MacToPhyControlInfo *const>(pCtrlInfo);
         if (cCtrlInfo)
                 return cCtrlInfo->retrieveSignal();
         return NULL;
     }
Signal* MacToPhyControlInfo::retrieveSignal () inline
Returns a pointer to the Signal of this ControlInfo.
NOTE: The ownership of the Signal is passed together with the Signal itself. This means the caller of this method is responsible for deletion of the Signal. MacToPhyControlInfo also loses its pointer to the Signal when this Method is called so following calls of this method will return null!
Definition at line 61 of file MacToPhyControlInfo.h.
Referenced by getSignalFromControlInfo().
{
                 Signal* tmp = signal;
                 signal = 0;
                 return tmp;
         }
static cObject* const MacToPhyControlInfo::setControlInfo (cMessage *const pMsg, Signal *const pSignal) inline static
Attaches a "control info" structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the signal.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters
pMsg The message where the "control info" shall be attached.
pSignal The signal which should be send.
Definition at line 80 of file MacToPhyControlInfo.h.
Referenced by BaseMacLayer::setDownControlInfo().
{
         MacToPhyControlInfo *const cCtrlInfo = new MacToPhyControlInfo(pSignal);
         pMsg->setControlInfo(cCtrlInfo);
         return cCtrlInfo;
     }
void MacToPhyControlInfo::setSignal (Signal * s) inline
Sets the signal of this MacToPhyControlInfo.
NOTE: Once a signal is passed to the MacToPhyControlInfo, MacToPhyControlInfo takes the ownership of the Signal.
Definition at line 44 of file MacToPhyControlInfo.h.
{
                 if(signal)
                         delete signal;
                 signal = s;
         }
Member Data Documentation
Signal* MacToPhyControlInfo::signal protected
A pointer to the signal representing the transmission.
Definition at line 17 of file MacToPhyControlInfo.h.
The documentation for this class was generated from the following file:
MacToPhyControlInfo.h