Veins Framework: FindModule< T > Class Template Reference
FindModule< T > Class Template Reference
Provides method templates to find omnet modules.
#include <FindModule.h>
Static Public Member Functions
static T findSubModule (const cModule *const top)
Returns a pointer to a sub module of the passed module with the type of this template.
static T findGlobalModule ()
Returns a pointer to the module with the type of this template.
static cModule *const findHost (cModule *const m)
Returns a pointer to the host module of the passed module.
static const cModule *const findHost (const cModule *const m)
Detailed Description
template<typename T = cModule *const>
class FindModule< T >
Provides method templates to find omnet modules.
Definition at line 13 of file FindModule.h.
Member Function Documentation
template<typename T = cModule *const> static T FindModule< T >::findGlobalModule () inline static
Returns a pointer to the module with the type of this template.
Returns NULL if no module of this type could be found.
Definition at line 44 of file FindModule.h.
Referenced by Veins::TraCIScenarioManagerLaunchdAccess::get(), Veins::TraCIScenarioManagerAccess::get(), Veins::ChannelAccess::getConnectionManager(), Veins::AnnotationManagerAccess::getIfExists(), default_veins_TraCI::handleParkingUpdate(), mfcv::handleParkingUpdate(), vehDist::handleParkingUpdate(), minicurso_UFPI_TraCI::handleParkingUpdate(), epidemic::handleParkingUpdate(), mfcv_epidemic::handleParkingUpdate(), Veins::TraCIScenarioManager::initialize(), BaseMobility::initialize(), BasePhyLayer::initialize(), and BaseConnectionManager::initialize().
 {return findSubModule(simulation.getSystemModule());}
template<typename T = cModule *const> static cModule* const FindModule< T >::findHost (cModule *const m) inline static
Returns a pointer to the host module of the passed module.
Assumes that every host module is a direct sub module of the simulation.
Definition at line 52 of file FindModule.h.
Referenced by BaseModule::findHost().
{
                         cModule* parent = m != NULL ? m->getParentModule() : NULL;
                         cModule* node   = m;
                         // all nodes should be a sub module of the simulation which has no parent module!!!
                         while( parent != NULL && parent->getParentModule() != NULL  ) {
                                 node   = parent;
                                 parent = node->getParentModule();
                         }
                         return node;
                 }
template<typename T = cModule *const> static const cModule* const FindModule< T >::findHost (const cModule *const m) inline static
Definition at line 64 of file FindModule.h.
{
                         const cModule* parent = m != NULL ? m->getParentModule() : NULL;
                         const cModule* node   = m;
                         // all nodes should be a sub module of the simulation which has no parent module!!!
                         while( parent != NULL && parent->getParentModule() != NULL  ) {
                                 node   = parent;
                                 parent = node->getParentModule();
                         }
                         return node;
                 }
template<typename T = cModule *const> static T FindModule< T >::findSubModule (const cModule *const top) inline static
Returns a pointer to a sub module of the passed module with the type of this template.
Returns NULL if no matching submodule could be found.
Definition at line 22 of file FindModule.h.
Referenced by FindModule< T >::findGlobalModule(), AccessModuleWrap< T >::get(), Veins::TraCIMobilityAccess::get(), Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::epidemic_app::handlePositionUpdate(), Veins::mfcv_epidemic_app::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), Flooding::initialize(), AdvancedFlooding::initialize(), BaseMacLayer::initialize(), Mac1609_4::initialize(), BaseWaveApplLayer::initialize_default_veins_TraCI(), BaseWaveApplLayer::initialize_epidemic(), BaseWaveApplLayer::initialize_mfcv_epidemic(), BaseWaveApplLayer::initialize_minicurso_UFPI_TraCI(), and Veins::BatteryAccess::registerWithBattery().
                 {
                         for (cModule::SubmoduleIterator i(top); !i.end(); i++) {
                                 cModule *const sub = i();
                                 // this allows also a return type of read only pointer: const cModule *const
                                 T dCastRet = dynamic_cast<T>(sub);
                                 if (dCastRet != NULL)
                                         return dCastRet;
                                 // this allows also a return type of read only pointer: const cModule *const
                                 T recFnd = findSubModule(sub);
                                 if (recFnd != NULL)
                                         return recFnd;
                         }
                         return NULL;
                 }
The documentation for this class was generated from the following file:
FindModule.h