Veins Framework: mfcv_rsu Class Reference
mfcv_rsu Class Reference
Small RSU Demo using 11p.
#include <mfcv_rsu.h>
Public Member Functions
virtual void initialize (int stage)
Initialization of the module and some variables.
Public Member Functions inherited from BaseWaveApplLayer
~BaseWaveApplLayer ()
virtual void initialize_default_veins_TraCI (int stage)
virtual void initialize_mfcv (int stage)
virtual void initialize_minicurso_UFPI_TraCI (int stage)
virtual void initialize_osdp (int stage)
virtual void initialize_service_discovery (int stage)
virtual void initialize_test1 (int stage)
virtual void initialize_epidemic (int stage)
virtual void finish ()
Called when the simulation has finished.
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Called by the signaling mechanism whenever a change of a category occurs to which we have subscribed.
Public Member Functions inherited from BaseApplLayer
BaseApplLayer ()
BaseApplLayer (unsigned stacksize)
Public Member Functions inherited from BaseLayer
BaseLayer ()
BaseLayer (unsigned stacksize)
virtual ~BaseLayer ()
virtual void handleMessage (cMessage *)
Called every time a message arrives.
Public Member Functions inherited from Veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from BaseModule
BaseModule ()
Function to get the logging name of id.
BaseModule (unsigned stacksize)
virtual int numInitStages () const
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
Protected Member Functions
virtual void onBeacon (WaveShortMessage *wsm)
virtual void onData (WaveShortMessage *wsm)
void sendMessage (std::string blockedRoadId)
virtual void sendWSM (WaveShortMessage *wsm)
virtual void handleSelfMsg (cMessage *msg)
handle self messages
virtual void handleLowerMsg (cMessage *msg)
handle messages from below
virtual WaveShortMessage * prepareWSM_rsu (std::string name, int dataLengthBits, t_channel channel, int priority, int rcvId, int serial=0)
Protected Member Functions inherited from BaseWaveApplLayer
virtual WaveShortMessage * prepareWSM (std::string name, int dataLengthBits, t_channel channel, int priority, unsigned int rcvId, int serial=0)
virtual WaveShortMessage * prepareWSM_epidemic (string name, int dataLengthBits, t_channel channel, int priority, unsigned int rcvId, int serial=0)
virtual unsigned int MACToInteger ()
virtual void handlePositionUpdate (cObject *obj)
Protected Member Functions inherited from BaseApplLayer
void sendDelayedDown (cMessage *, simtime_t_cref)
Sends a message delayed to the lower layer.
virtual const LAddress::L3Type myApplAddr () const
Return my application layer address.
virtual void handleLowerControl (cMessage *msg)
Handle control messages from lower layer.
virtual void handleUpperMsg (cMessage *msg)
Handle messages from upper layer.
virtual void handleUpperControl (cMessage *msg)
Handle control messages from upper layer.
Protected Member Functions inherited from BaseLayer
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from Veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
Protected Attributes
AnnotationManager * annotations
BaseMobility * mobi
bool sentMessage
Protected Attributes inherited from BaseWaveApplLayer
int beaconLengthBits
int beaconPriority
bool sendData
bool sendBeacons
simtime_t individualOffset
int dataLengthBits
bool dataOnSch
int dataPriority
Coord curPosition
int mySCH
int myId
cMessage * sendBeaconEvt
WaveAppToMac1609_4Interface * myMac
int sendSummaryVectorInterval
unsigned int maximumEpidemicBufferSize
unsigned int hopCount
string source
string target
Protected Attributes inherited from BaseApplLayer
int headerLength
Length of the ApplPkt header.
Protected Attributes inherited from BaseLayer
PassedMessage * passedMsg
The last message passed through this layer.
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
Protected Attributes inherited from Veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from BaseModule
bool debug
Debug switch for all other modules.
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Public Types inherited from BaseWaveApplLayer
enum WaveApplMessageKinds {
SERVICE_PROVIDER = LAST_BASE_APPL_MESSAGE_KIND, SEND_BEACON_EVT, SEND_BEACON_EVT_minicurso, SERVICE_EXPIRED_EVT,
SERVICE_QUERY_EVT, SERVICE_EVT, MOBILITY_EVT, SEND_BEACON_EVT_epidemic
}
Public Types inherited from BaseApplLayer
enum BaseApplMessageKinds { LAST_BASE_APPL_MESSAGE_KIND = 25000 }
The message kinds this layer uses.
enum BaseApplControlKinds { LAST_BASE_APPL_CONTROL_KIND = 25500 }
The control message kinds this layer uses.
Static Public Attributes inherited from BaseLayer
static const simsignalwrap_t catPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_PACKET_NAME)
SignalID for packets.
static const simsignalwrap_t catPassedMsgSignal = simsignalwrap_t(MIXIM_SIGNAL_PASSEDMSG_NAME)
Signal for passed messages.
static const simsignalwrap_t catDroppedPacketSignal = simsignalwrap_t(MIXIM_SIGNAL_DROPPEDPACKET_NAME)
Signal for dropped packets.
Static Protected Attributes inherited from BaseWaveApplLayer
static const simsignalwrap_t mobilityStateChangedSignal = simsignalwrap_t(MIXIM_SIGNAL_MOBILITY_CHANGE_NAME)
Static Protected Attributes inherited from BaseModule
static const simsignalwrap_t catHostStateSignal = simsignalwrap_t(MIXIM_SIGNAL_HOSTSTATE_NAME)
Stores the category of the HostState.
Detailed Description
Small RSU Demo using 11p.
Definition at line 32 of file mfcv_rsu.h.
Member Function Documentation
void mfcv_rsu::handleLowerMsg (cMessage * msg) protected virtual
handle messages from below
Reimplemented from BaseWaveApplLayer.
Definition at line 100 of file mfcv_rsu.cc.
{
     WaveShortMessage* wsm = dynamic_cast<WaveShortMessage*>(msg);
     ASSERT(wsm);
     if (std::string(wsm->getName()) == "beacon_rsu") {
         DBG << "Beacon (rsu) recebido!";
         onBeacon(wsm);
     }
     else if (std::string(wsm->getName()) == "beacon_node") {
         DBG << "Beacon (node) recebido!";
         onBeacon(wsm);
     }
     else if (std::string(wsm->getName()) == "data") {
         onData(wsm);
     }
     else {
         DBG << "unknown message (" << wsm->getName() << ")  received\n";
     }
     delete(msg);
 }
void mfcv_rsu::handleSelfMsg (cMessage * msg) protected virtual
handle self messages
Reimplemented from BaseWaveApplLayer.
Definition at line 84 of file mfcv_rsu.cc.
{
     switch (msg->getKind()) {
         case SEND_BEACON_EVT: {
             sendWSM(prepareWSM_rsu("beacon_rsu", beaconLengthBits, type_CCH, beaconPriority, 0, -1));
             scheduleAt(simTime() + par("beaconInterval").doubleValue(), sendBeaconEvt);
             break;
         }
         default: {
             if (msg)
                 DBG << "APP: Error: Got Self Message of unknown kind! Name: " << msg->getName() << endl;
             break;
         }
     }
 }
void mfcv_rsu::initialize (int stage) virtual
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseLayer.
Then we have to intialize the gates and - if necessary - some own variables.
Reimplemented from BaseApplLayer.
Definition at line 27 of file mfcv_rsu.cc.
{
         BaseWaveApplLayer::initialize_default_veins_TraCI(stage);
         if (stage == 0) {
             mobi = dynamic_cast<BaseMobility*> (getParentModule()->getSubmodule("mobility"));
             ASSERT(mobi);
             annotations = AnnotationManagerAccess().getIfExists();
             ASSERT(annotations);
         }
 }
void mfcv_rsu::onBeacon (WaveShortMessage * wsm) protected virtual
Implements BaseWaveApplLayer.
Definition at line 37 of file mfcv_rsu.cc.
Referenced by handleLowerMsg().
{
     std::cout << "\n wsm:" << wsm;
     std::cout << "\n wsm->getArrivalTime():" << wsm->getArrivalTime();
     std::cout << "\n wsm->getRoadId():" << wsm->getRoadId();
     std::cout << "\n wsm->getFullName():" << wsm->getFullName();
     std::cout << "\n wsm->getWsmVersion():" << wsm->getWsmVersion();
     std::cout << "\n wsm->getSecurityType():" << wsm->getSecurityType();
     std::cout << "\n wsm->getChannelNumber():" << wsm->getChannelNumber();
     std::cout << "\n wsm->getDataRate():" << wsm->getDataRate();
     std::cout << "\n wsm->getPriority():" << wsm->getPriority();
     std::cout << "\n wsm->getPsid():" << wsm->getPsid();
     std::cout << "\n wsm->getPsc():" << wsm->getPsc();
     std::cout << "\n wsm->getTimestamp():" << wsm->getTimestamp();
     std::cout << "\n wsm->getSenderPos():" << wsm->getSenderPos();
     std::cout << "\n wsm->:getWsmLength():" << wsm->getWsmLength();
     std::cout << "\n wsm->:getWsmData():" << wsm->getWsmData();
     std::cout << "\n wsm->:getSenderSpeed():" << wsm->getSenderSpeed();
     std::cout << "\n wsm->:getSenderAddress():" << wsm->getSenderAddress();
     std::cout << "\n wsm->:getRecipientAddress():" << wsm->getRecipientAddress();
     std::cout << "\n wsm->getSerial():" << wsm->getSerial();
     std::cout << "\n wsm->getArrivalTime():" << wsm->getArrivalTime();
     std::cout << "\n wsm->getDisplayString():" << wsm->getDisplayString();
     std::cout << "\n wsm->getBitLength():" << wsm->getBitLength() << "\n\n";
 }
void mfcv_rsu::onData (WaveShortMessage * wsm) protected virtual
Implements BaseWaveApplLayer.
Definition at line 64 of file mfcv_rsu.cc.
Referenced by handleLowerMsg().
{
         findHost()->getDisplayString().updateWith("r=16,green");
         annotations->scheduleErase(1, annotations->drawLine(wsm->getSenderPos(), mobi->getCurrentPosition(), "blue"));
         if (!sentMessage) sendMessage(wsm->getWsmData());
 }
WaveShortMessage * mfcv_rsu::prepareWSM_rsu (std::string name, int dataLengthBits, t_channel channel, int priority, int rcvId, int serial = 0) protected virtual
Definition at line 122 of file mfcv_rsu.cc.
Referenced by handleSelfMsg().
{
     WaveShortMessage* wsm = new WaveShortMessage(name.c_str());
     wsm->addBitLength(headerLength);
     wsm->addBitLength(lengthBits);
     switch (channel) {
         case type_SCH: wsm->setChannelNumber(Channels::SCH1); break; //will be rewritten at Mac1609_4 to actual Service Channel. This is just so no controlInfo is needed
         case type_CCH: wsm->setChannelNumber(Channels::CCH); break;
     }
     wsm->setPsid(0);
     wsm->setPriority(priority);
     wsm->setWsmVersion(1);
     wsm->setTimestamp(simTime());
     wsm->setSenderAddress(myId);
     wsm->setRecipientAddress(rcvId);
     wsm->setSenderPos(curPosition);
     wsm->setSerial(serial);
     if (name == "beacon") {
         // Adicionado (Minicurso_UFPI)
         //wsm->setRoadId(TraCIMobilityAccess().get(getParentModule()) ->getRoadId().c_str());
         //wsm->setSenderSpeed(TraCIMobilityAccess(). get(getParentModule())->getSpeed());
        //DBG << "\n ttt" << wsm->getSenderSpeed() << " ttt\n";
         DBG << "Creating Beacon with Priority " << priority << " at Applayer at " << wsm->getTimestamp() << std::endl;
     }
     else if (name == "beacon_rsu") {
            DBG << "Creating Beacon_rsu with Priority " << priority << " at Applayer at " << wsm->getTimestamp() << std::endl;
     }
     else if (name == "data") {
         DBG << "Creating Data with Priority " << priority << " at Applayer at " << wsm->getTimestamp() << std::endl;
     }
     return wsm;
 }
void mfcv_rsu::sendMessage (std::string blockedRoadId) protected
Definition at line 72 of file mfcv_rsu.cc.
Referenced by onData().
{
         sentMessage = true;
         t_channel channel = dataOnSch ? type_SCH : type_CCH;
         WaveShortMessage* wsm = prepareWSM("data", dataLengthBits, channel, dataPriority, -1,2);
         wsm->setWsmData(blockedRoadId.c_str());
         sendWSM(wsm);
 }
void mfcv_rsu::sendWSM (WaveShortMessage * wsm) protected virtual
Reimplemented from BaseWaveApplLayer.
Definition at line 79 of file mfcv_rsu.cc.
Referenced by handleSelfMsg(), and sendMessage().
{
         sendDelayedDown(wsm,individualOffset);
 }
Member Data Documentation
AnnotationManager* mfcv_rsu::annotations protected
Definition at line 36 of file mfcv_rsu.h.
Referenced by initialize(), and onData().
BaseMobility* mfcv_rsu::mobi protected
Definition at line 37 of file mfcv_rsu.h.
Referenced by initialize(), and onData().
bool mfcv_rsu::sentMessage protected
Definition at line 38 of file mfcv_rsu.h.
Referenced by onData(), and sendMessage().
The documentation for this class was generated from the following files:
mfcv_rsu.h
mfcv_rsu.cc