Veins Framework: Veins::TraCICommandInterface Class Reference
Veins::TraCICommandInterface Class Reference
#include <TraCICommandInterface.h>
Public Types
enum DepartDefs { DEPART_NOW = 2, DEPART_LANE_BEST_FREE = 5, DEPART_POS_BASE = 4, DEPART_SPEED_MAX = 3 }
Public Member Functions
TraCICommandInterface (TraCIConnection &)
std::pair< uint32_t, std::string > getVersion ()
void setSpeedMode (std::string nodeId, int32_t bitset)
void setSpeed (std::string nodeId, double speed)
void setColor (std::string nodeId, const TraCIColor &color)
void slowDown (std::string nodeId, double speed, int time)
void newRoute (std::string nodeId, std::string roadId)
void setVehicleParking (std::string nodeId)
double getEdgeCurrentTravelTime (std::string edgeId)
double getEdgeMeanSpeed (std::string edgeId)
std::string getEdgeId (std::string nodeId)
std::string getCurrentEdgeOnRoute (std::string nodeId)
std::string getLaneId (std::string nodeId)
double getLanePosition (std::string nodeId)
std::list< std::string > getPlannedEdgeIds (std::string nodeId)
std::string getRouteId (std::string nodeId)
std::list< std::string > getRouteEdgeIds (std::string routeId)
void changeRoute (std::string nodeId, std::string roadId, double travelTime)
double distanceRequest (const TraCICoord &position1, const TraCICoord &position2, bool returnDrivingDistance)
void stopNode (std::string nodeId, std::string roadId, double pos, uint8_t laneid, double radius, double waittime)
void setTrafficLightProgram (std::string trafficLightId, std::string program)
void setTrafficLightPhaseIndex (std::string trafficLightId, int32_t index)
std::list< std::string > getPolygonIds ()
std::string getPolygonTypeId (std::string polyId)
std::list< TraCICoord > getPolygonShape (std::string polyId)
void setPolygonShape (std::string polyId, const std::list< TraCICoord > &points)
void addPolygon (std::string polyId, std::string polyType, const TraCIColor &color, bool filled, int32_t layer, const std::list< TraCICoord > &points)
void removePolygon (std::string polyId, int32_t layer)
void addPoi (std::string poiId, std::string poiType, const TraCIColor &color, int32_t layer, const TraCICoord &pos)
void removePoi (std::string poiId, int32_t layer)
std::list< std::string > getLaneIds ()
std::list< TraCICoord > getLaneShape (std::string laneId)
std::string getLaneEdgeId (std::string laneId)
double getLaneLength (std::string laneId)
double getLaneMaxSpeed (std::string laneId)
double getLaneMeanSpeed (std::string laneId)
int32_t getLaneIndex (std::string nodeId)
std::list< std::string > getJunctionIds ()
TraCICoord getJunctionPosition (std::string junctionId)
bool addVehicle (std::string vehicleId, std::string vehicleTypeId, std::string routeId, simtime_t emitTime_st=-DEPART_NOW, double emitPosition=-DEPART_POS_BASE, double emitSpeed=-DEPART_SPEED_MAX, int8_t emitLane=-DEPART_LANE_BEST_FREE)
std::string getVehicleTypeId (std::string nodeId)
std::list< std::string > getVehicleTypeIds ()
std::list< std::string > getRouteIds ()
bool changeVehicleRoute (std::string nodeId, const std::list< std::string > &edges)
std::pair< double, double > positionConversionLonLat (const TraCICoord &)
Private Member Functions
std::string genericGetString (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId)
TraCICoord genericGetCoord (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId)
double genericGetDouble (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId)
int32_t genericGetInt (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId)
std::list< std::string > genericGetStringList (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId)
std::list< TraCICoord > genericGetCoordList (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId)
Private Attributes
TraCIConnection & connection
Detailed Description
Definition at line 15 of file TraCICommandInterface.h.
Member Enumeration Documentation
enum Veins::TraCICommandInterface::DepartDefs
Enumerator
DEPART_NOW
DEPART_LANE_BEST_FREE
DEPART_POS_BASE
DEPART_SPEED_MAX
Definition at line 20 of file TraCICommandInterface.h.
{
                         DEPART_NOW = 2,
                         DEPART_LANE_BEST_FREE = 5,
                         DEPART_POS_BASE = 4,
                         DEPART_SPEED_MAX = 3
                 };
Constructor & Destructor Documentation
Veins::TraCICommandInterface::TraCICommandInterface (TraCIConnection & c)
Definition at line 8 of file TraCICommandInterface.cc.
                                                                : connection(c)
 {
 }
Member Function Documentation
void Veins::TraCICommandInterface::addPoi (std::string poiId, std::string poiType, const TraCIColor & color, int32_t layer, const TraCICoord & pos)
Definition at line 257 of file TraCICommandInterface.cc.
Referenced by Veins::AnnotationManager::show().
{
     TraCIBuffer p;
     p << static_cast<uint8_t>(ADD) << poiId;
     p << static_cast<uint8_t>(TYPE_COMPOUND) << static_cast<int32_t>(4);
     p << static_cast<uint8_t>(TYPE_STRING) << poiType;
     p << static_cast<uint8_t>(TYPE_COLOR) << color.red << color.green << color.blue << color.alpha;
     p << static_cast<uint8_t>(TYPE_INTEGER) << layer;
     p << static_cast<uint8_t>(POSITION_2D) << pos.x << pos.y;
     TraCIBuffer buf = connection.query(CMD_SET_POI_VARIABLE, p);
     ASSERT(buf.eof());
 }
void Veins::TraCICommandInterface::addPolygon (std::string polyId, std::string polyType, const TraCIColor & color, bool filled, int32_t layer, const std::list< TraCICoord > & points)
Definition at line 228 of file TraCICommandInterface.cc.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), Veins::epidemic_app::handlePositionUpdate(), and Veins::AnnotationManager::show().
{
     TraCIBuffer p;
     p << static_cast<uint8_t>(ADD) << polyId;
     p << static_cast<uint8_t>(TYPE_COMPOUND) << static_cast<int32_t>(5);
     p << static_cast<uint8_t>(TYPE_STRING) << polyType;
     p << static_cast<uint8_t>(TYPE_COLOR) << color.red << color.green << color.blue << color.alpha;
     p << static_cast<uint8_t>(TYPE_UBYTE) << static_cast<uint8_t>(filled);
     p << static_cast<uint8_t>(TYPE_INTEGER) << layer;
     p << static_cast<uint8_t>(TYPE_POLYGON) << static_cast<uint8_t>(points.size());
     for (std::list<TraCICoord>::const_iterator i = points.begin(); i != points.end(); ++i) {
         const TraCICoord& pos = *i;
         p << static_cast<double>(pos.x) << static_cast<double>(pos.y);
     }
     TraCIBuffer buf = connection.query(CMD_SET_POLYGON_VARIABLE, p);
     ASSERT(buf.eof());
 }
bool Veins::TraCICommandInterface::addVehicle (std::string vehicleId, std::string vehicleTypeId, std::string routeId, simtime_t emitTime_st = -DEPART_NOW, double emitPosition = -DEPART_POS_BASE, double emitSpeed = -DEPART_SPEED_MAX, int8_t emitLane = -DEPART_LANE_BEST_FREE)
Definition at line 313 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandAddVehicle(), Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::epidemic_app::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), and Veins::TraCIScenarioManager::insertVehicles().
{
     bool success = false;
     uint8_t variableId = ADD;
     uint8_t variableType = TYPE_COMPOUND;
     int32_t count = 6;
     int32_t emitTime = (emitTime_st < 0) ? (-1) : (floor(emitTime_st.dbl() * 1000));
     TraCIBuffer buf = connection.queryOptional(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << vehicleId << variableType << count << (uint8_t)TYPE_STRING << vehicleTypeId << (uint8_t)TYPE_STRING << routeId << (uint8_t)TYPE_INTEGER << emitTime << (uint8_t)TYPE_DOUBLE << emitPosition << (uint8_t)TYPE_DOUBLE <<emitSpeed << (uint8_t)TYPE_BYTE << emitLane, success);
     ASSERT(buf.eof());
     return success;
 }
void Veins::TraCICommandInterface::changeRoute (std::string nodeId, std::string roadId, double travelTime)
Definition at line 127 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandChangeRoute().
{
     if (travelTime >= 0) {
         uint8_t variableId = VAR_EDGE_TRAVELTIME;
         uint8_t variableType = TYPE_COMPOUND;
         int32_t count = 2;
         uint8_t edgeIdT = TYPE_STRING;
         std::string edgeId = roadId;
         uint8_t newTimeT = TYPE_DOUBLE;
         double newTime = travelTime;
         TraCIBuffer buf = connection.query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << count << edgeIdT << edgeId << newTimeT << newTime);
         ASSERT(buf.eof());
     } else {
         uint8_t variableId = VAR_EDGE_TRAVELTIME;
         uint8_t variableType = TYPE_COMPOUND;
         int32_t count = 1;
         uint8_t edgeIdT = TYPE_STRING;
         std::string edgeId = roadId;
         TraCIBuffer buf = connection.query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << count << edgeIdT << edgeId);
         ASSERT(buf.eof());
     }
     {
         uint8_t variableId = CMD_REROUTE_TRAVELTIME;
         uint8_t variableType = TYPE_COMPOUND;
         int32_t count = 0;
         TraCIBuffer buf = connection.query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << count);
         ASSERT(buf.eof());
     }
 }
bool Veins::TraCICommandInterface::changeVehicleRoute (std::string nodeId, const std::list< std::string > & edges)
Definition at line 326 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandChangeVehicleRoute().
{
     if (getEdgeId(nodeId).find(':') != std::string::npos) return false;
     if (edges.front().compare(getEdgeId(nodeId)) != 0) return false;
     uint8_t variableId = VAR_ROUTE;
     uint8_t variableType = TYPE_STRINGLIST;
     TraCIBuffer buf;
     buf << variableId << nodeId << variableType;
     int32_t numElem = edges.size();
     buf << numElem;
     for (std::list<std::string>::const_iterator i = edges.begin(); i != edges.end(); ++i) {
         buf << static_cast<std::string>(*i);
     }
     TraCIBuffer obuf = connection.query(CMD_SET_VEHICLE_VARIABLE, buf);
     ASSERT(obuf.eof());
     return true;
 }
double Veins::TraCICommandInterface::distanceRequest (const TraCICoord & position1, const TraCICoord & position2, bool returnDrivingDistance)
Definition at line 156 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandDistanceRequest().
{
     uint8_t variable = DISTANCE_REQUEST;
     std::string simId = "sim0";
     uint8_t variableType = TYPE_COMPOUND;
     int32_t count = 3;
     uint8_t dType = static_cast<uint8_t>(returnDrivingDistance ? REQUEST_DRIVINGDIST : REQUEST_AIRDIST);
     // query road network boundaries
     TraCIBuffer buf = connection.query(CMD_GET_SIM_VARIABLE, TraCIBuffer() << variable << simId << variableType << count << p1 << p2 << dType);
     uint8_t cmdLength_resp; buf >> cmdLength_resp;
     uint8_t commandId_resp; buf >> commandId_resp; ASSERT(commandId_resp == RESPONSE_GET_SIM_VARIABLE);
     uint8_t variableId_resp; buf >> variableId_resp; ASSERT(variableId_resp == variable);
     std::string simId_resp; buf >> simId_resp; ASSERT(simId_resp == simId);
     uint8_t typeId_resp; buf >> typeId_resp; ASSERT(typeId_resp == TYPE_DOUBLE);
     double distance; buf >> distance;
     ASSERT(buf.eof());
     return distance;
 }
TraCICoord Veins::TraCICommandInterface::genericGetCoord (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId) private
Definition at line 395 of file TraCICommandInterface.cc.
Referenced by getJunctionPosition().
{
     uint8_t resultTypeId = POSITION_2D;
     double x;
     double y;
     TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId);
     uint8_t cmdLength; buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r; buf >> commandId_r;
     ASSERT(commandId_r == responseId);
     uint8_t varId; buf >> varId;
     ASSERT(varId == variableId);
     std::string objectId_r; buf >> objectId_r;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r; buf >> resType_r;
     ASSERT(resType_r == resultTypeId);
     buf >> x;
     buf >> y;
     ASSERT(buf.eof());
     return TraCICoord(x, y);
 }
std::list< TraCICoord > Veins::TraCICommandInterface::genericGetCoordList (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId) private
Definition at line 509 of file TraCICommandInterface.cc.
Referenced by getLaneShape(), and getPolygonShape().
{
     uint8_t resultTypeId = TYPE_POLYGON;
     std::list<TraCICoord> res;
     TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId);
     uint8_t cmdLength; buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r; buf >> commandId_r;
     ASSERT(commandId_r == responseId);
     uint8_t varId; buf >> varId;
     ASSERT(varId == variableId);
     std::string objectId_r; buf >> objectId_r;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r; buf >> resType_r;
     ASSERT(resType_r == resultTypeId);
     uint8_t count; buf >> count;
     for (uint32_t i = 0; i < count; i++) {
         double x; buf >> x;
         double y; buf >> y;
         res.push_back(TraCICoord(x, y));
     }
     ASSERT(buf.eof());
     return res;
 }
double Veins::TraCICommandInterface::genericGetDouble (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId) private
Definition at line 424 of file TraCICommandInterface.cc.
Referenced by getEdgeCurrentTravelTime(), getEdgeMeanSpeed(), getLaneLength(), getLaneMaxSpeed(), getLaneMeanSpeed(), and getLanePosition().
{
     uint8_t resultTypeId = TYPE_DOUBLE;
     double res;
     TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId);
     uint8_t cmdLength; buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r; buf >> commandId_r;
     ASSERT(commandId_r == responseId);
     uint8_t varId; buf >> varId;
     ASSERT(varId == variableId);
     std::string objectId_r; buf >> objectId_r;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r; buf >> resType_r;
     ASSERT(resType_r == resultTypeId);
     buf >> res;
     ASSERT(buf.eof());
     return res;
 }
int32_t Veins::TraCICommandInterface::genericGetInt (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId) private
Definition at line 451 of file TraCICommandInterface.cc.
Referenced by getLaneIndex().
{
     uint8_t resultTypeId = TYPE_INTEGER;
     int32_t res;
     TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId);
     uint8_t cmdLength; buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r; buf >> commandId_r;
     ASSERT(commandId_r == responseId);
     uint8_t varId; buf >> varId;
     ASSERT(varId == variableId);
     std::string objectId_r; buf >> objectId_r;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r; buf >> resType_r;
     ASSERT(resType_r == resultTypeId);
     buf >> res;
     ASSERT(buf.eof());
     return res;
 }
std::string Veins::TraCICommandInterface::genericGetString (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId) private
Definition at line 369 of file TraCICommandInterface.cc.
Referenced by getCurrentEdgeOnRoute(), getEdgeId(), getLaneEdgeId(), getLaneId(), getPolygonTypeId(), and getRouteId().
{
     uint8_t resultTypeId = TYPE_STRING;
     std::string res;
     TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId);
     uint8_t cmdLength; buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r; buf >> commandId_r;
     ASSERT(commandId_r == responseId);
     uint8_t varId; buf >> varId;
     ASSERT(varId == variableId);
     std::string objectId_r; buf >> objectId_r;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r; buf >> resType_r;
     ASSERT(resType_r == resultTypeId);
     buf >> res;
     ASSERT(buf.eof());
     return res;
 }
std::list< std::string > Veins::TraCICommandInterface::genericGetStringList (uint8_t commandId, std::string objectId, uint8_t variableId, uint8_t responseId) private
Definition at line 478 of file TraCICommandInterface.cc.
Referenced by getJunctionIds(), getLaneIds(), getPlannedEdgeIds(), getPolygonIds(), getRouteEdgeIds(), getRouteIds(), and getVehicleTypeIds().
{
     uint8_t resultTypeId = TYPE_STRINGLIST;
     std::list<std::string> res;
     TraCIBuffer buf = connection.query(commandId, TraCIBuffer() << variableId << objectId);
     uint8_t cmdLength; buf >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         buf >> cmdLengthX;
     }
     uint8_t commandId_r; buf >> commandId_r;
     ASSERT(commandId_r == responseId);
     uint8_t varId; buf >> varId;
     ASSERT(varId == variableId);
     std::string objectId_r; buf >> objectId_r;
     ASSERT(objectId_r == objectId);
     uint8_t resType_r; buf >> resType_r;
     ASSERT(resType_r == resultTypeId);
     uint32_t count; buf >> count;
     for (uint32_t i = 0; i < count; i++) {
         std::string id; buf >> id;
         res.push_back(id);
     }
     ASSERT(buf.eof());
     return res;
 }
std::string Veins::TraCICommandInterface::getCurrentEdgeOnRoute (std::string nodeId)
Definition at line 99 of file TraCICommandInterface.cc.
{
     return genericGetString(CMD_GET_VEHICLE_VARIABLE, nodeId, LANE_EDGE_ID, RESPONSE_GET_VEHICLE_VARIABLE);
 }
double Veins::TraCICommandInterface::getEdgeCurrentTravelTime (std::string edgeId)
Definition at line 87 of file TraCICommandInterface.cc.
{
     return genericGetDouble(CMD_GET_EDGE_VARIABLE, edgeId, VAR_CURRENT_TRAVELTIME, RESPONSE_GET_EDGE_VARIABLE);
 }
std::string Veins::TraCICommandInterface::getEdgeId (std::string nodeId)
Definition at line 95 of file TraCICommandInterface.cc.
Referenced by changeVehicleRoute().
{
     return genericGetString(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_ROAD_ID, RESPONSE_GET_VEHICLE_VARIABLE);
 }
double Veins::TraCICommandInterface::getEdgeMeanSpeed (std::string edgeId)
Definition at line 91 of file TraCICommandInterface.cc.
{
     return genericGetDouble(CMD_GET_EDGE_VARIABLE, edgeId, LAST_STEP_MEAN_SPEED, RESPONSE_GET_EDGE_VARIABLE);
 }
std::list< std::string > Veins::TraCICommandInterface::getJunctionIds ()
Definition at line 305 of file TraCICommandInterface.cc.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), and Veins::epidemic_app::handlePositionUpdate().
{
     return genericGetStringList(CMD_GET_JUNCTION_VARIABLE, "", ID_LIST, RESPONSE_GET_JUNCTION_VARIABLE);
 }
TraCICoord Veins::TraCICommandInterface::getJunctionPosition (std::string junctionId)
Definition at line 309 of file TraCICommandInterface.cc.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), and Veins::epidemic_app::handlePositionUpdate().
{
     return genericGetCoord(CMD_GET_JUNCTION_VARIABLE, junctionId, VAR_POSITION, RESPONSE_GET_JUNCTION_VARIABLE);
 }
std::string Veins::TraCICommandInterface::getLaneEdgeId (std::string laneId)
Definition at line 289 of file TraCICommandInterface.cc.
{
     return genericGetString(CMD_GET_LANE_VARIABLE, laneId, LANE_EDGE_ID, RESPONSE_GET_LANE_VARIABLE);
 }
std::string Veins::TraCICommandInterface::getLaneId (std::string nodeId)
Definition at line 103 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandGetLaneId().
{
     return genericGetString(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_LANE_ID, RESPONSE_GET_VEHICLE_VARIABLE);
 }
std::list< std::string > Veins::TraCICommandInterface::getLaneIds ()
Definition at line 281 of file TraCICommandInterface.cc.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), and Veins::epidemic_app::handlePositionUpdate().
{
     return genericGetStringList(CMD_GET_LANE_VARIABLE, "", ID_LIST, RESPONSE_GET_LANE_VARIABLE);
 }
int32_t Veins::TraCICommandInterface::getLaneIndex (std::string nodeId)
Definition at line 107 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandGetLaneIndex().
{
     return genericGetInt(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_LANE_INDEX, RESPONSE_GET_VEHICLE_VARIABLE);
 }
double Veins::TraCICommandInterface::getLaneLength (std::string laneId)
Definition at line 293 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandGetLaneLength().
{
     return genericGetDouble(CMD_GET_LANE_VARIABLE, laneId, VAR_LENGTH, RESPONSE_GET_LANE_VARIABLE);
 }
double Veins::TraCICommandInterface::getLaneMaxSpeed (std::string laneId)
Definition at line 297 of file TraCICommandInterface.cc.
{
     return genericGetDouble(CMD_GET_LANE_VARIABLE, laneId, VAR_MAXSPEED, RESPONSE_GET_LANE_VARIABLE);
 }
double Veins::TraCICommandInterface::getLaneMeanSpeed (std::string laneId)
Definition at line 301 of file TraCICommandInterface.cc.
{
     return genericGetDouble(CMD_GET_LANE_VARIABLE, laneId, LAST_STEP_MEAN_SPEED, RESPONSE_GET_LANE_VARIABLE);
 }
double Veins::TraCICommandInterface::getLanePosition (std::string nodeId)
Definition at line 111 of file TraCICommandInterface.cc.
{
     return genericGetDouble(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_LANEPOSITION, RESPONSE_GET_VEHICLE_VARIABLE);
 }
std::list< TraCICoord > Veins::TraCICommandInterface::getLaneShape (std::string laneId)
Definition at line 285 of file TraCICommandInterface.cc.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), and Veins::epidemic_app::handlePositionUpdate().
{
     return genericGetCoordList(CMD_GET_LANE_VARIABLE, laneId, VAR_SHAPE, RESPONSE_GET_LANE_VARIABLE);
 }
std::list< std::string > Veins::TraCICommandInterface::getPlannedEdgeIds (std::string nodeId)
Definition at line 115 of file TraCICommandInterface.cc.
{
     return genericGetStringList(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_EDGES, RESPONSE_GET_VEHICLE_VARIABLE);
 }
std::list< std::string > Veins::TraCICommandInterface::getPolygonIds ()
Definition at line 204 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandGetPolygonIds(), and Veins::TraCIScenarioManager::init_traci().
{
     return genericGetStringList(CMD_GET_POLYGON_VARIABLE, "", ID_LIST, RESPONSE_GET_POLYGON_VARIABLE);
 }
std::list< TraCICoord > Veins::TraCICommandInterface::getPolygonShape (std::string polyId)
Definition at line 212 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIScenarioManager::init_traci().
{
     return genericGetCoordList(CMD_GET_POLYGON_VARIABLE, polyId, VAR_SHAPE, RESPONSE_GET_POLYGON_VARIABLE);
 }
std::string Veins::TraCICommandInterface::getPolygonTypeId (std::string polyId)
Definition at line 208 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandGetPolygonTypeId(), and Veins::TraCIScenarioManager::init_traci().
{
     return genericGetString(CMD_GET_POLYGON_VARIABLE, polyId, VAR_TYPE, RESPONSE_GET_POLYGON_VARIABLE);
 }
std::list< std::string > Veins::TraCICommandInterface::getRouteEdgeIds (std::string routeId)
Definition at line 123 of file TraCICommandInterface.cc.
{
     return genericGetStringList(CMD_GET_ROUTE_VARIABLE, routeId, VAR_EDGES, RESPONSE_GET_ROUTE_VARIABLE);
 }
std::string Veins::TraCICommandInterface::getRouteId (std::string nodeId)
Definition at line 119 of file TraCICommandInterface.cc.
{
     return genericGetString(CMD_GET_VEHICLE_VARIABLE, nodeId, VAR_ROUTE_ID, RESPONSE_GET_VEHICLE_VARIABLE);
 }
std::list< std::string > Veins::TraCICommandInterface::getRouteIds ()
Definition at line 83 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIScenarioManager::handleSelfMsg().
{
     return genericGetStringList(CMD_GET_ROUTE_VARIABLE, "", ID_LIST, RESPONSE_GET_ROUTE_VARIABLE);
 }
std::string Veins::TraCICommandInterface::getVehicleTypeId (std::string nodeId)
std::list< std::string > Veins::TraCICommandInterface::getVehicleTypeIds ()
Definition at line 79 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIScenarioManager::handleSelfMsg().
{
     return genericGetStringList(CMD_GET_VEHICLETYPE_VARIABLE, "", ID_LIST, RESPONSE_GET_VEHICLETYPE_VARIABLE);
 }
std::pair< uint32_t, std::string > Veins::TraCICommandInterface::getVersion ()
Definition at line 12 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIScenarioManagerLaunchd::init_traci(), and Veins::TraCIScenarioManager::init_traci().
{
     bool success = false;
     TraCIBuffer buf = connection.queryOptional(CMD_GETVERSION, TraCIBuffer(), success);
     if (!success) {
         ASSERT(buf.eof());
         return std::pair<uint32_t, std::string>(0, "(unknown)");
     }
     uint8_t cmdLength; buf >> cmdLength;
     uint8_t commandResp; buf >> commandResp;
     ASSERT(commandResp == CMD_GETVERSION);
     uint32_t apiVersion; buf >> apiVersion;
     std::string serverVersion; buf >> serverVersion;
     ASSERT(buf.eof());
     return std::pair<uint32_t, std::string>(apiVersion, serverVersion);
 }
void Veins::TraCICommandInterface::newRoute (std::string nodeId, std::string roadId)
Definition at line 64 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandNewRoute().
{
     uint8_t variableId = LANE_EDGE_ID;
     uint8_t variableType = TYPE_STRING;
     TraCIBuffer buf = connection.query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << roadId);
     ASSERT(buf.eof());
 }
std::pair< double, double > Veins::TraCICommandInterface::positionConversionLonLat (const TraCICoord & coord)
Definition at line 343 of file TraCICommandInterface.cc.
{
     TraCIBuffer request;
     request << static_cast<uint8_t>(POSITION_CONVERSION) << std::string("sim0")
             << static_cast<uint8_t>(TYPE_COMPOUND) << static_cast<int32_t>(2)
             << static_cast<uint8_t>(POSITION_2D) << coord.x << coord.y
             << static_cast<uint8_t>(TYPE_UBYTE) << static_cast<uint8_t>(POSITION_LON_LAT);
     TraCIBuffer response = connection.query(CMD_GET_SIM_VARIABLE, request);
     uint8_t cmdLength; response >> cmdLength;
     if (cmdLength == 0) {
         uint32_t cmdLengthX;
         response >> cmdLengthX;
     }
     uint8_t responseId; response >> responseId;
     ASSERT(responseId == RESPONSE_GET_SIM_VARIABLE);
     uint8_t variable; response >> variable;
     ASSERT(variable == POSITION_CONVERSION);
     std::string id; response >> id;
     uint8_t convPosType; response >> convPosType;
     ASSERT(convPosType == POSITION_LON_LAT);
     double convPosLon; response >> convPosLon;
     double convPosLat; response >> convPosLat;
     return std::make_pair(convPosLon, convPosLat);
 }
void Veins::TraCICommandInterface::removePoi (std::string poiId, int32_t layer)
Definition at line 271 of file TraCICommandInterface.cc.
Referenced by Veins::AnnotationManager::hide().
{
     TraCIBuffer p;
     p << static_cast<uint8_t>(REMOVE) << poiId;
     p << static_cast<uint8_t>(TYPE_INTEGER) << layer;
     TraCIBuffer buf = connection.query(CMD_SET_POI_VARIABLE, p);
     ASSERT(buf.eof());
 }
void Veins::TraCICommandInterface::removePolygon (std::string polyId, int32_t layer)
Definition at line 247 of file TraCICommandInterface.cc.
Referenced by Veins::AnnotationManager::hide().
{
     TraCIBuffer p;
     p << static_cast<uint8_t>(REMOVE) << polyId;
     p << static_cast<uint8_t>(TYPE_INTEGER) << layer;
     TraCIBuffer buf = connection.query(CMD_SET_POLYGON_VARIABLE, p);
     ASSERT(buf.eof());
 }
void Veins::TraCICommandInterface::setColor (std::string nodeId, const TraCIColor & color)
Definition at line 45 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandSetColor().
{
     TraCIBuffer p;
     p << static_cast<uint8_t>(VAR_COLOR);
     p << nodeId;
     p << static_cast<uint8_t>(TYPE_COLOR) << color.red << color.green << color.blue << color.alpha;
     TraCIBuffer buf = connection.query(CMD_SET_VEHICLE_VARIABLE, p);
     ASSERT(buf.eof());
 }
void Veins::TraCICommandInterface::setPolygonShape (std::string polyId, const std::list< TraCICoord > & points)
Definition at line 216 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandSetPolygonShape().
{
     TraCIBuffer buf;
     uint8_t count = static_cast<uint8_t>(points.size());
     buf << static_cast<uint8_t>(VAR_SHAPE) << polyId << static_cast<uint8_t>(TYPE_POLYGON) << count;
     for (std::list<TraCICoord>::const_iterator i = points.begin(); i != points.end(); ++i) {
         const TraCICoord& pos = *i;
         buf << static_cast<double>(pos.x) << static_cast<double>(pos.y);
     }
     TraCIBuffer obuf = connection.query(CMD_SET_POLYGON_VARIABLE, buf);
     ASSERT(obuf.eof());
 }
void Veins::TraCICommandInterface::setSpeed (std::string nodeId, double speed)
Definition at line 38 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandSetSpeed().
{
     uint8_t variableId = VAR_SPEED;
     uint8_t variableType = TYPE_DOUBLE;
     TraCIBuffer buf = connection.query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << speed);
     ASSERT(buf.eof());
 }
void Veins::TraCICommandInterface::setSpeedMode (std::string nodeId, int32_t bitset)
Definition at line 31 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandSetSpeedMode().
{
     uint8_t variableId = VAR_SPEEDSETMODE;
     uint8_t variableType = TYPE_INTEGER;
     TraCIBuffer buf = connection.query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << bitset);
     ASSERT(buf.eof());
 }
void Veins::TraCICommandInterface::setTrafficLightPhaseIndex (std::string trafficLightId, int32_t index)
Definition at line 199 of file TraCICommandInterface.cc.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), and Veins::epidemic_app::handlePositionUpdate().
{
     TraCIBuffer buf = connection.query(CMD_SET_TL_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(TL_PHASE_INDEX) << trafficLightId << static_cast<uint8_t>(TYPE_INTEGER) << index);
     ASSERT(buf.eof());
 }
void Veins::TraCICommandInterface::setTrafficLightProgram (std::string trafficLightId, std::string program)
Definition at line 194 of file TraCICommandInterface.cc.
Referenced by Veins::default_veins_TraCI_TestApp::handlePositionUpdate(), Veins::minicurso_UFPI_TraCI_TestApp::handlePositionUpdate(), and Veins::epidemic_app::handlePositionUpdate().
{
     TraCIBuffer buf = connection.query(CMD_SET_TL_VARIABLE, TraCIBuffer() << static_cast<uint8_t>(TL_PROGRAM) << trafficLightId << static_cast<uint8_t>(TYPE_STRING) << program);
     ASSERT(buf.eof());
 }
void Veins::TraCICommandInterface::setVehicleParking (std::string nodeId)
Definition at line 71 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandParkVehicle().
{
     uint8_t variableId = REMOVE;
     uint8_t variableType = TYPE_BYTE;
     uint8_t value = REMOVE_PARKING;
     TraCIBuffer buf = connection.query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << value);
     ASSERT(buf.eof());
 }
void Veins::TraCICommandInterface::slowDown (std::string nodeId, double speed, int time)
Definition at line 54 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandSlowDown().
{
     uint8_t variableId = CMD_SLOWDOWN;
     uint8_t variableType = TYPE_COMPOUND;
     int32_t count = 2;
     uint8_t speedType = TYPE_DOUBLE;
     uint8_t durationType = TYPE_INTEGER;
     TraCIBuffer buf = connection.query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << count << speedType << speed << durationType << time);
     ASSERT(buf.eof());
 }
void Veins::TraCICommandInterface::stopNode (std::string nodeId, std::string roadId, double pos, uint8_t laneid, double radius, double waittime)
Definition at line 177 of file TraCICommandInterface.cc.
Referenced by Veins::TraCIMobility::commandStopNode().
{
     uint8_t variableId = CMD_STOP;
     uint8_t variableType = TYPE_COMPOUND;
     int32_t count = 4;
     uint8_t edgeIdT = TYPE_STRING;
     std::string edgeId = roadId;
     uint8_t stopPosT = TYPE_DOUBLE;
     double stopPos = pos;
     uint8_t stopLaneT = TYPE_BYTE;
     uint8_t stopLane = laneid;
     uint8_t durationT = TYPE_INTEGER;
     uint32_t duration = waittime * 1000;
     TraCIBuffer buf = connection.query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << count << edgeIdT << edgeId << stopPosT << stopPos << stopLaneT << stopLane << durationT << duration);
     ASSERT(buf.eof());
 }
Member Data Documentation
TraCIConnection& Veins::TraCICommandInterface::connection private
Definition at line 73 of file TraCICommandInterface.h.
Referenced by addPoi(), addPolygon(), addVehicle(), changeRoute(), changeVehicleRoute(), distanceRequest(), genericGetCoord(), genericGetCoordList(), genericGetDouble(), genericGetInt(), genericGetString(), genericGetStringList(), getVersion(), newRoute(), positionConversionLonLat(), removePoi(), removePolygon(), setColor(), setPolygonShape(), setSpeed(), setSpeedMode(), setTrafficLightPhaseIndex(), setTrafficLightProgram(), setVehicleParking(), slowDown(), and stopNode().
The documentation for this class was generated from the following files:
TraCICommandInterface.h
TraCICommandInterface.cc